### ISSUE TITLE
Try Option doesn't work in Policy Administration

### ISSUE THREAD

**Issue by HimashiRathnayake** [wso2/product-is#10016]
**Describe the issue:**

Try option doesn't work in the `Policy Administration` view in the `Management Console`. Without giving any response it redirects to the same page.

The flow works properly in `IS 5.10.0`.

**How to reproduce:**

1. Go to the [management console](https://localhost:9443/).
2. Go to `Main` > `Entitlement` > `PAP` > `Policy Administration`.
3. Click the `Try` option in any available entitlement policy.
4. Add the relevant details and click `Test Evaluate`.
5. Check whether it gives any response.

**Expected behavior:**

Should  return a response (Permit/ Deny/ NotApplicable)

**Environment information**  **:**
 - Product Version: IS 5.11.0 - BETA
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Suggested labels:**

**Comment by piraveena** [comment]
This issue happened due to the regression caused by this change [1]

After this commit it is changed to `if(Encode.forJavaScript(request.getParameter("msgId")) == null)`. This Encode.forJavaScript() [2] is always return a string value of encoded input string.  So this if condition is always false when `request.getParameter("msgId")=null`.  Due to this goes to the else part [3] and creates a `null` cookie.  In the usual flow(before this commit [1]), we creates new cookies with `MSG<timstamp>`. So it always a unique cookie [4]. Since the `null` cookie already exists in the browser, it does not hit the if condition. So the dialog box is not getting displayed

[1]https://github.com/wso2/carbon-kernel/commit/2cd76adfe364dbcad208eb9707c1452f7bc092d9
[2]https://owasp.org/owasp-java-encoder/encoder/apidocs/org/owasp/encoder/Encode.html#forJavaScript-java.lang.String
[3]https://github.com/wso2/carbon-kernel/blob/v4.6.1-beta2/core/org.wso2.carbon.ui/src/main/resources/web/dialog/display_messages.jsp#L32
[4] https://github.com/wso2/carbon-kernel/blob/v4.6.1-beta2/core/org.wso2.carbon.ui/src/main/resources/web/dialog/display_messages.jsp#L57
