### ISSUE TITLE
[consoleApp] Adding Openid connect as a new protocol for a SAML web application does not load configurations and navigates for a blank page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10031]
**Describe the issue:**
Unable to add openid connect as a new protocol from a created saml web applications access tab

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for Access tab 
5. Click on + New protocol
6. Select Quick setup > openid connect
7. Click Next

**Observation**
Configurations are not gettig loaded. Navigating for a blank page. Same behaviour in an incognito browser as well

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

![console11](https://user-images.githubusercontent.com/31848014/96960464-1b888280-1520-11eb-9b6e-2c5d19287e48.png)

**Comment by brionmario** [comment]
@ShanikaWickramasinghe This issue seems to be fixed with https://github.com/wso2/identity-apps/pull/1268

<img width="1149" alt="Screen Shot 2020-10-29 at 1 21 51 PM" src="https://user-images.githubusercontent.com/25959096/97540526-c817a800-19e9-11eb-9a6b-c836972519d8.png">

Hence closing the issue.
