### ISSUE TITLE
Input validations while filling basic information about the identity provider

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#10030]
**Is your suggestion related to an experience ? Please describe.**
The form to fill information about the IDP contains 3 stages. The first stage validates the inputs before moving to the second stage. The second stage validates only empty required fields. It even accepts space as an input, and proceeds to the third stage. In the third stage, when the Finish button is clicked, it views a message as "Provided request body content is not in the expected format.". It does not view which fields are invalid.

**Describe the improvement**
Before moving to the third stage, do all the necessary validations in second stage and properly indicate what is the error in which field.

**Comment by thivi** [comment]
Similar issue https://github.com/wso2/product-is/issues/10099

Since the connector properties are dynamically obtained from the API, we need the properties' `regex` attribute to provide the regex to validate the properties. The logic to validate the properties in the fronted should be implemented. At the same time, the `regex` attribute of all the properties has the `.*` pattern which would allow any value. To validate these properties, the right regex pattern should be returned from teh backend.

**Comment by thivi** [comment]
This PR implements the logic to validate the properties using the provided regex. https://github.com/wso2/identity-apps/pull/1282

The relevant backend issue to get the right regex from the backend is tracked here. https://github.com/wso2/product-is/issues/10150
