### ISSUE TITLE
Numbering of Unit Test

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10049]
**Is your suggestion related to an experience ? Please describe.**
There currently is a numbering mechanism which is used in the test decription of integration tests. These numbers are manually numbered and following is an example of this method. 

`"ITC-X.X.X - [<Component>] - <Testing Scenario>"`

The term `ITC` stands for `Integration Test Case` and the numbering is manually maintained. We need to discuss this numbering mechanism and how the numbering is maintained and goverened in the long run if we are to use this method in unit tests.

**Comment by ayshsandu** [comment]
@DimalChandrasiri what is the requirement of numbering the tests?

**Comment by DimalChandrasiri** [comment]
@ayshsandu Currently it's an adaption in integration test cases but the numbering is maintained manually. We need to discuss how we are going to govern this numbering mechanism if we are to proceed.

**Comment by deshalw** [comment]
As per recent discussion with Imesh, Jerad and Brian following points can be added to this discussion:

- Main purpose of this numbering could be to uniquely identify a test to refer to (eg. when investigating a failure from a test result report)
-- The key point here is the numbers being unique, for that ideally a test management tool of some sort should be utilized because manual numbering is often cumbersome
-- Given the context of this discussion is unit/integration tests, which are not often directly linked to test cases already managed in such tool, introducing a tool could be an overhead 
- A possible alternative could be to use a naming convention, to identify a test case within a hierarchy - ideally mapped to the application's structure --> point to further discuss

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
