### ISSUE TITLE
Icons used in the Console & My Account needs to be revamped.

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10067]
**Is your suggestion related to an experience ? Please describe.**
Some of the icons and placeholder illustrations used in My Account & Console have to be replaced/re-adjusted to align with the design guidelines. 

**Describe the improvement**
Design icons & illustrations for the following.

- [x] Empty List Placeholder Icons (Needed for: Applications, Remote Fetch, IDP, OIDC Scopes, Users, Groups, Roles, Userstores, Certificates, Attribute Dialects)
- [x] Empty Search Results Placeholder Icon (Need a generic icon for all features)
- [x] Refactor Connector Side Panel Icons.
- [x] Design illustrations for connectors.(Needed for: Idle Account Suspend, Account Disable, Account Recovery, Password Reset, Analytics Engine Configuration, Consent Information Controller, User Claim Update, Account Lock, reCaptcha for SSO Login, Self Registration, Lite User Registration, Ask Password, Password History, Password Patterns)
- [x] Revamp listing icons.(Needed for: Applications, Identity Providers, OIDC Scopes, Remote Fetch, Users, Groups, Roles, Userstores, Certificates, Attribute Dialects)

**Comment by kanchanagodage** [comment]
Fixed with [PR 1281](https://github.com/wso2/identity-apps/pull/1281) and [PR 1289](https://github.com/wso2/identity-apps/pull/1289)

**Placeholder icons**
![Placeholders@2x](https://user-images.githubusercontent.com/29212717/97561435-2c486500-1a06-11eb-9dcc-5f4254abb652.png)

**Illustrators for connectors**
![Illustrations-governance-connectors@2x](https://user-images.githubusercontent.com/29212717/97561573-66b20200-1a06-11eb-9d86-53bf1dbf1f7d.png)

**Icons**
![Icon Pack@2x](https://user-images.githubusercontent.com/29212717/97561664-8517fd80-1a06-11eb-84ed-d024e3ecb4fb.png)

**Comment by brionmario** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/1281 & https://github.com/wso2/identity-apps/pull/1289
