### ISSUE TITLE
Add 'Session Terminated' popup message when the password is reset 

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10115]
**Is your suggestion related to an experience ? Please describe.**
When there's a successful password reset; and if there's another active user session, the active user should be notified that the session has terminated. Currently, the message doesn't appear.

**Describe the improvement**
Please display a 'Session terminated' to active user sessions as mentioned above

**Additional context**
Tested with 5.11.0 Beta 3

**Comment by brionmario** [comment]
IMO, we can't distinguish if the session got terminated due to a password change or not. If we are to add a popup to notify users regarding session terminations, it'll apply for all session terminations.

A similar implementation was done for idle session timeouts https://github.com/wso2/identity-apps/pull/1164

**Comment by thivi** [comment]
The user will be logged out following a password reset. This should log the user out of all the other apps as well. Since there was a problem with the single logout, the user wasn't logged out of the other apps. This has been fixed by https://github.com/wso2/identity-apps/pull/1381. So, now, when the password is reset, the user will be logged out of all the apps.
