### ISSUE TITLE
[consoleApp] Desktop Application allows to register successfully without properly validating the requested URL

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10184]
**Describe the issue:**
As redirect url of a desktop application is a mandatory field if a user input the url and without clicking on + icon click on register it should not register the application

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Desktop Application
4. In the application registration window input a url for redirect url and without clicking on + icon click on Register

**Observation**
Application registration gets succesful
Also it allows to register a url without the correct format

**Expected Behaviour**
Requested url should need to have a proper validation as its a mandatory field

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console29](https://user-images.githubusercontent.com/31848014/97550091-39118c80-19f7-11eb-9e6d-eec5eefc1a14.png)

**Comment by thivi** [comment]
If a user enters a URL and then clicks on `Register` without clicking on the `+` button, then the URL will be automatically added. And we are not validating the URL since deep links on mobile devices can use URLs of any format. Only a warning is shown such as the one below: 
![image](https://user-images.githubusercontent.com/20745428/97913121-e24be000-1d73-11eb-9896-a6102c712918.png)
