### ISSUE TITLE
Unable to add non-ascii characters for username when creating a new user

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10190]
**Describe the issue:**
The warning `"A user already exists with this username"` is displayed when trying to create a new user that has non-ascii characters in the username. 
The error message `"Something went wrong: Error while filtering the users for filter with attribute name"` was displayed in the blurred background behind the create user form when typing characters in addition to the non-ascii ones. No exceptions were thrown. 

**How to reproduce:**
1. Go to Console > Manage > Users
2. Press New User
3. Add a username with non-ascii characters (eg: ŠĐČĆŽšđčćž)
4. Fill in the other relevant details as required. 

Note: I added the following configurations to the `deployment.toml` to allow any character to be added to the username when using the primary userstore.

```
[user_store]
username_java_script_regex = '.'
username_java_regex = '.'
```

**Screenshot:**
<img width="731" alt="Screenshot 2020-10-29 at 18 47 04" src="https://user-images.githubusercontent.com/19253380/97583320-cd421a80-1a1c-11eb-8887-d4ed766d8a6a.png">

**Expected behavior:**
The username should be validated and should proceed to the next step of the wizard. 

**Environment information:**
 - Product Version: 5.11.0-Beta3
 - OS: Mac
 - Database: MySQL 8, latin1 charset
 - Userstore: JDBC - "database_unique_id"

**Comment by pulasthi7** [comment]
This is due to those characters not being accepted by DB and hence throwing a SQL exception
```
Caused by: java.sql.SQLException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation 'like'
```

This is expected if the DB is configured to use latin1 charset. However, the error message should be fixed to reflect the SQL error rather than saying the user already exists.

Note that in this scenario SCIM search will give a 500 error whereas for user existence it will give a 200 (with 1 item)

@brionmario / @thivi Can we fix the error message shown to the user when a 500 is given by the SCIM search during user creation?
