### ISSUE TITLE
Warn logs during server start up

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#10201]
Following warn logs can be observed in the server startup with OOTB configurations (5.11.0-beta3)

```
WARN {javax.mail} - expected resource not found: /META-INF/javamail.default.address.map
```

```
WARN {org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator} - We don't support method overloading. Ignoring [doSingleLogout]
```

```
WARN {org.wso2.carbon.identity.event.internal.IdentityEventServiceComponent} - Properties for userOperationDataDASPublisher is not configured. This event handler will not be activated
```

```
WARN {org.wso2.carbon.identity.event.internal.IdentityEventServiceComponent} - Properties for liteUserRegistration is not configured. This event handler will not be activated
```

**Comment by piraveena** [comment]
`WARN {org.wso2.carbon.identity.event.internal.IdentityEventServiceComponent} - Properties for liteUserRegistration is not configured. This event handler will not be activated 
` is fixed with this PR https://github.com/wso2/carbon-identity-framework/pull/3177. This log is no longer available in IS5.11.0-beta6-snapshot pack
