### ISSUE TITLE
reCaptcha appears before number of failed attempts reaches in MyAcoount Login

### ISSUE THREAD

**Issue by SupunSPWithana** [wso2/product-is#10309]
**Describe the issue:**
reCaptcha appears before number of failed attempts reaches in MyAcoount Login

_Note :_  

1. I restarted the IS server and created a new user with Login permission from Management Console.
2. Then through a new Incognito Window went to MyAccount login, tried with wrong credentials for previously set no. of times.
3. After end of them reCaptcha appear and it was OK
4. But next time through a new tab/window when tried to Login to MyAccount with wrong credentials after the 1st attempt, the reCaptcha appeared. 

Doc followed : https://is.docs.wso2.com/en/latest/learn/configuring-recaptcha-for-single-sign-on/

**Expected behavior:**
reCaptcha MUST appear when number of failed attempts reaches, in MyAcoount Login

**Environment information**
 - Product Version: IS 5.11.0-Beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Comment by somindatommy** [comment]
This is the expected behavior. 

Let's assume the max failed attempts is 3. When the first 3 attempts have failed, the failed attempt count has been reached. When we try invalid login from a new browser/window, the user still has 3 failed attempts. Therefore, Recaptcha will be prompted. This max attempt will not be reset until the user is authenticated. You can verify this by enabling the `Failed attempts` claim in the user's profile.
