### ISSUE TITLE
Add toml configs for RecoveryEndpointConfig.properties

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#10315]
### Description

The following three properties in the RecoveryEndpointConfig.properties were templated with a fix[1].

```
identity.server.service.contextURL=https://localhost:9443/services
identity.server.service.access.username=admin
identity.server.service.access.password=admin
```
Therefore the above configs can be configured via deployment.toml as follows. This config needs to be documented.
```
[identity.auth_framework.endpoint]
identity_server_service_url="https://$ref{server.hostname}:9443/services"
username="admin"
password="admin"
```

**Related issues** https://github.com/wso2/product-is/issues/9752, https://github.com/wso2/product-is/issues/9778

[1] https://github.com/wso2/carbon-identity-framework/pull/3207
[2] https://is.docs.wso2.com/en/latest/develop/hosting-authentication-endpoint-on-a-different-server/#moving-the-accountrecoveryendpoint-from-wso2is-and-hosting-it-on-a-separate-web-server

**Comment by lacek** [comment]
I believe the example `identity_server_service_url` is wrong as the `/services` is extraneous.
When set to `"https://$ref{server.hostname}:9443/services"`, error is shown: `<faultstring>The service cannot be found for the endpoint reference (EPR) /services/api/identity/recovery/v0.9/captcha?tenant-domain=carbon.super&amp;captcha-type=ReCaptcha&amp;recovery-type=password-recovery</faultstring>`. The error is fixed by removing the `/services` segment from identity_server_service_url.

In [older version of API doc](https://docs.wso2.com/display/IS570/apidocs/account-recovery/#!/operations#PasswordRecovery#getCaptcha), the example request is `https://localhost:9443/api/identity/recovery/v0.9/captcha?tenant-domain=carbon.super&captcha-type=ReCaptcha&recovery-type=username-recovery`, in which there is no segment of `/services` after the host:port.

In [newer version of API doc](https://docs.wso2.com/display/IS511/apidocs/account-recovery/index.html), the captcha APIs are gone. But the rest of the APIs are still with the base path `/api/identity/recovery/v0.9`.

Relevant change can also be found at https://github.com/wso2/identity-apps/commit/714c12e3711a36b6d19bd9a6d1ba0266bc1caa8f#diff-30def54dcec306001906788bfa928f6043f2a5ee29d7d477367db08ba4dc9fe8L18

Therefore this example was probably based on outdated source code.
