### ISSUE TITLE
Browser session in My Account continues after the server is restarted

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10329]
**Describe the issue:**
The same browser session in My Account continues when the IS is stopped and restarted and no interaction is made with the page between the stopping and the restarting. The browser session ID changes only when the page is refreshed. The login screen isn't prompted when the page is refreshed or when a link is clicked. 

**How to reproduce:**
1. Login to the My Account app
2. Open developer tools (in chrome)
3. Go to Application > Storage > Cookies > https://localhost:9443
4. Copy the value of JSESSIONID with the path /myaccount and save it
5. Stop and restart the IS from the terminal
6. Click the links and navigate the already loaded my account page once the IS has restarted
7. Compare the JSESSIONID with what was saved in step 4
8. Refresh the page and compare like step 7 again

**Expected behavior:**
The session should be ended and the user should be redirected to the login page when a link is clicked or the page is refreshed after restarting the server

**Environment information:**
 - Product Version: IS 5.11.0-Beta5-SNAPSHOT
 - OS: Mac
 - Browser: Chrome
 - Database: MySQL 8
 - Userstore: JDBC

---

### Optional Fields

**Suggested labels:**
myaccount

**Comment by IsuraD** [comment]
The expected behavior is, the user should not be promoted to log in again. The session should be activated even though the server is restarted. 
The myaccount session is relying on the access token and the commonauth id cookie. Since the identity server sessions and the access tokens are persisted, those won't clear on restart. Thus this is the expected way .

**Comment by thanujalk** [comment]
User session in the IS associated with the `commonauth` cookie, which is valid for 15m by default, and the associated session data is persisted in the DB. So when you refresh app will send an authorization request to the IS and since the cookie is there, it will return with a valid authorization code. So you can log in without providing the credentials again.
If you want to prompt the login again, either you have to close the browser or clear the cookies.
