### ISSUE TITLE
Send email confirmation on self-signup without locking the account

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10356]
**Is your feature request related to a problem? Please describe.**
Let's consider the uscase: Allow user to self-signup and login to the application before confirming the email address. But the user should be able to confirm the email later on. We can show a message or limit the functionalities until the user confirms the email address.

**Describe the solution you would prefer**
Currently, we have the following configs.
- Enable Self User Registration
- Enable Account Lock On Creation

We can have an additional configuration like below.
- Enable Email Verification

This is to trigger an email verification mail during self-registration without locking the account.

**Comment by abhi4u1947** [comment]
NOTE: 

While the user's email address is not confirmed the following claim will remain false.

email_verified | boolean | True if the End-User's e-mail address has been verified;   otherwise false. When this Claim Value is true, this means that   the OP took affirmative steps to ensure that this e-mail address was   controlled by the End-User at the time the verification was performed. The   means by which an e-mail address is verified is context specific, and   dependent upon the trust framework or contractual agreements within which the   parties are operating.
-- | -- | --

In addition to be able to send email automatically for verification, it should also be possible that User Portal shows user that his email is not yet verified and he should have way to resend the verification email to verify it.

Additionally, from security consideration the email template should also offer a way to report if someone else has done a registration by using some othre person's email that its not done by him and user account should be blocked/disabled/deleted.
