### ISSUE TITLE
Add ability revoke tokens when session is removed via session termination API

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10481]
Currently, tokens are only revoked when the IDP session is terminated during a logout flow. 

Add the capability to revoke tokens when the session termination API is used to terminate a session

**Comment by piraveena** [comment]
Currently we revoke tokens bound to the same binding. 
**for example**: appA and appB have same token binding and appC have different token binding and all are in the same browser session.  when appA invokes logout, the tokens issued for appA and appB will be revoked. But not appC

**Comment by piraveena** [comment]
With this fix, we add a mapping to token and session. So when a session is terminanted via REST api, we will revoke the access token as well.  This is applicable for authorization code grant, implicit flow, refresh token grant and hybrid flow.

- If no sso-session binding is enabled then in some cases, the same accesstoken will be shared among the applications in the different browser sessions . In that case, if one application session is terminated, the respective token will also be revoked. This leads to a situation where the applications will also lose the accesstoken. Because the same accesstoken is used in many sessions. This has mapping of one accesstoken to many sessions

accesstoken | session
-- | --
xx | aa
xx | ab
yy | ac

- So it is always recommended to use sso-session binding if you are using session management rest api to terminate the sessions. In that situation, only there will be a one to one mapping for token and sessions.

accesstoken | session
-- | --
xx | aa
xy | ab
yy | ac
