### ISSUE TITLE
Configuring authentication steps in the Console app breaks authentication

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10550]
**Describe the issue:**
Configuring authentication steps using the Console app renders authenticating impossible.

**How to reproduce:**
1. Create an app through the Console.
2. Go to the Sign-on Method tab and add an additional step or add another authenticator to the existing tab and update.
3. Try signing in using the created app.
4. The SSO page throws an error.

Move on to the management console and check out the adaptive script. 
![image](https://user-images.githubusercontent.com/20745428/99633485-02aeb680-2a65-11eb-8564-5f83aca50cd3.png)

Updating the authentication steps through the console messes up the adaptive script.

**Comment by IsuraD** [comment]
Could recreate the issues. The issue is related to script generation. 

` "var onLoginRequest = function(context) {\n    executeStep(0);\n};\n"`


The same flow works when using the Management console. Still there is an issue in the UI. It shows null values as follows. 

![Screenshot 2020-12-22 at 04 56 20](https://user-images.githubusercontent.com/8455535/102831916-f5de0380-4412-11eb-982e-b954b969b9a6.png)
