### ISSUE TITLE
Thread local for storing the user store domain is not cleared properly. This can cause unnecessory NPEs

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10658]
When the user is authenticated against the user store manager we are setting the thread-local user store domain. Using this method. However, it was not cleared. 
Now in a flow where the user is not authenticated from the user store, (i.e. saml bearer grant, JWT bearer grant[2], Email OTP, TOTP, etc.) if we use the "createLocalAuthenticatedUserFromSubjectIdentifier" method[3] instead of "createFederateAuthenticatedUserFromSubjectIdentifier" it can cause intermitted NPE/strange issues due to it. 

As a general practice, we need to clear the set thread-local variable during the same request flow from the same thread. Otherwise, this can cause other unidentified issues as well.

[1] - https://github.com/wso2/carbon-kernel/blob/c02225a1299da08ba938c32ec77eb4199af8c86d/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/UserCoreUtil.java#L434
[2] - https://github.com/wso2-extensions/identity-oauth2-grant-jwt/pull/42/files
[3] - https://github.com/wso2/carbon-identity-framework/blob/d8ebf42510163048971298e54d4e35c3901c9e67/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/model/AuthenticatedUser.java#L90

**Comment by tharindu-bandara** [comment]
The concerned thread-local variable `threadLocalToSetDomain` is set and get via two utility methods from UserCoreUtil. In the codebase, there are multiple flows that `sets` this thread-local. The following shows the usages in wso2 and wso2-extensions organizations.
- https://github.com/search?p=2&q=org%3Awso2+setDomainInThreadLocal&type=Code
- https://github.com/search?q=org%3Awso2-extensions+setDomainInThreadLocal&type=code
- Multiple usages in the current development kernel branch(4.6.x).
These usages are from the abstract user store manager, Post authn handlers, Request coordinators, Application authenticators, and carbon server authenticators.

The following shows the multiple flows that `gets` this thread-local.
- https://github.com/search?q=org%3Awso2+getDomainFromThreadLocal&type=Code
- https://github.com/search?p=2&q=org%3Awso2-extensions+getDomainFromThreadLocal&type=Code
- Multiple usages in the current development kernel branch(4.6.x).
The usages again from the application authenticators, authentication handlers, utility methods which has additional usages apart from the listed ones, call back handlers, grant handlers, authentication handlers, etc.

Therefore it is difficult to actually find specific places where we could simply clear the variable in a particular request flow. For example, the user store domain name set by one of the user store managers, post authn handler etc could be used by the grant handler. It is complex and difficult to come up with a straightforward fix unless performing a full analysis about each available `get` method usecase. It becomes even difficult as in some scenarios like if we set the variable in one of the post auth handler intended to be used in a separate listener, but another post auth handler might un-intentionally use that value leading to an erroneous behaviour since it was not cleared still.

Therefore this issue needs a further detailed analysis on each usage of the thread local variable throughout the codebase and identify suitable safe solutions to clear it without breaking existing functionalities.

**Comment by tharindu-bandara** [comment]
As per the offline chat I had with @mefarazath there is a fix made already regarding this issue. 

https://github.com/wso2/carbon-identity-framework/pull/3357

With this, the thread-local is cleared for requests going through the Identity framework. Because in the fix, the request coordinator will clear the thread-local variable once authentication flow is concluded. Allowing listeners in the same request flow to use the variable(since it's the same request flow, the user store domain should be the same throughout) but immediately clearing it once flow is concluded. 

What's remaining is the requests that are not going through the identity framework.  We need to check and fix those usages to conclude this issue.

**Comment by piraveena** [comment]
This issue is not reproducible in IS 6.0.0-alpha3 pack. Please reopen the issue if you could reproduce it again
