### ISSUE TITLE
[Console] SAML SSO Authenticator summary details are incorrect

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10773]
**Describe the issue:**
Additional Query Parameters details are incorrect in the summary page of the authenticator.

<img width="600" alt="Screenshot 2020-12-15 at 12 26 01" src="https://user-images.githubusercontent.com/40847371/102184429-7661a900-3ed5-11eb-882c-2fa9d8d19970.png">

**How to reproduce:**

1. Log in to the Console and click on Develop tab
2. Click on "Identity Providers"
3. Click on "New Identity Provider" and select "Google"
4. Provide the required details and create an IdP
5. Click on Update icon in the created IdP
6. Go to the Authentication tab and click "New Authenticator"
7. Select "SAML SSO"
8. Add required details including Additional Query Parameters
9. Click Next

**Environment information**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL 5.7
 - Browser: Safari - 14v

**Comment by DimalChandrasiri** [comment]
Since this is related to query parameters, the ideal way of showing them is in a comma separated way so that the user has the ability to easily identify what the query parameters are. If wi tend to show them in such a way as the custom tags are shown, it'll mislead the users into thinking that query parameters are custom tags as well. Hence will not fix this issue and will be closed.
