### ISSUE TITLE
Console App breaks when email verified claim is enabled in the users profile

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10878]
**Describe the issue:**
Console App breaks when email verified claim is enabled in the user's profile

**How to reproduce:**
- Enable the `email verified` claim for the default profile
- Create a user from the management console 
- Navigate to the profile and complete the profile (do not add any values to `email verified` claim)
- View the profile from the console and notice that there are no errors.
- Now navigate to the management console and set the `email verified` claim value to `true'.
- Navigate back to the console and view the profile and notice that the profile is not displayed.

<img width="819" alt="Screenshot 2021-01-04 at 22 48 28" src="https://user-images.githubusercontent.com/39567992/103561276-36438400-4edf-11eb-85ec-0dd4ddb3f8ca.png">

**Expected behavior:**
The profile should be displayed without errors.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0

**Comment by brionmario** [comment]
After a debug session, the following issues were identified.

1. In the profile component, the data type from the schema is not considered ATM. All the fields are rendered as `text` fields. (https://github.com/brionmario/identity-apps/blob/master/apps/console/src/features/users/components/user-profile.tsx#L768)

2. The type in `emailVerified` claim schema is `STRING` but the value in the user response is `true`.

**User Response**

<img width="571" alt="Screen Shot 2021-01-04 at 11 09 03 PM" src="https://user-images.githubusercontent.com/25959096/103563049-24afab80-4ee2-11eb-97ff-c29409f23933.png">

**Schema**

<img width="547" alt="Screen Shot 2021-01-04 at 11 09 17 PM" src="https://user-images.githubusercontent.com/25959096/103563085-2d07e680-4ee2-11eb-8111-f3a1b145d493.png">

3. Since the value is `true` and the input field type is `text`, ` form.tsx` throws the following error.

<img width="547" alt="Screen Shot 2021-01-04 at 11 09 17 PM" src="https://user-images.githubusercontent.com/25959096/103563502-e1097180-4ee2-11eb-8789-c5714fb6d3da.png">

Checking if the value is trimmable before attempting to trim would solve this issue.

Change [line](https://github.com/wso2/identity-apps/blob/master/modules/forms/src/forms.tsx#L323) as follows.

```js
typeof value === "string" && !!value.trim()
```
or
```js
value.trim && !!value.trim()
```

**Comment by ayshsandu** [comment]
Fixed in following PR:
- https://github.com/wso2/identity-apps/pull/1474
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/320
