### ISSUE TITLE
[Console App]Indicate where the "Server Endpoint" details can be found

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11169]
**Is your suggestion related to an experience ? Please describe.**
In the console app there is no indication where the server endpoint details can be found. An application developer will need to know these endpoint details, although they are available there is no indication where it can be found.

<img width="709" alt="Screen Shot 2021-02-03 at 11 31 22 AM" src="https://user-images.githubusercontent.com/11583571/106705128-62077600-6613-11eb-978b-2cf0c009c14d.png">

**Describe the improvement**
Clearly indicate where the server connection details can be found.

**Comment by IsankaSR** [comment]
This is  fixed with [#3582](https://github.com/wso2-enterprise/asgardeo-product/issues/3582)

The improvement can be summarized as follows.

- Added a new tab named **Info** to include the server endpoints
- Added navigation to the Info tab through the Quick Start tab targeting users who skip the quick start guide.
- Removed the help panel in the application view as its content is now contained in the **Info** tab
