### ISSUE TITLE
Recheck the need for prompting username consent

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11186]
Consent for username was removed in 5.10.0 onwards as it was a mandatory claim that must always be there in order to proceed. Need to recheck whether this consent request should be re-added due to the possibility that PII info can be used in the username(possible GDPR issues).

The username consent was removed using the following PR[1]
[1] - https://github.com/wso2/carbon-identity-framework/pull/2745

**Comment by dewniMW** [comment]
The fix for PR [1] will remove prompting the consent for any claim uri which is configured as the subject claim uri. However, prompting consent should be there as the subject claim uri can be a PII. 

[1] https://github.com/wso2/carbon-identity-framework/pull/2745/files#diff-75cbe1ec0efc292018ed8b205e5349b7ea5f353b1a46a63fb2d5aadc8a401bc8L219

**Comment by dewniMW** [comment]
The finalized fix is to prompt consent for the subject claim URI only if it is configured as a requested claim. This capability will be enabled by default in 5.12.0. The migration impact is tracked with https://github.com/wso2/product-is/issues/11329

For 5.10.0 and 5.11.0 this capability is offered via WUM by the use of the following configuration. By default, the configuration will be disabled so as not to have any behavioural change.

```
[authentication.consent.subject]
prompt=true
```
