### ISSUE TITLE
Account blocking does not take effect for linked accounts in federated log in

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#11277]
**Describe the issue:**
Account blocking does not take effect for linked accounts in federated log in

**How to reproduce:**
1. Configure a federated IdP with JIT provisioning.
2. Log in to a service provider with a user non-existing in IS.
3. Logout from the service provider.
3. Go to the user's profile and make sure the user has been created.
4. Block/Disable the user account.
5. Try to log in again to the service provider.
6. You should be logged in successfully into the service provider.

**Expected behavior:**
When you perform the 5 steps above, in the 5th step the user must not be able to log in successfully into the service provider.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - IS 5.11.0

**Comment by isuruirj** [comment]
This issue is still there if the user is JIT provisioning to a secondary user store domain
How to reproduce:

1. Configure a federated IdP with JIT provisioning to a secondary user store.
2. Log in to a service provider with a user non-existing in IS.
3. Logout from the service provider.
4. Go to the user's profile and make sure the user has been created.
5. Disable/Lock the user account.
6. Try to log in again to the service provider.
7. You should be logged in successfully to the service provider.

Environment information: IS-5.7.0
