### ISSUE TITLE
When using OIDC scopes the claims displayed in the consent screen is not inline with the scope

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11331]
When performing a OIDC based auth flow we can request claims by sending a registered OIDC scope. These claims are only given if they are added as requested attributes.

When we add requested attributes those attributes are shown in the consent screen as attributes requesting for consent without any regards to the actually requested attributes using an OIDC scope.

ex:

- Set `email`, `givenname` as requested attributes in the SP config
- add `email` OIDC scope and do a OIDC auth request.

in the consent screen, it will ask consent for both `email` and `givenname`. 
It should only ask consent for the `email` attribute and in the token response it should only send back the `email` attribute in the id_token not both `email` and `givenname` attributes.

**Comment by senthalan** [comment]
@ChanikaRuchini are we good to close this?
Do we have any pending items to be completed?

**Comment by nilasini** [comment]
@ChanikaRuchini any update on this?

**Comment by ChanikaRuchini** [comment]
When we add as **requested attributes** flow works as expected. But when we add as **mandatory attributes** it prompts the `Provide Mandatory Details` screen without any regards to the actually requested attributes using an OIDC scope. But consent screen is working fine.

- Set email, givenname as mandatory attributes in the SP config
- add email OIDC scope and do a OIDC auth request.

![Screenshot from 2022-03-21 23-36-39](https://user-images.githubusercontent.com/36252774/159340869-9dd4b938-34e5-42ca-98d7-e52b1fe98b3a.png)

![Screenshot from 2022-03-21 23-37-00](https://user-images.githubusercontent.com/36252774/159340890-b74423cf-fc95-4ea7-bd31-879b4b710e99.png)

**Comment by nilasini** [comment]
Related issue https://github.com/wso2/product-is/issues/4847

**Comment by ImalshaG** [comment]
The above mentioned issue is fixed where the consent screen will only display claims that are filtered according to the scope requested. But the user will be prompted to enter mandatory claims regardless of the scope even though consent will not be requested. 
There is no straight forward solution to filter claims based on scope during the missing mandatory claims flow since it is handled by the framework. 
Since configuring a claim as a mandatory claim and not requesting it with the scope is a misconfiguration from the service provider and will not be a critical issue, it will be addressed as a separate effort by
https://github.com/wso2/product-is/issues/13511.

**Comment by ImalshaG** [comment]
Fixed by https://github.com/wso2/carbon-identity-framework/pull/3996 and the changes required for mandatory claims requesting page will be tracked by https://github.com/wso2/product-is/issues/13511. 
Related migration issue for this change: https://github.com/wso2/product-is/issues/13516

Closing the issue.
