### ISSUE TITLE
problem with the PickupDispatch sample app

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-is#11404]
**Describe the issue:**
I downloaded the app and configure IS as described here: https://is.docs.wso2.com/en/5.9.0/learn/deploying-the-sample-app/#deploying-the-pickup-dispatch-webapp

However when I try to login the page http://localhost.com:8080/pickup-dispatch/home.jsp, i can't and I see the following error in the localhost_access_log:
"GET /pickup-dispatch/oauth2client?error_description=Required+consent+not+found&error=consent_required&session_state=3da47831225acab4e2211daf39ff188f8f30944d5ffbe4afbde91899d38c6a64.bzGZPVE7lXfBId6uq2uz-Q HTTP/1.1" 302

what can be the issue?

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
This issue is happening due to this https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L2200. Since pickup dispatch uses OIDC session managemennt by default, we need select `Approve Always` consent
