### ISSUE TITLE
Newly created users are unable to login 

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11840]
**Describe the issue:**
With the [PR](https://github.com/wso2-support/identity-governance/pull/330), newly created users are unable to login when the askPassword attribute is present in the request (It overrides the password sent in the request with a random password).

**How to reproduce:**
Set askPassword attribute in the request and create a user.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by ChamathNS** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/508.

**Comment by rksk** [comment]
This configuration is false by default. It means we have not preserved backward compatibility.

**Comment by ChamathNS** [comment]
> This configuration is false by default. It means we have not preserved backward compatibility.

The behaviour in the default configuration should be, to set random values to credentials when the `askPassword` claim is present, right?

The configuration we introduced: `DisableRandomValueForCredentials` would disable setting random values to credentials when set to true. Hence, the default value of the configuration is set to 'false'.

**Comment by mifrazmurthaja** [comment]
> The behaviour in the default configuration should be, to set random values to credentials when the `askPassword` claim is present, right?

No, in the context of maintaining backward compatibility, we shouldn't change the password set by the user. A random password should be generated, only if the password is not present in the request. Further, this is applicable, if we're validating the value of the **askPassword** (`true/ false`). However, currently, only the presence of the attribute is validated and not the value. **Hence, if a user is created with askPassword set to false, with the default configurations, the user will not be able to login.**

**Comment by ChamathNS** [comment]
Hi @mifrazmurthaja here in the fix[1], what we did was to set the password a random value if the newly introduced config is 'false`. With the default value for the config being "false", we would preserve the pre-existing behavior as per [1], wouldn't we?.

[1] - https://github.com/wso2-support/identity-governance/pull/357/files

**Comment by rksk** [comment]
I think the confusion is that there were two stages.
01. no change was done to password regardless of `askPassword` 
02. a random password is used when `askPassword` is present regardless of the password value sent

Currently we are keeping 02 behaviour with `DisableRandomValueForCredentials = false`. But majority of the users might be expecting 01 as the default behaviour. Now they have to add `DisableRandomValueForCredentials = false` config to have previous behaviour after taking an update.

I agree that we can not keep 01 since there might be users who are already using 02 state and their usecase will start to break after an update. 

But 01 users also face an issue with adding users from management console (with ask password) since the random password generated from the [DefaultPasswordGenerator](https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.common/src/main/java/org/wso2/carbon/user/mgt/common/DefaultPasswordGenerator.java) is now overiddeden by [UserEmailVerificationHandler](https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java). The password complexity is now reduced hence the users who were having following regex set in the userstore password regex are now failing to add users if they do not set `DisableRandomValueForCredentials = true` manually after an update.

```
^((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%&*])).{0,100}$
```

Therefore, I would like to make two suggestions,
- Skip overriding the password at `UserEmailVerificationHandler` if is not empty
- Increase the complexity of the password generated by `UserEmailVerificationHandler` to match with `DefaultPasswordGenerator`
