### ISSUE TITLE
Use Async logger in log4j2 

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#11947]
**Is your suggestion related to an experience ? Please describe.**
We should move to Async logger for the file appenders to improve the performance. File write will cause IO. The asynchronous logger in Log4J 2 does this by decoupling the logging overhead from the thread executing your code. So we can reduce the load on the exciting thread.

**Comment by ImalshaG** [comment]
To enable async logging, disruptor-3.3.4.jar or higher is required. Therefore disruptor version bundled by the carbon-analytics-common repo should be upgraded from 3.3.2.wso2v2 to 3.4.2.wso2v1 which will be addressed by:
-  https://github.com/wso2/carbon-analytics-common/pull/776.

After carbon-analytics-common release v5.2.34, due to the http component upgrade the IS server is getting OutOfMemory errors at the server startup because there are different versions of httpcore and httpclient available. Following PRs will upgrade the httpcore, httpclient, httpmime and openid4java versions to resolve this issue.

- https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/79
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/350
- https://github.com/wso2/carbon-registry/pull/375

**Comment by ImalshaG** [comment]
Async logging can be enabled by adding the following config to the 
`<IS-HOME>/repository/conf/etc/pax-logging.properties` file.

```
org.ops4j.pax.logging.log4j2.async=true
```

**Comment by piraveena** [comment]
@ImalshaG Do we have anything pending here?

**Comment by ImalshaG** [comment]
The backend implementation is done and the asgardeo related additional changes will be tracked by https://github.com/wso2-enterprise/asgardeo-product/issues/4844. Hence, we can close this issue.
