### ISSUE TITLE
[consoleApp] When trying to access the console app browser ends up with a white screen.

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#12137]
**Describe the issue:**
When trying to access the /console browser it ends up with a white screen. The following stack trace was there in the console of the browser.
![image](https://user-images.githubusercontent.com/31571237/126060065-8a8b4968-1815-4cef-bc77-4ddd1685280b.png)

How to reproduce
1. Build the 5.12.0-m30-SNAPSHOT and start the server.
2. Try to access the console app.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-m30-SNAPSHOT
 - OS:  Linux
 - Browser [Firefox, Chrome]
 - Database Default

**Comment by brionmario** [comment]
Seems to be happening due to JSON syntax error in the `webapss/console/deployment.config.json.

```json
"generalConfigurations": {
    "disabledFeatures": [],
    "enabled": ,  // syntax error here.
```

`general_configurations` default.json configs have been removed in [this PR](https://github.com/wso2/carbon-identity-framework/pull/3608/files#diff-ccd8d78f18b752f00ba42b5384248d7b8e8c6cc965a44569e2654ca6ce5bb616L756) and `governance_connectors` config has been introduced but there are no references for `governance_connectors` in the [J2 file](https://github.com/wso2/identity-apps/blob/master/features/org.wso2.identity.apps.console.server.feature/resources/deployment.config.json.j2#L288).

**Comment by brionmario** [comment]
@AnuradhaSK Let's make sure this is fixed before the next milestone release.

**Comment by AnuradhaSK** [comment]
Reverted the problematic changes in https://github.com/wso2/carbon-identity-framework/pull/3619
