### ISSUE TITLE
Username recovery is not working after super admin password change

### ISSUE THREAD

**Issue by maneeshaindrachapa** [wso2/product-is#12469]
## **Issue**
Username recovery is not working after the super admin password is changed

### **How to reproduce:**

- Log in to admin console as super admin
- Create a new user and assign the required claims
- Enable username recovery in the resident identity provider
- Go to "_myaccount_" URL and try username recovery for the newly created user
- Which will give the error message of the below
```
Callback URL validation failed. org.wso2.carbon.identity.mgt.endpoint.util.client.IdentityRecoveryException: Error while instantiating IdentityProviderMgtServiceStub
```

### **Expected behaviour:**
Get a successful message of email username recovery information has been sent to your mail.

### **Environment information** 
 - Product Version: IS 5.11.0 , IS 5.10.0
 - OS: Linux - Ubuntu

### **Suggested development**
When the super admin user password is changed the **_RecoveryEndpointConfig.properties_** file admin username is not updated, need to update that property file when the admin password is changed. The file is located in **_accountrecoveryendpoint_**

**Comment by LakshiAthapaththu** [comment]
**In IS 5.11.0** -  super admin password  is read from RecoveryEndpointConfig.properties which resides in <IS_HOME>/repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/classes
After changing the super admin password, have to update the identity.server.service.access.password in RecoveryEndpointConfig.properties to the updated password in order to get callback url validated successfully. 

**In IS 5.12.0** - super admin password  is read from RecoveryEndpointConfig.properties which resides in <IS_HOME>/repository/conf/identity. 

But simply updating identity.server.service.access.password did not resolve the issue.

In https://github.com/wso2/carbon-identity-framework/pull/3207 the identity.server.service.access.password in RecoveryEndpointConfig.properties has been  templated and default values are set. Therefore, reset password should be configured as mentioned in https://github.com/wso2/product-is/issues/10315 to get that applied to the RecoveryEndpointConfig.properties.
