### ISSUE TITLE
Enabling read-only in user claims does not get applied to the console app

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#12837]
**Describe the issue:**
The read-only validation is not carried out for the user claims in Console App. Even though the claim is set to read-only, privileged users can update the user claim via the console app.
**How to reproduce:**

1. Enable read-only for a claim via the management console
![mgt-console](https://user-images.githubusercontent.com/36409448/144368383-ed8e62c8-ce0a-4bbb-a8db-c01b8bfc2953.png)

2. log in to the console app and try to edit that particular user claim from the console app 
![console-app](https://user-images.githubusercontent.com/36409448/144371302-752dcd4d-c800-404e-843c-0e85033a4e62.png)

**Expected behavior:**
The user should not be able to modify the read-only enabled claims 

**Environment information:**
 - Product Version: IS 5.11.0
 - OS:Linux
 - Browser: Chrome
---

**Comment by AnuradhaSK** [comment]
In 5.12.0-alpha9: if a claim is marked as read-only
- claim field is disabled in the console user profile -> Need to backport this to 5.11.0
- claim field is uneditable in my account user profile -> Fixed in IS-5.11.0 too
- BE allows updating read-only attributes - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/401 this is the BE PR for the master to fix this issue. need to backport this to 5.11.0. 
PS: read-only check has been removed from https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/401/files#diff-df0ead0dd10d4c36057797f416103585ee1a1b931cb8a7cf67e5cfac43e0dde9R224-R225 (identity claims and scim meta attribute. Recheck against all by default read-only attributes)

**Comment by nilasini** [comment]
@ImalshaG Can we close this issue? Is there anything pending?

**Comment by ImalshaG** [comment]
The console app related fixes needed for this issue are done and the SCIM related changes regarding the read-only claim will be addressed in a separate issue - https://github.com/wso2/product-is/issues/12910. 
Hence, closing this issue.
