### ISSUE TITLE
Exceptions occurred in authenticators are not handled appropriately

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#12947]
**Describe the issue:**
When an unexpected error has occurred in authenticators, the cause of the issue is not logged to identify the exact problem.

For instance, consider the DUO authenticator [1], if an unexpected error occurs then it is just re-directed without exactly logging the exception. There is no way to differentiate between an actual error and an authentication failure due to invalid credentials.

**Expected behavior:**
There should be a way to differentiate errors and authentication failures due to invalid credentials. If it was an error, the cause of the error should be logged to identify the problem. 

[1] https://github.com/wso2-extensions/identity-outbound-auth-duo/blob/e557cdcb2ad00feb9fa9bf7fdd2624008d8ba217/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java#L486

**Comment by piraveena** [comment]
This is handled from the framework by adding relevant debug logs

**Comment by deshankoswatte** [comment]
It is not a good standard practice to enable debug logs just to find an error. Debug logs are used obtain further information regarding errors. In my PR https://github.com/wso2-extensions/identity-outbound-auth-duo/pull/48, I have added error logs within the catch phrases so that by default the error will be logged without requiring to enable debug logs.
