### ISSUE TITLE
Incorrect destination URL is picked for tenants during destination validation for tenants. 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#13037]
**Describe the issue:**
When trying a login scenario for a SAML SP in a newly created tenant, the following error can be seen. 
```
Destination validation for Authentication Request failed. Received: [https://localhost:9443/samlsso?tenantDomain=t2.com]. Expected one in the list: [https://localhost:9443/samlsso]
```
This is not observed when the OOTB destination URL is readded again.

**How to reproduce:**

- Configure SAML SP for a tenant as in [1]. NOTE: enable signature validation and single logout (front channel logout - HTTP Post binding).
- Try loging in to the app.

[1] - https://piraveenaparalogarajah.medium.com/trying-out-saml2-pick-up-dispatch-app-with-wso2-identity-server-in-a-tenant-20626ac4865a

**Expected behavior:**
The by default destination URL should be picked by the server.
![Screenshot 2022-01-26 at 13 57 51](https://user-images.githubusercontent.com/39567992/151128748-36b9b96c-15bb-4349-b933-3d7fce04bf67.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 and above
 - OS: [e.g., Windows, Linux, Mac]

**Comment by piraveena** [comment]
By default, in the server it is configured as `https://localhost:9443/samlsso?tenantDomain=t2.com`. But in the server startup, this value is not read properly. At the server startup, from here https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/v5.9.2/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/util/SAMLSSOUtil.java#L661 destination URL is coming as null. Since it is null, it takes the default value `https://localhost:9443/samlsso`. But once we update the Resident IdP config again to `https://localhost:9443/samlsso?tenantDomain=t2.com`, it will work.
