### ISSUE TITLE
[SSO][Recaptcha] Recaptcha is not displayed after the user account is locked and the email notification is not sent

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13195]
**Describe the issue:**
When account locking (5 attempts) and `Prompt reCaptcha after max failed attempts` (3 attempts) enabled, recaptcha is prompted after the max failed attempts exceeded. However, if the user keeps on entering incorrect passwords, recaptcha prompt is disabled after the account is locked.

**How to reproduce:**
(Checked with IS resident IdP)
1. Enable `Lock user accounts on maximum failed attempts` - max failed attempts: 5
2. Enable `Prompt reCaptcha after max failed attempts` - max failed attempts for recaptcha: 3
3. Start IdP initiated SSO flow to a SP, use a valid username and provide incorrect password

**Actual outcome:**
- Recaptcha is prompted after 3 failed attempts
- Recaptcha prompt is not displayed after 5 failed attempts
- Try with a different account on the same window, recaptcha is prompted again after 3 failed attempts
- FE Error message states `Login failed! Please check your username and password and try again.`, no mention about the account being locked
- Warning (see comment 1) logged
- Account lock notification email is not received when the account is locked

**Expected behavior:**
- Recaptcha should continue to be prompted after the failed attempts
- Account lock notification email should be received

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 13
 - OS: Windows 10
 - Database: MySQL
 - Userstore: JDBC
 - Browser: Firefox 97

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by deshalw** [comment]
Warnings:
```[3dd423b0-baf3-4d7d-aec8-99369a053ab7]  WARN {org.wso2.carbon.identity.captcha.filter.CaptchaFilter} - Captcha validation failed for the user. Cause : reCaptcha response is not available in the request.```

Screen capture:

https://user-images.githubusercontent.com/37894306/156716443-79b9df05-0a1c-48a1-ba34-fa36499f3da8.mp4

**Comment by IsuraD** [comment]
Have you following this https://is.docs.wso2.com/en/latest/learn/setting-up-recaptcha/ and configure recaptcha keys?

**Comment by sandushi** [comment]
I tried with below configurations, and the flow is worked as expected. 

- Configuration : 
   - Enable `Lock user accounts on maximum failed attempts` -> max failed attempts: 5
   - Enable `Prompt reCaptcha after max failed attempts` -> max failed attempts for recaptcha: 3
   
- Expected behavior is, reCaptcha is prompted after 3 failed attempts and account is locked after 5 failed attempts. And after the 5 failed attempts, user cannot log in until user is unlocked. **Then reCaptcha is not required to prompt after 5 failed attempts because the users cannot login**. 

- Regarding to **Account lock notification email is not received when the account is locked** --> If email is configured in user profile of user,  notification email is received  when the account is locked.

- Regarding to **FE Error message states Login failed! Please check your username and password and try again** --> 
    -    Common Auth failure message is showed in the login page even user is locked. 
    - If we want to show the actual Auth failure message in login page , it is required to configure below in the `deployment.toml`
    
    `[authentication.authenticator.basic.parameters]`
    `showAuthFailureReason = true`
    `showAuthFailureReasonOnLoginPage = true`

![Screenshot from 2022-04-28 06-55-27](https://user-images.githubusercontent.com/36092400/165673586-6188db49-9c9a-4274-95e1-07712ce516dd.png)


- But the expected behavior, "Not required to prompt reCaptcha after max failed attempts to lock user account because user cannot login after the account is locked" is not clearly mentioned in the documentation. https://is.docs.wso2.com/en/latest/learn/configuring-recaptcha-for-single-sign-on/

**Comment by nilasini** [comment]
@sandushi Can you please create a doc issue and link here?
