### ISSUE TITLE
When a customer user tries recover the account with Forget password option when his login identifier is not username user is not notified about mismatching login identifier inputs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13242]
**How to reproduce:**
1. Login to console and enable multi attribute login for the claim mobile
2. Register a new customer user
3. Set the mobile number for the customer user in his profile
4. Enable account recovery via email from console account management section
5. Access console login URL and click forget password option
6. In the login identifier field enter the identifier as "admin" even though your login identifier is not set to username
7. You will receive a notification as recovery details sent for admin 

![a](https://user-images.githubusercontent.com/31848014/157841771-97acaddd-e1c6-4593-a018-31fc6524be91.png)

https://user-images.githubusercontent.com/31848014/157841813-0432138e-f73c-4583-8848-395f88c02247.mp4

**Expected Behaviour**

Here when the user input a value which is not his login identifier user should be notified that he haven't input the correct login identifier
Here whatever user input that value will be displayed in the popup message. If user input admin popup message will show it as admin. But during a scenario user haven't input the correct login identifier value user will be mis guided due to this

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 15

**Comment by AnuradhaSK** [comment]
IMO showing the account name as whatever the user input to the password recovery option's user identifier field in this message is okay. because:

- Once the multi-attribute login is supported in an IS. the applications integrated to IS users need to use the configured claim for login (not the username).
- In our authentication portal/recovery portal's user identifier input has the placeholder or input label as "User Identifier" it doesn't specify which claim is the user identifier. But if some user wants to display the actual user identifier (email/ mobile) that can be done by customizing/changing the portals. If the field species what value exactly need to put. So the above mention message is acceptable.
- If the IS supports multi-attribute login and multiple allowed claims for login (email or mobile or username) we need to dynamically generate the user identifier placeholders/ input field labels. As you have mentioned if we need to mention that user input is not a valid login identifier it is difficult when multiple allowed claims are configured.

WHAT NEED TO BE FIXED:

- In the scenario that multi-attribute login is enabled but username claim is **not configured** as an allowed claim if the user input an existing user's username for password recovery it triggers a password recovery event and sends a mail to that user. This should be avoided. 
- Fixed in https://github.com/wso2-extensions/identity-governance/pull/581
