### ISSUE TITLE
API response does not output the Location parameter and gives a UI error page as OAuth Processing Error when trying request path authentication flow

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13251]
**How to reproduce:**
1. Enable Multi attribute login for claim mobile https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/
2. Create a OIDC SP and setup playground app
3. Skip the login consent from local and outbound configs
4. Update the admin users mobile number from his profile
5. Add below config to deployment.toml 

```
[oauth]
consent_prompt=false

```
6. Try Request path authentication flows by providing mobile number value for username fields https://is.docs.wso2.com/en/latest/learn/oauth-request-path-authentication/

```
curl --location --request POST 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
--header 'Authorization: Basic RU1pYXdqeUJQYjZ0N0pEUlVSU1cxYXlvMlhnYTpNX2xXX1BWN2dJaW5QamRWZmxNbUZxR0Y2M1Fh' \
--header 'Cookie: JSESSIONID=ADBDB69F1ED4DCCD43779DCE4286719A6FBC586EBF813B6C2995884DB5C12B66AD4C901C04F490AA00CCB9E31FE8E3E31B1B25D7883F39A213773B09884DD8ACCCDE56A78C497B2C0EF727711E62B5420882D2769D65ECDE639BACC7D7F45D021544B6C26B7318EB38A9B68EF560CDFAA8E0D5CE62880803D40FA546907EA862; commonAuthId=b570cd38-3f88-4def-b6b9-bf2e16c725cb; opbs=34cb9b6d-0369-4afa-a4e4-c43c91b833fe' \
--data-raw 'grant_type=password&username=0713344555&password=admin'
```

```
curl --location --request POST 'https://localhost:9443/oauth2/authorize' \
--header 'Authorization: Bearer 484a3128-b98b-3164-9f64-45b19af26d27' \
--header 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
--header 'Cookie: JSESSIONID=ADBDB69F1ED4DCCD43779DCE4286719A6FBC586EBF813B6C2995884DB5C12B66AD4C901C04F490AA00CCB9E31FE8E3E31B1B25D7883F39A213773B09884DD8ACCCDE56A78C497B2C0EF727711E62B5420882D2769D65ECDE639BACC7D7F45D021544B6C26B7318EB38A9B68EF560CDFAA8E0D5CE62880803D40FA546907EA862; commonAuthId=b570cd38-3f88-4def-b6b9-bf2e16c725cb; opbs=34cb9b6d-0369-4afa-a4e4-c43c91b833fe' \
--data-raw 'response_type=code&client_id=EMiawjyBPb6t7JDRURSW1ayo2Xga&redirect_uri=http://localhost:8080/playground2/oauth2client&scope=openid'
```
**Actual behavior:**
Getting 200 in the API response with a HTML page for playground apps login page
Not getting the response from the API as below as mentioned in the doc https://is.docs.wso2.com/en/latest/learn/oauth-request-path-authentication/

`Location: https://curl-app/callback?code=37c79c505960e90d5b25f62ce760c98c&session_state=6d1a72e0f3f6392d6648ec5e6ed0`

![Screenshot from 2022-03-14 23-06-34](https://user-images.githubusercontent.com/31848014/158231005-e3be2f28-9fd0-40a5-a5ff-acf879a4d8f0.png)
![Screenshot from 2022-03-14 23-07-03](https://user-images.githubusercontent.com/31848014/158231051-e7ddaac3-4eec-4e93-b1f2-bea26faf258f.png)
![Screenshot from 2022-03-14 23-09-06](https://user-images.githubusercontent.com/31848014/158231075-dfc5ba1a-48d6-4a40-b4ab-ddd9d3e8e3da.png)

When try with oauth authenticator by following https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/ using playground apps UI getting the below error page

![Screenshot from 2022-03-14 23-29-41](https://user-images.githubusercontent.com/31848014/158233297-d013d7ab-a1e3-4c9f-a743-1930ce0fd04d.png)

Browser URL  for the landed page

`https://localhost:9443/authenticationendpoint/oauth2_error.do?oauthErrorCode=invalid_request&oauthErrorMsg=Invalid+authorization+request`

Attaching a Video

https://user-images.githubusercontent.com/31848014/158235550-870eca35-02e0-4d17-9fc6-50a1a4dc90a8.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 15
H2/Default

**Comment by sandushi** [comment]
- **Request path authentication flow** is used to authenticate user without having an identity provider login page to prompt the end user for credentials because authenticate requests contain the user’s credentials

- Regarding to the "**Getting 200 in the API response with a HTML page for playground apps login page
Not getting the response from the API as** `Location: https://curl-app/callback?code=37c79c505960e90d5b25f62ce760c98c&session_state=6d1a72e0f3f6392d6648ec5e6ed0` "

1. When we enable the `Automatically follow redirects` in postman settings, We get the response as you mentioned in the issue

        
```
 curl --location --request POST 'https://localhost:9443/oauth2/authorize' \
--header 'Authorization: Bearer e9eef4ca-c141-3516-8b79-aeef52ef93bf' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: commonAuthId=6b3f8dfc-7d75-4dfb-8fad-889fe6233a38; opbs=67179bce-13c6-43d5-a525-32918b57931c' \
--data-urlencode 'response_type=code' \
--data-urlencode 'client_id=h1EKlJd_LnnpQRqcBBphzXXie34a' \
--data-urlencode 'redirect_uri=http://localhost.com:8080/playground2/oauth2client' \
--data-urlencode 'scope=openid'
```
![Screenshot from 2022-04-08 16-48-49](https://user-images.githubusercontent.com/36092400/162426031-55aa8bc8-1993-4788-83b5-6661a4f78421.png)

2.When disable that option in postman settings, it gives the response as in doc https://is.docs.wso2.com/en/latest/learn/oauth-request-path-authentication/

![Screenshot from 2022-04-08 17-04-27](https://user-images.githubusercontent.com/36092400/162427851-291c4a0e-cad4-4f85-94c6-7518742ebf7d.png)

3. And I tried above curl using the terminal, it gives the response
![Screenshot from 2022-04-08 17-08-02](https://user-images.githubusercontent.com/36092400/162428357-a5291ab7-340c-4afe-8d28-8d16f649a8c2.png)

- Regarding to "**When try with oauth authenticator by following https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/ using playground apps UI getting the below error page**"

   - `accesstoken` can be passed as a query parameter in the request path authentication flow as mentione in the doc  https://is.docs.wso2.com/en/latest/learn/oauth-request-path-authentication/
   
       1. using `https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/` as in doc https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/  gives an error page as mentioned in the issue due to `invalid client exception`  , because in this request there is  not passing the `clientId`
       
       2. below curl responses as mentioned in the doc  https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/
       

```
curl --location --request POST 'https://localhost:9443/oauth2/authorize?access_token=e9eef4ca-c141-3516-8b79-aeef52ef93bf' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: commonAuthId=11610e72-f89a-4997-9fb7-d5037db381ea; opbs=67179bce-13c6-43d5-a525-32918b57931c' \
--data-urlencode 'response_type=code' \
--data-urlencode 'client_id=h1EKlJd_LnnpQRqcBBphzXXie34a' \
--data-urlencode 'redirect_uri=http://localhost.com:8080/playground2/oauth2client' \
--data-urlencode 'scope=openid'
```
![Screenshot from 2022-04-08 17-32-13](https://user-images.githubusercontent.com/36092400/162431724-b81cd0a9-fdda-4bc3-92fb-316388f71b52.png)


- According to these results there is no issues in the flow

- **My Suggestion** : needs to update the doc https://is.docs.wso2.com/en/latest/learn/try-request-path-authentication/ with more information 

- I have created a doc issue mentioning this https://github.com/wso2/product-is/issues/13437
