### ISSUE TITLE
Cannot Recover Password from myaccount when there are 2 users as admin & userstoredomain/admin when multiattribute login is enabled

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13266]
**How to reproduce:**
1. Register a unique id read write ldap as a secondory Userstore in a primary IS
2. So in the system there will be 2 usernames as admin (admin & userstoredomain/admin)
3. Enable multiattribute login for mobile claim and set the mobile number value in admin users user profile
4. Enable smtp configs for email sending in deployment.toml and set a gmail account email address too for the admin user in the user profile
5. Access myaccount
6. Click Forget Password
7. As the login identifier enter the mobile number of the admin user

**Actual Behavior**

When try to recover password getting a error message as theres are 2 usernames as admin
But here as the login identifier is mobile such a error page should not displayed 
We need to handle this scenario properly when the login identifier is set for another claim
![b](https://user-images.githubusercontent.com/31848014/158573067-23cca953-3742-4783-8347-51e85747d705.png)

https://user-images.githubusercontent.com/31848014/158573076-5956d615-5991-4029-bf77-80d4cd7aaad8.mp4

**Env**
IS 5.12.0 alpha 15
secondory US uniqueid read write ldap

**Comment by AnuradhaSK** [comment]
IMO this message showing the account name as what ever the user input to the password recovery option's useridentifer field is okay. because:

- Once the multi attribute login is supported in a IS. the applications integrated to IS uses need to use the configured claim for login (not the username). That need to be known by the endusers anyway.
- In our authentication portal / recovery portal's user identifier input has the placeholder or input label as "User Identifier" it doesn't specify which claim is the user identifier. But if some user wants to display the actual user identifier (email/ mobile) that can be done by customizing/changing the portals. If the field species what value execatly need to put. So the above mention message is acceptable.
- If the IS support multi attribute login and multiple allowed claims for login (email or mobile or username) we need to dynamically generate the user identifier placeholders/ input field labels. 

WHAT NEED TO BE FIXED:

- In the scenario that multi attribute login is enabled but username claim is **not configured** as allowed claim, if the user input an existing user's username for password recovery it triggers a password recover event and send a mail to that users. This should be avoided. 
- Fixed in https://github.com/wso2-extensions/identity-governance/pull/581

**Comment by AnuradhaSK** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/581 changes

https://user-images.githubusercontent.com/25483865/160141379-416f19f9-0f95-4b0d-b94a-8eca92757a11.mp4
