### ISSUE TITLE
JWKS end point can to be override by certificates.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13314]
**Describe the issue:**
JWKS end point can to be override by certificates. But this is can be done in other way round. 

https://user-images.githubusercontent.com/39077751/159829887-2c8b6314-dff0-42dc-a476-03c647b29391.mov

**How to reproduce:**
1. Login to Console.
2. Create OIDC application and add JWKS end point at the application creation time.
3. Navigate to protocol section and select certification to upload and override the JWKS endpoint

**Expected behavior:**
Once the user select to override the JWKS end point with the certification it should be allow  and notify the with the warning message.

Ex: 
<img width="503" alt="Screenshot 2022-03-24 at 07 47 10" src="https://user-images.githubusercontent.com/39077751/159829539-aab4dd11-3612-43ba-91c5-e4dccb73aaa2.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] IS 5.12.0 alpha 16
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
This happens in IDP section, not in application section

**Comment by piraveena** [comment]
Similar issue is reported here https://github.com/wso2/product-is/issues/12986

**Comment by minolih** [comment]
The above issue was reproduced in IdP section. Issue is not available in Application section. 
Issue in IdP section where an error is thrown when replacing JWKS URL with Certificate is fixed by https://github.com/wso2/identity-apps/pull/2918. 

Not displaying a warning when switching the tabs on overriding the current JWKS URL or certifcate is tracked as a different issue with https://github.com/wso2/product-is/issues/13398.
