### ISSUE TITLE
Updating/Viewing claims in OIDC scopes lead to removal of a claim

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#13365]
**Describe the issue:**
Trying to view claims of OIDC scope leads to a confusing user interface where all the checkboxes are not selected. It convince the user to click and enable them in order to use those claims and then finish the process. This leads to removal of those selected claims from the selected OIDC scope.

**How to reproduce:**
* Go to carbon console -> Manage -> OIDC Scopes -> List
* Click on the update button of any scope (i.e. : openid)
* Select some claims and click finish button (Not the remove button)
* Check again and now the claim is gone from the scope.

**Expected behavior:**
Claim should still there if the remove button is not pressed after the selection.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.12.0-alpha-14, Affects 5.11 too]
 - OS: [Linux Ubuntu 20.04]
 - Database: [Any]
 - Userstore: [Any]

**Comment by sandushi** [comment]
- Purpose of buttons
   - **remove** button :  remove the selected  claim/claims and stay in the same edit UI
   - **finish** button : redirect to the scope list UI after user removing the claims
   
- But, as mentioned in the issue if a user select a claim and click on finish button the selected claim is removed from the scope claims and redirect to the scope list UI because the selected claims are deleted before redirect to the scope list UI. 

- The button name **finish** doesn't give a clear meaning to the user in this section and this affects to the better UX. 

- **back** button in this UI is also used to redirect to the scope list UI. So as a suggestion we can remove the **finish** button as we can do the same thing using **back** button. 

- We can reduce the priority level of this issue as this issue is not affected to break the flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
