### ISSUE TITLE
SMS OTP event publisher in SMS Authenticator

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#13394]
**Is your suggestion related to an experience ? Please describe.**
The capability to trigger and publish an SMS OTP request event via the SMS OTP Authenticator if required should be provided as an improvement.

**Describe the improvement**
If required upon initiating an SMS OTP event, the SMS OTP Authenticator should be able to trigger and publish the event when the url is not configured (meaning, it is required to go ahead with the SMS publisher configuration). To achieve this, the notification channel should be added to trigger the SMS publisher [1].

[1] https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1508

**Comment by Pratheesha97** [comment]
### **Issue Summary:**

**Root Cause:**

- SMSOTP template not picked correctly due to missing the notification channel event. 

The event is published as expected, but it fails to trigger the notification due to missing the notification channel event. Due to the absence of the notification channel event ('SMS'), it takes 'Email' as the default notification channel and checks for the SMSOTP template using the path '/identity/email/smsotp' in registry resources. As the SMSOTP template is not found in the given path, it throws the following error.

`[2023-02-10 20:02:53,641]  WARN {org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator} -  Error occurred while calling triggerNotification, detail : org.wso2.carbon.email.mgt.exceptions.NotificationTemplateManagerServerException: Cannot find 'SMSOTP' template in the default 'en_US' locale for 'carbon.super' tenant`

**Steps to Reproduce:**

1. Create a new stream and publisher to facilitate SMS notifications [1] 

2. Configure SMS OTP as a Federated IdP via management console [2]. While configuring the IdP, leave the URL, payload and other fields on the screen blank. (meaning, it is required to proceed with the SMS publisher configuration when triggering notifications).

3. Try out the Login Flow.

**Fix:**

https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/v3.3.8/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1567-L1568

**References:**

[1] - https://docs.wso2.com/display/IS570/Configuring+Account+Recovery+Via+User+Preferred+Notification+Channel#:~:text=Create%20a%20new%20stream%20and%20add%20it%20to%20the%C2%A0%3CIS_HOME%3E/repository/deployment/server/eventstreams%C2%A0folder.%20A%20sample%20stream%20is%20given%20below.

[2] - https://docs.wso2.com/display/IS570/Configuring+SMS+OTP
