### ISSUE TITLE
Linked social accounts are not displayed in myaccount as expected

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13573]
**How to reproduce:**

Follow the steps for scenario 1 mentioned in blog https://medium.com/identity-beyond-borders/social-account-linking-with-wso2-identity-server-78b8a566e225

1. Register travelocity as SP
2. Register google as a IDP (idp name =google)
3. Configure basic and google as authenticators under step1
4. Add the adaptive script mentioned in blog under scenario 1
5. Add below config to deploymnet.toml
```
[user.association]
enable_for_federated_users = true

```
6. In local and outbound configs select Assert identity using mapped local subject identifier
7. Add a new user and register shnaikaw@wso2.com as the email from user profile
8. Access travelocity login page
9. Select google as the login option
10. Login from shanikaw@wso2.com user account
11. Access myaccount and checked personel info > Linked socail accounts section

Linked account is not displayed

https://user-images.githubusercontent.com/31848014/165306151-765025dd-d1ae-4dfc-ac12-ed91b7d614fb.mp4

![Screenshot from 2022-04-26 18-36-43](https://user-images.githubusercontent.com/31848014/165306853-87e535fe-7141-4770-9972-af9e3443e7ca.png)
![Screenshot from 2022-04-26 18-36-52](https://user-images.githubusercontent.com/31848014/165306873-e0ba739a-24d4-45ab-a171-db2ed4ff5fbf.png)

**Env**
IS 5.12.0 alpha 21 snapshot pack

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
**- Scenario1: Getting consent from user before associating the federated account**
1. Create an Google federated Idp and name it as `google`.
2. Use the below adaptive script 
```
var onLoginRequest = function(context) {
    var fedUser;
    executeStep(1, {
        onSuccess: function(context) {
            var idpName = context.steps[1].idp;
            Log.info("Idp Name:" + idpName);

            // Only execute this flow when the user login from the google idp.
            // If you want to target all your idps you can use something like
            // idpName !== "LOCAL"
            if (idpName === "google") {
                fedUser = context.currentKnownSubject;
                Log.info("FedUser's email:" + fedUser.remoteClaims.email);

                // Check if there is already a user association
                var assocUser = getAssociatedLocalUser(fedUser);
                Log.info("Associated User:" + assocUser);
                if (assocUser == null) {
                    var claimMap = {};
                    claimMap["http://wso2.org/claims/emailaddress"] = fedUser.remoteClaims.email;
                    Log.info("FedUser email claim:" + fedUser.remoteClaims.email);

                    var storedLocalUser = getUniqueUserWithClaimValues(claimMap, context);
                    if (storedLocalUser !== null) {
                        // Prompt a screen showing info on the user association
                        prompt("associationConsentForm", {
                            "email": fedUser.remoteClaims.email
                        }, {
                            onSuccess: function(context) {
                                // Get the user decision to associate from the prompt
                                var decision = context.request.params.decision[0];
                                if (decision === "yes") {
                                    Log.info("Decision:" + decision);
                                    // Perform basic authenticaion to confirm account ownership
                                    executeStep(2, {
                                        onSuccess: function(context) {
                                            // Get the authenticated user from basic authentication step
                                            var authUser = context.steps[2].subject;

                                            // Do any additional validation here
                                            // E.g. Validate whether storedLocalUser that we found is same as the authenticated user
                                            // storedLocalUser.username == authUser.username

                                            // Do the account linking
                                            doAssociationWithLocalUser(fedUser, authUser.username, authUser.tenantDomain, authUser.userStoreDomain);
                                        }
                                    });
                                }
                            }
                        });
                    }
                }
            }

        }
    });

};
```
4. Added relevant jsp files as mentioned in the blog. These jsp files are needed to get consent from the user
5. We could able to get the linked social account from the myAccount
<img width="1362" alt="Screenshot 2022-04-27 at 16 08 04" src="https://user-images.githubusercontent.com/17597293/165500958-0333e74f-90c2-45a1-9b87-585ce396ad05.png">

Following the doc didn't work due to a change in the adaptive script function. https://github.com/wso2/product-is/issues/12056

**Comment by piraveena** [comment]
**Option2: Linking accounts using JIT provisioning**
if the subject coming from the federated account matches with username of the local account, and if JIT provisioning is enabled, then both accounts will be associated automatically.

To Try it:
1. Configure another IS as a federated IDP(`wso2is-idp`). In the claim configuration, configure username as the subject in the SP in the federated IDP
2. Create an user account with username `test` in the federated IdP.
3. Create an user with username `test` in the Primary IS.
4. Enable JIT Provisioning in the IDP `wso2is-idp`
5. Configure an app in the primary IS and enabled federated login with `wso2is-idp` IdP.
6. log in to the app.
The both federated IdP and local account will be auto-linked since both have the same username.
You can check that from the MyAccount.
<img width="1217" alt="Screenshot 2022-04-27 at 18 31 21" src="https://user-images.githubusercontent.com/17597293/165534387-c3cf6248-f9e3-4b71-878d-0c476848b595.png">

**Comment by piraveena** [comment]
**Option 3: Linking local accounts**
https://is.docs.wso2.com/en/latest/learn/associating-user-accounts/ docs give the steps of linking local accounts. By using `UserAccountAssociationService` service, we can link the local accounts. This cannot be done for social account linking.

Also this doc https://is.docs.wso2.com/en/latest/learn/associating-user-accounts/ needs to be modified as `Associating Local User Accounts`. 

<img width="1123" alt="Screenshot 2022-04-28 at 09 59 28" src="https://user-images.githubusercontent.com/17597293/165676740-01807e3a-06f3-49ae-b239-e1199b5d225a.png">
