### ISSUE TITLE
Add OIDC scope management validations to IS-5.8.0

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#13624]
**Describe the issue:**
1. Scopes are not listed on the management console.
2. Claims cannot be added to a scope.

This an other issues were solved on #3979 3 years ago. However, those changes were merged for IS-5.7.0 and IS-5.9.0+, omitting the 5.8.0 version.

**How to reproduce:**
1. Update any OIDC scope and delete all of its claims.
2. Update any OIDC scope and delete some claim, then update the scope again and add the deleted claim.

**Expected behavior:**
1. If all claims of a scope are deleted the scope should remain listed on the management console.
2. The add claims to scope flow should work as expected.

**Environment information:**
 - Product Version: IS 5.8.0

**Comment by Yasara-Y** [comment]
@jcgarciaa The issue no.1 that you have described above is reproducible and the issue described in https://github.com/wso2/product-is/issues/3979 too is reproducible. 
But the issue you have mentioned in no.2 is not reproducible. Following are the steps I followed to reproduce it.
- Add a new oidc scope and add 2 claims to that. 
- Then delete one out of those 2 claims and update the scope.
- Next, add the deleted claim again to the same scope.

By following the above steps, I couldn't observe any glitch or error log. By the issue no.2 if you have meant the same issue in https://github.com/wso2/product-is/issues/3979, that's ok since that is reproducible. If not, could you please elaborate more on the steps to reproduce issue no.2 ?

Env info :
IS 5.8.0 latest U2 pack

**Comment by jcgarciaa** [comment]
Hi @Yasara-Y, I'll elaborate on the second case. I realized the issue happens when the claim you're adding is already present in another scope. Therefore:
- Go to the list of scopes.
- Update the openid scope and delete the nickname claim.
- Go back to the list of claims.
- Click Add Claims on the openid scope
- Add the nickname claim again.
The claim won't be added to the list.
