### ISSUE TITLE
Disable TOTP authenticator not functioning properly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#13662]
**Describe the issue:**
When we disable the TOTP for Identity Server using following toml configuration, it  is still working.
```

[authentication.authenticator.totp]
enable=false
```

**Expected behavior:**

The authentication steps for TOTP should not be generated, when it is disabled through toml configurations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.12.0 beta2]
 - OS: [e.g.Mac]
 

**Suggested labels:**

**Comment by Anandi-K** [comment]
The described behavior is not specific to TOTP. When any of the basic authenticators is disabled after the app is created the same scenario can be expected.

The expected behavior described in the issue is not practically achievable. We would have to remove the authenticator in DB from all the apps. Even if we were to achieve this, in a real life scenario if the disabled authenticator is the only authenticator used, when disabled it has no authenticators. Therefore, when an app is created and the TOTP or any authenticator is disabled through deployment.toml configuration the added apps should not be affected.

Since what this configuration should exactly do is a gray area, disabling authenticators using deployment.toml configuration will be removed from the docs as well.
