### ISSUE TITLE
Changing the app_title in My Account

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#13741]
**Describe the issue:**
According to [1], we should be able to change the app title of My Account in WSO2 IS with the following toml configuration:

```
[myaccount]
ui.app_title = "My Account | WSO2 IS"
```

However, this doesn't seem to work.

**Affected product version**
5.11.0

[1] https://github.com/wso2/identity-apps/blob/master/docs/CONFIGURATION.md#app_title

**Comment by LakshiAthapaththu** [comment]
This issue is already fixed via a patch.

**Comment by lacek** [comment]
@LakshiAthapaththu Is the patch is available to users of community edition?

If not, are there any guidelines for open source users to include relevant bug fixes (For now, I could only imagine one to fork from https://github.com/wso2/identity-apps, modify the title and build the MyAccount app from source)?

Otherwise, could you reveal the relevant repo(s) and commit(s) for the patch?

**Comment by LakshiAthapaththu** [comment]
@lacek 
This issue is not available in public branch. We haven't fix this issue separately in public branch as it got fixed when we do some other improvements/fixes.  Therefore there is no public PR which fixes the issue in public branch.

**Comment by piraveena** [comment]
@LakshiAthapaththu can we close this issue if it is not reproducible in the master?
