### ISSUE TITLE
Management Console and MyAccount pages don't load when Rancher Desktop is running

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#13763]
**Describe the issue:**

Management console and MyAccount pages stuck showing a loading icon when rancher desktop is running in the background.

<img width="1506" alt="Screenshot 2022-05-27 at 12 29 37" src="https://user-images.githubusercontent.com/45028707/170648723-fb790cbb-8331-4474-8b18-5eefbcc5ac77.png">

**How to reproduce:**

1. Start WSO2 IS
2. Start Rancher Desktop
3. Try to access [Management Console](https://localhost:9443/carbon) or [MyAccount](https://localhost:9443/myaccount) pages.

**Expected behavior:**

Pages should load without any issues.

**Environment information:**
 - Product Version: IS 6.0.0m1
 - OS: Mac 12.4 (M1)

**Comment by savindi7** [comment]
This is due to the Rancher dashboard which was introduced with the latest release and not an issue in Product IS. Disabling Kubernetes is the suggested workaround in order to run the Management console and My Account as expected. Please refer this link for more information on this - https://github.com/rancher-sandbox/rancher-desktop/security/advisories/GHSA-x5mj-x8h3-9pcc
