### ISSUE TITLE
The totalResults Value Is Incorrect in the Response for SCIM2 Paginated Get Users Request

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13772]
**Describe the issue:**
Get users endpoint in the SCIM2 API returns an incorrect value for the _totalResults_ attribute in the response when we set count parameter or startIndex parameter.
- Although there are 12 users in the primary user store, totalResults=2 in the SCIM2 API response when we request users with count=2 parameter.
- Although there are 12 users in the primary user store, totalResults=6 in the SCIM2 API response when we request users with startIndex=7 parameter.

<img width="843" alt="Screenshot 2022-05-30 at 11 00 41" src="https://user-images.githubusercontent.com/12953762/170923361-5f300551-f641-4527-824b-d4e1279fe331.png">
<img width="843" alt="Screenshot 2022-05-30 at 11 01 36" src="https://user-images.githubusercontent.com/12953762/170923385-28c1e666-89b5-4c8b-9422-8d5de07afd1b.png">
<img width="843" alt="Screenshot 2022-05-30 at 11 02 17" src="https://user-images.githubusercontent.com/12953762/170923388-2f983aa6-5325-414e-b454-9bd6486a2ec3.png">
<img width="843" alt="Screenshot 2022-05-30 at 11 02 32" src="https://user-images.githubusercontent.com/12953762/170923395-7a1d03b5-9fe2-41f9-8273-93b2df4acb9c.png">

**How to reproduce:**
1. Create multiple users (about 5 users) in the PRIMARY user store
2. Send a get request to the SCIM2 Users API by setting startIndex parameter (https://localhost:9443/scim2/Users?startIndex=3&domain=PRIMARY)
3. Send a get request to the SCIM2 Users API by setting count parameter (https://localhost:9443/scim2/Users?count=3&domain=PRIMARY)
4. Send a get request to the SCIM2 Users API by setting both startIndex and count parameters (https://localhost:9443/scim2/Users?startIndex=3&count=2&domain=PRIMARY)

**Expected behavior:**
The _totalResults_ attribute in the response should be equal to the number of total users in the primary user store but it's equal to the _itemsPerPage_ (which is less than the no of total users in user store when we set pagination params in the request). 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Comment by sahandilshan** [comment]
Hi @ravinduramesh 

This issue has already been discussed on several occasions now. Due to the limitation in the LDAP Store, we are unable to provide the total number of users for the LDAP user stores. But this is working without any issue with the JDBC store. As mentioned in this issue here https://github.com/wso2/docs-is/issues/1495 we need to update the is docs correctly.

**Comment by sahandilshan** [comment]
Hi @ravinduramesh 

Unlike the JDBC Stores, we cannot get the total user count in the LDAP stores. We have to fetch all users from the stores to get the count. We cannot perform this operation if the user store has a huge number of users because of performance issues. So we are setting a limit in the LDAP stores and we only get the user details up to that limit. So as you suggested, even if we perform two queries, it's not returning the correct total count if the LDAP store has lots of users.

**Comment by ravinduramesh** [comment]
Hi @sahandilshan 

Thanks for the detailed explanation. I opened a similar issue for roles also here [https://github.com/wso2/product-is/issues/13823](https://github.com/wso2/product-is/issues/13823). Could you please check that also.

**Comment by sahandilshan** [comment]
Closing this issue since this cannot be implemented due to the limitation in the LDAP. We have already updated the is-doc mentioning this limitation. You can track the progress of that [here](https://github.com/wso2/docs-is/issues/1495)
