### ISSUE TITLE
Custom Attributes(Claims) doesn't show up in the console app

### ISSUE THREAD

**Issue by Nirmal-De-Silva-99** [wso2/product-is#13868]
**Describe the issue:**
After creating a new attribute in the Console app and turning on the "Display this attribute on the user's profile" option, it still cannot be seen on the user's profile page in the Console App. But it can be viewed from the Management Console.

**How to reproduce:**
Create a new attribute(Claim) from the Console app or from the Management console. Both are okay to reproduce the issue.
<img width="527" alt="Screenshot 2022-06-07 143731" src="https://user-images.githubusercontent.com/65043823/172342454-6e667578-ae06-4196-bdd8-afeb36d263b3.png">

Here you can enter an existing attribute mapping. "address" is used here.
<img width="533" alt="Screenshot 2022-06-07 143816" src="https://user-images.githubusercontent.com/65043823/172342622-7e44a60d-4239-4473-bb5f-29b1fbf0ad67.png">

The newly created attribute can be found in the Management Console by navigating to Claims -> List -> http://wso2.org/claims
<img width="960" alt="Screenshot 2022-06-07 144719" src="https://user-images.githubusercontent.com/65043823/172344475-74d30c23-1aa8-49fb-bdcc-be0e757bed20.png">

Also, it can be viewed from Users and Roles -> List -> Users -> A user's User Profile -> default
![Web capture_7-6-2022_145345_localhost](https://user-images.githubusercontent.com/65043823/172345590-04f6f3d5-e74d-42dc-9c8e-fbed42499668.jpeg)

But the issue is, that the newly created attribute does not show up in the Console app.
![Web capture_7-6-2022_14565_localhost](https://user-images.githubusercontent.com/65043823/172346042-15add430-1159-465b-a82c-b49f7a49b7ca.jpeg)

**Expected behavior:**
A newly created Attribute(Claim) should be viewed from the Console app.

**Environment information:**
 - Product Version: [IS 6.0.0 M2]
 - OS: [Windows]
 - Database: [PostgreSQL]

**Comment by mpmadhavig** [comment]
### Solution 1
The console app and the myaccount app uses `/scim2/Me` API to recieve user profile attributes that are being displayed. 

So in order to display attributes you created in the user profile, you need to add a SCIM2 mapping to the attribute you created. This warning is already there in the user attribute info section that you will get redirected once the attribute is created. 

<img width="1512" alt="Screenshot 2023-01-24 at 12 05 27" src="https://user-images.githubusercontent.com/47152272/214227157-d12c2208-322b-4cea-9ca3-616f3d31d54b.png">

Click `here` button and get redirected to the SCIM mapped attributes page. Use the `Enterprise Schema` tab and create a SCIM user attribute mapping. 

The added mapping will be visible in `myaccount` -> `profile info` section.

### Solution 2

Use the below [documentation](https://is.docs.wso2.com/en/latest/references/extend/provisioning/extend-scim2-user-schemas/#add-the-custom-claim) link and follow the steps to add the custom attribute with a SCIM2 mapping.
