### ISSUE TITLE
Redirection issue in Claim Management API Definition and User's Challenge Questions and Answers API Definition

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13902]
**Is your suggestion related to a missing or misleading document? Please describe.**
_Run in Postman_ functionality in both [Claim Management API Definition](https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/#/) and [User's Challenge Questions and Answers API Definition](https://is.docs.wso2.com/en/latest/develop/challenge-rest-api/) redirects to the same API definitions in Postman as shown in the below figure.

<img width="1512" alt="Screenshot 2022-06-10 at 11 57 23" src="https://user-images.githubusercontent.com/38417165/173005002-28901d85-b646-4bf1-97ab-fc57e5daa7e2.png">

**Describe the improvement**
Correctly map the API definitions accordingly so that when opening in Postman it behaves correctly.

**Comment by Anandi-K** [comment]
This issue is not reproducible.
The mentioned Run in Postman functionality is not available on both [Claim Management API Definition](https://is.docs.wso2.com/en/latest/apis/claim-management-rest-api/#/) and [Challenge Answers API Definition](https://is.docs.wso2.com/en/latest/apis/challenge-rest-api/).

**Comment by nilminiwso2** [comment]
We will add postman collections to all API docs through this issue [1]. Therefore, let's close this one. 

[1] https://github.com/wso2/product-is/issues/13773
