### ISSUE TITLE
Basecamp connector does not integrate with Basecamp 2 product

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#13907]
**Describe the issue:**
To use Basecamp as a federated authenticator, I registered an application at [integrate.37signals.com](https://integrate.37signals.com/). The  [official guide](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Basecamp+Authenticator) instructs to select Basecamp 2 as the product with which the IS integrates. 
<img width="251" alt="Screenshot 2022-06-10 at 16 49 36" src="https://user-images.githubusercontent.com/28347418/173054259-a9db2c2d-180a-466b-9d5e-40aec352fbd1.png">

However with this configuration at the login, I am faced with the following error.
![Screenshot 2022-06-10 at 15-49-12 Authorize TestForIS6 integration](https://user-images.githubusercontent.com/28347418/173054231-9e2e8d17-c57d-4721-ac81-d67a0892c80d.png)

Note : If the IS is integrated with Basecamp 3, the authentication flow can be successfully completed without facing the above issue. 

**Environment information :**
 - Product Version: IS 6.0.0 - m1
 - OS: Mac OS 12.3.1
 - Database: Oracle12c
 - Userstore: JDBC

**Comment by asha15** [comment]
The issue occurred because you have integrated Basecamp 2 product with Basecamp 3 account. If we have a Basecamp 3 account, the integrated product should be Basecamp 3.

I have updated the documentation with this detail [1].

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Basecamp+Authenticator
