### ISSUE TITLE
Revoke all the possible tokens on an error in token revocation

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#14048]
**Describe the issue:**
Revoke all the possible tokens on an error in token revocation

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by lashinijay** [comment]
- This issue has been fixed in all the IS product versions except IS-5.8.
- The issue has been introduced with the following PR[1] and it has been ported to all the versions except IS-5.8. Therefore this issue is not reproducible IS-5.8.

[1] - [https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1501](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1501)
