### ISSUE TITLE
Doc Feedback: 403 occured while using GET /Users/{userId} endpoint of SCIM2 with scope internal_user_mgt_list

### ISSUE THREAD

**Issue by axiangcoding** [wso2/product-is#14140]
Location : https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/

Steps to Reproduce:
Get a access token using client_credentials grant with scope `internal_user_mgt_list`
Use it to call GET /Users, it returns all users information
Use it to call GET /Users/{userId} endpoint of SCIM2, it returns response :
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Operation is not permitted. You do not have permissions to make this request.",
    "status": 403
}
```

But according to the document, GET /Users/{userId} required scope `internal_user_mgt_list`, same as GET /Users, so i don't know why this error happend

**Comment by axiangcoding** [comment]
addition info: i'm using trial version Asgardeo, and the user i request is in my organization, could be something wrong here?

**Comment by chinthakarukshan** [comment]
@axiangcoding Please obtain a token using the scope **internal_user_mgt_view** and then use that token to call the GET /Users/{userId} endpoint.

**Comment by axiangcoding** [comment]
using scope **internal_user_mgt_view** for endpoint /Users/{userId} works, thanks

**Comment by Simkiw** [comment]
Hi,  

I tried adding that scope but I couldn't, whether from my web app or postman, i just couldn't.  
I could add whatever scope I wanted, but I couldn't add that scope, i don't see it in my token and it doesn't appear in the consent page. However, the other scopes do appear.  

Do you remember if you made any change from wso2 server side?

**Comment by Simkiw** [comment]
That's kinda true.  

I found the answer in one of their offcial demos.  
Basically, yes, all the scopes are included in wso2_folder/repository/conf/identity/identity.xml, and yes, all you need is to include that scope which protects the internal api in your token request.  

But here is the tricky part, you must enable the option **Management Application** during the service provider registration in wso2 console management if you wanna call those scim api through your client app on behalf of a user, otherwise you should proceed with the basic authentication (username:password).  
 
It's unfortunate it's not written in the docs.  

Anyway, thanks
