### ISSUE TITLE
Admin user couldn't see the active sessions of created user.

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14344]
**Describe the issue:**
Once the super admin user creates a new user under a super organization with admin privileges, the newly created user can log in to the console. So once the newly created user login to the console, there will be an active session and the admin user should be able to see the user's session. However, the active sessions of the newly created users are not visible to the admin user. Please refer to the screen cast below:

https://user-images.githubusercontent.com/13362482/180153945-e18ec142-2a61-4219-8778-888775da15da.mov

**How to reproduce:**

- Log in to the console (https://localhost:9443/console) as an admin user
- Create a user with admin privileges under super organization. 
- Now login to console with newly created admin privileges user.
- Logout and log in again to the console as an admin user.
- Navigate to the Manage -> Users section and edit the newly created user and verify the active sessions.

**Expected behavior:**
Admin users should be able to see the details of the active session.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
The issue is not reproducible on wso2is-6.1.0-m1-SNAPSHOT as shown in below figure where "sadilc" is an admin priviladged user and currently logged in via admin user. Though active sessions shown in super organization level users, the console app for sub organizations level hide the active session view.

![Screenshot 2022-08-31 at 07 16 13](https://user-images.githubusercontent.com/35717390/187575224-d6a999b0-2ca4-4bd4-bd06-467d0027151d.png)
