### ISSUE TITLE
Console Application login is displayed as 2 steps which is not consistent with Myaccount

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14355]
**How to reproduce:**
1. Get pack https://github.com/wso2/product-is/releases/tag/v6.0.0-alpha3
2. Extract the pack
3. Run the pack with sh wso2server.sh
4. Access console application

Navigating to below page where the console login is different from myaccount login page. Earlier console too had a signin page similar to myaccount

Here the current sign in page in the console seems to have more white spaces and at a glance it seems like this page is bit different from the other UIs. Is there a possibility to improve this page ?

![Screenshot from 2022-07-22 00-20-22](https://user-images.githubusercontent.com/31848014/180293863-b9109f8e-83d9-4b75-9e86-8797ad698531.png)

https://user-images.githubusercontent.com/31848014/180297495-24714ed5-5003-4c36-b185-6881136bb7d1.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
oracle jdk 11.0.13
ubuntu 20
IS 6.0.0 alpha 3

**Comment by savindi7** [comment]
This is the expected behaviour in the Console log in (having identifier first and basic auth steps) if configured for organization management in private cloud deployments. This is removed as a default feature in the pack from this PR - https://github.com/wso2/identity-apps/pull/3251. Therefore having basic auth for My Account and identifier first and basic auth steps in the Console is expected if configured. cc: @AnuradhaSK @piraveena
