### ISSUE TITLE
Calling all the /{federated-authenticators/authenticator_id} when clicking on Google IDP settings tab in console

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#14406]
**Describe the issue:**

When click on the **settings tab of one IDP** in console, all the ` /{federated-authenticators/authenticator_id}` APIs are called.
Due to this, there is a slowness in moving to settings tab.

**How to reproduce:**
1. Start the IS 6.0.0 server
2. Create an IDP (Ex:Google) form management console
3. Login to the console
4. Click on Identity Providers
5. Click on the IDP that you have created
6. Click on the settings tab.

You can observe the slowness of loading in settings section.
[Untitled_ Jul 26 2022 12_58 PM.webm](https://user-images.githubusercontent.com/36092400/180955127-d7aae63a-c6dd-4e85-b0fe-d57975c3ea09.webm)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 6.0.0 alpha3
 - OS: Ubuntu
 - Database: H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
this happens when we create an Idp from management console and try to access it from console. It calls all the Idp endpoints. It does not happen when we create the Idp from console and use it from the console

**Comment by savindi7** [comment]
These API calls are necessary to give the following view for IdP settings for when it is created through the Management Console. The user should be able to add multiple authenticators or change the authenticator from the list of authenticators in the Settings tab similar to the behaviour offered by the Management Console. Therefore this is an expected behaviour. cc: @piraveena 
Related PR - https://github.com/wso2/identity-apps/pull/3242

<img width="1467" alt="Screenshot 2022-08-02 at 12 54 52" src="https://user-images.githubusercontent.com/67315176/182316996-d2bb7bc2-4bfd-40e7-ac58-a5ff469ca7ee.png">
