### ISSUE TITLE
Artifact synchronization instructions are incomplete

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#14453]
The documentation at [1] only specifies that the userstores and tenants folders have to be shared in a multi-node environment and does not state that folders and files related to other features such as the workflow feature and also event publishers and event streams also need to be shared between the nodes.

Further, it is necessary to specify as a note that the _<IS_HOME>/deployment/server/webapps_ folder should not be shared in a multi-node environment. This needs to be fixed in the rsync documentation as well [2].

[1] - https://is.docs.wso2.com/en/5.11.0/setup/deployment-guide/#enabling-artifact-synchronization
[2] - https://is.docs.wso2.com/en/5.11.0/setup/configuring-rsync-for-deployment-synchronization/

**Comment by ImalshaG** [comment]
We have had an internal discussion on this and have decided that the 'bpel', 'humantasks', 'userstores' and 'tenant' folders should be shared. 

As discussed in the mail thread [1], event publishers and event streams are generally not modified through services. They normally contain configs about where the data should be published or streamed and users are instructed to add these config changes directly to the zip file. Therefore it is not required to share event related folders. 

However, since 'bpel' and 'humantasks' folders will be updated once new workflows are created through the admin console, we can consider these two folders the same as userstores and should instruct the users to sync these two folders together with 'userstores' and 'tenants' folders.

Therefore we need to update our docs to instruct users to share `bpel` and `humantasks` folders as well. This doc change needs to be added to all IS versions from 5.9.0 and above.

In addition to this, the following doc fix [2] should be ported to IS 6.0.0 and master as well as a part of the issue discussed in [3].
@nilminiwso2 Shall we look into this?

[1] Mail thread: [IAM-PATCH] Incorrect artifact synchronization instructions
[2] https://github.com/wso2/docs-is/pull/2444
[3] https://github.com/wso2-enterprise/wso2-iam-internal/issues/610

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
