### ISSUE TITLE
Different behaviours can be see for links that are invalid on Magic link

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14497]
**Describe the issue:**
Two different behaviours can be see for links that are invalid
- For linked that already used - Navigate ti authentication error page
![Screenshot 2022-08-02 at 15 33 37](https://user-images.githubusercontent.com/39077751/182519822-56690e11-21be-48ca-88d7-da49d6e17f86.png)

- Link that expired (5minutes) - Navigate to login page a again
<img width="875" alt="Screenshot 2022-08-03 at 08 15 49" src="https://user-images.githubusercontent.com/39077751/182519747-a66a48de-40b0-405c-96e1-59938e096735.png">

**How to reproduce:**
Scenarios 01
1. Login to the management console
2. Create application with authentication steps as Magic links.
3. Login to the application with identifiers 1st authentication. 
4. Get the received link and login
5. Log out
6. Login again with same link

Scenarios 02
1. Login to the management console
2. Create application with authentication steps as Magic links.
3. Login to the application with identifiers 1st authentication. 
4. Login with the link after expired time exceed  (5 minutes)

**Expected behavior:**
Have same behaviours for links that are invalid. Better to navigate authentication error page 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Avarjana** [comment]
Both the scenarios should have a similar handling mechanism with OIDC response. Following are the reasons for current behaviour,
- Expired link: Link will be checked against the cached entry and validate if it is expired.
- Used link: Try to get the cache entry to validate. Since the cache is cleared after the first attempt, context will be null.

**Suggestion to fix** (Will not be addressed ATM)
- Handle the null context in the used link scenario by sending additional required parameters with the magic link.
- Send a redirect url along with the magic link to redirect on failure to get context. (This can be captured without context)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
