### ISSUE TITLE
Service providers list is not loading - an error message pops-up when accessing the list

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#14501]
**Describe the issue:**
When the user tries to view the list of service providers, an error message is displayed and the list is not loaded

**How to reproduce:**
1. Start IS server, sign in as admin
2. Attempt to view service providers list (Console and MyAccount should be displayed by default)

**Expected behavior:**
- List of available SPs should be displayed

**Actual behavior:**
- SP list is not displayed
- Following error message is displayed:
- ```Error while loading service providers : org.apache.axis2.databinding.ADBException: Unexpected subelement {http://model.common.application.identity.carbon.wso2.org/xsd}inboundKey```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-beta2-SNAPSHOT (build # 4200)
 - OS: Windows, Chrome 103, Firfox 103
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

---
### Screenshots

![image](https://user-images.githubusercontent.com/37894306/182536699-c4200ecb-471d-41b9-be2a-47489e5d5dd8.png)

**Comment by ravinduramesh** [comment]
Closing the issue since the service provider listing page works as expected after merging the fixes.

<img width="1246" alt="Screenshot 2022-08-04 at 09 14 42" src="https://user-images.githubusercontent.com/12953762/182758727-9aabc40b-36b2-4726-add7-c798b757c1e6.png">

<img width="1246" alt="Screenshot 2022-08-04 at 09 15 10" src="https://user-images.githubusercontent.com/12953762/182758741-edd58382-54f8-46a6-96a1-acb00e896f69.png">
