### ISSUE TITLE
Self Registration is failing and Go Back button prompted during self registration navigates to a form resubmission error page when customizable login portal changes configured or not

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14520]
**How to reproduce:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4201/
2. Set up cusomizable login portal feature https://docs.google.com/document/d/1_XUbmrokb1Yy7T1eZ8wpiq5i3eKwxEXxrwbBmX5xC4Q/edit
3. Enable self registration from management console account management
4. Set up travelocity as the SP and the sample
5. Access http://localhost:8080/travelocity.com/home.jsp
6. Click on Create Account
7. Try to self register by filling mandotory fields
8. Will navigate to a error page
9. Click on the Go Back button in the error page 
10. Will get the below error page where form resubmission is failing

![Screenshot from 2022-08-04 11-53-09](https://user-images.githubusercontent.com/31848014/182778020-576274a2-99b2-48b2-b2c8-069ef2124b93.png)

![Screenshot from 2022-08-04 11-49-49](https://user-images.githubusercontent.com/31848014/182778163-2fb71f66-ed77-4c7e-a42e-3d13ed31118e.png)

Attaching a recording

https://user-images.githubusercontent.com/31848014/182778082-743ef511-fe52-4b9f-a1b5-9f9293851cb6.mp4

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ShanikaWickramasinghe** [comment]
As per Dilshan this issue can be reproduced without the customizable login portal changes too. Hence removing customizable login portal label

**Comment by DilshanSenarath** [comment]
After analyzing the issue, I found that this issue persist in both **IS 6.0.0 Beta** and **IS 6.0.0 Alpha3**. But **IS 6.0.0 Alpha2** haven't this issue. Followings are the identity-apps version used in each release.

- IS 6.0.0 Beta - v1.3.26
- IS 6.0.0 Alpha3 - v1.3.6
- IS 6.0.0 Alpha2 - v1.2.1014

According to my analysis this error occurs form the identity-apps v1.2.1026. 

- To verify that I configured the IS v6.0.0 alpha2 and pacth the identity-apps v1.2.1025. Then the issue was not there.
- After I configured IS v6.0.0 alpha2 and pacth the identity-apps v1.2.1026. Then the issue was found.

I think the root cause for the issue is these changes - https://github.com/wso2/identity-apps/commit/b01d521dc4046001073bb074f6890d2f1b92790a

**Comment by piraveena** [comment]
To fix this issue from UI level, change the callback regex pattern of self registration

<img width="1042" alt="Screenshot 2022-08-04 at 17 31 22" src="https://user-images.githubusercontent.com/17597293/182846751-c97fcf82-5840-4326-a631-4deba3027de8.png">
