### ISSUE TITLE
Tenant admin permission tree not shown properly

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#14569]
Tenant admin permission tree not shown properly
<img width="1114" alt="Screenshot 2022-08-06 at 18 28 09" src="https://user-images.githubusercontent.com/11583571/183249917-79f6adb3-42bc-4b78-a53c-9df59647e9f2.png">

How to reproduce:

1. Create a tenant.
2. Login to that tenant from Console app.
3. View admin user and check roles. 
4. Click to view permissions of admin role.

**Comment by kavinda1995** [comment]
When checking the **permission list** API response from the backend, noticed that we are not getting **_"All Permissions"_** permission node which is the root of all permissions. Without the whole tree from root -> branches -> leaf, permission list cannot generate correct permission tree. What's happening here is without the real root (All Permissions), permission list generator thinks that the root is "Admin permissions" (/permissions/admin) and since there are multiple nodes with same path (/permissions/admin) - it creates multiple root nodes. So adding the "All Permissions" node and correct tree nodes to the backend API response will fix this. 

Expected root node: 
```
{
    "displayName": "All Permissions",
    "resourcePath": "/permission/"
}
```

**Comment by ThumulaPerera** [comment]
Changing the backend API response could break the other places the API is used. It might be better to handle this by considering "Admin permissions" (/permissions/admin) as the root if "All Permissions" node is not in the reponse
