### ISSUE TITLE
Internal everyone role not shown for admin in fresh tenant.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#14570]
When we create a new tenant and login to it from the console app (don't login from management console) view the admin user and check the roles you will only see the admin role and internal everyone role is not visible. Once we go to the role section and come back or log into the management console and come back the role will be visible in the user.

**Comment by ImalshaG** [comment]
During tenant initialization, the internal/system role and admin roles are added to the IDN_SCIM_GROUP but not the internal/everyone role. 
When listing the roles of a user from the console app, since there are no attributes available in the IDN_SCIM_GROUP table for the internal/everyone role, that is not considered as a scim group and will be skipped. Therefore it won't be listed in the UI. Once we load the roles page, an entry is added to that table for the internal/everyone role, so afterwards the role will be visible in the user roles.
In the mgt console, there is no check for role attributes from the IDN_SCIM_GROUP, therefore user's roles will be displayed without an issue.

**Comment by ImalshaG** [comment]
When clicking the edit button of the admin user at manage-->user of console app, the existing user roles will be retrieved from the IDN_SCIM_GROUP table. During tenant initialization, since only admin roles and sytem role is added to that group, at this point internal/everyone role will not be available at this table, hence will not be retrieved as user roles. 
After clicking the roles tab while editing the user, again the user roles will be listed and at this point since the internal/everyone role is not available in the IDN_SCIM_GROUP table, that role will be added to this group. But by this time the roles to be listed at the UI are already loaded (loaded when clicking on edit of the user), therefore the newly added internal/everyone role is not listed in the UI. If we go back to any other page and come back to edit the user, since this role is now added to the IDN_SCIM_GROUP table, it will be now listed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
