### ISSUE TITLE
Console app shows only pre-configured set of grant types for service provider applications

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#14581]
**Describe the issue:**
The console can be used to view service providers and update the necessary configurations. The protocol section of the service provider only shows limited grant types for service provider applications. Organization_switch grant type is enabled for console app when organization management is enabled but the UI does not show that custom grant type.

![Screenshot 2022-08-06 at 21 10 48](https://user-images.githubusercontent.com/35717390/183256242-4ef9a280-472b-4669-95f2-fe762c7e08a2.png)

**How to reproduce:**

Log into console app
Go to applications and select Console app.
View protocol section of the service provider app. 

**Expected behavior:**
With the main grant types, at least all the enabled grant types should be shown.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-6.0.0-beta2]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [H2]

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3312. But we might need to change the displayName of the grant_type **organization_switch** to something better like **Organization Switch Grant** in the endpoint _/api/server/v1/applications/meta/inbound-protocols/oidc_  @sadilchamishka 
<img width="433" alt="Screenshot 2022-08-08 at 13 44 24" src="https://user-images.githubusercontent.com/19621533/183374050-f1a29a05-1b35-4d69-bf2c-9ecc35ba10f6.png">

**Comment by sadilchamishka** [comment]
Above comment is addressed by - https://github.com/wso2/identity-api-server/pull/382
