### ISSUE TITLE
IS 5.3.0 to 6.0.0 Migration: 3 SPs listed in the Mgt Console for the Same SP after Migration

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#14726]
**Describe the issue:**
When migrating an IS pack of 5.3.0 having a Service Provider configured, after migration to 6.0.0 in the management console under the Service Providers section, 3 apps can be seen with the same name and configurations. These additional apps are not available in the console app or in the SP_APP table of the DB.

**How to reproduce:**
1. Create a new Service Provider in the IS 5.3.0 pack.
2. Migrate the 5.3.0 pack to 6.0.0
3. Log into the mgt console of the 6.0.0 migrated pack and list the Service Providers.

The same app will be listed 3 times.

**Expected behavior:**
Only 1 app should be available under service providers.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: Mac
 - Database: MySQL, MSSQL

**Comment by ImalshaG** [comment]
In 5.3.0, additional 2 entries are added to the SP_INBOUND_AUTH table for each SP
![image](https://user-images.githubusercontent.com/47671237/185084178-fbad6906-7767-468d-9e48-22790a54b839.png)
and when loading the application list to be shown at the mgt console, applications are retrieved from the SP_APP table.

But in 6.0.0, only a single entry is available for each SP at the SP_INBOUND_AUTH table
![image](https://user-images.githubusercontent.com/47671237/185084876-4cd74198-ff9f-4825-ba07-d656cf370703.png)
and when loading applications to list in the mgt console the SP_APP table is joined with the SP_INBOUND_AUTH table. Therefore after migration 3 entries added at 5.3.0 will be now available for 6.0.0 in the SP_INBOUND_AUTH table and it will be displayed as separate SPs in the UI.

The extra 2 entries should be removed from the SP_INBOUND_AUTH table during migration for each SP.

**Comment by ashendes** [comment]
This is a very rare bug in IS that has been existing since 5.3.0, and it is currently affecting IS 6.0.0 due to a change in APP retrieving SQL queries.
This can be addressed via an update to the migration client.
A migrator can be added as a step in IS 6 to do the following,
1. Get a list of entries from SP_INBOUND_AUTH table from APP_ID where count >2
2. If entries for a particular APP_ID = 3, then delete entries where INBOUND_AUTH_TYPE are `passivests` and `openid`
![Screenshot from 2022-08-18 10-40-58](https://user-images.githubusercontent.com/25567263/185298890-a5bd8953-9d04-4867-80b6-6beee752c7c1.png)
3. If entries for a particular APP_ID = 2, 
  - then check whether the value of `PROP_NAME` for the entry with INBOUND_AUTH_TYPE as `passivests`. 
  - If the PROP_NAME value is `passiveSTSWReply`, then delete the **other** entry with INBOUND_AUTH_TYPE as `openid`. 
  - If the PROP_NAME value is NULL, then delete the entry where INBOUND_AUTH_TYPE is `passivests`.
![Screenshot from 2022-08-18 10-48-33](https://user-images.githubusercontent.com/25567263/185299751-536e57f5-2337-46f8-a482-efca77fa994d.png)
