### ISSUE TITLE
Docs: Allow user to recover password through email if the account is locked

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#14895]
Add the required documentation for [1].

[1] https://github.com/wso2/product-is/issues/1935

**Comment by nilminiwso2** [comment]
Related documentation:

[1] - https://github.com/wso2/product-is/issues/1935
[2] - https://is.docs.wso2.com/en/latest/guides/tenants/account-locking-per-user/
[3] - https://is.docs.wso2.com/en/latest/apis/user-functionality-mgt-rest-api/

**Comment by divyaamunugama** [comment]
The solution to the issue has been updated as follows: 

- **Issue**: When an account is locked, the user is unable to do anything to resolve it.
- **Solution**: Disable the security-question-based password recovery option so that a user cannot continue to try to reset their password.
- **Result**:  instead of locking the whole account, we would lock the functionality which would trigger an account lock.

Related doc for this fix: [1] https://is.docs.wso2.com/en/latest/guides/tenants/account-locking-per-user/

**What should be added to the doc space?** 
The feature doc is already available [1]. Improve the doc on how to fix the issue using the feature.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
