### ISSUE TITLE
Improvements on DCR Rest API

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-is#14959]
need to implement the following attributes in DCR rest API in order to communicate with APIM in OOTB manner.

1. **application_type**: to create native PKCE applications 
2. **ext_display_name**: In the current IS we couldn't create multiple applications from the same name. Therefore we need to have a display_name to handle consent management.
3. **ext_application_token_lifetime**: set application access token lifetime.
4. **ext_user_token_lifetime**: set user access token lifetime
5. **ext_refresh_token_lifetime**: set Refresh token lifetime.
6. **ext_id_token_lifetime** : set OpenID token lifetime. 
7. **bypassClientCredentials** : make client credentials optional.
8. **ext_token_type**: Create application with respective token type.

**Comment by chamathns** [comment]
According to the implementation at https://github.com/wso2-extensions/apim-km-wso2is/blob/master/components/wso2is.key.manager.operations.endpoint/src/main/resources/keymanager-operations.yaml

The following is a summary of client metadata parameters that are supported in KM which are not there in WSO2-IS

    application_display_name
    ext_application_owner
    ext_application_token_lifetime
    ext_user_token_lifetime
    ext_refresh_token_lifetime
    ext_id_token_lifetime
    pkce_mandatory
    pkce_support_plain
    bypass_client_credentials

**Comment by mefarazath** [comment]
> According to the implementation at https://github.com/wso2-extensions/apim-km-wso2is/blob/master/components/wso2is.key.manager.operations.endpoint/src/main/resources/keymanager-operations.yaml
> 
> The following is a summary of client metadata parameters that are supported in KM which are not there in WSO2-IS
> 
> ```
> application_display_name
> ext_application_owner
> ext_application_token_lifetime
> ext_user_token_lifetime
> ext_refresh_token_lifetime
> ext_id_token_lifetime
> pkce_mandatory
> pkce_support_plain
> bypass_client_credentials 
> ```

bypass_client_credentials is a bad name to use :P
I think its used to indicate public clients, unless it is coming from a spec let's use something that indicates it is a public client.

As a consistent format shall we use ext_ for any custom parameters we support

**Comment by chamathns** [comment]
@mefarazath for the bypass_client_credentials, here are a few suggestions.

Denotes if the client is public or not:

- ext_is_public_client
-  ext_client_type_public

Denotes if the credentials are optional:

-  ext_client_credentials_optional

Shall we go with `ext_client_type_public` ?

**Comment by mefarazath** [comment]
> @mefarazath for the bypass_client_credentials, here are a few suggestions.
> 
> Denotes if the client is public or not:
> 
> * ext_is_public_client
> * ext_client_type_public
> 
> Denotes if the credentials are optional:
> 
> * ext_client_credentials_optional
> 
> Shall we go with `ext_client_type_public` ?

I am okay with either of

* ext_is_public_client
* ext_client_type_public

one more suggestion

* ext_public_client

Also how check other vendors are doing?
and whether ext_ convention makes sense too ;)

**Comment by chamathns** [comment]
I did a comparison between the parameters we support currently with the parameters supported in spec. The comparison can be found in https://github.com/wso2/product-is/issues/15887

there, we are currently using only 4 custom parameters and 3 of them already have the ext preffix

**Comment by chamathns** [comment]
Therefore I think it makes sense to go with the ext_ suffix since we already have 3 custom parameters with that

**Comment by chamathns** [comment]
+1 for ext_public_client

**Comment by chamathns** [comment]
The following is a comparison between the IS DCR implementation and the IS-KM DCR implementation. I had missed a few parameters earlier because the actual implementation is different from the yaml files (I compared the parameters defined in the yaml files earlier)

Parameters | WSO2 IS DCR | WSO2 IS-KM DCR
-- | -- | --
redirect_uris | ✔️ | ✔️
client_name | ✔️ | ✔️
grant_types | ✔️ | ✔️
application_type | ✔️ | ✔️
jwks_uri | ✔️ | ✔️
url | ✔️ | ✔️
ext_param_client_id | ✔️ | ✔️
ext_param_client_secret | ✔️ | ✔️
contacts | ✔️ | ✔️
post_logout_redirect_uris | ✔️ | ✔️
request_uris | ✔️ | ✔️
response_types | ✔️ | ✔️
token_type_extension | ✔️ | ✔️
backchannel_logout_uri | ✔️ | ✔️
backchannel_logout_session_required | ✔️ | ✔️
ext_param_sp_template | ✔️ | ✔️
client_id |   | ✔️
client_secret |   | ✔️
application_display_name |   | ✔️
ext_application_owner |   | ✔️
ext_application_token_lifetime |   | ✔️
ext_user_token_lifetime |   | ✔️
ext_refresh_token_lifetime |   | ✔️
ext_id_token_lifetime |   | ✔️
pkce_mandatory |   | ✔️
pkce_support_plain |   | ✔️
bypass_client_credentials |   | ✔️
is_management_app | ✔️ |  


From the above analysis, you can see the following are the parameters unique to the WSO2 IS-KM DCR implementation.

    client_id
    client_secret
    application_display_name
    ext_application_owner
    ext_application_token_lifetime
    ext_user_token_lifetime
    ext_refresh_token_lifetime
    ext_id_token_lifetime
    pkce_mandatory
    pkce_support_plain
    bypass_client_credentials

@tharindu1st Any idea why there is a need for client_id, client_secret params and ext_param_client_id, ext_param_client_secret params in the IS-KM implementation?

**Comment by chamathns** [comment]
closing since done

**Comment by mefarazath** [comment]
> closing since done

Hope we added an integration test covering the new changes :)
If not let's do it please
