### ISSUE TITLE
Configuring Transport Level Security for TLSv1.3

### ISSUE THREAD

**Issue by dinzie95** [wso2/product-is#15105]
**Is your suggestion related to a missing or misleading document? Please describe.**
The document for Configuring Transport Level Security[1] is written only for TLS versions up to TLSv1.2. 
TestSSLServer.jar which is provided to verify the configurations only support cipher suites available for TLS versions up to TLSv1.2.

[1] https://is.docs.wso2.com/en/5.10.0/setup/configuring-transport-level-security/

**Describe the improvement**
IS versions that support jdk-11 are able to use TLSv1.3. Therefore the documentation needs to be updated with necessary changes.
TestSSLServer.jar needs to be compatible for TLSv1.3

**Comment by Anandi-K** [comment]
The issue suggests the following improvement: 
```
TestSSLServer.jar needs to be compatible for TLSv1.3
```
TestSSLServer is an external tool and this is not maintained by WSO2. And as mentioned in the [documentation](http://www.bolet.org/TestSSLServer/), it does not support TLS v1.3 protocol. 

We only use TestSSLServer to test whether all the configurations are set correctly. We can use an alternative which supports TLS v1.3 for the same scenario instead of TestSSLServer.

Suggested alternative: [testssl.sh](https://github.com/drwetter/testssl.sh)
