### ISSUE TITLE
Sending OTP to a custom to a user in custom userstore (The database has only one table)

### ISSUE THREAD

**Issue by absoft10** [wso2/product-is#15116]
Hey, 
I have made a custom userstore my overriding the UniqueIDJDBCUserStoreManager class, based on this article [](https://nishothan-17.medium.com/custom-user-store-manager-for-wso2-identity-server-5-11-0-6e23a4ddf1bb) .  My database has one table which has the username, password ,email, name and phone number. 

I able to authenticate successfully. However I am unable to send the OTP to the users phone number. Can any one please guide me how to send OTP to the user. Which properties do i have to set or over ride ? 

I would like to make a request for this feature. or documentation to be provided for this feature.

**Comment by madurangasiriwardena** [comment]
Hi @absoft10,

Sorry about the delay in replying. Your question is not complete with the details on what you have done so far. Since this is a question on how to complete your customization, this needs to go to our [community channels](https://wso2.com/community/), assuming that you don't have WSO2 support access.
