### ISSUE TITLE
Introduce a config to trigger account locked email on askPassword flow in IS 5.11.0

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15141]
**Describe the issue:**
An improvement has done the ask password flow to avoid triggering two emails via #13252. However, this fix has introduced a behavioral change.

It is required to introduce a config to toggle this behavior (sending two emails or not) to avoid any behavioral changes in the product.

**How to reproduce:**
Steps can be found in #13252

**Expected behavior:**
Improvements to the ask password flow should not introduce any behavioral changes. 

**Environment information:**
 - Product Version: IS 5.11.0

**Comment by UpekshaGalappaththi** [comment]
Adding to the above mentioned issue, there has been another behavioural change in the product related to the earlier improvement. While fixing the two emails sent issue in the ask password flow, the unlock email that is being sent after the user enters the password and unlocks his account in the ask password flow, has also been removed. This should also be controlled by the toggle introduced in order to have no behavioural changes to the product

**Comment by asha15** [comment]
Had a meeting to discuss the reported issue.

Participants: @isuruhettiarachchi @UpekshaGalappaththi @inthirakumaaran @Wathsara @asha15 

Meeting notes: 

- Since sending one email (`create new password for new account`) is the expected behavior, It was decided not to introduce a config to toggle the behavior in askpassword flow.
- It was suggested to send an account activation email when the user created the initial password.

**Comment by isuruhettiarachchi** [comment]
The initial issue discussed in this will not be fixed. Instead, a new email template will be sent after the user completes the ask password flow.

This will be fixed from [product-is/issues/15167](https://github.com/wso2/product-is/issues/15167) hence closing this issue.
