### ISSUE TITLE
Unable to login to an application with a user in a tenant when active session limit is configured

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#15223]
**Describe the issue:**
Login fails when trying to login to an application which is configured under a tenant(Not Super Tenant) with a user who is in the same tenant. The following error log is printed in the logs.

`
[2022-11-26 23:37:21,684] [e546b0bc-35ce-4a9a-86af-d84fdc7db827] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Error occurred while retrieving user sessions.
`

When debugging the code, encounter that in this place [1] the tenant domaiin always comes as `carbon.super` from the threadlocal. In [1] the tenant domain should be resolved in a different way to get the correct tenant domain.

Tried the scenario with IS 6.0.0 vanilla pack and also a U2 updated pack. You can refer the following screencast for more information.

https://user-images.githubusercontent.com/19262008/204104174-7bc9c6ef-f173-4e45-99c5-40a5d6b5aa6e.mov

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/internal/impl/UserSessionManagementServiceImpl.java#L232

**How to reproduce:**
1. Configure Concurrent session based adaptive authentication by following this doc [1] to a tenant. 
2. Create a user with in the same tenant which contains the admin or manager as a role (These roles are defined in the adaptive script. You can also change that in to any).
3. Try to login with the sample application configured in the tenant and you will see the login was not success and the above error log will be printed.
 
[1] https://is.docs.wso2.com/en/latest/guides/adaptive-auth/limiting-active-sessions-adaptive-auth/

**Expected behavior:**
Users in a tenant should be able to login to an application which configured the concurrent session based adaptive authentication.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - OS: Mac
 - Database: H2

**Comment by AnuradhaSK** [comment]
Retrieving the tenant domain from the caron context at [1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/internal/impl/UserSessionManagementServiceImpl.java#L232 works fine only when tenant qualified URLs are enabled. 
```
[tenant_context]
enable_tenant_qualified_urls = "true"
```

Ideally the above mentioned session limit handler should work in non carbon.super tenants even tenant qualified URLs are not enabled. So tenant resolution logic should be changed / username resolving from userid should be independent of tenant domain because user id is unique across the server
