### ISSUE TITLE
Add email template for account activation to be sent after the user completes the ask password flow

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#15226]
**Describe the issue:**
A new email template[1] has been added for account activation to be sent after the user completes the ask password flow.
Related issue: https://github.com/wso2/product-is/issues/15167

For migrating users either we can add this to the migration doc or else we can preserve the existing behaviour as the backend implementation is written in a way that preserves the current behaviour.

But for the existing users who get a password reset mail after the user completes the ask password flow will not get that mail as mentioned in https://github.com/wso2/product-is/issues/15167.

If we are not adding this to the migration client we can recommend the migrating customers to add this template via the migration docs. For that, we can ask to follow the "Customizing Automated Emails" document[2] to add the mail template. When adding the email template, add "accountActivationSuccess" as the "Template Type Display Name" when adding the email template type.

[1] https://github.com/wso2-extensions/identity-event-handler-notification/pull/181
[2] https://is.docs.wso2.com/en/5.11.0/learn/customizing-automated-emails/#customizing-automated-emails

**Comment by ImalshaG** [comment]
Since these changes are added to the `email-admin-config.xml` of the 6.1.0 pack, a migrating user will not have this new email enabled as the user will be replacing this `email-admin-config.xml` file with the xml file from the previous pack. Therefore should mention in the migration docs the steps to enable this new email for a migrating user using steps of https://is.docs.wso2.com/en/5.11.0/learn/customizing-automated-emails/#customizing-automated-emails.

**Comment by divyaamunugama** [comment]
Related doc PR: https://github.com/wso2-enterprise/migration-docs/pull/86

**Comment by nilminiwso2** [comment]
Closing this as the docs are added.
