### ISSUE TITLE
SCIM 2 Filter Request response resource attribute is case sensitive 

### ISSUE THREAD

**Issue by santoshsp16** [wso2/product-is#15234]
SCIM has support for the filter & gives the below image response 
![SCIM API1](https://user-images.githubusercontent.com/119281393/204533876-2cf90b86-d9bb-4591-9162-af5e641ab52b.PNG)

In response we see all the attribute are starting with small case except the Resources attribute which is having capital 'R'. Is it really needed  for R to be capital case in response or it is the typo error. And is Resource keyword is case sensitive.

We refer the different sites for the documentation from http://www.simplecloud.info/ it shows resources attribute R is capital.

**Comment by AnuradhaSK** [comment]
- SCIM RFC 7644 specification defines the SCIM resources query response as follows
- https://www.rfc-editor.org/rfc/rfc7644.html#section-3.4.2
- The key `Resources` starts with capital R
- There is no mention of the case sensitivity of the keys in response to JSON
- Since this is an open standard and need to confirm the interoperability between SCIM servers, it's better to adhere to the same keywords given in the specification
