### ISSUE TITLE
Issue with encoded URL in the reset password

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#15322]
**Describe the issue:**
The email that the user gets after clicking on forget password contains + signs after decoding, where the decoding should have spaces instead + signs. 
For instance, the following URL is the one the user receives when he click on forget password,

```
https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation=deb5c4be-b6e7-42e6-9bd1-707cbccdaff1&userstoredomain=PRIMARY&username=nipunau&tenantdomain=carbon.super&callback=https%3A%2F%2Flocalhost%3A9443%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DMY_ACCOUNT%26code_challenge%3DS7YYaLuSzXWK3uQgaKdB0rQUxckZHw6L71mAj3z6Z3s%26code_challenge_method%3DS256%26commonAuthCallerPath%3D%2Foauth2%2Fauthorize%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%3A%2F%2Flocalhost%3A9443%2Fmyaccount%2Flogin%26response_mode%3Dform_post%26response_type%3Dcode%26scope%3DSYSTEM+openid%26tenantDomain%3Dcarbon.super%26sessionDataKey%3D46566b91-42ad-4cf9-954d-1f251ad20dd3%26relyingParty%3DMY_ACCOUNT%26type%3Doidc%26sp%3DMy+Account%26isSaaSApp%3Dtrue%26authenticators%3DBasicAuthenticator%3ALOCAL
```
After decoding it, we get,

```
https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation=deb5c4be-b6e7-42e6-9bd1-707cbccdaff1&userstoredomain=PRIMARY&username=nipunau&tenantdomain=carbon.super&callback=https://localhost:9443/authenticationendpoint/login.do?client_id=MY_ACCOUNT&code_challenge=S7YYaLuSzXWK3uQgaKdB0rQUxckZHw6L71mAj3z6Z3s&code_challenge_method=S256&commonAuthCallerPath=/oauth2/authorize&forceAuth=false&passiveAuth=false&redirect_uri=https://localhost:9443/myaccount/login&response_mode=form_post&response_type=code&scope=SYSTEM+openid&tenantDomain=carbon.super&sessionDataKey=46566b91-42ad-4cf9-954d-1f251ad20dd3&relyingParty=MY_ACCOUNT&type=oidc&sp=My+Account&isSaaSApp=true&authenticators=BasicAuthenticator:LOCAL
```
In that URL, the `sp` value which should be `My Account` has been incorrectly parsed as `My+Account` and the scopes contain + signs in between them.

**How to reproduce:**
- Get a latest 5.11 pack (tested with 5.11.0.211) 
- Configure forget password settings in `deployment.toml`
- Go to `https://localhost:9443/myaccount` and select `Forget password`
- The received email has the incorrect URL.

**Expected behavior:**
The spaces send with query parameters should be decoded to spaces and not + signs.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0.211
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**
- https://github.com/wso2/product-is/issues/14876

**Comment by amanda-ariyaratne** [comment]
The callback URL is submitted as a form field value from the Recover Password page to password-recovery-notify.jsp. According to [W3C](https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1), encoding a space that is in a query parameter part of a URL to plus sign is accepted for forms that are submitted with the content type application/x-www-form-urlencoded.

> Control names and values are escaped. Space characters are replaced by `+', and then reserved characters are escaped as described in [[RFC1738]](https://www.w3.org/TR/html4/references.html#ref-RFC1738)

Therefore, a decoding of the URL should decode the + back to a space character. This is also correctly displayed when inspecting it using the browser tools.

<img width="1512" alt="Screenshot 2023-01-11 at 14 24 13" src="https://user-images.githubusercontent.com/28347418/211761743-64cea923-5e74-41ca-b146-9af4bbe25943.png">

However upon further investigation, it was observed that the following redirect URL is invoked with the redirection to the login page after the new password is submitted. 

```
https://localhost:9443/authenticationendpoint/login.do?authenticators=BasicAuthenticator%3ALOCAL&response_type=code&code_challenge_method=S256&type=oidc&tenantDomain=carbon.super&client_id=MY_ACCOUNT&response_mode=form_post&relyingParty=MY_ACCOUNT&passiveAuth=false&isSaaSApp=true&commonAuthCallerPath=%2Foauth2%2Fauthorize&scope=SYSTEM%2Bopenid&forceAuth=false&sessionDataKey=58037b24-bd66-43d6-8a41-b3ea52d09af8&passwordReset=true&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fmyaccount%2Flogin&sp=My%2BAccount&code_challenge=Nkyk_uGBOGF6ihUoLopa0HSvQNoTMsBeNOZooFMCgsY
```

In the above URL the spaces in the sp parameter and scope parameter are encoded to %2B (caused by encoding the query value twice from space to plus to %2B).

<img width="1512" alt="Screenshot 2023-01-11 at 14 49 00" src="https://user-images.githubusercontent.com/28347418/211767248-91a67bf8-82a1-45ed-a0ab-7735a9f04401.png">


**Expected behavior:**
The spaces should be encoded to plus or %20.

**Environment information :**
Product Version: IS 5.11.0.212 (not observed on vanilla pack IS 5.11.0)
OS: Mac
Database: H2
Userstore: LDAP
