### ISSUE TITLE
Address field is not getting updated in myaccount

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15348]
**Describe the issue:**
When updating the address field, a successful message is getting displayed, but entered value is not getting displayed/saved.

https://user-images.githubusercontent.com/47152272/211800252-a42dea0d-787d-4286-ba58-5acc9d491ea4.mov

**How to reproduce:**
1. Login to management console.
2. Create a tenant
3. Login to the myaccount using created tenant admin credentials
4. Goto `Personal Info` tab
5. Update address field and save.

**Expected behavior:**
Updated value should be displayed in the address field.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0 alpha2
 - OS: Mac M1 pro
 - Database: Postgres, H2
 - Userstore: JDBC

**Comment by chamathns** [comment]
The SCIM protoccol defines the "addresses (urn:ietf:params:scim:schemas:core:2.0:User: addresses)" as a complex attribute [1] with the following sub-attributes:

- _formatted_  The full mailing address, formatted for display or use with a mailing label.  This attribute MAY contain newlines.
- _streetAddress_  The full street address component, which may include house number, street name, P.O. box, and multi-line extended street address information.  This attribute MAY contain newlines.
- _locality_  The city or locality component.
- _region_  The state or region component.
- _postalCode_  The zip code or postal code component.
- _country_  The country name component.


But, we are maintaining the "urn:ietf:params:scim:schemas:core:2.0:User: addresses" claim mapped to a single claim (http://wso2.org/claims/addresses). Since this is contradicting the schema. we are skipping it when calling the GetUser method [2]. Therefore, the addresses claim won't appear in the scim/me GET response thereby not appearing in the UI.


We would need to think about the correct approach in fixing this since changing the addresses claim would cause backward compatibility issues for the on-prem users. Since this would require a considerable effort, this will be fixed in the next releases.

[1] - https://www.rfc-editor.org/rfc/rfc7643.html#section-4.1.2
[2] - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/111fc602d328841262bf1f073ec39984683bd92e/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3836-L3837

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
