### ISSUE TITLE
[IS 6.0.0] Analytics Engine Configuration and TypingDNA Configuration are not visible when using JDK 17

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15396]
**Describe the issue:**

- Analytics Engine Configuration and TypingDNA Configuration are not visible when using JDK 17 with WSO2 IS 6.0.0

- Current view

![Screenshot 2023-01-23 at 12 00 19](https://user-images.githubusercontent.com/13478571/213978226-bf29ce87-d0f5-4daa-aa9e-298eccd54cbb.png)

- Expected View

![Screenshot 2023-01-23 at 12 03 07](https://user-images.githubusercontent.com/13478571/213978550-97798791-29be-4070-85ad-b52ee6ec3fe0.png)

**How to reproduce:**

- Add the typing DNA connector to the pack and start IS with JDK 17

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.0.0]

**Comment by chamathns** [comment]
Analytics Engine implementation and TypingDNA implementation both are having JS function library implementations. In Java 17, we need to follow the steps in [1] to enable adaptive authentication features. 
The underlying reason here is that, both the analytics and typingDNA services require the JsFunctionRegistry service as a reference. 
But, this JsFunctionRegistry service is not getting registered in a java 17 setup since the nashorn script engine is not available. As a result, analytics and the typingDNA modules are also not getting registered.

Hence, to register the analyitcs and typingdna services, users must first follow the prerequisites listed in [1].

[1] - https://is.docs.wso2.com/en/latest/guides/adaptive-auth/configure-adaptive-auth/#prerequisites
