### ISSUE TITLE
[DOCS]explain why module ref="addressing is need to be commented.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1561]
Document: [Configuring Email OTP](https://docs.wso2.com/display/IS530/Configuring+Email+OTP)
Section: Step 1 - Deploy the EmailOTP artifacts
Step 3

Explain why we need to comment below line in <IS_HOME>/repository/conf/axis2/axis2.xml file.
> module ref="addressing

**Comment by shavidissa** [comment]
Thank you! Updated docs with the info on why (to avoid syntax errors).

[1] https://docs.wso2.com/display/IS530/Configuring+Email+OTP
[2] https://docs.wso2.com/display/IS540/Configuring+Email+OTP

**Comment by omindu** [comment]
@shavidissa I'm not sure how not commenting this property can lead to syntax errors.

**Comment by shavidissa** [comment]
Adding Shakila @Shakila . 
As per the information gathered it was mentioned: "That the element has syntax issues and it's coming from the product." Since it was not advised to document so, I added a generic comment on why we need to comment out the property ("Comment out the <module ref="addressing"/> property to avoid syntax errors.").

Do you think we need to change this?
