### ISSUE TITLE
Unable to modify custom fields from the myaccount application

### ISSUE THREAD

**Issue by sarindufit** [wso2/product-is#15673]
**Describe the issue:**
When a user self registers into myaccount, it is possible to add custom fields to the self registration via local claims. The values that the user provides to these custom fields should be editable via MyAccount portal later. However, this is currently not working as expected.  

Please refer to - https://github.com/wso2-enterprise/wso2-iam-internal/issues/384

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

---

**Comment by mpmadhavig** [comment]
@sarindufit could you please list down the steps you followed? Or mention any documentation link you refered to.

**Comment by mpmadhavig** [comment]
### Update

Followed the documentation provided to create a custom attribute [1].  The mentioned issue occurs when `creating the external claim mapping` step is  missed. Closing the issue since no fixes need to be done.

[1] https://is.docs.wso2.com/en/5.11.0/develop/extending-scim2-user-schemas/#add-the-custom-claim
