### ISSUE TITLE
Email sending failure in lite user registration

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#15799]
**Describe the issue:**
If a lite user registration request is made as given below, the server will respond with an internal server error.

Request
```
curl -X POST -H "Authorization: Basic [Base64encode(Username>:<Password>)]=" -H "Content-Type: application/json" -d '{"email
": "<regsiter_email>","realm": "PRIMARY","preferredChannel":"Email","claims":[], "properties": []}' "https://localhost:9443/api/identity/user/v1.0/lite"
```

Response
```
{
    "code": "20019",
    "message": "Internal server error",
    "description": "The server encountered an internal error. Please contact administrator.",
    "traceId": "dcc8721d-d654-467c-a6b0-f4c58d5821eb"
}
```

Error trace
```
2023-04-27 04:49:48,366] [dcc8721d-d654-467c-a6b0-f4c58d5821eb] ERROR {org.wso2.carbon.identity.user.endpoint.impl.LiteApiServiceImpl} - Error occurred in the server while performing the task. org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Error while adding self signup user
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
.
.
.
	... 74 more
Caused by: org.wso2.carbon.identity.event.IdentityEventException: Email notification sending failed. Sending email address is not configured for the user.
	at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.buildNotification(NotificationUtil.java:526)
	at org.wso2.carbon.identity.event.handler.notification.NotificationHandler.handleEvent(NotificationHandler.java:66)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.recovery.handler.LiteUserRegistrationHandler.triggerNotification(LiteUserRegistrationHandler.java:392)
	... 75 more
```

The request is successful if the email address is given as a claim value. 
```
curl -X POST -H "Authorization: Basic [Base64encode(Username>:<Password>)]=" -H "Content-Type: application/json" -d '{"email
": "<regsiter_email>","realm": "PRIMARY","preferredChannel":"Email","claims":[{"uri": "http://wso2.org/claims/emailaddress","value": "<regsiter_email>" }], "properties": []}' "https://localhost:9443/api/identity/user/v1.0/lite"
```

**How to reproduce:**
Follow the steps given in https://is.docs.wso2.com/en/6.0.0/guides/identity-lifecycles/self-registration-workflow/

**Expected behavior:**
The confirmation email should be sent using the registration email without defining it again in the claims.

**Environment information**
 - Product Version: IS 6.1.0

**Comment by inthirakumaaran** [comment]
similar issue reported in https://github.com/wso2/product-is/issues/11373

**Comment by inthirakumaaran** [comment]
Track the doc improvement for resending confirmation mail as well https://github.com/wso2/product-is/issues/13468

**Comment by DilshanSenarath** [comment]
After analysing the lite user registration flow, following details have been identified.

Example Payload
```json
{
    "email": "<regsiter_email>",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[], 
    "properties": []
}
```

Based on the existing implementation, the email field within the mentioned payload functions as the designated username for the user. However, during the process of sending email confirmations to users, the system attempts to retrieve the email address from email claims. Consequently, email notifications are dispatched to the email address found within the claims, even if we have explicitly provided an email address in the email field.

## The existing behaviour of the API in handling various payload types is as follows:
### Provide only email field
- Payload
```json
{
    "email": "dilshanse99@gmail.com",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[],
    "properties": []
}
```
- Response (Status - 500)
```json
{
    "code": "20019",
    "message": "Internal server error",
    "description": "The server encountered an internal error. Please contact administrator.",
    "traceId": "b740a817-17ba-4c38-88f7-1a87332824d1"
}
```
- As we haven't included the email within the claims, the send-to field becomes null when sending notifications. Consequently, the error message `Email notification sending failed. Sending email address is not configured for the user.` is triggered.
### Populate the designated email field and the email claims with the same email address
- Payload
```json
{
    "email": "dilshanse99@gmail.com",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response
```
201 Created
```
### Populate the designated email field and the email claims with the different email address
- Payload
```json
{
    "email": "dilshanse@gmail.com",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response
```
201 Created
```
- During user creation, the username is set as `dilshanse@gmail.com`, and the email address is set as `dilshanse99@gmail.com`. As a result, the email confirmation will be sent to the `dilshanse99@gmail.com` address.
### Populate the designated email field with a username and the email claim with an email address
- Payload
```json
{
    "email": "diltest",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response
```
201 Created
```
- Since the email field uses as the username, it undergoes username validation. This enables users to input a username through the email field while sending the actual email address via claims.
### Add the username claim with a different value
- Payload
```json
{
    "email": "dilshanse99@gmail.com",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/username","value": "diltest"},
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response (500)
```
{
    "code": "20019",
    "message": "Internal server error",
    "description": "The server encountered an internal error. Please contact administrator.",
    "traceId": "f8e58a4f-49f8-49de-b7b7-9d909715401b"
}
```
- There is a validation step to check whether the email field and username claim are same. If not the error `Username and the username claim value should be same.` is thrown.
### Add the username claim with the same value
- Payload
```json
{
    "email": "diltest",
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/username","value": "diltest"},
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response
```
201 Created
```
### Exclude the email field
- Payload
```json
{
    "realm": "PRIMARY",
    "preferredChannel":"Email",
    "claims":[
        {"uri": "http://wso2.org/claims/username","value": "diltest"},
        {"uri": "http://wso2.org/claims/emailaddress","value": "dilshanse99@gmail.com"}
    ],
    "properties": []
}
```
- Response (400)
```
{
    "code": "USR-10004",
    "message": "Bad Request",
    "description": "Either email or mobile should be submitted.",
    "traceId": "5483b079-0b6b-4363-beff-1091a727309a"
}
```

**Comment by DilshanSenarath** [comment]
Another related issue: https://github.com/wso2/product-is/issues/16206

**Comment by inthirakumaaran** [comment]
> Another related issue: #16206

This should have been sorted, @DilshanSenarath could u verify this issue?
