### ISSUE TITLE
Performance degradation in SCIM/Groups PATCH operation

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15986]
**Describe the issue:**
There was an improvement done in SCIM/Groups PATCH through https://github.com/wso2/product-is/issues/6918 by not returning the group members and returning 204 on success. Therefore, the retrieval and processing of users of the groups can be avoided. However, the list of users and the properties are still obtained at [1][2]. This is unnecessary, as the members of the group will not be included in the response.

**How to reproduce:**
Make a SCIM/Groups PATCH operation and observe the method invocations in AD and LDAP.

**Expected behavior:**
If the configuration below is added, no need to retrieve the members.
      ```
      [scim2]
      return_updated_group_in_group_patch_response=false
      ```

**Environment information**
 - Product Version: IS 5.11.0
 - Userstore: LDAP and AD

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.46/components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java#L525
[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.46/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3684

**Comment by piyarathnalakmali** [comment]
While performing a SCIM/Groups PATCH operation, group resource is fetched twice with the full user list,

1. To obtain the current user list in order to create the new user list
2. To create the SCIM response to be sent

So far two improvements have been done to optimise the performance of the SCIM/Groups PATCH operation.

- https://github.com/wso2/product-is/issues/6918 
   ```
  [scim2]
  return_updated_group_in_group_patch_response=false
  ```
  Above config was introduced by this improvement to send a 204 response instead of sending a 200 response with the updated user list. (To avoid fetching the group resource in the second case above)

- https://github.com/wso2/product-is/issues/9120
  
  This improvement is done to avoid fetching the user list of group while updating the resource (First case above).

Improvement done by https://github.com/wso2/product-is/issues/9120 is only applied to the `return_updated_group_in_group_patch_response=true`
path at the moment. So as a fix to this issue that improvement will be applied to the config false path as well. 

After the fix, if the `return_updated_group_in_group_patch_response=false` config is applied, full user list of the group will not be fetched at both places.
