### ISSUE TITLE
"PKCE Mandatory" and "Allow authentication without the client secret" breaks the device grant flow

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16079]
**Describe the issue:**
Setting/Unsetting the service provider configurations "PKCE Mandatory" and "Allow authentication without the client secret" breaks the device grant flow.

**How to reproduce:**
- Configure the device grant flow as mentioned in the document[1]
- Enable "PKCE Mandatory" option or disable the "Allow authentication without the client secret" option in the service provider(the same SP is used for code grant)
- When the "PKCE Mandatory" option is enabled, the flow breaks with the following error on the browser.
error_description=PKCE+is+mandatory+for+this+application.+PKCE+Challenge+is+not+provided+or+is+not+upto+RFC+7636+specification.&error=invalid_request
- When the "Allow authentication without the client secret" option is disabled the flow breaks while initiating the device grant flow.
{"error_description":"Unsupported client authentication mechanism","error":"invalid_client"}%

**Expected behavior:**
"PKCE Mandatory" and "Allow authentication without the client secret" options should not be considered for the device grant flow. They are only applicable to the code grant flow.

[1]https://is.docs.wso2.com/en/6.0.0/guides/access-delegation/try-device-flow/

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by asha15** [comment]
Hi @tharakawijekoon 

Thank you for reporting the issue. Enabling "Allow authentication without the client secret" is a mandatory requirement as the device code flow is related to the public client. Hence the error is expected behavior. When the "PKCE Mandatory" option is enabled, device code flow break issue has been fixed with the following PR: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2112
