### ISSUE TITLE
Getting 500 error response for client errors in SCIM/Groups PATCH

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#16097]
**Describe the issue:**

Getting 500 error response for the below listed client errors

  - Add a member to a group with only display name 
  - Add a member to a group with only id
  - Add a member to a group with invalid display name
  - Add a member to a group with invalid id
  - Add a user with mismatching user name and id
  - Add user with empty id
  - Remove a non-existent member from a group - Only happens with LDAP user stores. 
  - Remove a non-existent user from a group

More details about each of these scenarios can be found at https://docs.google.com/spreadsheets/d/1h8UTae7LnqWx0WYYGOUGkv3mT7Cu5HtX4kM2pOmlbLw/edit#gid=646167061

**How to reproduce:**
Try the scenarios listed above and observe the responses received

**Expected behavior:**
Should respond with 400 with the correct error type. Need to decide on the correct error type for each scenario according to the spec.

**Note**
Need to check on the migration impact as well because this behaviour is available in earlier product versions (available in 5.11.0) also.

**Comment by piyarathnalakmali** [comment]
When fixing these issues need to pay attention to the following case as well. 

According to the specification performing multiple operations in one PATCH request should happen as below.
```
Each PATCH operation represents a single action to be applied to the
same SCIM resource specified by the request URI.  Operations are
applied sequentially in the order they appear in the array.  Each
operation in the sequence is applied to the target resource; the
resulting resource becomes the target of the next operation.
Evaluation continues until all operations are successfully applied or
until an error condition is encountered.
```

Can test this with the following scenarios

1. Add and remove a non-existing member of a group in one request - user should not be added
2. Remove and add a non-existing member of a group in one request - user should be added
3. Add and remove an existing member of a group in one request - user should be removed
4. Remove an add an existing member of a group in one request - user should not be removed

**Comment by PasinduYeshan** [comment]
Following issues are addressed in this [PR](https://github.com/wso2/charon/pull/387)

- Change the error responses when adding a member to a group with only a display name.
- Change the error responses when adding a member to a group with only an ID.
- Change the error responses where a user is added with an empty ID.

**Comment by PasinduYeshan** [comment]
## Addressed Issue Scenarios and PRs

The following issue scenarios have been thoroughly addressed through the respective pull requests (PRs):

- Adding a member to a group with only the display name - [PR](https://github.com/wso2/charon/pull/387)
- Adding a member to a group with only the ID - [PR](https://github.com/wso2/charon/pull/387)
- Adding a member to a group with an invalid display name - [PR](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/478)
- Adding a member to a group with an invalid ID - [PR](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/478)
- Adding a user with mismatching user name and ID - [PR](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/478)
- Adding a user with an empty ID - [PR](https://github.com/wso2/charon/pull/387)
- Removing a non-existent member from a group (observed in LDAP user stores) - [PR1](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/478), [PR2](https://github.com/wso2/carbon-kernel/pull/3625)
- Removing a non-existent user from a group - [PR](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/478)

In the process of evaluating the above issue scenarios across various operational contexts, a specific scenario of interest emerged:

### Removal and Addition of a Non-Existing Member

When attempting to both remove and add a non-existing member of a group in a single request, a specific outcome was expected: the user should be added. The JSON snippet below depicts this scenario:

```json
{
    "schemas": [],
    "Operations": [
        {
            "op": "remove",
            "path": "members[display eq user1]"
        },
        {
            "op": "add",
            "value": {
                "members": [
                    {
                        "display": "user1",
                        "value": "db2c7659-1078-4afc-9bc3-f6fba6adc351"
                    }
                ]
            }
        }
    ]
}
```

This scenario operates as anticipated when using the username to remove the user. However, when utilizing the user ID for removal, a 400 response is encountered. The corresponding JSON snippet is provided below:

```json
{
    "schemas": [],
    "Operations": [
        {
             "op": "remove",
             "path": "members[value eq db2c7659-1078-4afc-9bc3-f6fba6adc351]"
        },
        {
            "op": "add",
            "value": {
                "members": [
                    {
                        "display": "user1",
                        "value": "db2c7659-1078-4afc-9bc3-f6fba6adc351"
                    }
                ]
            }
        }
    ]
}
```
This issue also has been fixed in the aforementioned PRs.
