### ISSUE TITLE
An issue in installing the server in FIPS 140-2-compliant mode on Mac OS.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16286]
**Describe the issue:**
When making the product pack fips compliant and then try to verify whether the pack is fips compliant or not fails with the bellow error.

```
Found bcprov-jdk15on entry in bundles.info. This should be removed.
Found bcpkix-jdk15on entry in bundles.info. This should be removed.
Verification failed : Product is not FIPS compliant.
```

This is the log from enabling Fips
```
Remove existing bcprov-jdk15on jar from plugins folder.
Successfully removed bcprov-jdk15on_1.70.0.wso2v1.jar from component/plugins.
Remove existing bcpkix-jdk15on jar from plugins folder.
Successfully removed bcpkix-jdk15on_1.70.0.wso2v1.jar from component/plugins.
sed: 1: "/Users/melani/Projects/ ...": invalid command code m
sed: 1: "/Users/melani/Projects/ ...": invalid command code m
Downloading required bc-fips jar : bc-fips-1.0.2.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3693k  100 3693k    0     0   456k      0  0:00:08  0:00:08 --:--:--  526k
Checksum verified: The downloaded bc-fips-1.0.2.3.jar is valid.
Downloading required bcpkix-fips jar : bcpkix-fips-1.0.7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  856k  100  856k    0     0   380k      0  0:00:02  0:00:02 --:--:--  382k
Checksum verified: The downloaded bcpkix-fips-1.0.7.jar is valid.
Please restart the server.
```
<img width="740" alt="Screenshot 2023-07-20 at 10 59 30" src="https://github.com/wso2/product-is/assets/41188245/a4e2df41-42d2-48eb-aa91-1cef7a5026f3">

**Expected behavior:**
The Verification should be successful after making the product Fips compliant.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0 Alpha3
 - OS: Mac
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
The root cause of the issue lies in two lines of the `fips.sh` script, specifically where `sed` commands are used. The discrepancy in behavior occurs because macOS employs the BSD version of `sed`, while Ubuntu uses the GNU version. The difference lies in the `extension` parameter, which is mandatory in macOS and optional in Ubuntu. Consequently, the current `sed` commands fail to execute properly, leading to a failure in FIPS compliance.

Erroneous Code
- https://github.com/wso2/product-is/blob/39af833329c2daa500ff0d8a8c36393724ab8844/modules/distribution/src/bin/fips.sh#L195
- https://github.com/wso2/product-is/blob/39af833329c2daa500ff0d8a8c36393724ab8844/modules/distribution/src/bin/fips.sh#L199

As a solution, there are two viable approaches:

1. **Use an empty string as the extension (Not recommended for macOS):**
   - This approach sets an empty string as the extension for the backup file. However, it is not recommended for macOS, and it may potentially cause unexpected issues on Ubuntu as well.
   - Example:
     ```bash
     sed -i '' '/bcprov-jdk15on/d' $bundles_info
     sed -i '' '/bcpkix-jdk15on/d' $bundles_info
     ```

2. **Create a backup file and delete it (Recommended approach for both macOS and Ubuntu):**
   - This method creates a backup file with the `.bak` extension and then removes the backup file after the `sed` operation is completed.
   - Example:
     ```bash
     sed -i.bak '/bcprov-jdk15on/d' $bundles_info && rm "$bundles_info.bak"
     sed -i.bak '/bcpkix-jdk15on/d' $bundles_info && rm "$bundles_info.bak"
     ```

**Comment by DilshanSenarath** [comment]
Considering all aspects, the most suitable approach is to utilize Perl instead of sed. Perl is readily available in both Ubuntu and macOS environments, offering consistent behavior on both platforms. Consequently, the proposed fixes are as follows.
 ```bash
     perl -i -ne 'print unless /bcprov-jdk15on/' $bundles_info
     perl -i -ne 'print unless /bcpkix-jdk15on/' $bundles_info
```
The command `perl -i -ne 'print unless /bcprov-jdk15on/' $bundles_info` is a Perl command used for text processing. Let's break down the components and explain what each part does:

1. `perl`: This is the command that invokes the Perl interpreter to execute the Perl code.

2. `-i`: This option enables "in-place" editing, similar to using `sed -i`. It modifies the input file directly without creating a backup file.

3. `-ne`: These are command-line options in Perl:
   - `-n`: Tells Perl to execute the code for each line of the input file (like a loop) without printing the line by default.
   - `-e`: Specifies the Perl code that follows as a command-line argument.

4. `'print unless /bcprov-jdk15on/'`: This is the Perl code that operates on each line of the input file.
   - `print`: This command prints the current line of the input file.
   - `unless /bcprov-jdk15on/`: This is a conditional statement using the "unless" construct. It checks if the regular expression `/bcprov-jdk15on/` is not found in the current line. If the regular expression is not matched (i.e., "unless" the pattern is present), the line is printed.

5. `$bundles_info`: This is a variable representing the path to the input file on which the Perl code is applied. The variable is expanded to its value, providing the full file path.

Overall, the command reads the content of the file specified by `$bundles_info` line by line, and for each line, it checks if the pattern `/bcprov-jdk15on/` is not found. If the pattern is not found, the line is printed to the standard output. As a result, lines containing the string "bcprov-jdk15on" are excluded from the output, effectively removing those lines from the file.
