### ISSUE TITLE
Lack of logs in AbstarctUserStoreManager class

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#16397]
**Describe the issue:**

1. Need to add more logs in [AbstarctUserStoreManager](https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java) , so that we can identify the flows properly:
2. Carbon-kerenel > usercore > AbstarctUserStoreManager.java > authenticateInternalWithID (method is too long. And logs are not sufficient. Need to check all the methods in this flow.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [6.2.0-alpha4]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AmshikaH** [comment]
Due to an error with running the PR builder with carbon-kernel PRs, integration tests couldn't be performed on the refactored methods, which are also core methods used in multiple authentication flows. Therefore, for the first stage of this issue, only debug logs have been added. Refactoring will be done in the second stage once the issue with running the PR builder has been resolved and further manual testing has been done.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
