### ISSUE TITLE
Missing Mention of Authentication Without Client Secret in Authorization Code Flow with PKCE

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#16444]
**Is your suggestion related to a missing or misleading document? Please describe.**
[The Authorization Code flow with PKCE](https://is.docs.wso2.com/en/latest/guides/login/oidc-auth-code-pkce/) is essential for public clients. However, solely enabling this flow will not suffice. It is also necessary to enable the 'Allow authentication without the client secret' option within the OAuth SP configuration. Currently, this requirement is not documented, and the emphasis is placed on noting the client secret, even though it is unnecessary for public clients.

**Describe the improvement**
1. Include a clear mention that the 'Allow authentication without the client secret' option must be enabled.
2. Clarify that public clients do not require a client secret or consider removing the mention of the client secret, as this document is exclusively intended for public clients (as indicated in the initial document description).

**Comment by janakamarasena** [comment]
There is no tight coupling with PKCE and public clients. While PKCE is mainly used as protection on authz code interception attacks which can be mainly present in public clients, its not the only use of pkce[1]. And also the current direction is that PKCE will be recommended to all types of apps confidential or public [2].

From the issue description what I got as the actual issue here is lack of guidence for public clients. For that if there is missing information lets address that in that manner in a place we provide guidance for public clients and not change the refered doc [3] to have public client information.

[1] - https://danielfett.de/2020/05/16/pkce-vs-nonce-equivalent-or-not/#confidential-clients
[2] - https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-authorization-code-grant
[3] - https://is.docs.wso2.com/en/latest/guides/login/oidc-auth-code-pkce/

**Comment by UdeshAthukorala** [comment]
These information was added to the doc space with below PRs:
- Master: https://github.com/wso2/docs-is/pull/3930
- 6.1.0: https://github.com/wso2/docs-is/pull/3932
- 6.0.0: https://github.com/wso2/docs-is/pull/3933

**Comment by UdeshAthukorala** [comment]
Closing since completed.
