### ISSUE TITLE
Support Remote Audit Log Server Configuration

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#16697]
**Is your suggestion related to an experience ? Please describe.**
With https://github.com/wso2/api-manager/issues/1565, we have implemented a UI/API to add configurations to publish the audit logs to a remote location. However, this implementation has below limitations.

- Configurations are not affected to all the nods in a cluster
- There is no way to check the configs once they are added
- If the remote server is un-available, logs for that period will be lost

**Describe the improvement**
We need to fill the above gaps in the feature.

**Comment by madurangasiriwardena** [comment]
Adding the configurations UI is tracked with https://github.com/wso2/product-is/issues/16464

**Comment by asekawa** [comment]
This feature fix will be QA rejected because of the following UI issues , as its unable to check the requiered flows accurately
1.https://github.com/wso2/product-is/issues/17007
2.https://github.com/wso2/product-is/issues/17012
3.https://github.com/wso2/product-is/issues/17035
4.https://github.com/wso2/product-is/issues/17040

**Comment by pavinduLakshan** [comment]
Closing the issue based on the "Done" state in the project.
