### ISSUE TITLE
Add missing application grant types in the new Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16715]
**Is your suggestion related to an experience ? Please describe.**
> We need to bring in the missing application grant type in the new Console. We need to discuss what grant types should be essentially included.

![image](https://github.com/wso2/product-is/assets/30111554/7503870b-1bba-4d7c-973a-6120a4f9c5a4)

**Comment by pavinduLakshan** [comment]
The following grant types are already available in the unified console, displayed to the end user depending on the application template.

- Code
- Implicit
- Password
- Client credentials
- Refresh token
- Device code
- Token exchange
- Organization switch

The following shows the missing grant types, and whether they should be included in the unified console along with the reasons.

| grant type | included in the unified console | reasoning |
| ---------- | ------------------------------- | ---------  |
| SAML2 | - | - |
| IWA-NLTM| YES | This will be required for the windows app template |
| account_switch| NO | due to https://github.com/wso2/product-is/issues/8806 |
| jwt-bearer | - | - |
