### ISSUE TITLE
Email templates are not updated with the proper branding configurations

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16764]
**Describe the issue:**

Email templates in the branding section, are not updated properly with the font colors and image logos added with the branding.

<img width="1226" alt="Screenshot 2023-09-22 at 10 35 56" src="https://github.com/wso2/product-is/assets/40081059/72c2edbd-c40f-467a-bf63-91ccce2cd060">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

- Product Version: [e.g., 7.0.0 M2 - https://github.com/wso2/product-is/releases/tag/v7.0.0-m2]
- OS: [e.g., Mac]
- Database: [e.g., MySQL, H2]
- Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Logo URLs are `http` therefore the logo images are not rendered in the template previews. In addition, we should use the assets from [WSO2 Branding](https://wso2.com/about/brand/) for email templates instead of current image URLs.

These should be fixed from the event handler extension [1].

[1] https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/features/org.wso2.carbon.email.mgt.server.feature/resources/email-admin-config.xml

**Comment by madurangasiriwardena** [comment]
Related improvements: https://github.com/wso2/product-is/issues/16985
