### ISSUE TITLE
Stabilize OIDC Conformance Test Suite

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16784]
**Describe the issue:**

Need to stabilize the OIDC Conformance test suite (https://github.com/wso2/product-is/actions/workflows/oidc-conformance-test.yml). Currently, most of the test cases are failing because the UI elements are changed after the unification effort. Need to change the references in the config files in the conformance test suite eg: https://github.com/wso2/product-is/blob/master/oidc-conformance-tests/config/browser_configuration.py

**Comment by chamathns** [comment]
This has been failing since the UI unification. We must get this stabilized and run it before the alpha release to identify any spec violations.
cc: @madurangasiriwardena @hasanthiP @jeradrutnam @NipuniBhagya

**Comment by janakamarasena** [comment]
Reopening the issue as the conformance suite is still falling. Let's close this issue once the conformance suite has passed.

**Comment by DilshanSenarath** [comment]
At present, the conformance test suite fails to run, displaying the following error for the claim mapping update API request.
<img width="996" alt="image" src="https://github.com/wso2/product-is/assets/74205483/a9e3b217-9840-46b0-b274-753b2c5b8951">

The error stems from a recent addition of default management APIs into the `API Resources` feature. This enhancement requires subscriptions and role permissions to access the APIs. Consequently, all API calls are currently failing. To address this issue, we must modify the conformance suite Python script to subscribe to the necessary APIs and acquire the relevant permissions.

This issue will be fixed with this PR - https://github.com/wso2/product-is/pull/17496
Local test summary with above fix
<img width="1406" alt="image" src="https://github.com/wso2/product-is/assets/74205483/4d3d3338-ff3c-49b5-95d5-5e0846b7969c">
<img width="1406" alt="image" src="https://github.com/wso2/product-is/assets/74205483/eb39c121-62c5-4739-95f3-68c5af529bed">

**Comment by DilshanSenarath** [comment]
The conformance test suite succeeded in the IS7 release - https://github.com/wso2/product-is/actions/workflows/oidc-conformance-test.yml
