### ISSUE TITLE
User Name Not Displaying in Greeting and Under Avatar in console/myaccount when Username is Set as Email 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16896]
**Describe the issue:**
When configuring WSO2 Identity Server to use email addresses as usernames in the JDBC user store(default H2), the user's name is not displayed in the greeting section and under the avatar in the console/myaccount page. This behavior is unexpected and impacts user identification and navigation within the console.

**How to reproduce:**
1. Configure deployment.toml configs and  Edit link corresponding to the Username claim and configure the Mapped Attribute property to `mail.` to use email addresses as usernames in the JDBC user store.
2. Log in to the Identity Server.
3. Navigate to console/myaccount.
Additional toml configs( no other changes in toml changes)
`[tenant_mgt]
enable_email_domain= true `

`
[user_store]
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
username_java_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'
`
Refereed: https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/#configure-email-address-as-the-username 

**Expected behavior:**
The user's name should be displayed in the greeting section and under the avatar in the console/myaccount page.

Tested Env:
Product Version: 7.0.0-m3 (default userstore & other changes)
Java Version: 17.0.8.1
Operating System: Ubuntu & MacOS

![Screenshot from 2023-10-09 17-37-36](https://github.com/wso2/product-is/assets/39120228/cdb345bd-a993-4cfb-8ad8-33d2f114616f)

![Screenshot from 2023-10-09 17-37-55](https://github.com/wso2/product-is/assets/39120228/f21a49cf-e61e-4ed9-8a02-b22a34939fac)

![Screenshot from 2023-10-09 17-38-59](https://github.com/wso2/product-is/assets/39120228/7d45d89c-f523-49e7-94de-01cec063a4ac)

**Comment by chamathns** [comment]
@NilukaSripalim can you please update the screenshots?

**Comment by pavinduLakshan** [comment]
Reproducible in the latest pack.

![Screenshot 2023-10-10 at 12 13 20](https://github.com/wso2/product-is/assets/41533942/08dd3d4d-584f-45c7-9a82-c13919cf745d)

**Comment by pavinduLakshan** [comment]
When the email as user name feature enabled, `profileInfo` state variable [1] is populated with an object with empty values.

```json
{
    "emails": [
        null
    ],
    "id": "06558241-851d-469e-9e37-7d4d4b23560d@carbon.super",
    "name": {
        "familyName": "",
        "givenName": ""
    }
}
```

This happens because the decoded token doesn't have email, profileurl and username properties when the email as username feature is enabled. [2]

```json
{
    "isk": "e69671283e98cf5095a15b0807c1b2a8b0285b102b0cb97a9685f0e8bb67cf3e",
    "at_hash": "XmNnXdbzAut6P0Er_5o7dQ",
    "sub": "06558241-851d-469e-9e37-7d4d4b23560d@carbon.super",
    "amr": [
        "BasicAuthenticator"
    ],
    "iss": "https://localhost:9443/oauth2/token",
    "sid": "f457390d-c3ed-4d72-ac90-02fe663e858e",
    "aud": "CONSOLE",
    "c_hash": "oiox3KdLcIYP0J2sLEqc7g",
    "nbf": 1696920938,
    "azp": "CONSOLE",
    "org_id": "10084a8d-113f-4211-a0d5-efe36b082211",
    "exp": 1696924538,
    "org_name": "Super",
    "iat": 1696920938,
    "jti": "85d20463-79b0-45fd-8c1c-8f303fc60c80"
}
```

[1] https://github.com/wso2/identity-apps/blob/master/apps/console/src/extensions/components/getting-started/components/advance-user-view.tsx#L467
[2] https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/authentication/store/actions/authenticate.ts#L94

**Comment by sahandilshan** [comment]
This is happening because once we mapped the email to the username, the claim mgt handler gets the value that is available in the email claim of the user profile and assigns it to the user. So when the new admin account (admin@wso2.com profile) gets created, it doesn't have the email address by default. We need to add it to the profile manually. Once we add the email to the profile, the username will be shown in the UI as expected.

<img width="485" alt="Screenshot 2023-10-16 at 10 21 44 AM" src="https://github.com/wso2/product-is/assets/32576163/d945b870-bc87-464b-91c9-6ad3b34fc84a">

As the solution, 
- We need to either update the documentation saying that we need to manually add the email address to the user profile or
- We need to add the email address by default when the new admin account get created

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
