### ISSUE TITLE
After adding a custom mandatory claim for B2B app, that claim is prompted for multiple times when trying the login flow

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16910]
**Describe the issue:**

when setting  custom attributes for sub org application , the  values for newly created custom attributes are asked twice

https://github.com/wso2/product-is/assets/40081059/c01e9cc5-bff1-4c9f-870b-cfbb42c13f46

**Feature issue relevant to the bug** - https://github.com/wso2/product-is/issues/16702

**How to reproduce:**

1. create a sub-organization.
2.create a b2b app and share with the application with a sub org
3.Create a  custom attribute to the application as requested and mandatory attributes
4.Create a new user to in the suborg

try to login into the sub org with the created user
**Expected behavior:**

Ideally the values of the attributes should not be asked for twice in the UI
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
1. Dur to https://github.com/wso2/product-is/issues/16914 this issue OIDC claim mapping and scim claim mapping haven't been created in sub-org space
2. inorder to retrieve user data from sub org to parent org, need to specify the relevant scopes which associates the requested user attributes. In this flow, scopes has not been requested from the application and the added custom attributes are not mapped into any scope
3. Due to the missing scope request parent org doesn't get attributes from sub org for the custom attributes.
4. Anyway, we don't have a mechanism to propergate oidc scope changes in parent to sub-organization. Need to fix this
5. Even though a mandatory attributes values were given during the login flow, those data not getting updated in the user profile for sub-org users. Need to investigate this issue and fix

**Comment by ChanikaRuchini** [comment]
oidc application login flow with custom mandatory attributes
[Untitled_ Oct 18,2023 1_18 PM.webm](https://github.com/wso2/product-is/assets/36252774/67f1a09d-228b-4e98-b410-8a3dfd48ad60)


saml application login flow with custom mandatory attributes
[Untitled_ Oct 18,2023 1_24 PM.webm](https://github.com/wso2/product-is/assets/36252774/fe835c3e-94b4-46ae-abe6-452b4c98bd92)
