### ISSUE TITLE
The "Bult import" users option should not be available /visible for secondary user store

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16980]
**Describe the issue:**

The "Bult import" users option should not be available for the secondary user store

https://github.com/wso2/product-is/assets/40081059/60e152ec-7f03-4693-b058-6fb4f3a3295e

Git issue - https://github.com/wso2/product-is/issues/16935
The local build given below is used for testing-
[https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoM](https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoMCpqP)

**How to reproduce:**

1.Login into the console using the below local pack
https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoMCpqP
2.Go to the user management section => users => Add user
3.Select a secondary user store(should create a secondary user store before)
3.Choose bulk import option
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
IMO, the primary function of the user store filter dropdown should be to refine the table results. Using it to conditionally hide or show options, like the bulk import, might not be the most intuitive approach. For instance, when adding a user, the wizard provides an option to select a user store if multiple are available. It would be more consistent. In the absence of multiple user stores, the system explicitly shows that the "DEFAULT" user store is selected, rather than making implicit assumptions based on the dropdown.

![image](https://github.com/wso2/product-is/assets/61885844/3b6590a9-6f89-4d58-ac0c-3ee37bcef364)

**Comment by PasinduYeshan** [comment]
Issue - https://github.com/wso2/product-is/issues/16935

**Comment by PasinduYeshan** [comment]
This issue is addressed in this PR - https://github.com/wso2/identity-apps/pull/4252

![image](https://github.com/wso2/identity-apps/assets/61885844/c435caf1-1a1b-4905-b681-d74aabdb8f0b)

**Comment by PasinduYeshan** [comment]
This is resolved in the wso2is-7.0.0-m4-SNAPSHOT-4889 Build

![Screenshot 2023-10-25 at 09 58 20](https://github.com/wso2/product-is/assets/61885844/01cb8d65-de6d-4e7c-b451-b18fb6225dd9)
