### ISSUE TITLE
Missing Icon in Connection Card Created After Configuring HYPR Authenticator in IS Console

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16994]
**Describe the issue:**
The connection card generated after configuring the HYPR authenticator in the IS console doesn't contain the corresponding icon.

<img width="1511" alt="Screenshot 2023-10-17 at 08 35 50" src="https://github.com/wso2/product-is/assets/41188245/4c74bcfd-d9c6-48b6-b0b0-b9699340a03f">

**How to reproduce:**

**Expected behavior:**
The Connection card should contain the corresponding icon.
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This issue is no longer reproducible in the latest build.

![Screenshot 2023-10-21 at 13 47 07](https://github.com/wso2/product-is/assets/41533942/f3da4d19-427f-4fb3-83fc-47c11266a097)
![Screenshot 2023-10-21 at 13 47 28](https://github.com/wso2/product-is/assets/41533942/55ff8704-7cb1-44b2-8da3-5189951728c6)
![Screenshot 2023-10-21 at 13 48 05](https://github.com/wso2/product-is/assets/41533942/6884cb7f-c4e4-4c64-880a-210e17dd1a0a)
