### ISSUE TITLE
Cannot import bulk users for suborganizations

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17051]
**Describe the issue:**

Cannot import bulk users for suborganizations , as getting the following error while importing a csv
<img width="1489" alt="Screenshot 2023-10-19 at 10 39 28" src="https://github.com/wso2/product-is/assets/40081059/258106bc-5811-41d9-b195-8239675b90f4">

**How to reproduce:**

1.Login into the console
2. Create a sub-organization
3.Go to users section
4.Click on add user
5.Select import bulk users option
6.Select upload option -> upload a csv file which contains user information

**Expected behavior:**

users should be able to import via csv successfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
- The sub-organizations use organization-qualified APIs (`o/<org-id>` path)
- The initial idea of not supporting the /scim2/Roles endpoint in the `o/<org-id>` path is to restrict creating carbon/hybrid roles inside the organizations. Instead, we use organization roles to manage permissions.
- Therefore selected set of scim2 endpoints was allowed to use in the `o/<org-id>` path
- If the `/scim2/Bulk` is supported in the `o/<org-id>` path, users can use the bulk endpoint to create carbon/hybrid roles
---------
- Since we are moving from given custom role mgt feature for B2B case and going to use /scim2/v2/Roles (still sub-orgs can't define their own role here). 
- As an improvement let's block the scim2/Roles endpoint for role creation and update for sub-orgs in API service level.
- Hence +1 to enable scim2/Bulk endpoint to use with organization context.

**Comment by PasinduYeshan** [comment]
This issue is addressed in following PRs.
- Enable `scim2/Bulk` endpoint to use with organization context - https://github.com/wso2/carbon-identity-framework/pull/5022

- Block sub orgs from role creation - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/489

- Fix claim dialects issue in front end - https://github.com/wso2/identity-apps/pull/4252

**Comment by PasinduYeshan** [comment]
This issue is resolved.
