### ISSUE TITLE
Support organization resource access with tenant & organization perspective

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#17120]
**Describe the issue:**

The organization resources should be accessible in tenant perspective and organization perspective.
- The tenant perspective resource access - `/t/<tenant-domain>/api/server/v1/applications`
- The organization perspective resource access - `/t/<tenant-domain>/o/api/server/v1/applications`

Each perspective has separate personas and use cases. Identity server should support for these cases.

**Comment by dewniMW** [comment]
In the on-prem console for the primary org (super tenant), currently endpoint paths are in the format `o/10084a8d-113f-4211-a0d5-efe36b082211`. Internally there can be logics that is written to fetch the organization ID from context (with the aforementioned improvement this would be null for super tenant). If so those flows might be impacted due to this. Therefore let's confirm that there are no breaking changes due to this.
