### ISSUE TITLE
Getting a 404 page when user tries to self register through the console

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17159]
**Describe the issue:**

Getting a 404 page when user tries to self register , due to the incorrect url.
There is a null point tenanted path in the registration url (https://localhost:9443/authenticationendpoint/null/register.do?utm_source=console)

https://github.com/wso2/product-is/assets/40081059/b01eded8-32ce-4325-b9a7-bc6177564ad9

**How to reproduce:**

1. Login in to the console
2.Click on the "Register" button
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ImalshaG** [comment]
With the recent unification effort, in the console login page the `Register` button is available for self registration even if self registration is disabled.
<img width="443" alt="image" src="https://github.com/wso2/product-is/assets/47671237/5f3b1e19-c7c9-421f-a744-67228169e7b5">

When self registration is enabled, both the `Register` button and `Create and account` button is visible.

<img width="457" alt="image" src="https://github.com/wso2/product-is/assets/47671237/cc272eef-576e-48f7-8f46-d4b15e1e492a">

Therefore `Register` button should be removed from the login UI.

In the login page, the logic handles myaccount and console separately [[1](https://github.com/wso2/identity-apps/blob/master/identity-apps-core/apps/authentication-portal/src/main/webapp/login.jsp#L1036)] but since the `tenantForTheming` parameter passed is null this button is not visible in the myaccount. Therefore we should be mindful about this logic when fixing this issue since the Register button might be visible if tenantForTheming value is not null.


[1] https://github.com/wso2/identity-apps/blob/master/identity-apps-core/apps/authentication-portal/src/main/webapp/login.jsp#L1036

**Comment by pavinduLakshan** [comment]
This issue is tracked with https://github.com/wso2/product-is/issues/17433
