### ISSUE TITLE
Order the role audience data of user's assigned role object

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17189]
**Describe the issue:**
Get postman collection https://api.postman.com/collections/3680909-831b3c6b-cb35-4d20-b033-aae888bb3bb1?access_key=PMAT-01HCKTY1A596D0E0R1G45JNMAC
1. Add the following config to deployment.toml
```
[legacy_authz_runtime]
enable = false
```
3. Create roles using scim2/v2/Roles API
4. Asisgn those roles to a user/ group
5. Get the group/ user 
The assigned roles will be returned as follows. The role's audience data should be located in order(as near by attributes)
<img width="1346" alt="Screenshot 2023-10-25 at 12 06 47" src="https://github.com/wso2/product-is/assets/25483865/a6966a85-1dc8-48a3-8bc9-a7c335945119">

Expected behavior:
```
    "roles": [
        {
            "display": "RoleXYZ",
            "value": "4eff56e8-1398-4f85-b6af-7d776f0966b9",
            "$ref": "https://localhost:9443/scim2/v2/Roles/4eff56e8-1398-4f85-b6af-7d776f0966b9",
            "audienceValue": "10084a8d-113f-4211-a0d5-efe36b082211",
            "audienceDisplay": "Super",
            "audienceType": "organization",
        }
    ],
```

**Analysis:**
We can't add audience as a complex object as follows due to scim spec violation. (Complex attribute's sub attribute can't be a complex attribute)
```
    "roles": [
        {
            "display": "RoleXYZ",
            "value": "4eff56e8-1398-4f85-b6af-7d776f0966b9",
            "$ref": "https://localhost:9443/scim2/v2/Roles/4eff56e8-1398-4f85-b6af-7d776f0966b9",
            "audience" : {
                 "value": "10084a8d-113f-4211-a0d5-efe36b082211",
                 "display": "Super",
                 "type": "organization",
            }
        }
    ],
```

Why the properties are not in order of insertion:
1.  sub attribute list in a complex object is a hashMap https://github.com/wso2/charon/blob/d5f33f80e27a99c8223749b88187ec072d88c736/modules/charon-core/src/main/java/org/wso2/charon3/core/attributes/ComplexAttribute.java#L106 in charon side -> We can fix this point by changing it to LinkedHashMap
2. But the final SCIM output is generated from the JSONEncoder . This is the place where complex object is processed https://github.com/wso2/charon/blob/d5f33f80e27a99c8223749b88187ec072d88c736/modules/charon-core/src/main/java/org/wso2/charon3/core/encoder/JSONEncoder.java#L366
JSONObject uses a hashmap inside.
Inorder to preserve the order of insertion need to move with jackson or Gson

**Comment by Shenali-SJ** [comment]
## Using Jackson to preserve the insertion order
In order to preserve the insertion order of attributes it was decided to use Jackson instead of Gson mainly due to the wide adoption of Jackson in the IS code base. 

There are two ways Jackson could be utilized to preserve the insertion order.
1. Using [SearlizationFeature](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.9.5/com/fasterxml/jackson/databind/SerializationFeature.html) enum
2. Using [JsonPropertyOrder](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/latest/com/fasterxml/jackson/annotation/JsonPropertyOrder.html) annotation

Out of the above two methodologies, the first option is chosen as configuring the object mapper directly without using annotations is known to be more convenient. 

### Configuring the object mapper using SerializationFeature
This was introduced with Jackson 2.9.5. (The IS code base is using Jackson [2.12.6.1](https://github.com/wso2/charon/blob/04c815d12e0ce8bc09cccb535eaa9ed977468320/pom.xml#L311) )

Therefore, [ORDER_MAP_ENTRIES_BY_KEYS](https://www.javadoc.io/static/com.fasterxml.jackson.core/jackson-databind/2.9.5/com/fasterxml/jackson/databind/SerializationFeature.html#ORDER_MAP_ENTRIES_BY_KEYS) feature in the SearlizationFeature enum in Jackson will be used to preserve the insertion order.

**Comment by Shenali-SJ** [comment]
Even though using Jackson to preserve the insertion order seemed like the most convenient solution, upon further analysis it was found that the existing code base would have to be changed considerably. Due to implementational level complexities, all the functions associated with the core functionality that is causing the problem need to be updated to use Jackson ObjectMapper as opposed to the already existing JSONObject.

Further analysis needs to be done to figure out if simply utilizing a LinkedHashMap would facilitate the purpose of preserving the insertion order of complex objects in order to avoid the complexities that would occur when migrating the code base to use Jackson ObjectMapper.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
