### ISSUE TITLE
When 'Application Domain' is selected from the filter dropdown, the Role page displays a blank UI. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17201]
**Describe the issue:**
In the role roles page when `Application Domain` is selected from the dropdown, it gets an empty UI. 
<img width="1499" alt="Screenshot 2023-10-25 at 14 45 09" src="https://github.com/wso2/product-is/assets/41188245/678d553a-25b2-4e9e-9f1e-47c97c5a873c">

https://github.com/wso2/product-is/assets/41188245/47b55a2e-5924-44c4-97ce-ae05ccb3f941

**How to reproduce:**

1. Redirect to the roles page 
2. Select `Application Domain` from the filter dropdown.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
- If someone has created "Application" domain roles through the legacy management console, or enabled Application domain role creation feature on the application creation event, those are also listed in the Roles list in new Console's roles UI.
- Therefore, the ability to filter roles by application domain is fine.

If there is no result found from the filter, the UI should show no result found instead of empty page

**Comment by NipuniBhagya** [comment]
Since we have the Adminstrator application role by default now this shouldn't reproduce in the latest packs. @melanisilva could you please verify?

**Comment by melanisilva** [comment]
Verified and not reproducible in the latest pack; therefore, closing this issue.

https://github.com/wso2/product-is/assets/41188245/56257032-15f5-4dff-bfb9-4a8c5dca6a43
