### ISSUE TITLE
When update the groups related to the user, its redirected to the profile section in the edit user interface

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#17322]
**Is your feature request related to a problem? Please describe.**

Currently in the edit user interface, when we update the groups related to the user, its redirected to the profile section of the interface.

**Describe the solution you would prefer**

Since this process breaks the user flow, because they expect to stay in the groups section, ideally to confirm whether the intended change has happened, they instead redirected to the profile section, and they have to click again on the groups tab to view the details have been updated.

**Additional context**

https://github.com/wso2/product-is/assets/55197812/0be297fd-b584-456f-83a4-bb88ae03af7c

**Related Issues:**
- #17318

**Comment by Achintha444** [comment]
This is fixed in the `roles` interface section. Developer who gets assigned for this issue can view those files to get an idea on how to approach this issue.

- https://github.com/wso2/identity-apps/blob/86af656e628d644f0c870c24d10f0a16aae98c8b/apps/console/src/features/roles/pages/role-edit.tsx#L54
