### ISSUE TITLE
myaccount access link is not visible to admin when admin switch to an org and come back to tenant

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17357]
**Describe the issue:**
1. admin login to console super tenant. my account access url is visible in header 
2. admin switch to the sub organization . Myaccount link is not visible -> This is expected
3. Admin switch back to super tenant. Still myaccount link is not visible -> This should be available 

https://github.com/wso2/product-is/assets/25483865/64ae7057-f042-4e1a-ae8e-579c70b897d5

**Comment by JayaShakthi97** [comment]
Here we are setting organization name rather than the id for first level orgs.
https://github.com/wso2/identity-apps/blob/eec53249a0d61b971e21fdd2afe0a623167bf08f/apps/console/src/features/authentication/hooks/use-sign-in.ts#L158

This affects the condition check here, since when a user switches back to root user_org will be available in IDToken. And the organization name becomes empty.
https://github.com/wso2/identity-apps/blob/eec53249a0d61b971e21fdd2afe0a623167bf08f/apps/console/src/features/core/components/header.tsx#L386

Need to validate why aren't we considering org_id other than org_name.

**Comment by JayaShakthi97** [comment]
- Fix is applied along with: https://github.com/wso2/product-is/issues/17467

Fixed in Beta-SNAPSHOT.

https://github.com/wso2/product-is/assets/37938529/7619190f-a147-4ccd-be08-b916f8d1683c
