### ISSUE TITLE
Getting an error when trying to enable SMS OTP

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17439]
**Describe the issue:**

Getting an error when trying to enable SMS OTP from the toggle

https://github.com/wso2/product-is/assets/40081059/998aa1c1-22aa-4e81-b228-5e94f8f43da8

**How to reproduce:**

1.Login to the console
2.Go to connections tab
3.Go to sms otp connection and try to enable it through a toggle

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JKAUSHALYA** [comment]
This configuration is related to the Asgardeo and we have to remove this "Toggle button" and related text in the IS. The text should be changed to pointing (Better to hyperlink) to the section where we can configure the SMS Providers. (Under the branding/notification channels/SMS Providers.)

However this text should be conditionally enabled in the Asgardeo due to this is related to how Asgardeo handles SMS sending at the moment. 

Due to this I think this should not be a blocker but a critical UI fix.

**Comment by madurangasiriwardena** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/4444
