### ISSUE TITLE
All Application list API displays allowed audience as `organization` for all applications

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#17447]
**Describe the issue:**
All Application list API displays allowed audience as `organization` for all applications

<img width="1426" alt="Screenshot 2023-10-31 at 14 53 32" src="https://github.com/wso2/product-is/assets/27746285/a47be56d-8fba-4da7-8c6d-a469e04dd6db">

**Steps to reproduce**

- Create a new application
- Change the allowed audience to `application` from the `Application > Roles` tab
- All Application list API displays allowed audience as `organization` for all the applications.

**Comment by AnuradhaSK** [comment]
This issue happens when the application list is invoked with different requested attributes other than `associatedRoles.allowedAudience`.
Ideally, allowedAudeince of associated role should not be returned in application listing view unless it is requested.

Fixed by:

https://github.com/wso2/identity-api-server/pull/522

After fixing:
<img width="1076" alt="Screenshot 2023-10-31 at 17 28 28" src="https://github.com/wso2/product-is/assets/25483865/c9f250dd-09cd-43ff-8cd8-41255c0cec0d">

<img width="1267" alt="Screenshot 2023-10-31 at 17 28 45" src="https://github.com/wso2/product-is/assets/25483865/dd100e35-deed-48fe-ac8b-927508469941">
