### ISSUE TITLE
Role creation button will disappear in carbon.super tenant if you switch to a suborg and come back

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17467]
**Describe the issue:**
1. Log into carbon.super tenant
2. Go to Roles tab and check that +New Role button is available
3. Create an organization
4. Switch to the new org
5. Come back to the carbon.super (root) org
6. Go to roles tab
7. Role creation button is not available.

https://github.com/wso2/product-is/assets/25483865/ccd2de24-8e23-41b0-b48d-5bcebdfbc164

Tried the same flow in another tenant. but couldn;t reproduce in that tenant

**Comment by dewniMW** [comment]
A similar behavior was observed for application create button.

**Comment by JayaShakthi97** [comment]
In the current UI implementation, a first-level organization is identified by IDToken's user_org value. If the user_org is not available, then it's a first-level org.
When a user logs in to a first-level org, IDToken's user_org value is not available. But when the user switches to an organization and switches back to the tenant, IDToken's user_org value is available. Due to this inconsistency, these flows are breaking.

**Comment by JayaShakthi97** [comment]
- This issue will be fixed with: https://github.com/wso2-extensions/identity-oauth2-grant-organization-switch/pull/26

**Comment by JayaShakthi97** [comment]
Fixed in latest beta-SNAPSHOT.

https://github.com/wso2/product-is/assets/37938529/2f619287-2ec3-40a9-a670-05e99511ae97

**Comment by JayaShakthi97** [comment]
- Refactoring is done to make the related flow fail-proof: https://github.com/wso2/identity-apps/pull/4522
