### ISSUE TITLE
Page refresh navigates to getting-started page

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#17477]
**Describe the issue:**

- Page refresh from any page like Users. Connections and Applications navigates the user to getting started page.
- Page refresh from **sub org** navigates to super org getting-started page. 

https://github.com/wso2/product-is/assets/27746285/203c3e63-fa8e-440a-b849-ac550d8491ca

https://github.com/wso2/product-is/assets/27746285/4cba979c-f1a6-4ba3-b31b-9ec31a10e719

**Steps to reproduce**

Scenario 01
-  Login to console
-  Navigate to Users section
-  Refresh the Page

Scenario 02
- Navigate to sub org
- Refresh the page
 
 **Expected Behaviour**
 User expects to navigate to the same page after page refresh

**Comment by ayshsandu** [comment]
same issue reported in https://github.com/wso2/product-is/issues/17554

**Comment by dhaura** [comment]
### Scenario 01 Analysis
- This issue occurred due to receiving `true` for `AppUtils.isAuthCallbackURLFromAnotherTenant()` [1] for super tenant paths and thus returning the base home path [2].
- In the above method the `tenantDomian` of the ID token and the tenant name contained in the Authentication Callback Url is compared.
- Previously (before enabling tenanted paths for super tenant), super tenant urls did not contain `t/carbon.super`, and therefore,  there was a special case for making the tenantDomain `""` for the super tenant since the tenant name contained in the Authentication Callback Url of the super tenant will be empty.
- But after enabling tenanted paths in IS super tenant, super tenant Authentication Callback Url now contains the tenant name as `carbon.super`, thus failing the above mentioned method.
- This issue is fixed by - https://github.com/wso2/identity-apps/pull/4542

[1] - https://github.com/wso2/identity-apps/blob/048751f18921241ee91852a0ec9a6dbe939f1a9e/apps/console/src/protected-app.tsx#L264
[2] - https://github.com/wso2/identity-apps/blob/048751f18921241ee91852a0ec9a6dbe939f1a9e/apps/console/src/protected-app.tsx#L268

**Comment by amanda-ariyaratne** [comment]
In the development server running on port 9001, page refresh on suborganization works as expected. But on the IS server, it navigates to getting started page of the primary organization.
