### ISSUE TITLE
x509 certificate authenticator configured AuthenticationEndpoint URL is not honored when redirecting to commonauth and authorize endpoints

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#17484]
**Describe the issue:**
When configuring x509 Authenticator the following configurations are included in deployment.toml file to configure AuthenticationEndpoint URL

[authentication.authenticator.x509_certificate.parameters]
name ="x509CertificateAuthenticator"
enable=true
AuthenticationEndpoint="[https://sswso2is.local:443/x509-certificate-servlet](https://sswso2is.local/x509-certificate-servlet)"
username= "CN"

But after the successful response from the configured AuthenticationEndpoint url above ([https://sswso2is.local:443/x509-certificate-servlet?<params](https://sswso2is.local/x509-certificate-servlet?%3Cparams)>), user redirects to https://<Identity_server_hostname>:8443/commonauth?sessionDataKey=<>&success=true instead of redirecting to configured Authenticationendpoint URL domain (ex: [https://sswso2is.local:443/commonauth](https://sswso2is.local/commonauth)). This happens because of [1]. Same happens when redirecting to /oauth2/authorize when redirecting from above mentioned commonauth endpoint.

**How to reproduce:**
This can be reproduced using following steps

1. Set up x509 authenticator as second step using [2]
2. Set up fronting nginx
3. configure different domain name from Identity server hostname for AuthenticationEndpoint using following configuration deployment.toml

[authentication.authenticator.x509_certificate.parameters]
name ="x509CertificateAuthenticator"
enable=true
AuthenticationEndpoint="[https://sswso2is.local:443/x509-certificate-servlet](https://sswso2is.local/x509-certificate-servlet)"
username= "CN"

4. Then map configured domain name in AuthenticationEndpoint URL config to wso2 identity server’s 8443 port in nginx
5. Configure x509 CertificateAuthenticator as second step in authentication flow

**Expected behavior:**
After successful response from configured x509-certificate-servlet endpoint (AuthenticationEndpoint="https://sswso2is.local:443/x509-certificate-servlet"), redirect user to the commonauth endpoint of configured domain name in above AuthenticationEndpoint URL (ex: https://sswso2is.local:443/commonauth) and then to oauth2/authorize endpoint instead of redirecting to https://<Identity_server_hostname>:8443/commonauth and https://<Identity_server_hostname>:8443/oauth2/authorize.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---
[1] - https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/82c502d07e0b4247ed442b6cab57e143d16d0e18/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/x509Certificate/X509CertificateServlet.java#L62

[2] - https://is.docs.wso2.com/en/5.11.0/learn/x509certificate-authenticator/
### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mpmadhavig** [comment]
The issue created was concerned about the following network calls.

1. `POST https://<Identity_server_hostname>:8443/commonauth`
- Purpose: Calls the initiateAuthenticationRequest of x509Authenticator.

2. `GET https://<configured_domain>:443/x509-certificate-servlet?client_id=MY_ACCOUNT&code_challenge=UjRw9rp9RVgfkZd0c9pAXere4SgxoL_sw-Blf6vZp2Q&code_challenge_method=S256&commonAuthCallerPath=/oauth2/authorize&forceAuth=false&passiveAuth=false&redirect_uri=https://localhost:9443/myaccount/login&response_mode=form_post&response_type=code&scope=SYSTEM openid&tenantDomain=carbon.super&sessionDataKey=7d070492-10a6-4e7f-a278-6376a0d18c2c&relyingParty=MY_ACCOUNT&type=oidc&sp=My Account&isSaaSApp=true`

- Purpose: Redirects user to the `AuthenticationEndpoint` config defined as a `x509_certificate` parameter and extract the x509 certificate from the browser.

```
[authentication.authenticator.x509_certificate.parameters]
name ="x509CertificateAuthenticator"
enable=true
AuthenticationEndpoint=https://<configured_domain>:443/x509-certificate-servlet
username= "CN"
```

3. `GET https://<Identity_server_hostname>:8443/commonauth?sessionDataKey=7d070492-10a6-4e7f-a278-6376a0d18c2c&success=true`

- Purpose: Process the extracted certificate and processAuthenticationResponse.

Invocation of the x509Authenticator happens by calling `https://<Identity_server_hostname>:8443/commonauth` endpoint, which resides in the IS server itself.

As part of authentication request initialization, x509Authenticator redirects user to the configured, AuthenticationEndpointURL to extract the certificate. After extraction, browser initiates another /commonauth request to send the certificate to the authenticator. Therefore the 3rd network call being initiated to the  `https://<Identity_server_hostname>:8443/commonauth` endpoint. As this request should be sent to the IS server, using the IS host name, the mentioned behavior in the issue is expected.

We see there is a gap in the documentation to the definition of the AuthenticationEndpoint config that could be confusing. We will address this by fixing the docs.

**Comment by daoxxx** [comment]
> 3. `GET https://<Identity_server_hostname>:8443/commonauth?sessionDataKey=7d070492-10a6-4e7f-a278-6376a0d18c2c&success=true`
> 
> * Purpose: Process the extracted certificate and processAuthenticationResponse.
> 
> Invocation of the x509Authenticator happens by calling `https://<Identity_server_hostname>:8443/commonauth` endpoint, which resides in the IS server itself.

As we see Invocation's made to x509 servlet's endpoint `:8443/commonauth`. So where does it actually reside?

> After extraction, browser initiates another /commonauth request to send the certificate to the authenticator. Therefore the 3rd network call being initiated to the `https://<Identity_server_hostname>:8443/commonauth` endpoint. As this request should be sent to the IS server, using the IS host name, the mentioned behavior in the issue is expected.

Who does processing of this request,  IS server itself or x509 servlet?

> We see there is a gap in the documentation to the definition of the AuthenticationEndpoint config that could be confusing. We will address this by fixing the docs.

Was this addressed in the docs? I can't find it.
