### ISSUE TITLE
Backup coded can be enabled through myAccount only when Authenticator App is configured

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17491]
**Describe the issue:**

Backup coded can be enabled through myAccount only when Authenticator App is configured.
Otherwise the button would remain disabled.

<img width="900" alt="Screenshot 2023-11-01 at 12 23 14" src="https://github.com/wso2/product-is/assets/40081059/22bfb973-16d8-4ef0-a558-a43e4b930a4c">
According this message , backup coded should be abled to configured when atleast one  step is  configured

https://github.com/wso2/product-is/assets/40081059/693cf3bf-08a3-42d6-94f5-fbb2504fc2d5

**How to reproduce:**

1. Go to the myAccount =>security
2. Go to the Additional Authentication section
3. Configure Passkey and SMS Number

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JeethJJ** [comment]
This issue occur since, by adding a mobile number, we are not enabling an authenticator.  As mentioned in the image above `At least one additional authenticator should be configured to enable backup codes.` 
Hence, when we add the mobile number, we do not allow the generation of backup codes. Adding authenticator app (totp) is considered as the totp authenticator being enabled here. 

Through myaccount is the only way a user can generate and download backup codes. So the user should be allowed to generate backup codes if that user has a chance of encountering smsOtp. 

This can be solved by adding a validation to confirm if the user has a mobile number added and if mobile number is available, we can enable backup code generation. But since mobile number is not a claim that is required by default, it can be removed which will result in the removal of an authenticator (if we treat mobile number here as an authenticator). Hence an approach need to be finalised on how to enable backup code for smsOtp.

**Comment by JeethJJ** [comment]
Feedback from @malithie :


We should not disable backup codes by authenticator at this point. There’s number of scenarios which are not of our control to decide that given we haven’t provided proper governance.
That means this should be always enabled in my account.
