### ISSUE TITLE
Double submission issue in TOTP

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#17530]
**Describe the issue:**
The double submission is not handled correctly in the TOTP submission button. After entering the TOTP value, and then submitting the form multiple times leads to authentication errors.

The cause of the issue is jquery is imported in the includes/footer.jsp file and in totp.jsp file the double submission preventing logic is implemented before including the footer.jsp file. Hence it gives following javascript error.

 _Uncaught ReferenceError: $ is not defined
    at :9443/totpauthenticationendpoint/totp.jsp?sessionDataKey=<>&authenticators=totp&type=totp&username=Bob%40carbon.super:171:17_

**How to reproduce:**
Set up TOTP authenticator as a MFA step. Then submit TOTP value by hitting submit button multiple times.

**Expected behavior:**
User should not observe authentication error and double submission needs to be correctly handled

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by jdchathuranga** [comment]
This can still be reproducible for both SMS OTP and TOTP. There was a previous issue which effects only for the iOS, but the current bug affected both iOS and Android platforms.

**Comment by jdchathuranga** [comment]
Hi @RushanNanayakkara 

This is easy to re-produce on the browser on iOS.

1. Open Safari on iOS or iOS Simulator (Tested on iOS 17 Simulator)
2. Go to Gmail
3. Provide WSO2 email
4. Then it will redirect to accounts.wso2.com, IS login page
5. Provide Credentials (If you are using saved credentials on iOS, there is another bug where it submits the form before checking the "Iam not a robot", that should also be addressed seperately)
6. Select TOTP for the 2FA
7. Type **Correct** TOTP Code and double/triple tap on the **Authenticate** button.



https://github.com/wso2/product-is/assets/3407831/89c2a5f8-22e3-4131-9623-a5f874ff3ccd

**Comment by RushanNanayakkara** [comment]
Hi @jdchathuranga , 

As I've mentioned in the previous comment we've sent the PRs for the TOTP issue since it was present in the pack. This was reproducible for TOTP flow due to an import issue. The jquery library is loaded[1][2] after the function in which it is used[3]. Therefore, the `Uncaught ReferenceError: $ is not defined` error is occurred. 
However, this was not reproducible for the SMS OTP flow. Upon inspection of the SMS OTP codebase[4], the imports seem to be in order and there seem to be no reason for this issue to occur. 

Since the SMS OTP issue needs further investigation and does not seem to be related to the TOTP issue, shall we track this through a different issue? 

[1] https://github.com/wso2/identity-apps/blob/c7ff1ea0021631cdfbf873f28bce3d8431e5d02b/apps/totp-authentication-portal/src/main/webapp/totp.jsp#L182
[2] https://github.com/wso2/identity-apps/blob/c7ff1ea0021631cdfbf873f28bce3d8431e5d02b/apps/totp-authentication-portal/src/main/webapp/includes/footer.jsp#L19
[3] https://github.com/wso2/identity-apps/blob/c7ff1ea0021631cdfbf873f28bce3d8431e5d02b/apps/totp-authentication-portal/src/main/webapp/totp.jsp#L80
[4] https://github.com/wso2/identity-apps/blob/20f048b19ffefa36f87de2a2717d1e161ad7daaa/apps/sms-otp-authentication-portal/src/main/webapp/smsotp.jsp

**Comment by jdchathuranga** [comment]
Yes, 

Also we need to track following issue as well, that is also impacting login flow on mobile devices.

If you are using saved credentials on iOS, there is a bug where it submits the form before checking the captcha, that should. so the login attempt fails.
This is implemented correctly on the Asgardeo provided login page, we can use saved password and then it prompts to fill the captacha.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
