### ISSUE TITLE
Do not issue non existing scopes for the the tokens although they are requested in the authorize call.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17551]
Shall we keep the same behaviour of the in IS not to issue non-existing scopes to the user? For backward compatibility keep a configuration to fall back to the behaviour of prior releases. 

Along with that remove asking for consent for the non-existing scopes in the consent page.

**Comment by madurangasiriwardena** [comment]
Can you elaborate the requirement more?

**Comment by ayshsandu** [comment]
> Can you elaborate the requirement more?

Steps to reproduce

1. register and configure the SPA app to provide authentication to the application
2. request some random scopes in the authorize request
3. upon providing the correct credentials user is asked to provide consent for the scopes requested in Step 2
    
![image](https://github.com/wso2/product-is/assets/5061791/2ccf0479-fed4-4a4f-99b6-4c45e9b0b24b)

5. Then register API resources and scopes with the name requested in the step 2
6.  Issue1
       - No longer users are presented with consent for the said scopes. This was confusing
    Issue 2
       - Tokens in step 3 have the scopes protected at step 5, even if the user doesn't have the permission

Note: Since we are encouraging to use the scopes with the API resources and roles, let's not issue scopes which are not known to the system. Can keep the behaviour to be enabled upon classic mode.

**Comment by janakamarasena** [comment]
One of the main blockers that we would need to sort out is using random scope to obtain unique token. This is specially a issue for self contained(jwt) tokens as the old token is revoked for new request. So if a user wants log into the same app from multiple devices(or browsers) then one of the current options is using a random scope

**Comment by chamathns** [comment]
there is an ux issue with having random scopes getting populated in the consent screen. but if we don't allow random scopes, we have to figure out a way to fix [1]

We can remove the random scopes getting populated in the UI. since these are random scopes without any permissions attached to them, there is no need to have them on the consent screen IMO. 

Since the fix for the concern raised at [1] is complex to fix, and since there are no security pitfalls with having such random swcopes, we decided to reduce the criticality. 

[1] https://github.com/wso2/product-is/issues/17551#issuecomment-1809517656
