### ISSUE TITLE
Why asking consent for Me endpoint (internal_login scope) in a weird manner 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17555]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/553228ff-cd13-48e5-b7fb-b5be948c17be)

**How to reproduce:**

1. subscribe to Me APIs from an application 
2. create a new API resource and subscribe to the same application
3. Create an application role with permissions for both above APIs
4. Assign it to a user
5. Login to the application that request the above scopes 
     - user with role in step 3 don't see the consent for internal login
     - user without role in step 3 see the consent for internal login

**Expected behavior:**
Consent is not explicitly required for the internal_login role.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sahandilshan** [comment]
```
Expected behavior:
Consent is not explicitly required for the internal_login role.
```

We cannot remove asking consent for internal_login scope since it allows us to do some critical changes to the user profile such as password reset and Add/Remove 2FA options. Hence it would be better if we rename the display name of the scope to give a better meaning. I have attached an screenshot with a possible suitable name for this

Instead of 
<img width="492" alt="Screenshot 2023-11-17 at 6 03 19 PM" src="https://github.com/wso2/product-is/assets/32576163/5074f94b-8b3c-4bd3-a0dc-984257257103">

**Comment by ayshsandu** [comment]
Still, the consent doesn't give a clear idea of the purpose. 

Ideally, critical actions like password update should happen over additional permission levels. 

At least for now rename the consent to something like 

```
 - XXXX 
          - View and make updates to your profile
```

**Comment by sahandilshan** [comment]
This will be properly fixed when we provide the improvement suggested with https://github.com/wso2/product-is/issues/17904

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
