### ISSUE TITLE
When user tries to sign in with email OTP as the first factor , the flow works when we enter the Username only

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17578]
**Describe the issue:**

When user tries to sign in with email OTP as the first factor , the flow works (email OTP is sent to the usern email)when we enter the Username only.
As in the UI eventhough it asks for the email adresss of the user , the flow works only when we enter the UI only.
<img width="1441" alt="Screenshot 2023-11-06 at 09 30 46" src="https://github.com/wso2/product-is/assets/40081059/90b231ec-8fa4-47b2-9c2d-9c3db3161954">

**How to reproduce:**

1. Login to the console
2. Create an application
3. Go to sign in methods of the created application and assign email OTP as the first factor.
4. Try to login into the created application
5. Enter the username and click on continue

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
According to the discussions had with @brionmario and @amanda-ariyaratne , the label value should be the username / the attribute name configured for the username in multi attribute login. Currently this label value is hardcoded as "Email" in identifierauth.jsp because it has been missed to update the logic accordingly when porting Asgardeo apps to IS.
