### ISSUE TITLE
Incorrect wording in Group's Roles tab empty placeholder

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#17636]
**Describe the issue:**

Incorrect wording for group's perspective --> "No groups assigned to the role."

![Screenshot 2023-11-07 at 3 56 27 PM](https://github.com/wso2/product-is/assets/37938529/e0eb5ee1-1bc1-43cc-9bb5-e129572aab6f)

**How to reproduce:**
1. Login to the console.
2. Visit Groups > Create a Group (Do not assign roles).
3. Visit the Roles tab inside the Group edit view.
4. Observe the empty placeholder content.

**Expected behavior:**
- "No roles assigned to the groups." --> as viewing from the group's perspective.
- The description also needs to be fixed accordingly.

**Comment by Achintha444** [comment]
* Fixed in the latest identity server, hence closing the issue.

<img width="1800" alt="Screenshot 2023-11-14 at 13 42 00" src="https://github.com/wso2/identity-apps/assets/46097917/7e94e450-7663-4869-bc94-ebf76f1e7f03">
<img width="1800" alt="Screenshot 2023-11-14 at 13 42 14" src="https://github.com/wso2/identity-apps/assets/46097917/d9ac9ce4-53a5-4428-b45b-5e97e70f015f">
