### ISSUE TITLE
B2B sub organization IDPs should use root organization's key pairs for operations. 

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#17667]
**Describe the issue:**
Assume there's a b2b sub org connecting to their enterprise IDP using SAML. If the SAML Request signing is enabled, signing should be done using root orgs private key. 

If the IDP is sending assertions encrypted, b2b IDP should try to decrypt the encrypted assertion using root organizations private key. 

Our behaviour is, other way around. It tries to decrypt using sub orgs keys.

**Comment by hasinthaindrajee** [comment]
I assume the same issue will be there in JWT flows as well.

**Comment by indeewari** [comment]
@hasinthaindrajee, If we take a use case where root organization has several sub organizations connected, which are separate legal entities, can we share the same private key of the root org among sub organizations ? I see a security conflict there.. WDYT ?

**Comment by sadilchamishka** [comment]
Let's think of this scenario. The John who is an admin of Medverse wanted to onboard their enterprise SAML IDP. He required to provide the public certificate of the IS to that SAML IDP.

If he invoke the `https://localhost:9443/t/7f82291b-f80a-446c-bcbe-ce439d0004fd/identity/metadata/saml2` endpoint he would return a certificate related to Medverse. What if improve this by returning the EasyMeet public cert instead of Medverse's public cert.  The the fix sent by the https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/166 will fix the issue.

<img width="642" alt="Screenshot 2023-11-13 at 20 38 20" src="https://github.com/wso2/product-is/assets/35717390/e47d0bed-3029-4b7b-8f1c-4c71a4a7b302">

Assumptions
- Medverse can't keep there own certificates.
- The `identity/metadata/saml2` endpoint should be organization qualified request and it will return its root tenant's certificate.

**Comment by hasinthaindrajee** [comment]
Is this fixed for JWT's as well ?

**Comment by sadilchamishka** [comment]
> Is this fixed for JWT's as well ?

Yes, it was already. though we are federated from an organization, the root app always exist in the tenant and tokens signed by that tenant. The API-gateways trust the tenant, hence there should be no issue.

When accessing organization resources
Let say zoom has b2b customer call wso2
1. In IS perspective when accessing wso2 resources->. `/t/zoom/o/...`
2. In business perspective ->  `zoom.us.apigee.net/create-recording`      -> The gateway trust the zoom tenant. The token issued for wso2 org is signed by zoom tenant.
