### ISSUE TITLE
Unwanted PATCH request is sending when updating OIDC protocols in the CONSOLE app

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17694]
**Describe the issue:**
Unwanted PATCH request is sending to the application endpoint when we update the oidc information of an application.

**How to reproduce:**
1. Create OIDC app in the console (SPA, OIDC tradtional web app, OIDC Standard based application)
2. Once app got created, navigate to the `protocol` tab
3. Click `Update`

Once you click update, you will be able to see the following two requests,
<img width="666" alt="Screenshot 2023-11-09 at 11 38 26 AM" src="https://github.com/wso2/product-is/assets/32576163/66c1edcc-1da2-4d5e-b2e2-1f007b526251">

The first request is an unwanted request that is sent from the CONSOLE app. 
Sample request
```
curl 'https://localhost:9443/api/server/v1/applications/e444584e-f19b-4d60-b9c1-b13b2da73969' -X PATCH -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Access-Control-Allow-Origin: https://localhost:9443' -H 'Authorization: Bearer ade5f4e4-2759-376d-8388-45c90c2b1939' -H 'Origin: https://localhost:9443' -H 'Connection: keep-alive' -H 'Cookie: atbv=3deb71e4-a91d-42ed-b08b-b656a63380ba; JSESSIONID=65366E3D9B6885C38DCFF5BCD81BCA08; commonAuthId=308f9dd5-a801-4a09-a843-e18803ee89bf; opbs=279f3889-39ce-4238-b3bb-eb60de2f3d7a' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw '{}'
```
Due to this issue, unwanted AUDIT logs get published.

**Expected behavior:**
We don't need to send an PATCH request to the application endpoint when updating the protocol details. We just need to PUT request that is being send to the the OIDC endpoint

**Comment by DilshanSenarath** [comment]
Currently, when updating the protocol section, two endpoints are being called: 
- The application endpoint with certificate details
- The inbound protocol endpoint with protocol details. 
Clicking the 'update' button triggers both of these requests since they are relevant to the same form and share a single update button.

Another issue (https://github.com/wso2/product-is/issues/17713) has been identified to introduce the update of protocol details from the application endpoint. Once this capability is implemented, a single request to the application endpoint from the frontend can be sent. This modification will prevent the generation of two separate Audit logs. Therefore, this issue will be closed.

**Comment by DilshanSenarath** [comment]
Currently, when updating the protocol section, two endpoints are being called: 
- The application endpoint with certificate details
- The inbound protocol endpoint with protocol details. 

Clicking the `update` button triggers both of these requests since they are relevant to the same form and share a single update button.

Another issue (https://github.com/wso2/product-is/issues/17713) has been identified to introduce the update of protocol details from the application endpoint. Once this capability is implemented, a single request to the application endpoint from the frontend can be sent. This modification will prevent the generation of two separate Audit logs. Therefore, this issue will be closed.
