### ISSUE TITLE
[SMS OTP Provider] "Something went wrong" error is displayed when user tries to add a configuration of different type

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17814]
**Describe the issue:**
We provide 3 types of SMS OTP Configurations: Twilio, Vonage and Custom. If one type of SMS OTP is already configured, a new type of configuration is not allowed to be created - which is valid. But, the display of "Something Went wrong" error at this step SHOULD BE Corrected. 

**How to reproduce:**
Prerequisite: An existing SMS OTP type should be already configured. (E.g. Vonage)

1. Navigate to Branding > Channels
2. Click on "SMS OTP Provider"
3. Add a custom or different type of SMS OTP
4. Click "Update"

**Expected behavior:**
Ideally user should be able to overwrite an SMS OTP Provider

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
There are couple of issues with updating the sms providers.

1. When an sms provider is created and attempted to update immediately after creating, the page sends a POST request instead of a PUT request.

2. When the SMS provider configs are reverted and the user attempts to create a SMS provider, app sends a PUT request instead of a POST request.

Both issues happen due to the state variable `existingSMSProviders` not being synced properly. These will be fixed with https://github.com/wso2/identity-apps/pull/4752

**Comment by pavinduLakshan** [comment]
Verified in the beta build.

https://github.com/wso2/product-is/assets/41533942/337e84eb-d1fb-4795-81b0-ed1d7df71e5b
