### ISSUE TITLE
[API based authentication] There should be a way to continue when the authentication context is expired

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17872]
**Describe the issue:**
When using API based authentication, if a user stays idle in the middle of the authentication flow and continue after some time, the API response payload doesn't give enough information to proceed from there. 

Response doesn't have details for AUTHENTICATOR_PROMPT:
```
{
    "flowId": "d3fc725b-58af-4c77-8b3e-bcde1a8a71b8",
    "flowStatus": "INCOMPLETE",
    "flowType": "AUTHENTICATION",
    "nextStep": {
        "stepType": "AUTHENTICATOR_PROMPT"
    },
    "links": [
        {
            "name": "authentication",
            "href": "https://localhost:9443/t/carbon.super/oauth2/authn",
            "method": "POST"
        }
    ]
}
```

In the server side, the authentication context is expired.

Console error:
```
[2023-11-17 13:22:49,759] [c4e80117-fa09-4088-afb9-9a59526b55c1] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Redirecting to retry page as the authentication context has expired.
```

**How to reproduce:**
1 - Configure username/password and totp authentication flow
2 - Start tying API based authentication flow,
3 - After initiating the authentication flow, wait for some time to submit username/password (until the context get expired)

**Expected behavior:**
Server should initiate a new authentication flow, or give a error response with instructions to start a new authentication flow

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
Fixed with 
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2298
https://github.com/wso2/carbon-identity-framework/pull/5288

The current framework does not support reinitiating the auth context internally. With the above fixes, an error response will be sent as below. The client can reinitiate the auth flow if the specific error is received. This is somewhat similar to how we are handling the same case in the redirect flow. In the redirect flow before the login details are submitted we do a call to the /logincontext api to check if the context is still active. If the context isn't active and a application access url is set we redirect the user to the access url.

```json
{
    "code": "ABA-60008",
    "message": "Authentication flow time out.",
    "description": "Authentication flow has timed out as it took too long to complete.",
    "traceId": "171d97a7-d49d-4345-828c-28adbab694f9"
}
```
