### ISSUE TITLE
Enabling self service will remove account lock option

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18030]
**Describe the issue:**
When user enable self registration option, account lock option get removed from console user section. Also once disable the self registration option will not revert this. Hence need to check this on new pack.  

https://github.com/wso2/product-is/assets/39077751/ac72e4e7-f263-45a7-a972-9961fa7238e4

**How to reproduce:**
1. Login to console
2. Create user
3. Check wether account lock option is available
4. Navigate to login & registration
5. Select self registration
6. Enable self registration  (This should not be enable before)
7. Check user lock option is avaible.

**Expected behavior:**
User lock option should be there even though the self registration get enable. Disable self registration will not display back the account lock option. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0-beta
 - OS: [e.g., Windows, Linux, Mac]
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest build. 

https://github.com/wso2/product-is/assets/41533942/2aaa4b33-ee2e-48f8-89f7-f7d5d9adaf9b

**Comment by ZiyamSanthosh** [comment]
**Analysis**

This is reproducible in the latests build.
According to [1], the account lock option will be shown when value of `SelfRegistration.LockOnCreation` is set to true. When `Activate account immediately` option is checked[2] under self registration, this particular property is set to false. Hence, the account lock option is not visible under the edit user UI. Then if the self registration option is disabled[3], the false value remains the same because, only the value of `SelfRegistration.Enable` will be changed. Ideally, when self registration is disabled, all properties relevant to the self registration should be brought back to default values.

[1] https://github.com/wso2/identity-apps/blob/a6e7fd7ae7be4ae70393e3e30f820384511cb7bf/apps/console/src/features/users/components/user-profile.tsx#L1156
[2]
<img width="308" alt="Screenshot 2024-01-17 at 10 52 28" src="https://github.com/wso2/product-is/assets/50801227/84eb183d-246b-4305-b0f5-e99fad1134aa">
[3]
<img width="308" alt="Screenshot 2024-01-17 at 10 52 54" src="https://github.com/wso2/product-is/assets/50801227/16cfc3d1-bdc2-45ba-a7d0-ff84267e7de5">

**Comment by ZiyamSanthosh** [comment]
https://github.com/wso2/product-is/assets/50801227/5fce2c54-c7e0-456c-9aa9-40bc68147778
