### ISSUE TITLE
Logout wreply url is missing from console ui when creating a passiveSTS application.

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#18076]
**Describe the issue:**
From the PR https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/144, WReply Logout URL was added to passiveSTS and it is considered as a mandatory field in the edit window. 

<img width="1253" alt="Screenshot 2023-11-24 at 13 45 31" src="https://github.com/wso2/product-is/assets/46132469/b0e47330-8515-4226-86fd-a8bb3800c854">

But when creating a new passiveSTS application, that field is not asked from the user.
<img width="1253" alt="Screenshot 2023-11-24 at 14 06 33" src="https://github.com/wso2/product-is/assets/46132469/4b3c9b83-e431-4149-8a4e-694696d4686e">

**Environment information**
 - Product Version: 7.0.0-beta
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by Lakshan-Banneheke** [comment]
The WReply Logout URL validation was added to the backend and was marked as mandatory in the edit window with https://github.com/wso2/identity-apps/pull/4518 to enforce users to configure the wreply logut url.

Setting configurations for passive sts application in the create window was not available when this change was done. Since  we seem to be now allowing users to set the configuration in the create window, the WReply Logout URL should be added here as well and marked as mandatory.

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/1b855326-7a53-430c-ba12-bf4537ebf706
