### ISSUE TITLE
Redeploying error is printed when configuring SMS provider

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18159]
**Describe the issue:**
1. Login to super tenant/ any other tenant via console
2. Go to email & SMS configurations
3. Configure an SMS provider
4. Check the carbon log. The following warn log get printed
```
[2023-11-29 10:06:18,152] [aaf21d7a-9601-4ab2-bfa0-cdb9685821e2]  WARN {org.wso2.carbon.identity.notification.sender.tenant.config.handlers.DefaultChannelConfigurationHandler} - Error while re-deploying resource.Error occurred when deploying the event publisher configuration for with name: SMSPublisher.
```

https://github.com/wso2/product-is/assets/25483865/c9361ebf-35c5-45db-9495-f4c8b3307c96

**Comment by aaujayasena** [comment]
@AnjanaSamindraPerera Shall we update the status

**Comment by AnjanaSamindraPerera** [comment]
According to analysis, this warning is thrown due to the [URL](https://github.com/wso2/carbon-analytics-common/blob/57e7496d4c82eec9de15bd00034200763e330fd3/components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapterFactory.java#L86) considered to be required from event-publisher. Since we are using Twillo or similar SDK we are not attaching any URLs. Hence reducing the criticality of the issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
