### ISSUE TITLE
Federated email OTP type config is missing in CONSOLE app view

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#18198]
**Describe the issue:**
The email OTP type (use numeric OTP values) config is missing from the CONSOLE UI. This config is visible in SMS OTP config.

https://github.com/wso2/product-is/assets/47152272/248a089a-f428-4de5-aea3-a5729721ea23

**How to reproduce:**
1. Configure a email OTP as a federated IDP. 
2. Login to CONSOLE and view the email OTP connection as displayed in the screen recording.

**Expected behavior:**
Use numeric OTP or not field should be visible.

**Comment by savindi7** [comment]
We are getting the initial data from the endpoint, `/identity-providers/{identity-provider-id}/federated-authenticators/{federated-authenticator-id}`. 

<img width="515" alt="Screenshot 2024-01-03 at 19 57 44" src="https://github.com/wso2/product-is/assets/67315176/e93788b6-aeaf-4866-ab62-e027e0516292">

The property with key `OnlyNumericCharactersForOtp` is not being recieved from this response (as shown in the above screenshot) although we get in from the metadata endpoint. We set the form fields based on this response.

**Comment by mpmadhavig** [comment]
> We are getting the initial data from the endpoint, `/identity-providers/{identity-provider-id}/federated-authenticators/{federated-authenticator-id}`.
> <img alt="Screenshot 2024-01-03 at 19 57 44" width="515" src="https://private-user-images.githubusercontent.com/67315176/293938588-e93788b6-aeaf-4866-ab62-e027e0516292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDc2ODAsIm5iZiI6MTcwNDM0NzM4MCwicGF0aCI6Ii82NzMxNTE3Ni8yOTM5Mzg1ODgtZTkzNzg4YjYtYWVhZi00ODY2LWFiNjItZTAyN2UwNTE2MjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA1NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Yjc2YThjNTk5NTVhMzcwOTg0MjIxN2M5NzE3OWE2Zjg2ZTJkZmEwN2QyYWI5NjUyMzcyOGZkMGQyZjE5MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LQ-0E6wAuw3zESQEIJM-8tVqgoMWQd1goe0_BI6oAZA">
> 
> The property with key `OnlyNumericCharactersForOtp` is not being recieved from this response (as shown in the above screenshot) although we get in from the metadata endpoint. We set the form fields based on this response.

Please check the request when saving the input from the management console. There if you uncheck the field, the input value is not getting added to the formData. Hence it will not be getting stored under the relevant connector which has lead to this API call result.

**Comment by savindi7** [comment]
Why is it necessary to do this for this field in particular? when we get the other properties without them being checked in the Management console? @mpmadhavig

**Comment by Thumimku** [comment]
Hi Devs,

There were several discussions back and forth hence I summarise the issue.

## How to reproduce the issue now.
Now we changed the UI of the authenitcators section of the custom connectors, where you can't find smsotp nor email otp.
<img width="938" alt="1" src="https://github.com/wso2/product-is/assets/25488962/e24553e3-c19c-46d6-bcd5-6b2916f8879a">
To do this you have to go to carbon console and enable the authentictors, then you can reproduce the issue

## Root cause
as @mpmadhavig  said, not having `OnlyNumericCharactersForOtp` property in the `/identity-providers/{identity-provider-id}/federated-authenticators/{federated-authenticator-id}` casued the issue and the reason for not having is since we update the values from carbon console to reproduce the issue. Form sent to update didn't has the boolean value (current behaviour of form in carbon console).

## Why SMS-OTP is working as expected

As noted by https://github.com/wso2/product-is/issues/18198#issuecomment-1837414370 comment, SMS-OTP also has this property but its working as expected. The reason is OnlyNumericCharactersForOtp` property type is [string](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1564C29-L1564C35) in smsotp. Even though if there is no value provided, empty string will store as value Hence when calling the authenticators config for the connectors, the property will be there.

## Impact

### New Users

But this issue not going to happen in future when we configure the email otp authenticator in react console, cause when we showing the form all details will be there and when submitting it regardless of the boolean value update/create request of the email otp authenticator will contain `OnlyNumericCharactersForOtp` property. Hence this won't happen for new users.

### Migrated Users

Even though we developed this [feature](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/156) in last year, we already sent some patch versions of this feature for old IS versions (Refer Mentioned PRs in the Public PR).
Hence this issue may happen for migrated users.

### How to fix for migrated user

1. We should render the properties coming from `identity-providers/meta/federated-authenticators/{federated-authenticator-id}` \
2. We should fill the values of the properties based on`/identity-providers/{identity-provider-id}/federated-authenticators/{federated-authenticator-id}` 
3. We should fill the properties which was left in step 2 by its default values.

Since this issue not going to happen in future when we configure the email otp authenticator in react console, we can reduce the issue priority.

**Comment by dasuni-30** [comment]
### Analysis

Currently, we don't have the capability to add `Email OTP` authenticator template for the custom connector through the console. Only following templates are available in the console for custom connectors.
<img width="720" alt="Screenshot 2024-01-17 at 14 59 11" src="https://github.com/wso2/product-is/assets/27746285/6a00c644-98e2-4afd-8a77-5c53b340c269">

We can only add the email otp authenticator by updating the custom connector through the management console. related issue: https://github.com/wso2/product-is/issues/18934

**Comment by mpmadhavig** [comment]
This particular issue doesn't involve with creating a Federated email OTP authenticator from the new CONSOLE application. What we need to focus on is of a user who has migrated from an earlier version who has already configured an email OTP authenticator using federated authenticators. As we have mentioned about the alphanumeric OTP feature for email OTP, the user might want to configure this from the console. As we have introduced this new CONSOLE, user might wantto change the config from the new CONSOLE. In that case we are supposed to show this config irrespective of whether the user can configure the email OTP from the new console or not.

**Comment by mpmadhavig** [comment]
This issue will be fixed temporarily with this PR, https://github.com/wso2/carbon-identity-framework/pull/5290.
