### ISSUE TITLE
Default IS logo doesn't included in emails eventhough it is shown in preview

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18194]
**Describe the issue:**

- Keep default branding
- Check the email preview under the Branding section
- You can see the identity server logo on top of the title 
<img width="1360" alt="Screenshot 2023-11-30 at 09 11 41" src="https://github.com/wso2/product-is/assets/25483865/2b72444f-c2a3-424c-a07f-8f75d6e7667e">

- Try a flow that sends the email, the received email doesn't have the logo
<img width="698" alt="Screenshot 2023-11-30 at 09 10 25" src="https://github.com/wso2/product-is/assets/25483865/bf68e3e9-c386-47a8-8ad7-f9058343adf8">

- Through branding configure a custom logo and try the email receiving flow. Then you can see the logo
<img width="678" alt="Screenshot 2023-11-30 at 09 10 32" src="https://github.com/wso2/product-is/assets/25483865/942299fd-c7f2-4705-bd9b-8fc92034ebc9">

**Comment by NipuniBhagya** [comment]
@pavinduLakshan isn't this fixed now?

**Comment by pavinduLakshan** [comment]
As per the offline discussion, it was decided to keep the emails without a default logo and therefore remove the fallback logo URLs from the email templates UI in console.

**Comment by pavinduLakshan** [comment]
Removing the fallback logo URL in the frontend results in displaying a broken image icon in the preview, since src="" is an invalid image URL.

To address this, we can add an `onerror` attribute to the email template's img tags with the value `this.style.display='none’`. This hides the broken image icon in the preview when branding is not configured, while not affecting actual sent emails as far as I understood.
