### ISSUE TITLE
SMS OTP is not available in organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18247]
**Describe the issue:**
- Log in to carbon.super
- Go to organizations and create an organization
- Switch to the created org space from console
- Go to connections section
- Try to configure the SMS OTP connection. It is not available

<img width="1704" alt="Screenshot 2023-11-30 at 19 26 50" src="https://github.com/wso2/product-is/assets/25483865/a23d0047-2270-40d3-b0a2-8d8925935603">

- Create an application in root org and share it with the organization. Under the shared application's signin method configurations SMS OTP is not available 
<img width="1704" alt="Screenshot 2023-11-30 at 19 29 16" src="https://github.com/wso2/product-is/assets/25483865/5b5c4ef2-fba5-4183-bf63-aed907729909">

**Comment by PasinduYeshan** [comment]
As agreed upon in our discussion, if a sub-organization lacks specific SMS configurations, these settings will be automatically inherited from the root organization for the purpose of sending notifications. However, it's important to note that the `api/server/v1/notification-senders/sms` APIs will only retrieve and display SMS configurations that are explicitly set for the current organization. It will not include any configurations that are inherited from the parent organization.

**Comment by PasinduYeshan** [comment]
This issue if fixed by following PRs.
- https://github.com/wso2/carbon-identity-framework/pull/5283
- https://github.com/wso2/product-is/pull/18507
- https://github.com/wso2/carbon-identity-framework/pull/5312
- https://github.com/wso2/identity-api-server/pull/560
- https://github.com/wso2/identity-apps/pull/4912
- https://github.com/wso2-extensions/identity-event-handler-notification/pull/213
- https://github.com/wso2-enterprise/asgardeo-apps/pull/977
