### ISSUE TITLE
Invite offline option is not available

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18248]
**Describe the issue:**
Invite offline option is not available
<img width="573" alt="Screenshot 2023-11-30 at 19 30 44" src="https://github.com/wso2/product-is/assets/39077751/d281643d-22aa-4c32-a961-491580987967">

**How to reproduce:**

**Expected behavior:**
![image](https://github.com/wso2/product-is/assets/39077751/a4362159-f29b-4b5c-87b7-7d5af68d5050)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
- The highlighted option remains disabled unless the "Invite user to set password" connector is enabled in the login and registration page, and user has entered a valid email address in the add user wizard form. 

- It is not possible to show the `Invite Offline` in onprem console because the relevant APIs are only supported for the cloud offering.

**Comment by aaujayasena** [comment]
- The highlighted option remains disabled unless the "Invite user to set password" connector is enabled in the login and registration page, and user has entered a valid email address in the add user wizard form. -> this requirement is not clearly mention in the UI. Since user name can enter nonemail username as well, better to add the help note for enhance the user experience.

**Comment by aaujayasena** [comment]
@pavinduLakshan as per the discussion are we good to move this to backlog?

**Comment by JeethJJ** [comment]
@aaujayasena I will be working on the invite-link endpoint. Hence we don't need to move this to backlog.

**Comment by JeethJJ** [comment]
The backend support for the API is provided with the above PRs. This implements the `/api/users/v1/offline-invite-link` endpoint for the successful flow. This API should be called to generate the offline invite link for a user right after the user creation, if Invite-Offline option is selected.  

Since this depends on user creation flow, no error handling has been done yet.  So, if this is required to be used standalone, error handling has to be done along with.
