### ISSUE TITLE
[JIT Provisioning][Account Linking] the account gets linked only when provisioned silently

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18365]
**Describe the issue:**
User can only link a social account only when provisioned silently. With other provisioning scheme (even with "provisioning consent"), user cannot link his social to the default account. 

**How to reproduce:**
1. Login to IS Console
2. Create a google connection with a provisioning scheme that is NOT "provision silently"
3. Connect the google connection to console
4. Create a default user in console whose username is similar to google username
5. Logout and login to console with google 
6. Verify whether user can link his account

**Expected behavior:**
There should be some clarity and documentation as to how account link performs with the provisioning. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment]
The expected behavior is not to automatically account linking at JIT provisioning flow as mentioned in above. The account linking must be perform by login to the myaccount.

With the fix: https://github.com/wso2/carbon-identity-framework/pull/5301, we will prevent automatic account linking at the silent JIT provisioning as well.
