### ISSUE TITLE
[Doc] Update IS 5.4.0  version  as supported versions in Email OTP Authenticator 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1836]
IS 5.4.0 supported **Email OTP** Authenticator. Update in doc [1] as below
`The WSO2 Identity Server 5.1.0, 5.2.0,  5.3.0 and 5.4.0 product versions support EmailOTP.`

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Multi-factor+Authentication+using+EmailOTP

**Comment by shavidissa** [comment]
Added the following line to docs because the store mentioned what versions of IS the connector works on. Maintaining it in docs will be an overhead going forward.

"For more information on the WSO2 Identity Versions supported by the connector, see the IS Connector store."
Kanapriya mentioned that the store will be updated with 5.4 too.
[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Multi-factor+Authentication+using+EmailOTP
