### ISSUE TITLE
[Custom Connector] Make default/Enabled 2 unnecessary options for authenticators in a custom connector

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18378]
**Describe the issue:**
There are 2 options, enabled and make default options for authenticators. But only one authenticator can be enabled at a time. Hence, both make default and enabled options are redundant, one is enough. 

<img width="1512" alt="Screenshot 2023-12-03 at 16 07 35" src="https://github.com/wso2/product-is/assets/106053688/e6be74db-01ff-4c5f-801d-4902825f4e1e">

**How to reproduce:**
1. Login to IS Console
2. Configure the custom authenticator
3. Add 2 authenticators. 
4. Verify the "make default", "enabled" options

**Expected behavior:**
One of that option is required in this aspect. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
We discussed about allowing only **one** federated authenticator to the custom connector with https://github.com/wso2/product-is/issues/18651. Hence we removed the `Make default` and `Enabled` options since it is not required when there's only one federated authenticator. (This behavior is only applicable when we add a new custom connector. If the user has already added a couple of authenticators, the user will have the enabled/default options)

**Comment by dasuni-30** [comment]
Verified in the pack

- default/Enabled options are removed when there's only one federated authenticator.

<img width="1440" alt="Screenshot 2024-01-16 at 10 19 09" src="https://github.com/wso2/product-is/assets/27746285/bde65eae-26d7-4f7c-990f-9f15906956d7">
