### ISSUE TITLE
User attribute change verification email not received. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18414]
**Describe the issue:**
User attribute change verification email not received. 

<img width="951" alt="Screenshot 2023-12-04 at 18 20 47" src="https://github.com/wso2/product-is/assets/39077751/732eeb20-4a2d-41c7-be49-c1f6235c8218">

**How to reproduce:**
1. Login to console
2. Navigate to User Attribute & Store
3. Select User attribute change verification
4. Click to enable ussr email verification update 
5. Create user
6. Update created user email

**Expected behavior:**
email should be received to the previous email

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Rashmini** [comment]
Analysis of the issue:

- From the UI, configs get updated properly.
- According to [1][2], sending the verification email is controlled by sending the `verifyEmail` temporary claim along with the update request. This option is enabled from identity.xml by setting `UseVerifyClaim` to true. If `UseVerifyClaim` is disabled, `verifyEmail` claim is not checked.
- Since `UseVerifyClaim` is set to true by default, the email confirmation is not getting sent. However, this is working in My Account. This needs to be analyzed and fixed from the backend if needed.

Furthermore, following behaviours were observed, which needs to be fixed.

- When `Enable user email notification on update` config is enabled and `Enable user email verification on update` config is disabled, `{{verification-pending-email}}` is not getting resolved in the email template.
- When both `Enable user email verification on update`  and `Enable user email notification on update` configs are enabled, both emails are not received when the email is changed from the console. However, both emails receive when the email is changed from the My Account.

![image](https://github.com/wso2/product-is/assets/36252940/8b73ff2d-d15b-4c87-bb21-e28026fa0b70)


[1] https://github.com/wso2-extensions/identity-governance/blob/9cff578c45572227f98ae1b9c8d5c0e0ed8df5fa/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/util/Utils.java#L1304
[2] https://github.com/wso2-extensions/identity-governance/blob/8c8c3d4954d2bf5ff6b1c7f34aa3d320cb02ca74/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java#L516

**Comment by madurangasiriwardena** [comment]
I believe asking to send the `verifyEmail` attribute in the request is fundamentally wrong and defeats the purpose of this feature.

When digging deep in to the feature, I could find that it has been decided to not to use such a `verifyEmail` attribute to trigger the flow. However as a resolution for https://github.com/wso2/product-is/issues/10358, this `verifyEmail` attribute is later introduced. But I believe the solution introduced for https://github.com/wso2/product-is/issues/10358 should have been different and it should handle the email otp flow separately without changing the original feature.

@ashanthamara please check the technical feasibility in doing this and if possible let's fix this properly. But since the above behavior is currently available in the product, we will have to change the behavior with a configuration.

**Comment by madurangasiriwardena** [comment]
@Kanapriya can you please add the update of your analysis?

**Comment by Kanapriya** [comment]
The analysis added in the doc https://docs.google.com/document/d/1Uc4XWGuB5zfGdtyCASixmGDaw1b7W4PRF0iyrrs4GU0

**Comment by UdeshAthukorala** [comment]
Decided to change the default value of the config `UseVerifyClaim` to false and fix(https://github.com/wso2/product-is/issues/10358) by Skip triggering email/mobile verification during email OTP/SMS OTP flows using a thread local.

This will be fixed with the following PRs:
- https://github.com/wso2/carbon-identity-framework/pull/5350
- https://github.com/wso2-extensions/identity-governance/pull/795
- https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/176
- https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/184

**Comment by UdeshAthukorala** [comment]
Close since all the PRs are merged.

**Comment by UdeshAthukorala** [comment]
- Related Documentation Updates for IS 7.0 is tracked with https://github.com/wso2/product-is/issues/18892
