### ISSUE TITLE
Organization's authentication portal doesn't show the resolved branding

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18420]
**Describe the issue:**

1. Configure branding in the root organization
2. Create an organization
3. Switch to the organization and check the branding
4. You can see the resolved branding there
5. Configure an application in root tenant and share it with org
6. Try application login via SSO
7. Enter the organization name which you need to login
8. The authentication portal prompted will not have the resolved branding. It has the default branding
9. Click forget password on the organization login page. The prompted recovery portal also doesn't have the proper branding

https://github.com/wso2/product-is/assets/25483865/1650ca4d-942a-44ab-b6c7-689915edb2b9

**Comment by DilshanSenarath** [comment]
This issue was produced due to this change - https://github.com/wso2/carbon-identity-framework/blame/95d0fc703c1826a3268508268871b6d2368c5e6a/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointUtil.java#L782-L787

As a result of this change, the path `https://localhost:9443/o/fc5bf22b-71d6-4354-be2b-44fe99e533b4/api/server/v1/branding-preference/resolve` is transformed into `https://localhost:9443/t/fc5bf22b-71d6-4354-be2b-44fe99e533b4/api/server/v1/branding-preference/resolve`. The addition of `t/` to the URL leads to an error message being returned by the REST API.

```
{
    "code": "BPM-60002",
    "message": "Branding preferences are not configured.",
    "description": "Branding preferences are not configured for organization: fc5bf22b-71d6-4354-be2b-44fe99e533b4.",
    "traceId": "fe2fd349-d1a1-4896-8a9d-8ac836d442f9"
}
```
