### ISSUE TITLE
Parent organization page not  properly load when switch back from sub organization. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18431]
**Describe the issue:**
Parent organization page not  properly load when navigate from sub organization. 

https://github.com/wso2/product-is/assets/39077751/e50a7c68-4119-4f59-a785-2ffbc6160970

**How to reproduce:**
1. Login to console
2. Create organization
3. Switch to sub organization
4. Switch back to parent org to from sub org

**Expected behavior:**
Parent org oage should be load properly. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  wso2is-7.0.0-rc1-SNAPSHOT-4964-
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Looks like this is happening when `read` permission is given to the Getting Started page (https://github.com/wso2/carbon-identity-framework/pull/5258/files#diff-ccd8d78f18b752f00ba42b5384248d7b8e8c6cc965a44569e2654ca6ce5bb616R1180)

Passing an empty array seems to be fixing the issue. But we can't keep this as empty since it'll break RBAC.

```toml
console]
getting_started.scopes.read = []
```

**Possible Solutions**
- Looks like route filtering logic is interrupting the `/o/ord_id` removing logic. Need to revisit.
- A quick fix if the above doesn't work is to treat `Getting Started` page like we do for `404`. (https://github.com/wso2/identity-apps/blob/98520537bea59165863e8adcc63f854787c7b280/apps/console/src/features/core/utils/route-utils.ts#L58)
