### ISSUE TITLE
Add language switcher to Complete Sign Up page in JIT provisioning

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#18477]
**Describe the issue:**
Add language switcher to Complete Sign Up page

<img width="1440" alt="Screenshot 2023-12-07 at 09 20 52" src="https://github.com/wso2/product-is/assets/27746285/9608d4f6-9874-46e3-b800-8658e9c2d01c">

**How to reproduce:**
1. Login to IS Console
2. Create an IdP
3. Enable JIT with provisioning scheme "prompt for username, password and consent"
4. Connect the IdP to an application
5. Login to the application
6. Select sign in with IdP

**Expected behavior:**
The complete Sign Up page is expected to have the language switcher in the footer

**Comment by brionmario** [comment]
This may be a limitation in the language switcher.

For some routes, language switcher can't be used since it'll cause a redirect when the language is switched causing the flow to break.

Enabled paths list: https://github.com/wso2/identity-apps/blob/master/identity-apps-core/apps/recovery-portal/src/main/webapp/includes/product-footer.jsp#L104

**Comment by dasuni-30** [comment]
### Fixed in the new pack

<img width="610" alt="Screenshot 2023-12-14 at 16 52 47" src="https://github.com/wso2/product-is/assets/27746285/778e6f46-74d0-4396-a431-ac4804c7f539">
