### ISSUE TITLE
[Custom Connector] [SAML] : HTTP Binding is allowed to save empty

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18623]
**Describe the issue:**
When creating a SAML authenticator in the custom connector, we are allowed to save the authenticator without the HTTP Protocol binding field since it is non mandatory

**How to reproduce:**
1. Create a custom connector
2. Click on the Settings
3. Navigate to create a SAML authenticator and verify the HTTP Protocol Binding type

**Expected behavior:**
The field should be mandatory with a default selected protocol binding type

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
Default value issue in the dropdown is fixed with https://github.com/wso2/identity-apps/pull/5132 PR. However, if we need to make the `HTTP Binding` as a required field we need to update the meta data coming from the backend.

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/0367349b-1e33-43cd-8e17-334f3f56cd52">
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/e001c29c-8c23-43ef-b05c-63a5bded0e16">
<img width="1512" alt="22 - 11-17" src="https://github.com/wso2/product-is/assets/74205483/40fb83f7-b7c6-42b0-b42b-3451b3be48a1">

**Comment by Thisara-Welmilla** [comment]
As there is a default values for the HTTP binding field. Therefore no need to make it mandatory. Hence closing the issue.
