### ISSUE TITLE
[Custom Connector] (SAML) UserName Id format should be a drop down field on creation

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18625]
**Describe the issue:**
Username Id format should be a drop down in the creation page as if we type an invalid value here, it is not getting saved. 

**How to reproduce:**
1. Create a custom connector
2. Navigate to the Settings page
3. Create a SAML authenticator with NameId format having an invalid value
4. Click Save and verify the saved details

Recording: 

https://github.com/wso2/product-is/assets/106053688/c91f63f7-ff59-4de4-bf59-19f81bcc0ba8

**Expected behavior:**
The field should be a drop down

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
The reason for this is not being presented as a dropdown because we are currently not receiving any options from the backend. These forms are dynamically rendered, and the input box will be converted into a dropdown only if the options array is not empty. To achieve this, we need to pass the Name ID Formats from the backend side.
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/237968e1-f281-4592-9c5f-e9c1a1998172">
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/d9efc3a6-0837-4e28-988a-6bcf5977672e">

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/168/files
