### ISSUE TITLE
Unable to Assign JIT Provisioned (Federated Users) to an Already Created Group

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18645]
**Describe the issue:**
When attempting to assign Just-In-Time (JIT) provisioned federated users to an already created group, the system displays the users in a grid. However, after receiving a success message indicating that users have been added, the users are not listed within the group.
Note:

Despite being able to successfully add and list JIT Provisioned (Federated) users during the Group creation wizard, encountering an issue when attempting to assign them to an already created group.

**How to reproduce:**
Access the User Management section > Group.
Try to assign JIT Provisioned (Federated) users to an already created group.
Observe that although the users are displayed in the grid and a success message is received during the Group creation wizard, they are not listed in the group when added later.

**Expected behavior:**
JIT Provisioned (Federated) users should be successfully added to the group, whether during the Group creation wizard or afterward, and should be visible in the group's user list.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: wso2is-7.0.0-beta4-SNAPSHOT
OS: Mac
Database: DB2
Userstore: JDBC

---

[groupissue.webm](https://github.com/wso2/product-is/assets/39120228/ebc32d78-72c2-47a1-9484-aaf76277c55f)

**Comment by ZiyamSanthosh** [comment]
**Analysis**

It was identified that both **username** and **userPrincipal** claims are mapped to the same user attribute **uid**. When a user logs in using the FIDP for the second time after the jit provisioning, the corresponding attribute **uid** for the claim username is getting deleted. This fails the validation that happens when the user is added to an existing group. 

Even through the username claim is already declared as indelible, userPrincipal claim was mapped to the same attribute name and it deletes the uid attribute from the database since it is not being sent by the FIDP.

As a solution for this issue, the userPrincipal claim is now added as an indelible claim during jit provisioning.

**Comment by ZiyamSanthosh** [comment]
Closing this issue hence this is completed.
