### ISSUE TITLE
No Authorization Policy API Resources should not be listed as an option when assigning permissions to a role.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18689]
**Describe the issue:**
In the current console, even the no policy API resources are listed in the `Select API Resource` dropdown in the Assign permission tab.

<img width="1201" alt="Screenshot 2023-12-19 at 17 12 51" src="https://github.com/wso2/product-is/assets/41188245/1ad8cd00-af2e-4643-be7f-89e1c879dcbd">

<img width="1192" alt="Screenshot 2023-12-19 at 17 10 53" src="https://github.com/wso2/product-is/assets/41188245/70d175c9-b3fd-437d-b6dd-71aa6ca7a2b2">

**How to reproduce:**

1. Create a No policy API resource from API Resources.
2. Navigate to the Roles page and select a role.
3. Go to the Permissions tab.
4. click on the `Select API Resource` dropdown.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by SujanSanjula96** [comment]
When creating an application audience role, the ideal behaviour should be only giving the APIs authorized under RBAC policy  to be assigned to the role. In organization audience roles, we can't do such thing since we don't know how the APIs are going to be authorized in different applications. For the application audience roles, we need to add the validation in UI for avoid the confusion that why APIs authorized under no policy should be assigned to the role. Also, we need to think whether we need to add this as a backend validation as well.
