### ISSUE TITLE
Getting a 500 internal server error when inviting a parent user to a suborganization

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18695]
**Describe the issue:**

Getting a 500 internal server error when inviting a parent user to a suborganization

https://github.com/wso2/product-is/assets/40081059/c4ba2c2f-0189-4a20-a0e0-225316487ea6

**How to reproduce:**

1.Login to the console
2.Create a user
3.Create a sub org and switch into it
4.Go to users section
5.Go to add user
6.Select a single user  from drop down
7.Click on  invite parent user

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
This occurs when trying to invite a user who is not existing in the parent organization

**Comment by dewniMW** [comment]
The issue is not yet resolved.
Exception occurs at https://github.com/wso2-extensions/identity-organization-management/blob/d86a85c41dc69eb5fa67abda0b1b2e16e19df6aa/components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java#L610-L611 due to invitedUserId being null
