### ISSUE TITLE
Incorrect Language support in the suborganization login page

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18730]
**Describe the issue:**

Incorrect Language support in the suborganization login page, specially the warning  messages doesn't  translate properly

<img width="497" alt="Screenshot 2023-12-21 at 17 26 41" src="https://github.com/wso2/product-is/assets/40081059/335cff57-91cd-4236-a839-e2c518bf7e4d">

The Organizational email doesn't change at all.

https://github.com/wso2/product-is/assets/40081059/ffea07f6-ea26-4e93-95f0-7131a1be7e34

**How to reproduce:**

1.Login to the console.
2. Enable email domain discovery from `login and registration` page.
3.Create a suborganization.
4.Create a application in the parent org and share it to the suborg.
5.Access the application via the sub org path.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
There are several i18n issues.

1. UTF-8 doesn't seem to contain some characters used in some languages such as spanish, french etc. Therefore, when the page encoding is set to UTF-8, those characters are rendered as unreadable symbols. A possible alternative would be to encode those characters manually when sent from the backend. [1]

2. An i18n mapping is missing for the key `organization.email` for some languages, which will be fixed with https://github.com/wso2/identity-apps/pull/5129

3. Since the error message to be displayed in this page is taken from a query parameter, it's encoded using `Encode.forHTMLContent` to avoid possible XSS exploits. However, this results in some characters in some languages being converted to non-alphanumeric symbols. Need to find a proper way to encode these type strings keeping the original characters from being encoded to other symbols.

[1] https://stackoverflow.com/a/29870880/8810941
