### ISSUE TITLE
Issue with Progressive Enrollment of Passkey for JIT-Provisioned Federated User

### ISSUE THREAD

**Issue by AfraHussaindeen** [wso2/product-is#18774]
**Describe the issue:**

There is an issue in the progressive enrollment process for Passkey with JIT provisioned federated users. The issue arises when a JIT provisioned user, who hasn't yet enrolled a passkey, engages in the progressive enrollment during the Passkey authentication flow. Although the user successfully authenticates through a federated authenticator at an intermediate phase, the process encounters a failure immediately after the user  consents to create a passkey.

At the point of failure, the following error is logged in the console.

`Exception: ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! FIDO2 trusted origin: https://localhost:9443/ sent in the request is invalid.`

This error points to a problem with the FIDO2 trusted origin in the request, which seems to be causing the breakdown of the Passkey enrollment flow.

**How to reproduce:**
1. Log in to the WSO2 Identity Server Console.
2. Configure Google as a federated authenticator (as per [1]).
3. Set up the Passkey to support progressive enrollment (refer to [2]).
4. Create an application in the console and add Passkey login. Ensure Passkey progressive enrollment is enabled and usernameless authentication is disabled (refer to [3]).
5. Add Google as an additional authenticator for the first step in the sign-in method tab of the created application and save the changes.
6. Attempt to log in to the application, which will redirect you to the multi-option sign-in page.
7. Click on the `Sign in with Passkey` button.
8. You will be redirected to a page to add a username. Enter the username and click `Create a passkey`.
9. Then select `Sign in with Google`.
10. Authenticate yourself following the steps provided by Google. (Ensure the user is already JIT provisioned.)
11. You will then be redirected to a page stating no passkey found. Click on `Create a passkey`.

The issue arises in the final steps, where the system fails to redirect the user to perform the passkey creation .

References:
[1] https://is.docs.wso2.com/en/next/guides/authentication/social-login/add-google-login/
[2] https://is.docs.wso2.com/en/next/guides/authentication/passwordless-login/add-passwordless-login-with-passkey/#:~:text=usernameless%20authentication.-,Enable%20Passkey%20progressive%20enrollment,%C2%B6,-This%20feature%20allows
[3] https://is.docs.wso2.com/en/next/guides/authentication/passwordless-login/add-passwordless-login-with-passkey/

**Environment information** **:**
 - Product Version: IS 7.0.0-beta6
 - OS: Mac
 - Database: H2

---

**Comment by Thumimku** [comment]
### Root cause:
When doing JIT provisioning from google, User created with email type username, But the deployment is alphaNumeric username configured.

During the Passkey Enrollment flow we [preprocess Username to get mappedLocalUsername](https://github.com/wso2-extensions/identity-local-auth-fido/blob/054f03770a7b386650c3a3d87327755e2084cb74/components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java#L1170) which will add carbon.super (the tenant domain) to the username.

Later IS try to StartRegistrationOptions, IS tries to resolve the user's displayname. For that it p[asses the tenant qualified username to userstore](https://github.com/wso2-extensions/identity-local-auth-fido/blob/c402b2c5cdb39c20110bc86b4d482c6f3750913a/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java#L951) which results  user not found.

<img width="1627" alt="Screenshot 2024-01-24 at 15 32 28" src="https://github.com/wso2/product-is/assets/25488962/dda7a097-37b3-4f33-8fa0-ae2ee37bae1f">

**Comment by Thumimku** [comment]
I tried to remove the preprocess procedure, but encountered following issue.

[Here](https://github.com/wso2-extensions/identity-local-auth-fido/blob/7f4bfb7f49ac3dbd0f55528fb8b9d66c6a3710f6/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java#L424) we retrieve user from username.

If we remove the preprocess procedure, retrieving user will fail cause [we are trying to resolve tenant domain from the username](https://github.com/wso2/carbon-identity-framework/blob/e5c55dfd9dc0ca4d1a46ee48c66d1124e796724e/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/User.java#L198).

Ideal soluction should be improving framework User Model to retrieve user from username and tenant domain passed seperately.
