### ISSUE TITLE
Organization update is not available when using special characters as organization name

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18963]
- Create an organization with some special characters as in the image.
<img width="1346" alt="image" src="https://github.com/wso2/product-is/assets/12690906/8dea2a85-e9de-448d-80ff-c42bde1ed670">
- Try to edit the organization
- The 'Update' button is not available to edit the organization.

(If we don't use any special characters the 'Update' button is available.

**Comment by brionmario** [comment]
*Analysis*

We use the `https://localhost:9443/t/carbon.super/api/users/v1/me/organizations` to validate if the organization settings are editable for the logged in user.

When there are special characters, the search query returns an  empty response, causing the above validation to fail.

##### Request

<img width="919" alt="Screenshot 2024-01-18 at 20 16 52" src="https://github.com/wso2/product-is/assets/25959096/1e177f4e-0fd9-4541-9975-00046a5fde32">

##### Response
<img width="916" alt="Screenshot 2024-01-18 at 20 16 56" src="https://github.com/wso2/product-is/assets/25959096/fd1b32e2-f99b-429b-bedd-7caf00b87100">

**Comment by brionmario** [comment]
As per @AnuradhaSK 

In previous discussions, the conclusion was not to restrict the allowed characters for the org name, instead, URL code where required and handle safely. 

Here the problem is in BE:

https://github.com/wso2/identity-organization-management-core/blob/0cd14f2102ff4164d453501d0e2f30a14ac8df4e/components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/filter/FilterTreeBuilder.java#L52-L73 only these characters were used in tokenizer

**Comment by ashendes** [comment]
The straightforward fix to this issue is only a matter of adding the extra special characters in [1]. But there are certain reserved special characters used in the filter strings, such as` ( ) ' "` etc, that need to be restricted in the org name. We need to discuss whether such characters. An allowed list of characters need to be decided and enforced from both the FE and BE.

Also, complex filter queries using the operators AND, OR are not working. Only the first filter is processed. Need to analyse further if complex filter queries are required in this service.

[1] https://github.com/wso2/identity-organization-management-core/blob/0cd14f2102ff4164d453501d0e2f30a14ac8df4e/components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/filter/FilterTreeBuilder.java#L52-L73

**Comment by hwupathum** [comment]
As a temporary fix, exclamation mark will be added to the list of allowed characters in https://github.com/wso2/identity-organization-management-core/pull/124. 

A new issue https://github.com/wso2/product-is/issues/19069 is created to handle this issue properly.
