### ISSUE TITLE
SMS OTP length is not setting properly

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#18965]
**Describe the issue:**
When the user sets the length for the SMS OTP it does not set properly.

**How to reproduce:**
1. Set a length for the SMS OTP (Other than 6).
2. Create an application
3. Add the SMS OTP as a sign in method.
4. Do the authentication process from the application
5. Notice that the SMS OTP length is staying the same.

https://github.com/wso2/product-is/assets/46097917/ecc416a3-4e17-4988-a88d-f59ad80743db

**Expected behavior:**
SMS OTP length should set properly.

**Comment by JayaShakthi97** [comment]
The issue is due to the SMS OTP length being hardcoded when unifying the JSPs (https://github.com/wso2/identity-apps/commit/8d5a59ef74f982f5a112025bc8bc60d7daa54c98#diff-c8b3158ae9a1b5a1a756dfa7111a4da6c25856347ce5ff04063fe70a05dc1ac9R41).
This was done as the Local SMS Authenticator implementation was not available in the IS at that time.

Since the Local SMS authenticator implementation is available now, this can be updated to read the length from https://github.com/wso2-extensions/identity-local-auth-smsotp/blob/main/components/org.wso2.carbon.identity.local.auth.smsotp.authenticator/src/main/java/org/wso2/carbon/identity/local/auth/smsotp/authenticator/util/AuthenticatorUtils.java#L69.

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/5259
