### ISSUE TITLE
Unable to set the IdP Issuer Name in a connection from the console

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19013]
**Describe the issue:**
Idp issuer name setting fails in a connection with the following api error. However it works if you set the idp issuer name when creating the idp (through a cURL). In the console its only possible to set the issuer when updating the connect. 
```json
{
    "code": "IDP-65005",
    "message": "Unable to update identity provider.",
    "description": "Server encountered an error while updating the identity provider for identifier Cannot replace idpIssuerName as it does not exist..",
    "traceId": "22c504da-5446-416f-842b-bff6e7401a18"
}
```

**How to reproduce:**
Create a connection and try to update the Issuer
<img width="1389" alt="Screenshot 2024-01-19 at 13 16 28" src="https://github.com/wso2/product-is/assets/11583571/496f0d40-ca57-45b7-8641-c26c60c19915">

**Expected behavior:**
IMO the experience in console of updating the Issuer after creating the connection is correct as we only need to set the issuer in certain cases. Therefore it should be possible to update the issuer via the api.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
**Analysis**

When adding an IDP, even though the value of the issuerName[1] is sent as an empty string, because of [2] it will not be added as an IDP property and stored in the database. Later updating the IDP, the validation [3] to check the existence of the property being updated will fail for issuerName since it is not already there.

[1]
![Screenshot 2024-01-20 at 12 28 52](https://github.com/wso2/product-is/assets/50801227/2799dfb2-ca56-4f89-968a-46e359b1ea0e)
[2] https://github.com/wso2/identity-api-server/blob/dce6837b1ab9e24b5796cbafd5b743162959e8b8/components/org.wso2.carbon.identity.api.server.idp/org.wso2.carbon.identity.api.server.idp.v1/src/main/java/org/wso2/carbon/identity/api/server/idp/v1/core/ServerIdpManagementService.java#L2127
[3] https://github.com/wso2/identity-api-server/blob/dce6837b1ab9e24b5796cbafd5b743162959e8b8/components/org.wso2.carbon.identity.api.server.idp/org.wso2.carbon.identity.api.server.idp.v1/src/main/java/org/wso2/carbon/identity/api/server/idp/v1/core/ServerIdpManagementService.java#L3318

**Comment by ZiyamSanthosh** [comment]
Closing since this completed.
