### ISSUE TITLE
Unable to configure custom inbound authentication protocol

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19038]
**Describe the issue:**
No place to configure custom inbound authentication protocols downloaded from the connector store[1] in the new console. I tried adding both "JWT SSO Inbound Authenticator" and the "CAS Inbound Authenticator" and both of them did not show up as available applications to configure. The data related to these authenticator were retrievable using the APIs [2] and [3].

I have a vague memory that these were previously available through a custom application template like the custom connector template in connections.

[1] - https://store.wso2.com/store/assets/isconnector/list?q=%22overview_category%22%3A%22inbound%20authenticator%22
[2] - https://is.docs.wso2.com/en/next/apis/application-rest-api/#tag/Application-Metadata/operation/getInboundProtocols
[3] - https://is.docs.wso2.com/en/next/apis/application-rest-api/#tag/Application-Metadata/operation/getCustomProtocolMetadata

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

**Comment by madurangasiriwardena** [comment]
Since the framework version is updated, above mentioned connectors in the store are no longer compatible with IS 7. Attaching the updated connectors for testing purposes.

- https://maven.wso2.org/nexus/content/repositories/releases/org/wso2/carbon/extension/identity/authenticator/inbound/cas/org.wso2.carbon.extension.identity.sso.cas/2.0.19/org.wso2.carbon.extension.identity.sso.cas-2.0.19.jar
