### ISSUE TITLE
Password pattern: The given sample in the document is the default password regex

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1921]
In [1] the sample values given are itself the default values for password pattern configuration. Ideally the documentation should be a guide to a user who wants to try it out. Below should be there in document

1. The explanations of the params in the config and the default values
2. Set of custom sample values and steps written that incorporates them

[1] https://docs.wso2.com/display/IS540/Password+Patterns

**Comment by shavidissa** [comment]
Thank you!
Since there are many sample values that can be given it might be hard to provide a list. Therefore, as suggested, I renamed the column as default values and added the following text: "Update the default values and click Update. ".

Further, Added an info note under the default password patterns, directing the users to [1].
This will allow the user to come up with their own pattern after getting an idea of each character used.

[1] https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
[2] https://docs.wso2.com/display/IS540/Password+Patterns
