### ISSUE TITLE
Check whether `<IS>/repository/conf/sms/sms-templates-admin-config.xml` configured messages get consumed when SMS sending

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19290]
**Describe the issue:**

- Identified https://github.com/wso2/product-is/issues/19287 when checking self-registration flow
- identified https://github.com/wso2/product-is/issues/19289 when trying to check mobile number update

Need to check if the messages configured in `<IS>/repository/conf/sms/sms-templates-admin-config.xml` are utilized when sending SMS.

-----------------------------------

Below scenarios also need to be checked:

- In earlier versions, we set up SMS OTP as the identity provider. Therefore, the configuration in the management console should appear as the custom connector in the new console.
- This https://stackoverflow.com/a/77850112/10055162 was possible in previous SMS OTP authenticator, need to check whether that flow works as expected in old SMS flow

**Comment by asha15** [comment]
I've conducted testing on the scenarios mentioned above using a custom SMS provider. 

Self-registration flow:  Tested the self-registration flow using the steps mentioned in https://github.com/wso2/product-is/issues/19287#issue-2107274242 and the flow worked seamlessly. However if i changed the template in sms-templates-admin-config.xml which is not utilized.

Mobile number update: I tested the mobile number verification test case and the flow worked as expected. I received the SMS as well. Anyway the template sms-templates-admin-config.xml is not utilized.

SMS OTP as identity provider: SMS OTP configured in the management console is displayed as a custom connector in the react console. I have used that connection as the second factor and the authentication flow worked fine.

[Screencast from 15-02-24 14:12:39.webm](https://github.com/wso2/product-is/assets/28682701/fdd06b1b-e42c-499c-89df-d751235c14a2)
 
Tested the following flow as well and it's worked as expected: https://stackoverflow.com/a/77850112/10055162

However during the testing a [regression](https://github.com/wso2/product-is/issues/19601) has been found , and it's fixed with https://github.com/wso2/identity-apps/pull/5526
