### ISSUE TITLE
Unable to add values for Custom attributes in sub-organization user profile update

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19307]
**Describe the issue:**
when attempting to update user attributes in a sub-organization user profile. Specifically, the custom attributes are not getting updated as expected.

**How to reproduce:**

1. Create a custom Attribute 
2. Navigate to the sub-organization user profile.
3. Attempt to update user attributes, including custom attributes.
4. Observe that custom attribute values are not being added or updated.

**Expected behavior:**
Custom attributes should be updatable in the user profile, even in sub-organizations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

[customattribute.webm](https://github.com/wso2/product-is/assets/39120228/97d7bbea-c28d-4574-9830-9dec68edbf16)

**Comment by PasinduYeshan** [comment]
Here this issue arises when attempting to update a custom attribute that is not present in a sub-organization. This custom attributes should not appear in the user profile in sub-organization unless they are associated with a custom claim requested by a shared application.

Following video highlights that when a custom attribute is requested by an application, and that application is shared with 'sub1' (a sub-organization) but not with 'sub2' (another sub-organization), updating the custom attribute fails in 'sub2'. This failure occurs because the custom claim associated with the attribute does not exist in 'sub2'.

https://github.com/wso2/product-is/assets/61885844/375d2e04-3a22-4a7a-a6d1-66ba89a039b3

To address this, custom attributes should be hidden in the user profile of a sub-organization if the corresponding claims are not present there. The current frontend implementation for rendering user profiles calls the `scim2/Schemas` endpoint. In sub-organizations, it uses the same response retrieved from the tenant, without making a request for the schema upon switching to the sub-organization. As a fix, when switching to a sub-organization, an API call should be made to the organization-specific (/o/scim2/Schemas) path to fetch the correct schemas.

**Comment by PasinduYeshan** [comment]
In the new behavior, following video highlights that when a custom attribute is requested by an application, and that application is shared with 'sub1' (a sub-organization) but not with 'sub2' (another sub-organization), custom attribute (`Custom1`) is not displayed in the `sub2` and custom attribute values are properly updated in `sub1`.

https://github.com/wso2/identity-apps/assets/61885844/4c50b566-d87c-46a8-ba33-0a9dd3997134
