### ISSUE TITLE
The JWT bearer grant type presentation is not consitent

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19338]
The jwt bearer grant type name presentation is not align with the rest of the grant type name presentations
<img width="418" alt="image" src="https://github.com/wso2/product-is/assets/12690906/d71615eb-544e-4c40-9f6c-632a32ed50a7">

**Comment by DilshanSenarath** [comment]
We obtain the label for grant checkboxes from the following meta endpoint, using `displayName` as the label:

<img width="722" alt="image" src="https://github.com/wso2/product-is/assets/74205483/90d23b1b-5b6d-49ee-b327-9923f4d4641a">
<img width="684" alt="image" src="https://github.com/wso2/product-is/assets/74205483/a71a0ce5-0d7c-409a-94db-53c41b62a6bd">

The issue arises because the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant's displayName is also `urn:ietf:params:oauth:grant-type:jwt-bearer`. To address this, a fix requires modifying the metadata from the backend.

**Comment by DMHP** [comment]
https://github.com/wso2/identity-api-server/pull/587

**Comment by DMHP** [comment]
![Image](https://github.com/wso2/product-is/assets/12690906/3e553aa4-a480-4f21-b21a-c91d64e4171e)
