### ISSUE TITLE
EmailVerified Schema Parameter Returns True Without Email Verification After Email Update.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19356]
**Describe the issue:**
When an admin creates a user and invites the user to set a password, the 'emailVerified' schema returns as true only when the user sets the password through the provided link. However, in a scenario where the admin updates the email address, the 'emailVerified' schema still returns true even without the email being verified

https://github.com/wso2/product-is/assets/41188245/245aa0fb-94df-4a5d-9934-1e6cda065b11

after just updating the email -> 

<img width="1509" alt="Screenshot 2024-02-02 at 08 33 42" src="https://github.com/wso2/product-is/assets/41188245/e5de3131-6552-4579-8933-9303c567d53d">

**How to reproduce:**

1. Create a new user -> Invite user to set password and verify whether the  GET User call returns EmailVerified schema value
2. Set the password via set password link 
3. again check the the  GET User call returns EmailVerified schema value in here the param can be found and will have the value True.
4. Then Update the specific user's email and again check the  GET User call's EmailVerified schema value -> Still have the param value as true which is not valid.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Hi melani, I think we are considering two flows here. When we need to trigger a notification when the user updates the email the following configuration `Enable user email verification on update` should be enabled.

![image](https://github.com/wso2/product-is/assets/30111554/9693b42f-e6f8-4b1f-a33f-ff34edf4d7ed)

In the admin-initiated user creation flow could you please check if the email verification notifcation is triggered if the above configuration is triggered? If that works we may need to revisit the requirement of this configuration for the ask password flow.

**Comment by Lakshan-Banneheke** [comment]
### Analysis

There are two distinct scenarios associated with this flow. There's a configuration in the User Attribute Change Verification section to Enable user email verification on update. There are two scenarios based on whether this configuration is enabled or disabled.

Scenario 1: Enable user email verification on update disabled.
When the admin user updates the email of a user, the email claim is instantly updated and the verification is still kept as true as mentioned in this issue. However, since the `Enable user email verification on update` config is disabled, it's correct to say that the email is verified even after updating to a new one due to two reasons. 1. Verification is not enforced for the updated email. 2. The initial email of the user has been previously verified. Therefore the existing behaviour is correct.

Scenario 2: Enable user email verification on update enabled.
When an admin user updates the email, a verification mail is sent to the new email address. Furthermore, the email claim of the user is not updated to the new email. The email claim still contains the previously verified email. The new email is added to a `pendingEmails` list in the user schema. Once the user confirms the new email only, the email claim will be updated with the newly verified email. Therefore, at all times the email claim will contain only a verified email address. Therefore the EmailVerified schema parameter returning true is the correct behaviour.

Had a discussion with @DMHP and confirmed that based on the above analysis, the existing behaviour is correct.
