### ISSUE TITLE
Receiving a 400 Error for SCIM Group PATCH Request in User Creation Flow When Active Directory is Configured

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19516]
**Describe the issue:**
In scenarios where Active Directory (AD) is configured and there's a delay in the SCIM call for user creation, the subsequent group patch call is resulting in a 400 error.

<img width="1505" alt="Screenshot 2024-02-12 at 17 06 18" src="https://github.com/wso2/product-is/assets/41188245/57825925-665d-41e7-b4db-af91a95a0fe7">

https://github.com/wso2/product-is/assets/41188245/b27749ae-e109-426c-8276-eee7fca9223d

**How to reproduce:**

1. Configure an Active Directory (This is expected to occur in all the User stores that may have a delay)
2. try to add a user to the created User store.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
### Analysis

Tried both SCIM user creation API call and the Group PATCH call and got the below responses.

<img width="1087" alt="Screenshot 2024-02-16 at 12 51 18" src="https://github.com/wso2/product-is/assets/41188245/8afb388e-8a6d-4c7b-8e41-0dbf1da7afe8">

The Groups PATCH call is failing 
<img width="1086" alt="Screenshot 2024-02-16 at 12 51 38" src="https://github.com/wso2/product-is/assets/41188245/3bffcd1b-ef17-4216-9917-34970064c0f8">

**Comment by UdeshAthukorala** [comment]
This is due to a incorrect mapping in the for the username attribute. In this setup for the userstore configurations we have used `cn` as the username and in the Identity server userstore attribute mappings we have used `sAMAccountName` as the username.  So this error occured due to this miss matching.

Once we used the same value(`cn` or `sAMAccountName`) for all the places that we defined as username the issue was not occured.

  - Userstore configurations
  
    ![userstore-configurations](https://github.com/wso2/product-is/assets/36252606/26bffc7f-853d-4911-8216-21484d2b53a1)
  
  - IS Attribute mappings
  
    ![IS_Attribute_mapping](https://github.com/wso2/product-is/assets/36252606/7d52eb7b-43a0-4a59-9262-fb95e23d7802)

cc: @melanisilva , @somindatommy
