### ISSUE TITLE
Cannot login to management console from macOS High Sierra

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#1956]
Get a pack from current master branch of product is (5.4.0) and start it in a macOS High Sierra. Try to login to management console. A warn message is shown in the terminal [1]. Also a blank page comes with 403 - Forbidden status due to missing csrf token. This works without any issue in the latest wum updated 5.3.0 pack
  
[1] 
WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/admin/login_action.jsp, error:required token is missing from the request)

**Comment by ashensw** [comment]
This is due to the known issue [1][2] in the JDK and macOS High Sierra. As a workaround, you can do the following to overcome the issue.

- Open <IS_HOME>/repository/conf/tomcat/catalina-server.xml and change the compression="on" to compression="off" in Connector configuration and restart the server.

[1] https://bugs.openjdk.java.net/browse/JDK-8189789
[2] https://stackoverflow.com/questions/46539453/tomcat-with-compression-enabled-causes-error-on-os-x-high-sierra

**Comment by ashensw** [comment]
Added a note to the IS540 documentation [1][2].

[1] https://docs.wso2.com/display/IS540/Installing+on+Linux+or+OS+X
[2] https://docs.wso2.com/display/IS540/Getting+Started+with+the+Management+Console
