### ISSUE TITLE
User should not be able to have the same mobile number when its is setup as multi attribute login identifier

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#19609]
**Describe the issue:**

User should not be able to have the same mobile number when its is enabled as a multi-attribute login identifier

**How to reproduce:**

1.Login to the console
2.Go to Login and registration section
3.Go to Multi Attribute Login
4.Enable Multi Attribute Login
5.Add `http://wso2.org/claims/mobile` in the allowed attribute list
<img width="1097" alt="Screenshot 2024-02-15 at 12 36 08" src="https://github.com/wso2/product-is/assets/40081059/e1934327-b0dd-4d16-8e52-79458c629ee9">
6.Add two users
7.Go to the created users and add the same mobile number for both the users and Update

Furthere more noticed , that the the created users  with the same mobile number can not login into the application when trying to login with the mobile number 
**Expected behavior:**

When a attribute is enabled as a Multi Attribute Login identifier , same attribute value should not used as it has to be unique

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sandushi** [comment]
- In WSO2 Identity Server, certain attributes which are defined as multi attribute login identifiers aren't automatically treated as unique. 
- When using an attribute as a login identifier, it's important to make sure each attribute has a distinct value. This prevents conflicts when multiple instances share the same value for the designated login identifier. 
- We have given the capability to maintain the uniqueness of the attributes.
- Our documentation explains how to make an attribute unique; you can find the steps here: https://is.docs.wso2.com/en/next/guides/users/attributes/configure-unique-attributes/. 
- We've also linked to documentation on multi-attribute login at https://is.docs.wso2.com/en/next/guides/authentication/multi-attribute-login/

- By making the attribute as a unique attribute and enabling the listner through the deployment.toml, the above explained scenarios works as expected behavior.
