### ISSUE TITLE
[User Attribute Change Verification] "Enable mobile number verification on privileged users" configuration does not have an effect on triggering the sms otp notification by an admin or user

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19720]
**Describe the issue:**
There are 2 ways the mobile number could be updated.
1. By the administrator
2. By the user itself

In both these cases, without the configuration of "Enable mobile number verification on privileged users", the behaviour is working as expected:

Recording: 

https://github.com/wso2/product-is/assets/106053688/2120869a-4804-4bd2-9039-24750fbf460f

**How to reproduce:**
1. Navigate to User Attribute Change configurations
2. Disable "Enable mobile number verification on privileged users" and enable "Enable user mobile number verification on update"
3. Verify the mobile number update behaviour

**Expected behavior:**
The configuration should be revisited on its validity

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by bhagyasakalanka** [comment]
The configuration option "Enable mobile number verification on privileged users" allows administrators or privileged users to verify the mobile numbers of other users on their behalf. This setting is specifically designed to enable OTP verification by administrators and does not control or affect the ability of administrators to set mobile numbers for users.

For example, in a banking scenario, the bank may choose to handle OTP verification on behalf of its users. Instead of the user entering the OTP themselves, the bank can request the OTP from the user and perform the verification on their end. Enabling this configuration allows administrators or privileged users to complete the OTP verification process on behalf of users in such cases.

We can use following API calls to do the required verification by the Admin/Privilege users

Set user mobile number by admin
```
curl --location --request PATCH 'https://localhost:9444/scim2/Users/a55c547d-7ffe-436f-8862-0cd0163943ab' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data '{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                    "verifyMobile": "true"
                },
                "phoneNumbers": [
                    {
                        "type": "mobile",
                        "value": "0123456734"
                    }
                ]
            }
        }
    ]
}'
```

Verify user mobile number by admin
```
curl --location 'https://localhost:9444/api/identity/user/v1.0/validate-code' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data '{
    "code": "d2Kqas",
    "properties": []
}'
```

**Comment by bhagyasakalanka** [comment]
Closing this issue as this is not a valid issue
