### ISSUE TITLE
[B2B] For a shared role, connected application section is not loading in the Roles page

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19833]
**Describe the issue:**
For a shared role, connected application section is not loading for the Roles

**How to reproduce:**
Currently, the B2B Organization will only have roles that are shared to the organization by an application. Even then, the Role doesn't populate the shared applications in the following screen:
<img width="1512" alt="Screenshot 2024-02-25 at 15 25 54" src="https://github.com/wso2/product-is/assets/106053688/36497708-afa0-45cf-8956-92d1ba4c7ab8">

**Expected behavior:**
If this is not a feasible screen within the B2B organization, then it should be removed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
This issue is no longer valid for IS-7.0.0 and IS-7.1.0.

IS roles can be separated based on their audience. 
If the role is :
1. application audienced role - It can be connected only to the role defined app only. Since that information is mentioned in audience details, the Connected Apps tab was not in application audience based roles
2. organization audienced role - Earlier, the organization audienced role consuming applications can select which roles will be consumed by that application. Then connected apps of an org audienced role was benifical. However, 
 with https://github.com/wso2/product-is/issues/20, the necessity of associating organization roles with Applications was removed. Therefore, an org audienced role consuming applications can be derived by allowed role audience of the application.

Now, even in root orgs/ sub orgs console do not show connected apps tab for roles.


**Root org:**

Application audienced role:

<img width="1515" alt="Screenshot 2024-11-20 at 12 04 31" src="https://github.com/user-attachments/assets/431a9190-4853-4da2-bac8-7e04231f135c">

Organization audienced role:

<img width="1472" alt="Screenshot 2024-11-20 at 12 04 39" src="https://github.com/user-attachments/assets/a73d8647-10e5-40b4-8a6a-79677aa3b3cd">

**Sub org:**

Application audienced role:

<img width="1220" alt="Screenshot 2024-11-20 at 12 05 04" src="https://github.com/user-attachments/assets/396ecced-448b-4c21-8d7b-69d803b0a202">


Organization audienced role:

<img width="1357" alt="Screenshot 2024-11-20 at 12 04 54" src="https://github.com/user-attachments/assets/602abb4c-34d2-4c52-a7d5-ae2d309609b1">
