### ISSUE TITLE
[Bug] Unable to create an SP with the same name after deleting an SP

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1984]
1. Create an SP by following the document at [1]
2. Delete the SP.
3. Create a new SP with the same configuration and attempt to save

Expected Results:-
- User should be able to save SP

Actual Results:-
- A warning message is displayed as shown in attached image.
[1] https://docs.wso2.com/display/IS530/Adding+and+Configuring+a+Service+Provider#AddingandConfiguringaServiceProvider-Addingaserviceprovider

![sp](https://user-images.githubusercontent.com/13449310/34561403-cd5e6114-f16f-11e7-8061-ce2fff287342.jpg)

**Comment by pubudup** [comment]
Tested in : 5.3.0
Severity: High

**Comment by omindu** [comment]
@pubudu538 is this a wum updated pack ?

**Comment by pubudup** [comment]
@omindu, we are testing IS 5.3.0 Update1 in a 2 node cluster

**Comment by omindu** [comment]
@pubudup You mean 5.4.0 ? IS 5.3.0 don't have an update1.

**Comment by pubudup** [comment]
@omindu yes. It's 5.4.0 update1

**Comment by omindu** [comment]
@pubudup I tried this in a single node but couldn't reproduce the issue. By looking at the screenshot, the error seems to have appeared while saving SAML configs. This is most likely due to the SAML configs of the previous SP was not deleted when deleting the SP.

When creating a SAML SP we store the data in 2 places. Some in identity DB and some (SAML related configs) in the registry under `/_system/config/repository/identity/SAMLSSO/`. When the configs in the registry is not removed, this error can occur. One of the possible causes of this can be an issue with registry mounts. If the issue is not with the registry mounts, we have to further investigate why this is happening.

- How often can this be reproduced ?
- Were there any errors while deleting the 1st SP

Better if you can attach the related carbon logs of both nodes and the confs to the ticket as well.
