### ISSUE TITLE
The invite parent user modal in console settings is incorrect

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#19889]
**Describe the issue:**

Invite parent users from the user's menu is correct as it says invite a parent user.

<img width="582" alt="Screenshot 2024-02-29 at 00 32 28" src="https://github.com/wso2/product-is/assets/35717390/09cc63f6-a863-4ea1-8332-418737b6e2bf">

But the way console settings user invite shows is incorrect as it always state invite from "carbon.super" even for any level organization. This not consistent and invalid.

<img width="581" alt="Screenshot 2024-02-29 at 00 31 43" src="https://github.com/wso2/product-is/assets/35717390/45620827-29de-42a9-bf6b-44c433463a12">

Also its better to improve the two options of Add Administrator button to as invite parent user.
The invite new user is incorrect.

<img width="1136" alt="Screenshot 2024-02-29 at 00 35 18" src="https://github.com/wso2/product-is/assets/35717390/55fb11da-e3a4-4610-8146-1aa5db5ed8fd">

**Comment by ShanChathusanda93** [comment]
Fix is available in the master pack. Please refer the below SS.

1. Add Administrator dropdown
<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/19262008/5301d99f-b31f-47e5-a82f-1455272f13b0">

2. Invite Administrator wizard
<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/19262008/b854c53f-c37f-4dcc-9a28-fd4ab08f3568">

Since the fix is merged closing the issue.
