### ISSUE TITLE
Organization operations are not visible if we create an organization from the API

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#20316]
**Describe the issue:**
In IS we can create organizations from the API and the Console. When we create an organization from the Console we can see the organization switch button.

https://github.com/wso2/product-is/assets/19262008/beb64099-e6d1-4519-926c-45cd8e4e2fbe

But if we create an organization from the API, the switch button is not available.

https://github.com/wso2/product-is/assets/19262008/94081d0c-5c04-4812-8cc0-82ef2be9feae

Organization creation request
```
curl --location 'https://localhost:9443/api/server/v1/organizations' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data '{
  "name": "ABC Builders 1",
  "description": "Building constructions",
  "type": "TENANT",
  "parentId": "10084a8d-113f-4211-a0d5-efe36b082211",
  "attributes": [
    {
      "key": "Country",
      "value": "USA"
    }
  ]
}'
```

Even the options are not working, we can delete the organization from the API.

**How to reproduce:**
1. Execute the above mentioned API call and list down the organizations from the Console.

**Expected behavior:**
- The user who create the organization should be able to do the other operations from the Console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-7.0.1-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by yasirjanjua** [comment]
@sadilchamishka this issue also occurs using the client_credentials grant type.

**Comment by sadilchamishka** [comment]
Hi @yasirjanjua 

![abc](https://github.com/user-attachments/assets/8a75ac24-c396-4918-b832-10da48746b49)

A user with organization listing permissions can view all the organizations. **However, management access to each organization depends on the application roles assigned to the currently logged-in user for those specific organizations.**

Consider the following scenario:

- B2B App1 creates organization1.
- B2B App2 creates organization2.

Within the context of B2B App1, only organization1 can be managed. Similarly, within the context of B2B App2, only organization2 can be managed. It is due to the two users who logged into B2B App1 and B2B App2 has only the corresponding application's roles.

> If these organizations (organization1 and organization2) are created via the Console App (a B2B application provided by WSO2 Identity Server to streamline IAM capabilities), they will fall under the Console App's context. This happens because the logged-in user (The organization creator) is automatically assigned the Console Administrator Role (In corresponding org) during the organization creation process.

But as you expected there can be use cases where organization1 or organization2 is required to displayed in the console app as an organization which can be managed. In that case what we have to do is to assign the corresponding Console Administrator role (In the required org) to the console app login required user.

Hope you got the reason behind this experience, and I will share the steps to accomplish the requirement you need.

Thanks,
Sadil

**Comment by sadilchamishka** [comment]
The following steps are referred from the documentation (I have referred from the 4th point onwards) [1].  The documentation is about assigning a role of another B2B application. In this case I assumed it as the Console app.

1. First you can get a token from the root organization (You can follow the same approach followed to get a token to create the organization).

2. Switch the token with the required organization
```
curl -X POST https://localhost:9443/oauth2/token \
-u  '<client_id>:<client_secret>' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=organization_switch&token=<access token obtained for root organization>&switching_organization=<created organization id>&scope=internal_org_role_mgt_view internal_org_role_mgt_update internal_org_user_mgt_create internal_org_user_mgt_list internal_org_application_mgt_view'
```

3. Find the ID of the user who gets created in the organization. The name will be same as the organization creator.
```
curl --location 'https://localhost:9443/o/scim2/Users?filter=userName eq <username of the user created in step 1>' \
--header 'Authorization: Bearer <access-token-obtained-for-the-organization>' \
--header 'Content-Type: application/json'
```

4. Find the Console Administrator role ID. The audience value is the application name which is "Console"
```
curl --location 'https://localhost:9443/o/scim2/v2/Roles?filter=displayName eq <admin-role-name> and audience.value eq <role-audience-value>' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <access-token-obtained-for-the-organization>'

```

5. Assign the Console Administrator role to the user.
```
curl --location --request PATCH 'https://localhost:9443/o/scim2/v2/Roles/<admin-role-id>' \
--header 'Authorization: Bearer <access-token-obtained-for-the-organization>' \
--header 'Content-Type: application/json' \
--data '{
    "Operations": [
        {
          "op": "add",
          "path": "users",
          "value": [
            {
              "value": "<user-id obtained from step 4>"
            }
          ]
        }
    ]
}'
```

[1] - https://wso2.com/asgardeo/docs/guides/organization-management/onboard-org-admins/self-service-approach/#maintain-admins-in-the-root-organization
