### ISSUE TITLE
Carbon management console session timeout is not configurable from deployment.toml

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#20477]
**Describe the issue:**
Carbon management console session timeout should be configured in <IS_HOME>/repository/conf/tomcat/WEB-INF/web.xml file as below.

```
    <session-config>
        <session-timeout>1</session-timeout>
        <cookie-config>
            <secure>true</secure>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>
 ```

However, this is not configurable from the deployment.toml even though there is a default value in the default.json file `tomcat.management_console.session_timeout`

**Expected behavior:**
Management console session timeout should be able to configured from the toml file

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10

**Comment by Thisara-Welmilla** [comment]
The <IS_HOME>/repository/conf/tomcat/carbon/WEB-INF/web.xml file does not have a corresponding .j2 file in the IS pack. Due to the complexity of the configurations in web.xml file, the .j2 file has been removed from the IS pack [1]. Our documentation advises updating the web.xml file directly to modify the session timeout value [2].

[1]. https://github.com/wso2/product-is/pull/6562/files
[2]. [Running the Product - Accessing the Management Console](https://is.docs.wso2.com/en/5.10.0/setup/running-the-product/#accessing-the-management-console).
