### ISSUE TITLE
Organization Hierarchy is not Displayed Properly In IS Console

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#20690]
**Describe the issue:**
When you switch into a child organization with a level depth of 2 or more, the organization hierarchy navigation bar displayed at the top of IS Console, is incomplete as it only shows the first two levels of the organization hierarchy (Root organization and level one parent organization).

https://github.com/user-attachments/assets/a92e801e-6281-460c-b739-56486a8f4acb

**How to reproduce:**
1. Log into IS Conosle with super tenant admin credentials.
2. Create an oragnization.
3. Switch into the organization created at step 2.
4. Create a child organization in the currently switched organization.
5. Switch into the organization created at step 4.
6. Now observe the organization hierarchy navigation bar at the top of the IS Console.

**Expected behavior:**
Complete organization hierarchy should be displayed at the top of IS Console.

**Environment information:**
 - Product Version: `IS 7.0.1 SNAPSHOT`
 - OS: `macos`
 - Database: `default`
 - Userstore: `default`

**Comment by pavinduLakshan** [comment]
Dropdown is properly displayed on reloading the page after navigating to a suborg in a deeper level, hence the issue should be due to a missing state update when switching between organizations.

<img width="1507" alt="Screenshot 2024-07-29 at 11 54 56" src="https://github.com/user-attachments/assets/a35a299e-213d-4757-86a4-578d9a576609">

**Comment by pavinduLakshan** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/6686
