### ISSUE TITLE
Getting DB Scripts issues when executing Oracle RAC DB scripts related to IS 6.1

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21229]
**Describe the issue:**

Getting  the following identity  DB Scripts issues when executing Oracle RAC DB scripts related to IS 6.1

[identitydb-oracle-rac-script.txt](https://github.com/user-attachments/files/17238558/identitydb-oracle-rac-script.txt)

**How to reproduce:**

Execute the identity DB script specified for oracle-RAC against the created database
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: [e.g., IS 6.1]
OS: [e.g. Linux/Oracle RAC vm]
Database: [e.g., Oracle Rac]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Sachin-Mamoru** [comment]
For the issue of `identity DB script` execution, the issue was due to the following syntax [1] in the IS 6.1.0 pack,

<img width="805" alt="image" src="https://github.com/user-attachments/assets/cc5c3476-705c-401d-bdb7-29ef9ecb7b01">


[1] https://github.com/wso2/carbon-identity-framework/pull/5796/files#diff-207ef1dd512efb93ba96db44a9e391111fa17bc248ea7a31e108750e47fee9acL1604-L1620
