### ISSUE TITLE
Upgrade dependency 'xercesImpl' to v2.12.2

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#21428]
Upgrade xercesImpl to version 2.12.2

**Comment by asha15** [comment]
Fixed with the following PRs:

- https://github.com/wso2/identity-api-server/pull/724
- https://github.com/wso2/identity-api-server/pull/726
- https://github.com/wso2/identity-api-server/pull/729
- https://github.com/wso2/carbon-analytics-common/pull/853
- https://github.com/wso2/identity-api-server/pull/670
