### ISSUE TITLE
Incorrect returning of matching alias in the logic of RequestObjectValidator implementation.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#2159]
In the for loop at [1], it is assigning the value to variable 'alias'. So even when the alias is a not match for sent in thumbprint an 'alias' value is wrongly returned. Ideally it should not return an alias value if there is no matching cert and log an error.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/RequestObjectValidatorImpl.java#L308-L336

**Comment by Pushpalanka** [comment]
This was happening in the request Object validation flow. It was not honoring the thumbprint check for the value sent in the request object.

**Comment by Buddhimah** [comment]
Old Implementation get  the signature by the keystore. To get the certificate it uses the alias that matches with the certificate using the getAliasForX509CertThumb function.     Here it Enumerates the aliases in the keystore and match the thumbprint with the SHA-1 encoded certificate.then return the matching alias the issue was the even when non of thumbprints matches the alias that comes in final iteration returns in the function. 
But in the new implementation this handles in a different way. It retrieves the certificate not through the keystore but using the service provider certificate. So above kind of issue will not occur.Hence Later Versions does not show this issue

**Comment by DMHP** [comment]
As this issue is already fixed in the master branch closing the issue.
