### ISSUE TITLE
Handling state parameter in RP-Initiated Logout requests with invalid id_token_hint param

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#21702]
**Describe the issue:**
According to the specification [1], if the state parameter is included during RP-Initiated Logout, it should be passed back to the RP during redirection.

However, it was observed that when the logout is initiated from the RP with an invalid `id_token_hint`, the state parameter is not returned in the response.

The documentation [2] also states that if an application sends this parameter, WSO2 Identity Server will return it in the response.

As per the specification and documentation, the behavior should be improved to return the state parameter to the RP even if the `id_token_hint` provided is invalid.

[1]. https://openid.net/specs/openid-connect-rpinitiated-1_0.html#:~:text=OPTIONAL.%20Opaque%20value,to%20the%20RP.
[2]. https://is.docs.wso2.com/en/latest/guides/authentication/oidc/add-logout/#:~:text=page%20after%20logout.-,state,-The%20parameter%20passe

**How to reproduce:**
Below is a sample request.
```
https://localhost:9443/oidc/logout?client_id=<clientid>&post_logout_redirect_uri=<redirect_uri>&state=<state>&id_token_hint=<invalid_id_token>
```
**Expected behavior:**
As per the specification and documentation, the behaviour should be improved to return the state parameter to the RP regardless of the validity of `id_token_hint`.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0.0

**Related issues:**
[1] https://github.com/wso2/product-is/issues/21156

**Comment by kayathiri4** [comment]
This is not reproducible in master. The expected behavior

Ideally the state param has to be returned if we are redirecting to the application, and state param is not returned if redirected to IS error pages.

Example:

1. If the either callback url or (id_token_hint and client_id) is not added in the logout request (This scenario will be fixed with this update)
2. If the client ID is present and passing invalid id_token_hint
For 1 and 2 - redirected to application and state param should be returned
If the client ID is not passed, we try to resolve the the client id from id_token_hint. Here, if the id_token_hint is invalid, it redirects to IS error pages, where the state param will not be passed.

(https://localhost:9443/authenticationendpoint/oauth2_error.do?oauthErrorCode=access_denied&oauthErrorMsg=Error+occurred+while+decrypting+the+id+token+%28JWE%29.&crId=844e98a7-40e0-45cd-b20f-5d14fddc9a70)
