### ISSUE TITLE
Unable to SSO to other applications after login to an application with basic auth request path authentication configuration

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2192]
Steps followed when testing [1]
1. Configure SSO for app1 and configure basic auth request path authentication
2. Configure SSO for app2
3. Entered credentials in app1 login and logged in to the app
4. Tried login in to app2 and redirected to IS login to enter credentials 

Suggested Labels
- 5.4.0, Bug 

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389#2c1b

**Comment by djphan** [comment]
Hi just chiming in with Dan above who is working on the issue, we found a temp workaround to fix SSO in the bug above but we need to investigate and consult on the implications of this change: https://github.com/danAtInv/carbon-identity-framework/commit/15ed6a463d96679aafe87affcbafd2cf46f7a418

**Comment by djphan** [comment]
If the above link expires but the workaround is to remove  `sequenceConfig.setCompleted(false);` in DefaultAuthenticationRequestHandler.java in the conclude flow. But we don't know what the impact is on the rest of the flows (this enables SSO)

**Comment by danAtInv** [comment]
Just an update - the above fix was incorrect.  I think I have found a better fix:
https://github.com/danAtInv/carbon-identity-framework/commit/136c8c84360e334c5891b33e9105e50be116b0b0
This code tries to find previously authenticated RequestPathAuthenticators, in the same way that previously authenticated StepAuthenticators are searched.  Would love some feedback on this fix!

**Comment by malithie** [comment]
Hi @danAtInv,

Thanks a lot for contributing. We noted a slight problem with the fix you provided. I have commented on the PR about the implication.

If I give an overview of this issue, it had occurred due to the fix done over [1] as per the architectural discussion at [3].
Previously when an authentication request comes for an active session, in each step we validated if the user has been authenticated over the respective IdP of a particular authenticator. The login prompted only if the user had not been authenticated with the respective IdP.
Because of this validation below use case failed.
- There are two SPs as A and B.
- A had been configured for basic authentication
- B had basic authenticator in the first step and FIDO in second step
- User logged in to A providing username and password. User then access B. Even though the expectation is to prompt for authentication with FIDO device, the user will get directly logged in for app B. 
This is because in both authenticators the IdP is picked as 'LOCAL'. So it just validated if the user had been authenticated over the respective IdP only.

With [1] we had fixed this to validate both the IdP and the authenticator being previously authenticated with.
Therefore, now, when request path basic authentication is configured for one of the apps and the other authenticates with the basic authenticator, even though the IdP is same, as the authenticators (validated against authenticator names) are different, login will be prompted. 

We have initiated a discussion at dev@wso2.org [3] to decide on the appropriate fix for this issue.
You can follow up on that thread for more information. We highly welcome your suggestions as well in finalizing the solution for this issue.

[1] https://wso2.org/jira/browse/IDENTITY-6198
[2] https://mail.wso2.org/mailarchive/architecture/2017-July/028336.html
[3] https://mail.wso2.org/mailarchive/dev/2018-July/077707.html

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
