### ISSUE TITLE
Self-contained access token can not be revoked

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#2255]
We can not revoke the self-contained access token by calling revoke endpoint

curl -X POST --basic -u "jWefQUw0zWPZRp_Lyzx8yejBjSwa:TqYp_cqcXeZLU66eE1Jd7t6w9msa" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "token={self contained access token}&token_type_hint=access_token" https://localhost:9443/oauth2/revoke

This only works when we put the hash of the ID token,
curl -X POST --basic -u "jWefQUw0zWPZRp_Lyzx8yejBjSwa:TqYp_cqcXeZLU66eE1Jd7t6w9msa" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "token={hashed self contained access token}&token_type_hint=access_token" https://localhost:9443/oauth2/revoke

**Comment by GDRDABARERA** [comment]
This is not a bug. This is the expected behaviour of the self contained access-token implementation. Since we are storing the hash when we are revoking we need to send the hash of the self-contained access token in the revoking request.

**Comment by GDRDABARERA** [comment]
Hence, closing the issue.

**Comment by mefarazath** [comment]
IMO, this is a bug that needs to be fixed.

If we do not support revoking at all then it's acceptable since self-contained tokens are not meant to be sent back to the authorization server for introspection. So even revoking doesn't matter since the application wouldn't know the token is revoked unless it comes back to the authorization server for introspection.

If sending the hash revokes token, then we need to investigate this a bit further.

**Comment by madurangasiriwardena** [comment]
Cannot reproduce in the latest pack.
