### ISSUE TITLE
Migration procedure from IS 5.3.0 to IS 5.4.0 - Migration does not work as expected

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2260]

**Comment by nilasini** [comment]
One issue is migration client is migrating the inactive tenants.

The second issue is if the particular identity server doesn't have a local claim which is used by another claim dialect then there will be exception while migrating. So in order to avoid that need to add all the local claims which have dependency with other claim dialects added through migration.

**Comment by nilasini** [comment]
Needs to check Oauth migration for inactive tenants as well.
