### ISSUE TITLE
 Import Photos Action button on playground 2 webapp

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2299]
Why we are using action button called " Import Photos", IMHO this makes user confused since our samples are not aligned with any of photo import context. 

https://docs.wso2.com/download/attachments/85367791/Playground-sampleHome.png

**Comment by madurangasiriwardena** [comment]
"Import Photos" is applicable for OAuth flow where user tries to import photos from a resource server and user is redirected to authenticate against the authorization flow.

Yes, in a OpenId Connect flow this may not be relevant, as the application retrieves user information instead of interacting with a resource server, and we can improve the application to reflect this flow.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
