### ISSUE TITLE
Include a step by step sample on how we can use consent api in documentation

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2363]
Include a step by step sample on how we can use consent api in documentation [1]. It does not explain much in the doc.

[1] https://docs.wso2.com/display/IS550/Consent+Management+Using+REST+APIs#ConsentManagementUsingRESTAPIs-Definitionsforconsentmanagement

**Comment by sherenewso2** [comment]
Hi Ushani, 

Could you elaborate more on what is required and why we need a step-by-step of this please? Since it's a REST API doc, its intuitive that to try it out, the user would have to try out the given curl commands right? 

The commands have been listed out in [1] in the order in which they should be tried out (first purpose and pii categories, and then purposes, and finally consent). 

[1] https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html

**Comment by sherenewso2** [comment]
Please re-open if you think a tutorial is needed
