### ISSUE TITLE
Doc issues on  'Store service provider cert in DB instead of the keystore' section

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2369]
Doc Link : https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider 

1. What is the purpose of "Application Certificate" , mention why ? list down all the use cases where we use this cetificate. 

 " Copy the content in the .pem file of your service provider application certificate "

2. What is the 'certificate' here be specific on supported certificate format 

3. Link or provide hint how to generate .PEM file and what is .PEM format in very shortly

**Comment by rushmin** [comment]
# Paste / Upload the application's certificate.

## When this certificate is used

This certificate is used to validate the signatures of the signed requests from the application (service provider) to the Identity Server. Therefore the certificate is used in below scenarios.

1) Validating the signatures of SAML authentication requests for logout requests.
2) Validating the signature of OIDC request object (we need a link here)

## The format of the certificate

WSO2 IS expects the certificate in PEM format. 

PEM is a Base64 encoded format, therefore contains ASCII  character and easier to deal with rather than a binary encoded certificate.

## How to obtain the PEM  encoded certificate

The PEM content of a certificate in a JKS file, can be obtained by following the steps below.

1) Export the certificate from the keystore. The exported certificate will be in binary format.
```
keytool -export -keystore <keystore-path> -alias <alias-of-the-certificate> -file <path-of-the-expected-certificate-file>

e.g. keytool -export -keystore wso2carbon.jks -alias wso2carbon -file wso2carbon.crt
```
2) Convert the above binary encoded certificate to a PEM encoded certificate.
```
openssl x509 -inform der -in <path-of-binary-certificate> -out <path-of-expected-pem-content>

e.g. openssl x509 -inform der -in wso2carbon.crt -out wso2carbon.pem
```

**Comment by rushmin** [comment]
@mefarazath  could you please check the above paragraph and provide a link to the 2nd point of "When this certificate is used" section

**Comment by mefarazath** [comment]
> What is the purpose of "Application Certificate", mention why? list down all the use cases where we use this certificate.

- Validate the signature of the SAML2 authentication requests and the SAML2 logout requests that are sent by the service provider
https://docs.wso2.com/display/IS530/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Configuringtheserviceprovider

- Encrypt id_token

- Validate Signed Request Object sent in OAuth2/OIDC Authorization Request
https://docs.wso2.com/display/IS550/OIDC+Request+Object+Support+in+WSO2+Identity+Server

**Comment by rushmin** [comment]
Thank you @mefarazath. Updated the draft.

**Comment by rushmin** [comment]
The documentation has been updated. (https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider)
