### ISSUE TITLE
Filter claims from SSO consent approval for OIDC

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2400]
Output user information of ID tokens, userinfo requests should be restricted based on the user consent

**Comment by mefarazath** [comment]
- Initial Implementation added with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/825
- Improvement to support prompt=consent and approve always option was added with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/834

However, we cannot do this for back channel grant types which talk to the token endpoint directly. This is because currently, we have a limitation of not being able to provide consent via the dashboard for back channel grant types.

This improvement was added with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/839
