### ISSUE TITLE
Make the error message more descriptive when user fails the self sign up. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2556]
If the user is missed to enable to self-sign up feature through Management Console, it is better in the error message if we can include from where that user needs to enable the self-sign up feature. 

## Steps to re-create
1. Follow the steps in [Configuring self sign up](https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Configuringselfsignup) document. 
2. **DO NOT** enable self registration in Identity Providers -> Resident-> Account Management Policies -> User Self Registration 
3. Follow the rest of the steps. 
4. Access the dashboard. 
5. Click on Register Now link. 
6. Register by providing details. 

User will be navigated to an error page since **enable self registration** is disabled. 
![self2](https://user-images.githubusercontent.com/31693103/36478641-7ea13286-172b-11e8-8874-5ea43440afab.png)

As an improvement, we can further provide details to the user from where he can enable the self-registration from Management console. (Identity Providers -> Resident-> Account Management Policies -> User Self Registration)

Type/Improvement
Affected/5.5.0-Alpha

**Comment by hasinthaindrajee** [comment]
The option you have described is only allowed for system admins. Not for users .. Hence it's an invalid option. However with alpha3 we have the username first approach where you need to enter the username first, so that we can identify your tenant domain and then allow you to proceed. With this an early message will be shown if self sign up is disabled.
