### ISSUE TITLE
The email address does not get validated in self signup. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2578]
Document: https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation

## Steps to re-create
1. Follow the steps in the above document. 
2. Login to dashboard and click on 'Register Now' link. 
3. Provide details as below. 

> First Name: Isuru
> Last Name: Uyanage
> Password: $password
> Email: isuruuy@gmail.co (Provide an invalid email address)

4. Click on Register button. 

**Expected:** Since the email address is invalid, it expects to be validated. 
**Actual:** It pops up a message saying **Confirmation link has been sent to your email** without verifying the validity of the email provided by user. 

It is better if we can verify the email provided because sometimes the email address can be misspelled and still it confirms that an email is sent, which misleads the user. 

Type/Improvement
Affects/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by hasinthaindrajee** [comment]
The given email address is a valid email address (regex). The only way to get it confirmed is send the mail and see whether sending fails. But still it will not be successful since mail servers do a retry multiple times on failures. Basically we validate email using a regex. ex - you can't enter isuru/gmail as email. The given address is a valid address according to patterns.
