### ISSUE TITLE
failedLoginAttempt count is incorrect

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2609]
Document: https://docs.wso2.com/display/IS550/apidocs/User-export-apis/#!/operations#UserExport#getMe

## Steps to re-create
1. Self-signup a user and login to the dashboard using unlocked user credentials. 
2. Logout and do a failed login attempt to Dashboard. 
3. Do a failed login attempt to Management Console using the just created username. 
4. Execute the following curl command. 

```
curl -k -H "Authorization: Basic base64(username:password)" -H "Content-Type: application/json" -X GET "https://localhost:9443/api/identity/user/v1.0/me"
```
5. Verify the response.

**Expected:** failedLoginAttempts should be 2
**Actual:** failedLoginAttempts is 0

Type/Bug
Severity/Major
Priority/High
Affected/5.5.0-Alpha

**Comment by hasinthaindrajee** [comment]
Did you enable identity management here ? Account locking ? Failed login attempts will only come into picture when account locking is enabled.

**Comment by isuruuy429** [comment]
@hasinthaindrajee Yes Account lock has been enabled.

**Comment by hasinthaindrajee** [comment]
In order to retrieve this information from me endpoint, you either have to authenticate to dashboard or to service using correct credentials (username and password) which means you have successfully authenticated at least once upon downloading credentials. So the failed login attempt count will be reset to 0 once you have a successful authentication. However you can get confirmed this is working properly in the following way.

Login to dashboard using a one browser as user x.
Open another browser and make some failed login attempts. 
Go back to the first browser and download user info from profile. (this functionality users the same service but has previously authenticated session)
You will see the correct count.
