### ISSUE TITLE
Consents will be displayed in the dashboard only after logging into the app 

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2661]
**Steps**
1. Register the travelocity app
2. Check the consents in the dahsboard

The app will not be displayed under consent management. Even though the user has not logged into the app, we can show all the apps the user has access to so that the user can update the consent details before logging into the app in the dashboard itself.

**Comment by ayshsandu** [comment]
This is the expected behavior. User gives consent to the Application during the authhentication flow. In the user dashboard we list available consent receipts[1] for a particular user. We have special cased the _System consent_ which is collected by the resident IDP. System consent can be given during self signup and for already on-boarded users, it can be accepted from the user Dashboard.

[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Configuringconsentforservices
