### ISSUE TITLE
Newly added claims are not appearing when logging into an app

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2663]
**Steps**
1. Modify and add new claims in the travelocity app
2. Login to the travelocity app 

**Issue**
The newly added claims will not be displayed unless they are mandatory claims

**Comment by hasinthaindrajee** [comment]
This is the expected behaviour.  If the claim is mandatory for SPs functionality it should go under mandatory claims. Otherwise it's an optional one. If the user needs new optional claims to be visible they need to revoke the existing claim and give a new consent. Basically if the new claim is a must to have, they need to make it a mandatory claim.

**Comment by dilinisg** [comment]
I found the below info from the doc below. Under "Consent for newly added attributes" section, it says,

`"For consents in other applications (other than the system consent), the user will be prompted to provide consent for newly added attributes during the SSO flow."`

https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Workingwithyourauthorizedapplications

Can you please point me if the behaviour you mentioned for mandatory claims and other claims is documented anywhere? If not shall we elaborate the details given in this document?

**Comment by hasinthaindrajee** [comment]
@sherenewso2 : Shall we improve documentation on this ?

**Comment by sherenewso2** [comment]
Described in the 'Accepting consent for new attributes' section in doc [1]

[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Configuringconsentforservices
