### ISSUE TITLE
Error after approving consent for oauth authz code flow for tenant users

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2889]
The error happens due to SP being identified as the default super tenant SP after consent approval hence consent processing fails. But if we send the `tenatDomian` param with the correct SP tenant domain in the authz request the error cannot be seen.

**Comment by mefarazath** [comment]
This error is due to line segements 

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/15859989e2a92579e7128fbd5b7f4725d2f07b10/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L1249-L1253

```
        if (StringUtils.isNotEmpty(oauthRequest.getParam(MultitenantConstants.TENANT_DOMAIN))) {
            params.setTenantDomain(oauthRequest.getParam(MultitenantConstants.TENANT_DOMAIN));
        } else {
            params.setTenantDomain(MultitenantConstants.SUPER_TENANT_DOMAIN_NAME);
        }
```

Ideally, we should be able to derive the Sp tenant domain from the client_id since its unique across the server. Relying on the tenantDomain query param can lead to unexpected behaviour since the code expect the value returned from params.getTenantDomain() to be service providers tenantDomain
