### ISSUE TITLE
Rest API for updating challenge questions/answers 

### ISSUE THREAD

**Issue by BarathArivazhagan** [wso2/product-is#3023]
Hi,

Are there any rest endpoints to update the challenge questions/answers of the user. 

I am able to get the challenge questions of the user using below link

https://docs.wso2.com/display/IS530/apidocs/account-recovery/#!/operations#PasswordRecovery#securityQuestionGet

Would like to know similar endpoints for updating the challenge questions set ?

**Comment by darshanasbg** [comment]
Done a simple search on this and found the following reference,
https://docs.wso2.com/display/IS530/Managing+Challenge+Questions
which is referred from,
https://docs.wso2.com/display/IS530/apidocs/account-recovery/index.html#guide

So, we don't have rest API which directly mapped to ChallengeQuestionManagementAdminService.setUserChallengeAnswers()..

@IsuraD Please correct me otherwise.

**Comment by IsuraD** [comment]
Yes. Currently, we don't have a REST API to set user/tenant challenge questions. Can use **ChallengeQuestionManagementAdminService** soap service.
