### ISSUE TITLE
wso2-5.1.0-beta missing column 'is_dumb_mode'

### ISSUE THREAD

**Issue by filip-vt** [wso2/product-is#305]
Just installed the beta with postgres and apparently I get this error when creating/editing Service Providers.

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "is_dumb_mode" does not exist
  Position: 39
```

I greped the included sql schemes (including the rest of the DB backends) and there is no mention of column "is_dumb_mode". I can't deduct immediately which table is missing this column.

**Comment by darshanasbg** [comment]
The exact column name is, "IS_DUMB_MODE" which is a column in "SP_APP" table.. Case difference might resulted no references when you grep the schema, since grep is case sensitive by default.

As per [1], this column already there in the beta pack, so you might deployed the beta pack over an existing database which had older schema.

Hope you solved the issue by using the latest version available.

[1] https://github.com/wso2-attic/carbon-identity/commit/e8643107d8c0b0f3c42eebd220f3c28893752c1b
