### ISSUE TITLE
Security threats from the current conditional authentication based on HTTP Cookies

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3054]
By setting a test cookie, can skip the multi level authentication which will be causing security threats where the strong authentication can be overridden by a hacker. This should be improved to validate the test cookie from IS level, before skipping the multi steps.

**Comment by pulasthi7** [comment]
Hi @IndunilRathnayake ,

The example is provided mainly to demonstrate the ability to set the cookies by script. In production, this cookie must be signed or encrypted so that the cookie can't be tampered.

Anyway, since we have an utility function to sign/encrypt cookies, we need to update the example and QSG with that function, so that users can directly re-use it.

@NipuniBhagya , Can you please update the QSG now with above?
@sherenewso2 , @ShirazAzad : Can you please update the docs?

**Comment by madurangasiriwardena** [comment]
Since the New-Device-Based Authentication Template signs the cookie and validates it, and [doc](https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference) has information about signing and encryption, resolving this issue.
