### ISSUE TITLE
Too many SQL queries getting executed in tenant creation

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#3074]
There are around 12500 SQL queries getting executed when we create a tenant in IS-5.3.0 default pack. But in IS-5.2.0, it was around 1660 SQLs. 

Almost all additional queries has been done against following tables.
IDN_CLAIM_MAPPING	
IDN_CLAIM_MAPPED_ATTRIBUTE	
IDN_CLAIM_DIALECT	
IDN_CLAIM_PROPERTY	
IDN_CLAIM

**Comment by malithie** [comment]
This issue occurs as below happens whenever a claim gets added in order to load claims back to the cache. 

- Add claim, attribute mappings and attribute properties to the database
- Get all claims from the database
- For each claim a database call is initiated to retrieve attribute mappings and another call is initiated to retrieve metadata properties

Above gets significant in tenant creation flow as all claims get added to the database upon tenant initialization.

**Comment by malithie** [comment]
Added https://github.com/wso2/product-is/issues/3081 to identify and improve the flow when adding a claim.
With this respective issue we will focus only on improving the flow while adding all claims in bulk mode with tenant creation.
