### ISSUE TITLE
Regular expressions for claims are not getting validated for the values entered in missing claim page

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3229]

**Comment by emswbandara** [comment]
The fix for this is complex as we need to invoke multiple admin services from the UI to handle the following scenarios.

- User has configured missing claims using local claim dialect
- User has configured custom claim mappings.
- User has configured SP Claim dialect.

As a proper fix for this we need to expose a back-end OSGI service and validate this during post authentication handler.

**Comment by emswbandara** [comment]
reducing severity due to above technical limitation.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
