### ISSUE TITLE
[Doc] Some configuration changes has been missed in migration documentation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3481]
The following points has been missed in \[1] under 5.0.0 to 5.1.0 migration configuration changes. But it has been documented in 5.0.0 to 5.1.0 migration documentation \[2]

`Configure the <NEW_IS_HOME>/repository/conf/identity/identity.xml file with the same configurations made in the <OLD_IS_HOME>/repository/conf/identity.xml file.`

`Configure the <NEW_IS_HOME>/repository/conf/identity/provisioning-config.xml file with the same configurations made in the <OLD_IS_HOME>/repository/conf/provisioning-config.xml.`

`Configure the <NEW_IS_HOME>/repository/conf/identity/identity-­mgt.properties file with the same configurations made in the <OLD_IS_HOME>/repository/conf/security/identity-mgt.properties file. `

\[1] https://docs.wso2.com/display/IS550/Upgrading+From+an+Older+Version+of+WSO2+IS
\[2] https://docs.wso2.com/display/IS510/Upgrading+from+the+Previous+Release

**Comment by sherenewso2** [comment]
Added a note in [1] and the "Tip" mentioning to see the migration guide [2] for more information was changed to "Recommended" because it is also better for users who are migrating from older versions to also check the relevant migration guide to ensure nothing was missed related to new config files or other changes. 

[1] https://docs.wso2.com/display/IS550/Upgrading+From+an+Older+Version+of+WSO2+IS
[2] https://docs.wso2.com/display/IS510/Upgrading+from+the+Previous+Release
