### ISSUE TITLE
Redirected to an error page when user keeps the login page open for a long time and then tries to login

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#4000]
**Description**
When the login page is opened for a long time and then the user tries to login giving the username and password, the authentication flow will fail while directing to an error page with "INVALID REQUEST".
This error occurs only when the login page is opened for more than the session cache timeout time and a session data clean up task is run during that time.

**Tested environment**
WSO2IS version 5.4.1

**Steps to reproduce**
To reproduce the error frequently,

- Reduce the time of session cleanup period in repository/conf/identity/identity.xml file
- Disable cache by changing the configurations in repository/conf/identity/identity.xml file

Steps :

1. Create a service provider with OAuth/OpenID Connect Configuration in WSO2 IS.
2. Enter the URL given below and replace the client id and the redirect url relevant to the app registered in IS to load the login page
>  https://localhost:9443/oauth2/authorize?client_id=_<client_id>_&grant_type=implicit&response_type=token&scope=SelfManage&redirect_uri=_<redirect_url>_&prompt=login
3. Wait for a session clean up task to happen
4. Try to login using the credentials
5. "INVALID REQUEST" page will be shown.

**Comment by mefarazath** [comment]
This has been solved with https://github.com/wso2/product-is/issues/3202

Previously the issue was that when an OAuth2 login request was sent and when the user is prompted the login page, there were several cache entries added to IDN_AUTH_SESSION_STORE table up to that point.

As an example,
```
48fac047-a12e-4454-8147-a2feabef0779      OAuthSessionDataCache	STORE
48fac047-a12e-4454-8147-a2feabef0779	AuthenticationRequestCache	STORE
48fac047-a12e-4454-8147-a2feabef0779	AuthenticationRequestCache	DELETE
e47d0f16-0ebd-4e61-aefb-75472ea89b10	AuthenticationContextCache	STORE
```
At this instant if the Session Clean up task ran, it would delete all three entries with id ''48fac047-a12e-4454-8147-a2feabef0779". Thereafter even if the user is authenticated successfully the overall request would fail since context data required by OAuth2 component in entry is deleted.
`48fac047-a12e-4454-8147-a2feabef0779      OAuthSessionDataCache	STORE
`
This deletion is a bug in the session data logic.

The improvements done with https://github.com/wso2/product-is/issues/3202 when a temporary cache entry is deleted it will only delete the entry belonging to the same cache type (not just blindly deleted by the cache entry id). So for the above example when the improved session cleanup task runs it will only delete the entry 

`48fac047-a12e-4454-8147-a2feabef0779	AuthenticationRequestCache	STORE
`
This would allow the request to complete even if the session data cleanup run in the middle of the request (ie. when user is waiting on the login page)
