### ISSUE TITLE
Holding server start with configuration errors detected

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#4020]
In Identity server we have two types of files.
1. Server configurations (identity.xml, carbon.xml etc)
2. Artifacts (File based SP configurations (sso-idp-config.xml), IDP configurations etc. )

If there is a issue with server configurations better to exist from the process. At the same time, there should be meaningful error message at the startup mentioning which functions will not work properly when there is error in type 2 of config files.

**Comment by hauntingEcho** [comment]
While this approach makes sense in general, I disagree that the specific items you mentioned are artifacts rather than server configurations.  Specifically, sso-idp-config.xml is read at server boot time only rather than being hotpluggable.

For example, the contents of `repository/deployment/server/webapps`, which are loaded as-needed and reloaded when changed on the filesystem and are isolated from one another, I would consider to be artifacts which should not bring down the server as a whole.

It *may* also make sense to move the stuff from sso-idp-config.xml into the files in `repository/conf/identity/service-providers/` and have those be hot-pluggable, but I'd argue that's a separate issue (or two).

**Comment by isharak** [comment]
I also agree with the point we need to move the sso-idp-config.xml file in to the service-providers/ folder location which more intuitive to the users

If we think how these configs get deployed I agree that we can consider this as a server configurations since we have to restart the server if we need to change.

When it comes to sso-idp-config.xml possibility of adding invalid configuration into these files is rare since it will properly test in each environment along with relevant service providers application. Even in the server startup we can validate the syntax but still there is a chance for invalid configurations (Eg: invalid issuer, AssertionConsumerServiceURLs ) which will block the actual execution.
How this handle at the moment is it will log the error so we need to monitor the error log and forcefully shout down the server and fix it. If someone is not using and mistakenly configured that he still possible to use the server without fixing the configs. With the proposed approach it will block the server start up so no need to wait till you see the error log or till you test the functionality.
With the improvement I think it will slightly improve the usability so I think we can consider this as a future improvement.

**Comment by ruwanta** [comment]
I am not agreement with stopping the server boot-up if "sso-idp-config.xml" file contains errors. Let me explain why.

Some of deployments does not need any "SSO" or "IdP" Configurations at all. The use cases that deployment can work perfectly well with any error on "sso-idp-config.xml" irrespective of the error is due to syntax error or configuration parameter being invalid.
So stoping the server functionality altogether when a sub-system is configured wrong, seems unproductive for people who do not wish to use that subsystem

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
