### ISSUE TITLE
New datasource connections are getting created when listing users/roles in management console.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#4306]
When listing users/roles in management console when there is a secondary JDBC userstore in a tenant, new datasorce connections are getting created with the secondary JDBC userstore database.

**Affected Products**

APIM-2.5.0 
IS-5.6.0

**Comment by GDRDABARERA** [comment]
This issue can not be resolved because of the bad architectural design. Hence removing this Count implementation feature is the solution.

In the secondary user-store advanced configurations, remove the count Implementation class.

Then the count Retriever feature will be disabled. Hence Unwanted datasource connections will be not created.

**Comment by GDRDABARERA** [comment]
The solution of this issue will be a doc jira, we have to deprecate this  count Retriever feature in the documentation[1] as this has long-running connection leaks.

[1] - https://docs.wso2.com/display/IS570/Counting+users+and+roles+using+Management+Console+and+Admin+Services

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
