### ISSUE TITLE
Error While Creating a New Tenant Using a Deleted Tenant Name.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4386]
**Description:**
Getting an error when trying to create a tenant with the same name as deleted one. 

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2IS-5.3.0

**Steps to reproduce:**

- Create a tenant and delete the tenant using the admin service (RemoteTenantManagerService).
- Try to recreate the tenant with the same name (domain) as the deleted one an error occurred.
- Wait for 15minutes for the cache to get invalidate and try the same. Still, an error occurred.
- Try to create the tenant with the same name as the deleted one after a restart, no errors occur and the tenant gets created without any issue. **Needs to get this done without restarting the server.**

**Comment by malithie** [comment]
@Kavindu-Dodan , we later fixed the service to address tenant deletion (in a limited manner) and addressed this case.
Could you please point the fix and get this resolved

**Comment by Kavindu-Dodan** [comment]
This issue was caused due to a cache entry and persisted configurations that won't get removed through mentioned admin service.

**RemoteTenantManagerService** only focuses on clearing up cache entries and database entry on the tenant. But there is another cache entry that won't get cleared through this service. So you must use **TenantMgtAdminService** to delete a tenant. But this was never used hence there were several unattended bugs. 

Following PRs were created to fix these bugs. They further include proper clearing of cache and removal of configurations. 
- https://github.com/wso2/carbon-kernel/pull/1923
- https://github.com/wso2/carbon-multitenancy/pull/149

**Comment by malithie** [comment]
Use of RemoteTenantManagerService should be discouraged then.
@Kavindu-Dodan 
Shall we create another issue to track the doc impact and close this one

**Comment by Kavindu-Dodan** [comment]
Created the issue https://github.com/wso2/carbon-kernel/issues/1967. 

I think we must remove/deprecate **RemoteTenantManagerService** altogether.
