### ISSUE TITLE
Server do not start when the DBMS is PostgreSQL. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#4500]
Due to missing tables related to the Configuration Store feature [1], the server starts with an exception in the startup logs when the underlying DBMS is PostgreSQL.

[1] https://github.com/wso2/product-is/issues/4499

**Comment by tharindu-bandara** [comment]
Please find the [issue](https://github.com/wso2/product-is/issues/4526) tracking the root cause for this. A detailed description can also be found there.

**Comment by emswbandara** [comment]
cannot be reproduced in the latest pack - 5.8.0-alpha4-Snapshot

**Comment by mefarazath** [comment]
But this is reproducible on a WUM updated pack of IS 5.7.0, so what's our solution?
Shouldn't we fix to only activate the feature if relevant tables are present?

**Comment by malithie** [comment]
@emswbandara , we need to create a task to track that redundant feature enabling disabling blocks should be cleaned up when all table schemas gets  introduced for each database type.

**Comment by emswbandara** [comment]
@malithie I have already added this concern in [here](https://github.com/wso2/product-is/issues/4303)

**Comment by mefarazath** [comment]
There is a bit of confusion related to this issue and information is scattered in multiple git issues.

What's the root cause of this behaviour?
How was this fixed, was it done by having appropriate data source configurations or code fix?

@tharindu-bandara @emswbandara appreciate if you could explain?

**Comment by emswbandara** [comment]
@mefarazath , currently the schemas related to all database types have not been added for this feature. Therefore this issue can be reproduced if the relevant table/column is not available. However it is intermittent since the connection that is used to check the column existence will have uncommitted changes when there's a SQLException (due to table unavailability), if another code uses this same connection from the connection pool, to query the database this exception can be thrown. Therefore as a fix for this we have introduced a config to enable/disable this feature.

**Comment by mefarazath** [comment]
@emswbandara Thanks you for the explanation. Can you point me to the PR which introduced this fix?

Also if the error occurs due to uncommitted connections, will having <CommitOnReturn> property in datasource configurations be sufficient?

**Comment by tharindu-bandara** [comment]
@mefarazath Having the <commitOnReturn> enabled in the data source configurations resolves this issue.
