### ISSUE TITLE
Support OIDC back channel logout

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4590]
Spec: https://openid.net/specs/openid-connect-backchannel-1_0.html

**Comment by sagara-gunathunga** [comment]
Following feature documentation [1] is not in a production ready state, hence I'm reopening this issue. Please find some of main issues below. 

 About Doc
============
"OpenID Connect back-channel logout feature enables logging out users from a client application/relying party (RP) by directly communicating the logout requests between the RP and authorization server/OpenID Provider (OP). This approach is more reliable as it does not require communicating the logout requests through a user agent/browser and maintain active RP browser sessions for the communication to succeed. "

IMO above description is not enough to introduce the feature, we should cover following points ...

- Start with mentioning available logout mechanisms supported in OIDC.   

- it's not clear for readers what does this mean as "directly communicating ", spend few lines to explain the concept with clear examples. 

- Explain why we believe this method is more reliable 

-  "does not require communicating the logout requests through a user agent/browser and maintain active RP browser sessions " then how it track sessions with IDP, explain the underline logic. 

- Include possible use cases where back-channel logout is much preferable than front-channel logout. 

- Add a note saying front channel logout feature is not yet supported but it's a prioritized feature of the product roadmap.  

 About Sample
============
 Use of OAuth2 Playground sample to "demonstrate" a logout feature is way too odd for me, we can justify the decision in case we don't have proper samples but here we have 2 well designed samples which are ideal to demonstrate propagation of logout messages.  

- Replicating same app and asking to think them as separate apps is not a good demonstration strategy specially when we have proper samples in place. 

- Why somebody has to install/deal-with  Maven and Git in order to try IS samples ? we have passed these points during last year. 

- Why somebody has to install and deal-with Tomcat, again  we have passed these points during last year.

- This sample instructions contains more then 20 steps but if we use correct samples we can cut down around 10 steps, that is a great UX improvement.  


[1] - https://docs.wso2.com/display/IS580/OpenID+Connect+Back-Channel+Logout

**Comment by malithie** [comment]
Doc is addressed with [1]
Reported [2] to get new samples fixed

Resolving the feature as it is completed with further improvements being tracked

[1] https://github.com/wso2/product-is/issues/4650
[2] https://github.com/wso2/product-is/issues/5248
