### ISSUE TITLE
identity-inbound-auth-cas: SP: static service url vs dynamic service url

### ISSUE THREAD

**Issue by malnajdi** [wso2/product-is#4610]
**[environment]**
server: Linux Debian Stretch
wso2is version: 5.3.0 to 5.7.0
identity-inbound-auth-cas version: 2.0.2

**[problem-description]**
The current implementation will show you the login page if you have accessed the same or anything extra to the URL defined in the SP CAS Configuration service URL which is good but, If you try to login with anything that is extra than the URL defined in the SP CAS Configuration service URL it will give you 500 error

**[current-working-example]**
1. I defined https://[application-server]/login/ as Service URL
2. GET request to https://[application-server]/login/
3. It will result in redirecting [302] to GET https://[wso2is-server]/identity/cas/login?service?=https://[application-server]/login/
4. show login page
5. login and everything works fine

**[example-of-the-issue]**
1. I defined https://[application-server]/login/ as Service URL
2. GET request to https://[application-server]/login/?next=https://[application-server]/user-list/
3. It will result in redirecting [302] to GET https://[wso2is-server]/identity/cas/login?service?=https://[application-server]/login/?next=https://[application-server]/user-list/
4. show login page
5. login and 500 error

**[reproduce-problem]**
1. I copied the identity-inbound-auth-cas to the folder _**<IS_HOME>/repository/components/dropins**_
2. I ran the wso2is server
3. I defined new service provider named: cas-client-webapp
4. I opened the CAS Configuration under Inbound Authentication Configuration
5. I set the Service URL as **https://[server-address]/cas-client-webapp/**
6. I open a browser and access the url **https://[application-server-address]/cas-client-webapp/?next=https://[application-server-address]/user-list/**
7. login
8. 500 error will be shown

**[what-solution-expected]**
i should be able to define a base Service URL and it would be valid for any thing that comes after this url.
If my service url is https://wso2.com, than me accessing https://wso2.com/login/ or https://wso2.com/login/?next=/home/ or https://wso2.com/users/ should validate correctly and when i am presented with the login form, I should see the query parameter named sp=<sp-i-defined>  not sp=default.

Thanks

**Comment by mohdnajdy** [comment]
@thanujalk any update regarding this ?

**Comment by mohdnajdy** [comment]
@malithie is there a real due date for 5.8.0-GA milestone ?

**Comment by ten2net** [comment]
Looking forward to the problem being repaired as soon as possible

**Comment by malithie** [comment]
@mohdnajdy 
5.8.0 RC 2 is already released and GA will be pushed by early next week. 
I'm sorry to convey that this issue has not been addressed with 5.8.0 version.
We will have a look and get back to you on this.

**Comment by mohdnajdy** [comment]
@malithie that is very sad. I was waiting for this for months. I was told by @thanujalk that it will be with the  5.8.0-GA milestone i guess it was a false promise. anyway. Can you at least let us know of a work round ? this is causing some issues in my environment.

**Comment by mohdnajdy** [comment]
@thanujalk is there any workaround that i can do till this fix is in place ?

**Comment by janakamarasena** [comment]
Hi @mohdnajdy,

This[1] is a code level workaround for your issue. I have done the modifications on top of identity-inbound-auth-cas version: 2.0.2[2]. Try it out and let me know.


[1] - https://github.com/janakamarasena/identity-inbound-auth-cas/commit/9bffd044fedc0ce29798a08148c592f35b06bc96
[2] - https://github.com/janakamarasena/identity-inbound-auth-cas/tree/w-fix-4610

**Comment by mohdnajdy** [comment]
Hello, @janakamarasena Thanks a lot for your response and trying out to help in this matter.
If you can see i did a similar fix 3 months ago https://github.com/mohdnajdy/identity-inbound-auth-cas/blob/master/components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/processor/SSOLoginProcessor.java

My problem with this fix is the service provider it's picking seems to be **"Default"** 
an example of the url **"type=cas&sp=default&isSaaSApp=true&authenticators=BasicAuthenticator:LOCAL"**

I just want to confirm from you if for example i changed the Subject Claim URI: to use email instead of the username will it work for that SP or it will ignore it since its **Default** service provider.

**Comment by mohdnajdy** [comment]
@janakamarasena i will give an example after i tested some short coming of the solution. 

This solution allows me to make it possible to authenticate successfully. But I also want to keep the advantages of the other features of **Local & Outbound Authentication Configuration** an example of this if i set Authentication Type as advanced and i put my own steps it will not work due to the fact it did not pick the right SP it picked **default** as i stated earlier in the comment above. I would like to have a working work-around where i can utilize the same features. other wise my current setup will break.

Thanks and i hope i get some response.

**Comment by janakamarasena** [comment]
@mohdnajdy for this you will need to do some minor changes to the [carbon-identity-framework](https://github.com/wso2/carbon-identity-framework) as well. You can find the needed changes here[1]. I have done the changes to the master branch, you can checkout the relevant version tag and do the changes. Please note that this is a quick fix and very well may not be the optimum solution. This fix along with the one I gave you previously[2] should be enough. Try it out and let me know.

[1] - https://github.com/janakamarasena/carbon-identity-framework/commit/acd1ec9e7ba3cf5cb9f720580610dcc9a0ca007e
[2] - https://github.com/janakamarasena/identity-inbound-auth-cas/commit/b3dc8f510752c6613b1e322a4594d39610ee56a4

**Comment by mohdnajdy** [comment]
@janakamarasena Thanks a lot for the reply, I would like to request your assistant on where should i put the carbon-identity-framework jar after i build it? will it be in dropin ?

**Comment by janakamarasena** [comment]
@mohdnajdy the jar file will be in plugins(IS-HOME/repository/components/plugins). 
The relevant jar is **org.wso2.carbon.identity.application.authentication.framework**-\<version>.jar (ex:org.wso2.carbon.identity.application.authentication.framework-5.12.387.jar) you will have to pick this relevant version tag from the [carbon-identity-framework](https://github.com/wso2/carbon-identity-framework) and do the fix on that. What is the IS version you are using atm?

**Comment by mohdnajdy** [comment]
@janakamarasena 5.7.0

**Comment by janakamarasena** [comment]
@mohdnajdy for IS 5.7.0 you have to do the workaround in carbon-identity-framework [v5.12.153](https://github.com/wso2/carbon-identity-framework/tree/v5.12.153). More specifically you have to update this file[1].

[1] - https://github.com/wso2/carbon-identity-framework/blob/v5.12.153/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/AbstractRequestCoordinator.java

**Comment by mohdnajdy** [comment]
@janakamarasena Thanks a lot i have build the project and did everything exactly as you mentioned and everything works now. Thanks a lot. 

Question: When do you think an elegant solution will be in place for this ?

**Comment by janakamarasena** [comment]
@mohdnajdy Glad to hear that everything is working.

We are planning to have this capability in the product with the 5.9.0 release, which will be around early September this year.

**Comment by janakamarasena** [comment]
While working on the improvement we came across a few complexities. Currently, we are using the service URL to resolve the service provider[1]. When we make it dynamic we will have to introduce a new mechanism to resolve the service provider. 
Due to this reason we were not able to release this feature with IS590. We are looking into the best way we can achieve this.  And plan to release this feature in an upcoming release.

[1] - https://github.com/wso2/carbon-identity-framework/blob/v5.14.139/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/AbstractRequestCoordinator.java#L63

**Comment by mohdnajdy** [comment]
@janakamarasena is there any assurance for it to be release on 5.10 ? this was supposed to be in 5.8.

**Comment by ajanthan** [comment]
I am facing this issue with IS 5.9.0. I've patched the cas connector with code from @janakamarasena's fork. Still it did not work. Any help?

**Comment by malnajdi** [comment]
Hey, it's been a long time, Will this issue see the light with 5.11.0 ? Thanks.
