### ISSUE TITLE
WSO2 IS 5.7 openid well know document issue

### ISSUE THREAD

**Issue by kratosmat** [wso2/product-is#4671]
Hi all,
I am experiencing this issue, I have a is 5.7 (as km) behind a haproxy with proxy port (443) and I am not able to retrieve the well-known resource.

I have tried to put the UseEntityIdAsIssuerInOidcDiscovery property into identity.xml but it continue not to working.

So, in order to reproduce the issue:

- install an haproxy as reverse proxy with a frontend on 443 and backend to is on 9443 port
- install wso2 is as km (version 5.7) without offset
- configure the proxy port on catalina
- configure the host name of haproxy on carbon.xml
- I have added the UseEntityIdAsIssuerInOidcDiscovery property in identity.xml as suggested on the PR #2085 (https://github.com/wso2/carbon-identity-framework/pull/2085)

However I continue to have the same error when I try to retrieve the URL https://<my-hostname>/oauth2/oidcdiscovery/.well-known/openid-configuration

This issue is related to the number 4188: https://github.com/wso2/product-is/issues/4188

Thanks a lot,
Matteo.

**Comment by tharindu-bandara** [comment]
Thank you @kratosmat for creating the issue. I am working on this will give you an update soon.

**Comment by tharindu-bandara** [comment]
Hi @ecky-l @davebaol @gorkma ,

Let me explain why these issues are caused. I will provide you with a high-level abstract of the issue first, and then direct you to some reported issues because they already do contain detailed explanations.
#### OpenID connect discovery not working in 5.7.0 with standard SSL port 443
This is caused due to a request validation issue at the OIDC discovery endpoint. You can find more details on this from the [reported issue](https://github.com/wso2/product-is/issues/4276)[1]. 
#### Issuer does not reflect multi-tenant scenario
There is an identified inconsistency in the OIDC issuer location value in the Identity Server. Ideally, the resident IDP entity ID value should be honored for the OIDC issuer location. Please refer to the [reported issue](https://github.com/wso2/product-is/issues/4277)[2] for additional details. This issue is a byproduct of this inconsistency.

_Both of the above issues have been fixed for the Identity Server and available as a WSO2 IS 5.7 WUM update for the paid subscriptions. These fixes are also merged with the opensource code base and will be available in the next release of WSO2 Identity Server for non-paid usage. If you do not have a paid subscription, you can still build the [product-is](https://github.com/wso2/product-is/releases) locally and get the latest snapshot version with the above fix included._

Now I will explain the user stories for the above-raised concerns, once the mentioned fix is available. 

- [X] **OpenID connect discovery not working in 5.7.0 with standard SSL port 443** issue is fixed OOTB.
- [X] We have introduced a config option,` <UseEntityIdAsIssuerInOidcDiscovery>`. Once this is enabled(which is enabled by default in the snapshot and in the next release) per-tenant Resident IDP entity id value is honored as the OIDC issuer, which is applicable system-wide, including tenants. Once enabled, the proper resident IDP entity ID values for tenants need to be configured(for the example tenant case you have mentioned above, resident IDP entity ID value should be `https://wso2is.local/t/tenant1.local/oauth2/oidcdiscovery`). Now the discovery endpoint responds with the pre-configured, proper OIDC issuer location value reflecting the tenant.

The reason behind having the ` <UseEntityIdAsIssuerInOidcDiscovery>` config option is to preserve the backward compatibility.

Usage of the ` <UseEntityIdAsIssuerInOidcDiscovery>` config option with an IS pack containing the mentioned fix, is also explained in the [WSO2 document](https://docs.wso2.com/display/IS570/OpenID+Connect+Discovery#OpenIDConnectDiscovery-ConfiguringtheOpenIDProviderIssuerlocation) as well[3].

Feel free to try it out and see whether your concerns are resolved.

[1] https://github.com/wso2/product-is/issues/4276
[2] https://github.com/wso2/product-is/issues/4277
[3] https://docs.wso2.com/display/IS570/OpenID+Connect+Discovery#OpenIDConnectDiscovery-ConfiguringtheOpenIDProviderIssuerlocation

**Comment by maghibus** [comment]
I have the same problem, sir

**Comment by tharindu-bandara** [comment]
@maghibus Please have a look at https://github.com/wso2/product-is/issues/4671#issuecomment-474463819.

**Comment by kratosmat** [comment]
Hi tharindu,
how I can find the commit that solves these issues?

Thanks a lot,
Matteo.

**Comment by tharindu-bandara** [comment]
Hi @kratosmat,

No worries!.

There are two PRs for this. 

1. [Fix the issues](https://github.com/wso2-support/identity-inbound-auth-oauth/pull/318)[1]
2. [Add `<UseEntityIdAsIssuerInOidcDiscovery>` to the identity.xml](https://github.com/wso2/carbon-identity-framework/pull/2085)[2].

You can use the first PR and add the config option manually to the identity.xml as well. 

Merge commits for above are,
1. https://github.com/wso2-extensions/identity-inbound-auth-oauth/commit/3acd90b8b45878de866c20fc1e1f2adc27c2bb48
2. https://github.com/wso2/carbon-identity-framework/commit/2e8071c44fcf588027de189b1319c00fe67c173a

I Hope this would get your issue resolved.

[1] https://github.com/wso2-support/identity-inbound-auth-oauth/pull/318
[2] https://github.com/wso2-support/carbon-identity-framework/pull/458

Thanks,
Tharindu.

**Comment by kratosmat** [comment]
Hi all,
after trying to compile the source code with bad results, I have used a trial subscription to download all updates of wso2is as km 5.7, but the bug is not solved, I have the same error.

There is anyone that has solved this blocking issue?

Thanks a lot,
Matteo.

**Comment by tharindu-bandara** [comment]
Hi @kratosmat,

The fix for this issue is released with the update number, 3794. Shall we verify whether this includes in your distribution?.

 Since you have the trial subscription, I will list how to get the latest updated product using [WSO2 Update Manager](https://wso2.com/updates/wum) first.

Execute below commands after installing the [WSO2 Update Manager](https://wso2.com/updates/wum), 

1. `wum init`
2. `wum add wso2is-km-5.7.0`
3. `wum update wso2is-km-5.7.0`

Once the update process is done, it will show the location of the updated product. Extract this updated product and go to the `<Extracted-Folder>/wso2is-km-5.7.0/updates/wum`. 

Open the file you find there. Check whether the update `3794` is listed there under the `installed-updates:`.

Thanks and regards,
Tharindu.

**Comment by kratosmat** [comment]
Hi Tharindu,
it was my fault, I was not using the distrubution under full directory.
Now it seems ok.
Thanks a lot,
Matteo.



Matteo Cusmai

**Comment by tharindu-bandara** [comment]
Hi Matteo,

Awesome! 

Let me know if anything else comes up.

Thanks and Regards,
Tharindu

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
