### ISSUE TITLE
Claims not received in user info for the access token, id token in response, and id token for the code,  when using code id_token token of OIDC hybrid flow

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4758]
**Environment:**
DB: DB2
JDK: Java 8

**Steps to reproduce:**
1. Create a tenant
2. Create a user in that tenant
3. Update first name -> http://wso2.org/claims/givenname, last name -> http://wso2.org/claims/lastname, email -> http://wso2.org/claims/emailaddress claims of that user
4. Create an oauth application
5. Configure claims section as below.
![image](https://user-images.githubusercontent.com/4951983/54875755-85174b00-4e2a-11e9-8f3a-c75f1ad69335.png)
6. Make sure above claims are available for OIDC scopes as below.
given_name (mapped to http://wso2.org/claims/givenname) in openid scope
email (mapped to http://wso2.org/claims/lastname) only in email scope
family_name (mapped to http://wso2.org/claims/lastname) only in profile scope
gender (mapped to http://wso2.org/claims/gender)in openid scope
7. Initiate a request with OIDC Hybrid flow for response type **code id_token token** for below scopes and verify user infor response for the access token, id token in response and id token received for the code over a token request. Note below.

- When request initiated for **scope=openid**
**_Response of userinfo for the accss token_**
Expects given_name for openid scope but returned only sub
**_id_token in **code id_token token** authorization request_**
Expects given_name for openid scope but returned only sub
**_id_token of token request initiated for the **code** returned from **code id_token token** authorization request_**
Expects given_name for openid scope but returned only sub

- When request initiated for **scope=openid email profile**
**_Response of userinfo for the accss token_**
Expects given_name, family_name, email for and returned all
**_id_token in **code id_token token** authorization request_**
Expects given_name, family_name, email, but returned only sub
**_id_token of token request initiated for the **code** returned from **code id_token token** authorization request_**
Expects given_name, family_name, email, but returned only sub

**Comment by nilasini** [comment]
The above issue has since the requested claims had been selected after taking first access token. According to the consent management behaviour if the consents had been created for one user then until he revoke the consent the newly requested claims won't get asked during the consent page hence the newly requested claims won't get added to the user until the consent revocation happen. There was already an issue reported for this consent management behaviour. Please refer \[1] for more details.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227
