### ISSUE TITLE
Upgrade WSO2 IS tomcat version to 8+

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4974]
when we do the following to a webapp in WSO2 IS
```
cp wso2is-5.6.0/repository/deployment/server/webapps/authenticationendpoint.war .
echo "test" > example.txt
zip -u authenticationendpoint.war example.txt
cp authenticationendpoint.war wso2is-5.6.0/repository/deployment/server/webapps/
```
If we restart the server the contents of `wso2is-5.6.0/repository/deployment/server/webapps/authenticationendpoint/` are unchanged

We can resolve this issue by upgrading tomcat version to 8+ in wso2 IS

**Comment by hauntingEcho** [comment]
for clarity on the impact - currently there is no single automated deployment mechanism which can work for all WUM updates, once the overall artifact has been correctly configured in chef/ansible/puppet/etc infrastructure:
* stopping the server before deployment fails to deploy updated WARs
** deployment code can work around this by deleting all exploded WARs.  However, this will not work when new WARs are added (e.g. when named by version number)
* not stopping the server before deployment fails due to other config files

**Comment by senthalan** [comment]
Currently, we are planning to upgrade to tomcat 9

**Comment by senthalan** [comment]
With this https://github.com/wso2/carbon-kernel/pull/2214 the tomcat version of the products is upgraded to Tomcat 9.

The 5.9.0-alpha packs run with the tomcat 9
