### ISSUE TITLE
No audit log for account lock event

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#4991]
No audit log for account lock event. All we have is an audit log saying claim is updated. Event that doesn't say what is the claim and whether the claim was updated to locked or unlocked.

This is only one example I came across. But I am sure WSO2 Identity Server is lacking this type of important audit logs which we have to fix.

**Comment by nilasini** [comment]
With the fix for the issue \[1] we have introduced a new listener and property for audit logging the preferred claims. If we enable that improvement then we could log the account lock claim. Doc issue had been created to track the doc issue \[2].

Further to find out all the important audit logs created a new issue \[3].

Since the issue for account locking is fixed closing the issue.

\[1] https://github.com/wso2/product-is/issues/4367
\[2] https://github.com/wso2/product-is/issues/5036
\[3] https://github.com/wso2/product-is/issues/5037
