### ISSUE TITLE
Authenticate to provision a user with OAuth with sufficient privileges fails

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5078]
**Steps to reproduce**

1. Add a secondary JDBC userstore - e.g. TEST
2. Create a new role in TEST. e.g. TEST/role1 and do not assign any permissions.
3. Create a new user in TEST domain and assign the above role to him. e.g. TEST/user1

4. Create a OAuth service provider and obtain an access token for TEST/user1. 
5. Now try to provision a new user using SCIM2 by authorizing with the above access token.
`curl -v -k -H "Authorization:Bearer 9eb61d5e-4df6-383d-b2b0-47a153bc9c16" --data '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"vindula4","password":"admin","emails":[{"primary":true,"value":"vindula_home.com","type":"home"},{"value":"vindula_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

This fails with 403 forbidden error as expected.

6. Next update the TEST/role1 with following permission.

`/permission/admin/manage/identity/usermgt/create`

7. Now obtain a new access token for the same user.
8. Now if we try to provision a new user using SCIM2 by authorizing with this new access token, it is failing with 403 unauthorized error even though required permission is assigned to the role.

 in user.core debug logs we can see the following

`[2019-04-17 16:23:36,155] DEBUG {org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager} -  Authorization cache hit. TEST/user1 user is not Authorized to perform ui.execute on /permission/admin/manage/identity/usermgt/create`

**Comment by malithie** [comment]
Changing the severity for further review

**Comment by IsurangaPerera** [comment]
Here we have authentication flow and authorization flow. Token validation service is used at authentication and username is set by the validator. However, when "Use user store domain in local subject identifier" is not enabled in **Local & Outbound Authentication Configuration** usernames of secondary user-store users are set without the domain parameter.
Since the user realm is configured depending on the tenant name when authorizing secondary user store users at Authorization Valve suffering from a caching issue which resulted in permission update ignorance.
This issue is not affected to tenant users as the tenant is explicitly appended to the username at the time of authentication.

This issue can be overcome by enabling "Use user store domain in local subject identifier" in **Local & Outbound Authentication Configuration**

**Comment by malithie** [comment]
With the way presently this is designed we have a mechanism to overcome this respective problem as mentioned by @IsurangaPerera 
Yet, the design of this handler is conceptually wrong. Even here the access token is used to authenticate the user.
IMO, to keep the present design on, we can call user info endpoint and get user realm and proceed with present design rather than depending on the subject returned from the introspection endpoint.
Or the handler should be designed under the authorization aspect.
@IsurangaPerera , can you please create a separate issue to address this

**Comment by malithie** [comment]
We need to document the fact that to get for the respective service provider, user store domain in subject identifier needs to be enabled.
@IsurangaPerera , can you please create a doc issue to track this

**Comment by malithie** [comment]
Further noted that this happens when below config in identity.xml is set to 'true'.
`<BuildSubjectIdentifierFromSPConfig>true</BuildSubjectIdentifierFromSPConfig>`

There is a problem on identifying the user realm information with this config
From the authorization rest valve perspective we can of course ask to enable "Use user store domain in local subject identifier" that @IsurangaPerera mentioned above.
Yet, there is a concern on how user realm information can be relayed from introspection.
Requirements, concerns around this needs to be thought through .

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
