### ISSUE TITLE
incorrect status in DB tables when User Store Delete in Authorization Code flows 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#5227]
Suggested Labels
Affected : 5.8.0-Snapshot 6
Severity: Major
Priority: Highest
DB - Mysql 5.7 and oracle
Component: USER STORE DELETE
Type-Bug

Steps to reproduce
Create a user in the secondary user store
Obtain an authorization code and an Access token using Authorization code grant
Delete User store

Expected Behavior
STATE column value should change to invalidated in IDN_OAUTH2_AUTHORIZATION_CODE

Actual behavior
STATE column value in IDN_OAUTH2_AUTHORIZATION_CODE table still shows the status as Active

**Comment by janakamarasena** [comment]
This [query](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/SQLQueries.java#L89)[1] is called to make the active authz codes inactive. But since it expects the tokenId which is not available(only available when a token is generated from an authz code ) the query will not affect any active authz codes.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/SQLQueries.java#L89
