### ISSUE TITLE
Add IDN_AUTH_USER_SESSION_MAPPING data cleanup to session cleanup scripts

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5287]
Currently, the data cleanup of IDN_AUTH_USER_SESSION_MAPPING table is handled within the code and is done when the session clean up task is running. We need to add the cleanup of this table's data to the session cleanup scripts as well for when the session clean up task is disabled and the cleanup scripts are used.

**Comment by IsuraD** [comment]
@DinikaSen is working on this.

**Comment by DinikaSen** [comment]
ack

**Comment by rksk** [comment]
Still, it does not cleanups up the records from IDN_AUTH_USER_SESSION_MAPPING for the following scenario since we have added IDN_AUTH_USER_SESSION_MAPPING cleanup into the session data cleanup section only.

- A user logs in and logs out
- So we have two entries in the IDN_AUTH_SESSION_STORE table for SESSION_TYPE AppAuthFrameworkSessionContextCache with STORE and DELETE operations
- The operation data cleanup section of the session cleanup stored procedure cleans up these entries from the IDN_AUTH_SESSION_STORE table
- Still, the entry in the IDN_AUTH_USER_SESSION_MAPPING table is not cleaned up 
- Because operation data cleanup has a lower timeout defined in the script than session data cleanup (12h < 14d)

To solve this issue fully, we will have to improve the session cleanup stored procedure and also clean all the stale data in the IDN_AUTH_USER_SESSION_MAPPING table as well. Because we use the data on the IDN_AUTH_USER_SESSION_MAPPING for session termination operations in events like password update. If we have stale data accumulated in the IDN_AUTH_USER_SESSION_MAPPING table, it will iterate though all of these and spend longer to complete the password change operation.

The following query can be used to delete stale data on IDN_AUTH_USER_SESSION_MAPPING table for MySQL.
```
DELETE T1
FROM IDN_AUTH_USER_SESSION_MAPPING T1
LEFT JOIN 
IDN_AUTH_SESSION_STORE T2
ON T1.SESSION_ID = T2.SESSION_ID
WHERE T2.SESSION_ID IS NULL;
```
