### ISSUE TITLE
Fix app ownership update logic in OAuthAdminService

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5323]
According to the current logic, if the app owner we are trying to update (using OAuthAdminService#updateConsumerApplication()) is an invalid one, then the ownership of the app goes to the user who calls the OAuthAdminService#updateConsumerApplication().

Instead, we should fix the logic to keep the current app owner to be the app owner if the user we are trying to update as the new app owner is an invalid user.

**Comment by IshikaGodage** [comment]
**Reproducing steps**
1.  Login to identity server
2. Setup a auth app
3. Create a user (user1)
4. Update the app using an invalid app owner. (using OAuthAdminService#updateConsumerApplication())
E.g.: The request should be authenticated using user1's credentials.
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://dto.oauth.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:updateConsumerApplication>
         
         <xsd:consumerAppDTO>
            <xsd1:applicationName>appp2</xsd1:applicationName>
            
            <xsd1:oauthConsumerKey>gq8DC8PgYYJzwFbbuM50hbQH3FYa</xsd1:oauthConsumerKey>
            
            <xsd1:oauthConsumerSecret>ksXl5pq8l9rz0Y1ltyDyLaD7qeIa</xsd1:oauthConsumerSecret>
            <xsd1:username>tyyyyy@carbon.super</xsd1:username>
         </xsd:consumerAppDTO>
      </xsd:updateConsumerApplication>
   </soapenv:Body>
</soapenv:Envelope>`

5. After getting app details (using OAuthAdminService#getOAuthApplicationDataByAppName())
E.g: Request
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:getOAuthApplicationDataByAppName>
         
         <xsd:appName>appp2</xsd:appName>
      </xsd:getOAuthApplicationDataByAppName>
   </soapenv:Body>
</soapenv:Envelope>`
E.g. Response
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:getOAuthApplicationDataByAppNameResponse xmlns:ns="http://org.apache.axis2/xsd">
         <ns:return xsi:type="ax2402:OAuthConsumerAppDTO" xmlns:ax2399="http://base.identity.carbon.wso2.org/xsd" xmlns:ax2402="http://dto.oauth.identity.carbon.wso2.org/xsd" xmlns:ax2398="http://oauth.identity.carbon.wso2.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ax2402:OAuthVersion>OAuth-2.0</ax2402:OAuthVersion>
            <ax2402:applicationAccessTokenExpiryTime>3600</ax2402:applicationAccessTokenExpiryTime>
            <ax2402:applicationName>appp2</ax2402:applicationName>
            <ax2402:backChannelLogoutUrl xsi:nil="true"/>
            <ax2402:bypassClientCredentials>false</ax2402:bypassClientCredentials>
            <ax2402:callbackUrl xsi:nil="true"/>
            <ax2402:frontchannelLogoutUrl xsi:nil="true"/>
            <ax2402:grantTypes>refresh_token urn:ietf:params:oauth:grant-type:saml2-bearer implicit password client_credentials iwa:ntlm authorization_code urn:ietf:params:oauth:grant-type:uma-ticket urn:ietf:params:oauth:grant-type:jwt-bearer</ax2402:grantTypes>
            <ax2402:idTokenEncryptionAlgorithm>null</ax2402:idTokenEncryptionAlgorithm>
            <ax2402:idTokenEncryptionEnabled>false</ax2402:idTokenEncryptionEnabled>
            <ax2402:idTokenEncryptionMethod>null</ax2402:idTokenEncryptionMethod>
            <ax2402:idTokenExpiryTime>3600</ax2402:idTokenExpiryTime>
            <ax2402:oauthConsumerKey>gq8DC8PgYYJzwFbbuM50hbQH3FYa</ax2402:oauthConsumerKey>
            <ax2402:oauthConsumerSecret>ksXl5pq8l9rz0Y1ltyDyLaD7qeIa</ax2402:oauthConsumerSecret>
            <ax2402:pkceMandatory>false</ax2402:pkceMandatory>
            <ax2402:pkceSupportPlain>false</ax2402:pkceSupportPlain>
            <ax2402:refreshTokenExpiryTime>84600</ax2402:refreshTokenExpiryTime>
            <ax2402:renewRefreshTokenEnabled>true</ax2402:renewRefreshTokenEnabled>
            <ax2402:requestObjectSignatureValidationEnabled>false</ax2402:requestObjectSignatureValidationEnabled>
            <ax2402:state xsi:nil="true"/>
            <ax2402:tokenType xsi:nil="true"/>
            <ax2402:userAccessTokenExpiryTime>3600</ax2402:userAccessTokenExpiryTime>
            <ax2402:username>user1@carbon.super</ax2402:username>
         </ns:return>
      </ns:getOAuthApplicationDataByAppNameResponse>
   </soapenv:Body>
</soapenv:Envelope>`

6. Since  **tyyyyy@carbon.super** is not a valid username, the app owner's name should be **admin@carbon.super**. However it was changed to **user1@carbon.super**
