### ISSUE TITLE
TOTP for Federated users does not work when there is no associated local user

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5360]
**Summary**
According to the current implementation, if we have federated authentication as the first step and TOTP authentication as the second step, the TOTP authenticator fails when there is no associated local user for the federated user.

**Analysis**
The TOTP authenticator tries to read the secretKey from the local userstore to check whether the user has enabled TOTP. Even if we skip that step, there is a need to store the secretKey locally to be used for the next authentication attempts.

**Suggestions**
As a solution for that, we can enable JIT provisioning. Still, JIT provisioning will not work here because provisioning is done at the end of the authentication flow and we are failing at the TOTP step.

To address the provisoning issue, we can generate and store the secretKey as a remote claim when there is no associated user in the local userstore, until the provisioning is done. So, we will be able to continue with the locally available secretKey second authentication onwards. Here, we will have to add a new "usecase" value for TOTP configs for this specific scenario.

**Comment by rksk** [comment]
Related: https://github.com/wso2/product-is/issues/1802

**Comment by ruwanta** [comment]
Let us look at the flow in logical way,

Federated authentication means establishing a trust relationship with Federated IdP. In theory this trust should be good enough, there should not have a reason for a second factor which depends on users attributes. The reason is that all the user attributes are also provided by the same federated IdP. There is no real security enhancement using second factor given by the same federated party. Multi-factor authentication, if needed, needs to be handled by federated IdP, which holds users primary attributes.

The second factor should be performed with information what WSO2 IS as IdP can attest, which requires user having his details entered in WSO2 IS itself. 

The above is true even for JIT provisioning. First time user needs to be provisioned, and then asked to enter missing claims while provisioning. Second factor should be prompted after first time provision is done. Elaborate logic for this may be handled by authentication script.

**Comment by ruwanta** [comment]
With my previous comment, I would argue that the current behaviour is correct, and provides real security. 
Proposed approach only gives false sense of security IMO.

**Comment by rksk** [comment]
yes, agree with @ruwanta 

As you mentioned, we can skip the 2nd factor when the user is getting provisioned for the first time. If needed, we can prompt for 2nd factor for the next authentication requests by the same user using an authentication script.

**Comment by ruwanta** [comment]
@rksk 
Quote
```
we can prompt for 2nd factor for the next authentication requests by the same user using an authentication script.
```
This is not the case. WSO2 IS can not identify whether it is first time or second time login. However it can check the existence of a claim(or a set of claims) and decide to prompt second factor or fail or allow to login. 
This will cover almost all real cases.

**Comment by rksk** [comment]
yes, if the user exists locally, we can assume as it is the first time.
