### ISSUE TITLE
Stop sending three emails to user when newly created with askPassword option

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5451]
**Description**
When admin create a new user account with askPassword option, individual emails are sent to the given email for each of following option, when they are enabled.
* Enable User Email Verification
* Enable Account Lock On Creation Enabled
* Enable Notification Internally Management

**Type**
Improvememt

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
identity-governance, identity-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Identity Governance, Component/Identity Mgt, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5192

**Comment by piraveena** [comment]
For askPassword flow, the account is not locked by default. So, only one mail is sent in askPassword flow.
For user self registration flow and user email verification flow, 2 emails are sent. Because, In both the cases account is locked. So one mail is sent for accountLocking and the other email with confirmation code

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
