### ISSUE TITLE
UserInfoRecovery.UseHashedUserNames property should be removed

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5484]
Moved from https://wso2.org/jira/browse/IDENTITY-5829

Currently, when using an email address as the username, we ask users to set the UserInfoRecovery.UseHashedUserNames property in the identity-mgt.properties file to true.

This should be done through the code itself instead of the user having to configure a property. The code should check if there is an @ sign or not and do the relevant thing.

**Comment by johannesboon** [comment]
This too may be useful for other reasons:

The current default implementation of the [RecoveryProcessor](https://github.com/wso2/carbon-identity-framework/blob/48672a4962308080b3dc3d6a2170fbf837323531/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/RecoveryProcessor.java#L740) also does not function correctly for usernames with an underscore at the end of the username because:

- it is not covered by stripSpecialChars (which seems very insecure in case you want to attack an account with the letter z in the name!)
- it breaks the function getUserExternalCodeStr because the split function returns an extra underscore in front of the UUID

Switching to any of the following options fixes that:

- UserInfoRecovery.UseHashedUserName=true (and maybe upgrade SHA-1 to SHA-256 as default hash as SHA-1 is insecure)
- Use a standard encoding mechanism instead of reinventing it badly (like Base64 with an alternative Alphabet that does not clash with registry special chars)

Switching is not backward compatible, meaning an account that needs to be confirmed after creation cannot be confirmed anymore with an old activation code (and resending is not possible with the old 5.2.0 implementation)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
