### ISSUE TITLE
[Self Registration REST API] Wrong Content-Type in Register User successful response

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5701]
Moved from: https://wso2.org/jira/browse/IDENTITY-7373

Hi,

I'm using the Self Registration REST API (v0.9) of Identity Server 5.3.0.

This is what I added in <IS_HOME>/repository/conf/identity/identity.xml:
```
<SelfRegistration>
        <Enable>true</Enable>
        <LockOnCreation>true</LockOnCreation>
        <Notification>
            <InternallyManage>false</InternallyManage>
        </Notification>
        <ReCaptcha>false</ReCaptcha>
 </SelfRegistration>
```
The important thing here is that I have disable the internal management of the notifications because I want to manage it myself.

So when I use the Register User (https://localhost:9443/api/identity/user/v0.9/me) resource of the API it returns the Validation Code so I can handle it. But the Content-Type of the response is application/json and the body is a plain text. Here is an example:

```
HTTP/1.1 201 Created
Date: Thu, 14 Jun 2018 07:10:42 GMT
Content-Type: application/json
Content-Length: 36
Server: WSO2 Carbon Server

8ff16bfe-64d5-43a4-95b7-d9d2285a4936
```
When there is an error all goes well because in that case the Content-Type is application/json and the body is a JSON:

```
HTTP/1.1 409 Conflict
Date: Thu, 14 Jun 2018 09:46:19 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: WSO2 Carbon Server

{"code":"20030","message":"Conflict","description":"User test_user already exists in the system. Please use a different username."}
```
Maybe a simple solution could be include the Validation Code in a JSON:
```
HTTP/1.1 201 Created
Date: Thu, 14 Jun 2018 07:10:42 GMT
Content-Type: application/json
Content-Length: 36
Server: WSO2 Carbon Server

{"code":"8ff16bfe-64d5-43a4-95b7-d9d2285a4936"}
```
The same happens with the Resend Code (https://localhost:9443/api/identity/user/v0.9/resend-code) resource of the API. Here is an example of response:
```
HTTP/1.1 201 Created
Date: Thu, 14 Jun 2018 09:49:35 GMT
Content-Type: application/json
Content-Length: 36
Server: WSO2 Carbon Server

81279f88-ae62-454e-9520-838a1ea80364
```
Thanks!

**Comment by gayashanbc** [comment]
I'm working on this issue.

**Comment by gayashanbc** [comment]
**Update:** Fixing this issue will introduce a change in the existing API. It might break the flow in existing client applications due to the change in the API response.
Hence, it was decided to return the response as it is without changing it.

Code snippet related to this issue is located at [wso2-extensions/identity-governance](https://github.com/wso2-extensions/identity-governance) repository, in [this line](https://github.com/wso2-extensions/identity-governance/blob/30d246b7a9c2d973bf30e6926bfb0a15003711bf/components/org.wso2.carbon.identity.user.endpoint/src/main/java/org/wso2/carbon/identity/user/endpoint/impl/MeApiServiceImpl.java#L101).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
