### ISSUE TITLE
Federate logout request to OIDC IDPs

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5958]
Currently, we don't federate the logout requests to OIDC IDPs. To solve this, we can initiate RP init logout request to the logout endpoint of federated IDP. This has to be implemented in [OIDC (outbound), authenticator](https://github.com/wso2-extensions/identity-outbound-auth-oidc) and relevant OIDC authenticators.

**Comment by mefarazath** [comment]
Hi @piraveena,

Is there a general specification related to federated IDP logout? 
AFAIK different OIDC providers have non-standard endpoints to support logout.

Amazon Cognito - https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html

Azure AD - https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#send-a-sign-out-request

So with this improvement how are we planning to implement OIDC federated logout in a generic manner?

**Comment by piraveena** [comment]
Hi @mefarazath,
There is no specs specifically mention about federated logout. With this feature, we are planning to do an RP initiated logout from the client to federated IDP in a general manner. From the oidcAutheticator, we will be able to call the logout endpoint of the federated IDP with parameters such as id_token_hint,etc.

Refer the mail thread "OIDC Federated Logout for Identity Server" in architecture@wso2.org

**Comment by darshanasbg** [comment]
Hi @mefarazath,

What did you mean by "general specification related to federated IDP logout"?

In this case, the Identity Server act as the RP and Federated IDP act as OP. So in order to logout, Identity Server should initiate an RP initiated logout request to the OP as described in [OIDC Session Management spec](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout).

In summary the general specification to refer in here is [RP-Initiated Logout in OIDC Session Management spec](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout)

**Comment by tharindu-bandara** [comment]
@Chamodii @darshanasbg 

As the fixes are merged now, shall we close this issue?
