### ISSUE TITLE
Remove AuthenticationContext from TOTPAdmin service

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5999]
TOTPAdmin service expects AuhenticationContext as a parameter [1] for certain operation. This should be removed in a backward compatible manner

[1] - https://github.com/wso2-extensions/identity-outbound-auth-totp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/application/authenticator/totp/services/TOTPAdminService.java#L96

**Comment by eran13com** [comment]
@omindu  the TOTPAdminService cannot be imported to SoapUI and it gives following error.

Source: https://localhost:9443/services/TOTPAdminService?wsdl
Error: type 'Enum@http://www.w3.org/2001/XMLSchema' not found.

As a workaround instead of using SoapUI we can use curl commands to invoke the TOTPAdminService as mentioned in the documentation
[https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator](url). Also please find modified TOTPAdminService wsdl file here [TOTPAdminServices.wsdl.zip](https://github.com/wso2/product-is/files/3446047/TOTPAdminServices.wsdl.zip)
