### ISSUE TITLE
Incorrect expires_in value returned in implicit flow response

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6266]
Token expiry is set to 3600s

Tried implicit flow 
https://idp.wso2.com:9443/oauth2/authorize?scope=openid adsadad&response_type=token&redirect_uri=https://localhost/callback&nonce=13e2312637dg136e1&client_id=fwShRafR65jrKIzGXcuZavhyx60a

The response
https://localhost/callback#access_token=48259ad7-4eef-3147-9a66-f580a5aca03f&token_type=Bearer&expires_in=3899&session_state=88cd5b9a1bbf90ac34ac1ebd8d843c677336f6899a5656fa3c900add60fc6929.ZQx1-Ksp3L2k6UzcdNNcAA

expires_in=3899

The expires in value is 3899 which is invalid since the maximum value it can take is 3600

**Comment by dewniMW** [comment]
This issue is due to oauth timestamp skew time being modified for 5 minutes with the new default.json file available at [1]

[1] https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json

**Comment by dewniMW** [comment]
PR https://github.com/wso2/carbon-identity-framework/pull/2444 resolves this issue.
