### ISSUE TITLE
Error-SAML2 IdP Initiated Single Logout with WSO2 Identity Server

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6326]
Affected Version: wso2is-5.9.0-alpha
Priority: Medium
Severity: Medium

Step to reproduced:

Created SAML service provider in super tenant mode and Enable IDP initiated SLO : My SLO URL is as follows : 

https://localhost:9443/samlsso?slo=true&spEntityID=travelocity.com&returnTo=https://localhost:8080/travelocity.com/slo

So when append , "returnTo=https://localhost:8080/travelocity.com/slo", getting an error 
ERROR {org.wso2.carbon.identity.sso.saml.processors.IdPInitLogoutRequestProcessor} - Invalid 'returnTo' URL in the request

**Comment by dewniMW** [comment]
The returnTo URL should be the URL that needs to be redirected to after the logout. Therefore the URL needs to be a valid URL. The issue was not reproducible by passing a valid URL. Please find below the configurations I have used for testing.

IdP Initiated SLO Return to URL in service provider configuration: http://localhost:8080/travelocity.com

Logout request:
https://localhost:9443/samlsso?slo=true&spEntityID=travelocity.com&returnTo=http://localhost:8080/travelocity.com
