### ISSUE TITLE
[IS-5.7.0] db2.sql script is not working for latest db2 version(11.5)

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6403]
**Description**
Db2.sql script(<IS-HOME/dbscripts/db2.sql) is not working for the latest db2 version(11.5). To setup the db2 follow the documentation[1]

`DB21034E The command was processed as an SQL statement because it was not a 
valid Command Line Processor command. During SQL processing it returned:
SQL0104N An unexpected token "CREATE TABLE REG_CLUSTER_LOCK( REG_LOCK_NAM" 
was found following "BEGIN-OF-STATEMENT". Expected tokens may include: 
"<space>". SQLSTATE=42601`

We can resolve this issue by removing "/" from the script.

**Affected Versions** 
- IS-5.7.0

**Suggested Labels**
- Bug
- db2

[1] - https://docs.wso2.com/display/ADMIN44x/Changing+to+IBM+DB2

**Comment by nilasini** [comment]
@hasinidilanka we can't resolve the issue

`DB21034E The command was processed as an SQL statement because it was not a valid Command Line Processor command. During SQL processing it returned: SQL0104N An unexpected token "CREATE TABLE REG_CLUSTER_LOCK( REG_LOCK_NAM" was found following "BEGIN-OF-STATEMENT". Expected tokens may include: "<space>". SQLSTATE=42601
`
by removing delimiter "/" from the script. We should remove the new lines from the script.

**Comment by nilasini** [comment]
Relevant doc issue can be tracked through \[1]

\[1] https://github.com/wso2/docs-is/issues/530
