### ISSUE TITLE
Admin service UserStoreConfigAdminService updates secondary userstore.xml file with zero bytes.

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#6409]
ISSUE
----------
Identity server maintains a UUID (**UniqueID**) for the secondary user stores to not return the encrypted password for the admin service [1], Hence the update/edit (**editUserStore**) request does contain the same UniqueID and random password ID which received from the get method (**getSecondaryRealmConfigurations**), the server will not update the userstore password, instead it will retain the same password and updates the other fields which come  in the (editUserStore) request.

However, in a **distributed Identity server setup**, the (UniqueID) parameter **differs** from **node** to **node**, Hence the method (editUserStore) should be call to the same node, where it received the parameter (UniqueID) for the specific node on the (getSecondaryRealmConfigurations) method of the admin service

If multiple nodes were fronted by a load balancer and the Admin Service client (SOAP) does not handle the session affinity gracefully (cookie-based), the request will not go to the same node where the (UniqueID) parameter is received by the method (getSecondaryRealmConfigurations). 

In such a scenario, the identity server will override the particular secondary userstore file with zero bytes, hence the server is unable to correlate the UniqueID available and the received in the payload of the (editUserStore) method in the admin service.

Behaviour is the same even the clustering is enabled.

STEPS TO REPRODUCE
-------------------------------------

1. Setup a two-node identity server sharing the <CARBON_HOME>/repository/deployment/server directory among them.
2. Create the secondary userstore in one of them and verify the same will deploy in the other node automatically since the <CARBON_HOME>/repository/deployment/server directory is shared.
3. Create a WSDL project in soap using the admin service [1].
4. Call the SOAP method (getSecondaryRealmConfigurations) pointing to **node one** and verify the (UniqueID) parameter received.
5. Call the SOAP method (getSecondaryRealmConfigurations) pointing to **node two** and verify the (UniqueID) parameter received.
6. Try the (editUserStore) method over the **node two** by sending the correct payload and the (UniqueID) parameter received from **node one**.
7. The created secondary userstore file gets updates with zero bytes.

[1] https://localhost:9443/services/UserStoreConfigAdminService?wsdl

**Comment by tharindu-bandara** [comment]
This has already been fixed with the pull request, https://github.com/wso2/carbon-identity-framework/pull/2243.

The reason for this issue is, earlier when user store configuration file is updated, it opens a zero byte stream on the user store configuration file, then build the document model for the file from UserDTO object in the edit request and finally witing the document model to the zero-byte stream. However, if an exception is thrown while building the document model, the zero byte stream is flushed to the file causing this error. 

With the above pull request, [this order is changed](https://github.com/wso2/carbon-identity-framework/blob/1f7738a2d061d567af743234ac7237351d230b03/components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurationUtil.java#L339). The document model is built prior to open the zero byte stream which ensures that this issue is eliminated.

### Further explanation:

**The Issue:**
The writeUserMgtXMLFile in the existing code is used to update the file-based user store configuration files. The existing flow works in the following manner.

Create a StreamResult object for the configuration file.
StreamResult result = new StreamResult(Files.newOutputStream(userStoreConfigFile));. If the config file already exists, this step will create a zero byte stream StreamResult object.
Then the code logic is executed to build a Document Model from the UserStoreDTO.
Finally, the document model is stored with the StreamResult object created in step 1.
The scenario mentioned in wso2/product-is#6409 presents a UserStoreDTO with an invalid UUID to this logic, which breaks the step 2, and then step 3 is never performed thus setting the configuration file to zero bytes as created in step 1.

**Changed Approach With Above Pull Request:**
Step 1 mentioned in the above should be performed once the Document model is successfully prepared and ready to be written to the file. Otherwise, any error occurs in the Document model preparation sets the configuration file to zero bytes. Thus, the flow is changed to the following order.
- Step 2
- Step 1
- Step 3
