### ISSUE TITLE
Refactor code that handles the OIDC logout

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6418]
Currently, when an OIDC logout happens the OIDCLogoutServlet is called and also a SESSION_TERMINATE event is fired from the framework and its captured by OIDCLogoutEventHandler. 

This code can be changed to handle the logout request entirely through the SESSION_TERMINATE event via OIDCLogoutEventHandler. This is the behaviour of SAML Logout[1]

[1] - https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/SAMLLogoutHandler.java

**Comment by darshanasbg** [comment]
Also consider the case mentioned in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1173/files#r324422922

**Comment by ayshsandu** [comment]
@janakamarasena can you verify whether these are captured in latest session related git issues?

**Comment by piraveena** [comment]
@ayshsandu , this is a different issue. We do oidc logouts in inbound component once we get the logout response from framework. If the session termination invoked by an OIDC app, we don't do logouts during session termination event.  In saml bac-channel logouts, we rely on session termination event. but in oidc we don't. This is an inconsistency in our code. This needs to be refactored

**Comment by piraveena** [comment]
In OIDCLogoutHandler, we check whether this request is triggered by an OIDC app [1]. If it is triggered by an OIDC app, then we listen to session_termination event to logout the other oidc applications. Because we do back-channel logouts[2]. So this session termination event trigges logout in oidc inbound only if the logout request is initiated by saml or rest api. 

But in SAML, we rely on session termination event for logouts. And it is better to refactor the oidc logout also to rely on session termination event. Because there can be some cases where the framework might remove commonauth session and trigger session termination event. But if federated logout fails in the middle, then inbound component may not be able to receive a response. So in that case, even though the session is terminated in the framework side, inbound session may exist. 

 So we need to refactor oidc back-channel logout to be triggered after session_termination evet is fired.


[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.117/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/handler/OIDCLogoutEventHandler.java#L53. 
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.117/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/servlet/OIDCLogoutServlet.java#L659 when the inbound component gets response from the framework.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
