### ISSUE TITLE
[Config] Template "MultipleAttributeEnable" in user-mgt.xml

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#6579]
Following property has not been templated in the user-mgt.xml.
`<Property name="MultipleAttributeEnable">true</Property>`

**Comment by nilasini** [comment]
we can add any properties to user-mgt.xml by only specifying the properties in deployment.toml would be fine because the user-mgt.xml.j2 is a loop with properties.

To enable multiple attributes you should add below property to deployment.toml under [user_store]
**`properties.MultipleAttributeEnable = true`**

Created a doc issue to add this.
