### ISSUE TITLE
Add Account Linking Functionality

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-is#6628]
A System Integrator i started working with, which we are working at an opp with, stated that WSO2 IS misses some functionalities that can lead it to become a true CIAM tool. One of this is Account Linking:
1) from the User Portal it should be possible to link to external IdP (specially social sites like Facebook) and start the sign up process logging in to the external IdP and importing user data; moreover it should be possible to complete the account registration with further data
2) the same as 1 should be possible from an app (SP) directly, without going to the user portal.

**Comment by darshanasbg** [comment]
Hi @stefanonegri,

As you are talking about sign-up process, user won't be able to login in to the user portal in the first place..

When user try to access user portal, user will get the login page similar to the below one.
![image](https://user-images.githubusercontent.com/1617810/66811596-019c8300-ef4f-11e9-8a60-b041adbf13dc.png)

Then user will be able to click on register link in that UI and start the self registration process.

In the default self registration form, as of now, it only have the option of direct registration (without utilizing any external IDP).

But the product is capable of start the sign up process logging in to the external IdP, use the information retrieved by the external IdP to fill information required in the registration process and only request additional information to complete the registration process. In order to get this capability to the registration form, its need to customize only the registration UI as of now.

In the customized registration form, you just need to add a "idp initiated login link" to the social IDP you wish to enable during the registration. As the product is capable of JIT provision users in the login flow, the rest of the user on-boarding process will be work as you mentioned above.. 

Thanks,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
