### ISSUE TITLE
Single sign-on does not work if one service provider is connected to the same IdP via federation

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-is#6705]
**Scenario:**

1) I have 2 applications (dispatch and manager) configured as service providers
2) The manager application is connected directly to authenticate with the central IdP
3) The dispatch application is connected to authenticate with the central IdP via federation
4) When I first login from the manager application, I will be automatically logged into the dispatch application using SSO. 

SSO does not work if I log in first from the dispatch application

**Comment by omindu** [comment]
Hi Natasha,

Can you elaborate more on what you mean by central IdP here ? 
Are there 2 IdPs involved or are you a single IdP and configuring itself as a federated IdP ?

**Comment by johannnallathamby** [comment]
Hi Omindu,

Yes, there are two IdPs. Let's call one as A and other as B. Portal 1 is registered as service provider in IdP A. Portal 2 is configured as service provider in IdP B. IdP B is configured as a service provider in IdP A. Both portal 1 and IdP B is configured for Basic authentication in IdP A. Now if you login to portal 2 via federation to IdP A, and the try to login to portal 1 directly via IdP A, SSO doesn't work.

**Comment by omindu** [comment]
Hi Johann/Natasha,

How are the hostnames configured for IdP A and IdP B ? Are they both running in same host name (localhost or otherwise) ? If so this scenario can be explained as follows

As IS tracks the SSO session with commonAuth ID cookie, in non working scenario (portal 2 via federation to IdP A), IdP will set the commonAuth ID cookie to it's hostname. Once the federation is complete, IdP B will also write the commonAuth ID cookie to it's hostname. If both the hostnames are the same, when Portal 1 is login into IdP A, SSO may not work as the server might be presented with the wrong commonAuth ID cookie.

If the IDPs have different domain names, can you attach SAML tracer for both working and non working scenarios. Make sure not to mask the cookies when exporting the SAML trace.

**Comment by NatashaWso2** [comment]
Hi Omindu,

Both IdP A and IdP B are running with the same host name i.e. localhost

Is there any workaround we can use to get this working? Or is this the expected behavior?

**Comment by omindu** [comment]
Hi Natasha,

This is the expected behavior. To overcome this, you can configure one of the IDPs to use a different domain name. So there won't be duplicate commonAuth ID cookies for the same domain.

**Comment by NatashaWso2** [comment]
Hi Omindu,

I was able to get SSO working for both the portals after configuring both IdPs to use different host names. 

Closing this ticket since the issue has been resolved. Thank you for the support provided
