### ISSUE TITLE
Datasource for WSO2_CARBON_DB 

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#6785]
Hi, 

Can the WSO2 CarbonDB changed to another datasource, since embedded databases are not recommended in production? 

Thanks

**Comment by darshanasbg** [comment]
@hefesita Can you mention the product version that you are using? So I can give you more relevant answer.

**Comment by hefesita** [comment]
I am using 5.9.0.

**Comment by darshanasbg** [comment]
* In IS 5.9.0, the default `WSO2CarbonDB` datasource is only used in the local registry mount of the server.
* In every IS version, only for the local registry mount, its recommended to use to embedded H2 DB even in the production deployment.
* So you don't need to change WSO2CarbonDB datasource in IS 5.9.0 and its not even showing in the deployement.toml file by default.

In 5.9.0, it use the [new configuration mode](https://is.docs.wso2.com/en/5.9.0/references/new-configuration-model/)l, so all server configurations are done using the `deployment.toml` file which is located inside the `<IS_HOME>/repository/conf` directory.

There are two datasources available in the default deployment.toml file as follows,
```
[database.identity_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"
```
So, its sufficient to change only these two datasources without considering WSO2CarbonDB even for production deployments due to the reasons mentioned originally.

**Comment by hefesita** [comment]
Ok, thank you for the explanation.  
I have one more question, if possible, regarding the governance_identity_store as org.wso2.carbon.identity.governance.store.UserStoreBasedIdentityDataStore . I get an error that one attribute is unmapped http://wso2.org/claims/identity/failedLoginAttemptsBeforeSuccess even though I use the default claim-config.xml. In the claim-config.xml there is no entry on that attribute. Am I missing something?
Thanks again

**Comment by darshanasbg** [comment]
This seems to be a bug in the default claim configurations for the embedded ldap. Can you please report a separate issue with the steps you have followed with the error you get?

Thanks,

**Comment by hefesita** [comment]
I will. 
Thanks

**Comment by darshanasbg** [comment]
Thanks for reporting the issue @hefesita.

Adding a link to the new issue https://github.com/wso2/product-is/issues/6787 for future reference.
