### ISSUE TITLE
Need help to configure on premise AD as user store

### ISSUE THREAD

**Issue by sheikirfanbasha** [wso2/product-is#6844]
Hi Team,

I need to connect to AD which is behind firewall and can't be exposed. 

I read it from this [blog](https://dzone.com/articles/authenticate-end-users-for-apis-ldap-ad-saml-datab) that `WSO2 Idenity Cloud` has this functionality which allow us to download agent to hook up to the AD.

Is it possible to achieve the same with the WSO2 identity server that I have it downloaded and running in my system?

**Comment by darshanasbg** [comment]
The technique mentioned in the blog for the `WSO2 Identity Cloud` is done by using some additional modules to Identity Server distribution and connecting to external systems like message brokers etc..

So you don't have same capability in the vanilla distribution of the Identity Server you download.

To achieve your requirement, the simplest way is to connecting to the AD through VPN.

**Comment by sheikirfanbasha** [comment]
Thanks for the quick response @darshanasbg . We do not want to use the option of `VPC` or `VPN`.

I am thinking of installing the vanilla distribution of Identity server behind the firewall and expose only specific list of APIs to the outside world _(which do not necessarily reveal all the information about the AD users. Like may be just expose the GET roles API)_. 

Is there any quick way to expose only a specific list of APIs? 

I understand that the the below setting exposes all the admin APIs. But in this use case, I just want to expose only selected list.

```xml
<HideAdminServiceWSDLs>false</HideAdminServiceWSDLs>
```

**Comment by darshanasbg** [comment]
Installing an IS locally to AD and exposing via APIs is a good solution that can be do with OOTB capabilities..

Identity Server does not have a functionality to turn off APIs. Exposing only the required endpoints needed to be handled through an external proxy or a load balancer.

Infact, `HideAdminServiceWSDLs` flag does not disable any Admin service, rather it only determine whether to **expose the wsdl or not**.

Since now its mostly use REST APIs, can recommend to have a look at SCIM 2.0 APIs.
To list group information - https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#GroupsEndpoint#getGroup
To list information of the authenticated user - https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#MeEndpoint#getUserMe

Apart from the path based restrictions, better to have another rule so that the exposed API can only be accessed from whitelisted servers.

**Comment by sheikirfanbasha** [comment]
Thanks for the detailed suggestion @darshanasbg

**Comment by darshanasbg** [comment]
Happy to help @sheikirfanbasha 👍
