### ISSUE TITLE
Recaptcha not prompting without the Account Lock

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#6848]
Recaptcha is not working without account locking.
When we deselect the account locking filed Recaptcha also not working. 
There could be scenarios where we have the requirement of enabling the re-captcha without enabling the account locking.

Product version: 5.8.0 WUM 1572511942074 / 5.8.0 Vanilla
Severity: medium
Priority: high
OS: Ubuntu

**Comment by ruwanta** [comment]
Hi @Seralahthan 
Can you explain few "scenarios where we have the requirement of enabling the re-captcha without enabling the account locking." for the completeness of this improvement please.

Cheers,
Ruwan

**Comment by pamodaaw** [comment]
This issue is fixed in the master branch with the PRs https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/64 and https://github.com/wso2-extensions/identity-governance/pull/335.

The necessary documentation changes are tracked in the issue https://github.com/wso2/docs-is/issues/967.
