### ISSUE TITLE
"WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'admin[-1234]' at [2019-11-26 22:51:59,135+0530]/

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6945]
Affected version: wso2is 5.10.0 m7

Type: bug
Severity: Medium
Priority: High

Step to reproduced:
1. Server startup, 
2.Navigate to https://localhost:9443/carbon/ 
3.getting warning log in wso2carbon log,

**WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'admin[-1234]' at [2019-11-26 22:51:59,135+0530]**

**Comment by madurangasiriwardena** [comment]
Can you please elaborate more on the issue? By reading your issue description, what I could understand was after starting the when you try to just access https://localhost:9443/carbon/, you are getting this warn log.

The reason for this might be, you already have cookies set in the browser (with the previous sessions you have loged in) and those cookies are sent with the request to https://localhost:9443/carbon/. But since the cookie value is not understood by the server, it might be printing the warning log. To confirm this, can you try the same flow with a private browser session and see if the warn log line is printed.

**Comment by NilukaSripalim** [comment]
unable to reproduced with the latest.
