### ISSUE TITLE
Show application display name in the sso login consent page

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#6950]
$subject.

@mefarazath Can you advice whats the service authentication endpoint should consume retrieving this information and whats the element that should be used in the service provider object?

@malithie What's the display name that's used in 'user application' service? We can use the same here.

**Comment by mefarazath** [comment]
@darshanasbg 
We decided to allow (spaces, dot, underscore and hyphen) in the service provider name. This was the main limitation that prompted us to have a separate display name. 

Since we have loosened the constraints on the service provider name, we can use the same to have a friendly name for the applications.

So ServiceProvider#getApplicationName() would give the name.

**Comment by darshanasbg** [comment]
So the application developer should use a friendly\display name for the 'service provider name' when creating the SP and that will be used for any place (like SSO login, User Portal, Admin Management console) to show the application name.

In that case we don't need a change in the consent page as we are sending the application name already.

We just need to change dashboard\userportal SP names to have proper names.

**Comment by darshanasbg** [comment]
Dashboard is no longer available in the product, and user portal display name has been updated with: https://github.com/wso2/identity-apps/pull/159.
