### ISSUE TITLE
How to return to service provider

### ISSUE THREAD

**Issue by ayasha88** [wso2/product-is#6959]
Hi! I am following the DemoFaceIdAuthenticator. My authenticator work like this: I do not have a webpage where I authenticate, but I receive a certificate in the header and I have to check on a ldap if it is ok or not. The problem is that I don't know how to correctly return to my original service provider page.

I have created an Authenticator with initiateAuthenticationRequest and processAuthenticationResponse. In the initiateAuthenticationRequest I immediatly call the processAuthenticationResponse as I don't have to redirect to another page. In processAuthenticationResponse  I check the certificate/username, I put 

```
context.setSubject(authenticatedUser);
AuthenticatorFlowStatus status = AuthenticatorFlowStatus.SUCCESS_COMPLETED;
```

but it doesnt redirect.
Should I do something else?

**Comment by inthirakumaaran** [comment]
Hi @ayasha88,

Glad to hear that you are creating an authenticator.

While writing a custom authenticator for IS, you need to implement the LocalApplicationAuthenticator. In doing so, you only have to override the existing methods. Our authentication framework will handle the flow itself. 

Normally **initiateAuthenticationRequest** is used to prompt a page to user to get credentials and **processAuthenticationResponse** used to validate those credentials. It seems there are some mismatches to those overrides you have done

In your case, you can override the **process** method rather than the above two as you don't need to get any input from the user.

Please follow https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator doc to see what is expected from those methods and https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L103 to see how to override process method

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
