### ISSUE TITLE
Should accessURL be a mandatory attribute in the SP config? 

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#7095]
Right now `accessURL` is mandatory if only the `Service Provider` is `discoverable`. 

`accessURL` is required to avoid other issues like,
* To avoid bookmark issue
* To avoid browser back button issue
* To avoid redirecting to dashboard\user-portal after self-registration with email validation.
etc.

Thus, IMO `accessURL` should be a mandatory attribute in `Service Provider`.

Along with that, for better UX, it can make `imageURL` also mandatory. So all related UIs can use SP logo in consistent way without depending whether application is `discoverable` or not.

**Comment by thanujalk** [comment]
+1. Better make this mandatory.

**Comment by omindu** [comment]
@darshanasbg What exactly meant by `discoverable` in this context?

Also, IMO keeping the `imageURL` should be kept optional and not a mandatory step in creating the SP.

**Comment by mefarazath** [comment]
It makes sense to make the accessURL mandatory. 

But I am having an opinion on the ImageURL. 

> So all related UIs can use SP logo in consistent way without depending whether application is discoverable or not.
Can't we have a generic image if the application specifies one? That way all apps will have an image.

**Comment by darshanasbg** [comment]
> It makes sense to make the accessURL mandatory.
> 
> But it doesn't sound right to mandate the imageURL.
> 
> > So all related UIs can use SP logo in consistent way without depending whether application is discoverable or not.
> 
> Can't we have a generic image if the application doesn't specify an imageURL? That way all apps will have an image.

We do have this support, from the places we show the application image..

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by rksk** [comment]
This is yet to be addressed. Here are a few suggestions:

1. Instead of making the accessURL mandatory, we can add a warning on the app configuration page if no accessURL is configured.
2. When accessURL is not configured, the logincontext call should indicate the session context expiry, and a clear message should be shown to the user before they submit login credentials.
sample
```
Login Expired!

The login flow was interrupted for your security. This may occur when a page is left inactive for an extended period or accessed through a saved link.

Please restart your sign-in from the application to continue.
```
3. Check and fix the login context check for all login pages. Currently, it is only added to the idf handler and basic authentication.


Suggestion No. 2 is mainly because there are cases where it is not possible to define an access URL. For example, a Service Provider might be used for federation from another Identity Provider, and that IDP has many applications configured.

The problem is that the current error message for an expired session context is only shown after the user submits their credentials, not when the page is loaded or when they attempt to submit. This leads users to often assume the issue is with the IDP itself, sometimes without even reading the message shown.
