### ISSUE TITLE
EnableFederatedUserAssociation in identity.xml not respected

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#7285]
to reproduce:
1. unzip a fresh copy of WSO2IS 5.9.0 or 5.10-alpha2
1. in `repository/conf/identity/identity.xml`, change `EnableFederatedUserAssociation` to true
1. start the server
1. shut down the server
1. open `repository/conf/identity/identity.xml` and see that `EnableFederatedUserAssociation` is false

**Comment by ruwanta** [comment]
Hi @hauntingEcho ,
May be this behaviour is related to the new configuration model introduced by 5.9.0. Similar issue related to configuration change available at https://github.com/wso2/product-is/issues/6649. 

I would suggest a test, to see if it is the case, by removing "deployment.toml" file which forces 5.9.0 or 5.10.0 configuration behaves exactly like pre 5.9.0 products.

Also for more information one can go through few references.
1. https://wso2.com/blogs/thesource/2019/10/simplifying-configuration-with-WSO2-identity-server/
2. https://is.docs.wso2.com/en/5.9.0/references/new-configuration-model/

**Comment by piraveena** [comment]
Hi @hauntingEcho ,
Please follow this document https://is.docs.wso2.com/en/5.9.0/learn/associating-user-accounts/ to associate user accounts with IS 5.9.0 or IS 5.10.0-alpha2

**Comment by madurangasiriwardena** [comment]
@hauntingEcho can you please try the documentation pointed by @piraveena. What you need to do is basically, add the following configuration to the `/repository/conf/deployment.toml` file.

```
[user.association]
enable_for_federated_users = true
```

However, the recommended approach is to have the enable_for_federated_users parameter set to false so that manual federated user association is not allowed by default via the dashboard.

Closing the issue since the required configurations are properly mentioned in the documentation. Please feel free to reopen the issue, if you need further clarification.
