### ISSUE TITLE
Inconsistency in the email attribute types added via management console and SCIM 2.0 

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#7290]
There is an inconsistency in the email attribute type depending on the method used to add the user email. I think it'll be better if we can decide and maintain one format.

**Method 01 - via the management console**

When the user profile is updated via the management console the email is set as given below.
GET the user details via the SCIM 2.0 endpoint.

```
Path: https://localhost:9443/scim2/Me
Method: GET

Response (email):
"emails": [
        "nipuni@gmail.com"
 ]
```
**Method 02 - via SCIM 2.0 endpoint**

When a user is created by directly calling the SCIM 2.0 endpoint the email is set as a complex attribute.

```
Sample Request:

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kimj@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Response (email):

"emails": [
        {
            "type": "home",
            "value": "kim.jackson@gmail.com"
        },
        {
            "type": "work",
            "value": "kimj@wso2.com"
        }
    ],
```

**Comment by madurangasiriwardena** [comment]
@NipuniBhagya The reason for this is you are updating 2 different claims from the 2 places.

If you check the mapped local claim of `urn:ietf:params:scim:schemas:core:2.0:User:emails.home` in `urn:ietf:params:scim:schemas:core:2.0:User` dialect (which is what you are updating with SCIM 2 call), it is `http://wso2.org/claims/emails.home`

However, if you update the email from management console you are updating `http://wso2.org/claims/emailaddress`

Reason for this is when implementing SCIM 2, since email is a complex attribute, we couldn't use the existing `http://wso2.org/claims/emailaddress` and had to introduce a few new claims such as `http://wso2.org/claims/emails.home`

If you want to update the `http://wso2.org/claims/emails.home` from the management console, you can mark it as supported by default and it will be showing in the user profile.

**Comment by emswbandara** [comment]
@NipuniBhagya according to the spec, the emails field can contain both, primitive and complex attributes. Please refer https://tools.ietf.org/html/rfc7643#section-2.4. Internally we use the `http://wso2.org/claims/emailaddress` claim to store the primitive values and claims such as `http://wso2.org/claims/emailaddress.home` will be used to store the complex attributes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
