### ISSUE TITLE
Missing key-mapping for user_store configuration property "CaseInsensitiveUsername"

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#7297]
As for now the key-mappings.json file contains many key-mappings regarding to the user_store properties. Regarding to Configuring JDBC databases[1], "CaseInsensitiveUsername" property is not mapped in the key-mappings.json file.

[1]. https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-jdbc-user-store/

**Comment by piraveena** [comment]
Hi @ShanChathusanda93 ,
Not all the userstore properties are mapped in key-mapping.json file. Only some mandatory properties common to all userstores are mapped. If you want to add some userstore properties, you can add it as below:

```
[user_store.properties]
CaseInsensitiveUsername=true
```

There are some other properties also not added. So we can add them as properties since these are not common for all userstores

```
RolenameJavaScriptRegEx
CaseInsensitiveUsername
IsBulkImportSupported
PasswordDigest
StoreSaltedPassword
TenantManager
UserNameUniqueAcrossTenants
```

**Comment by ShanChathusanda93** [comment]
Hi @piraveena,
Thank you very much for the response. I think it is better to keep this issue open until these properties are added (As per the internal discussion).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
