### ISSUE TITLE
Documentation error/bug on Bulk Import Users Ask Password option -  5.8 

### ISSUE THREAD

**Issue by RenanMartorelli** [wso2/product-is#7321]
According to the 5.8 documentation, 'Ask Password' option on bulk user creation can be activated by leaving the field 'Password' as an empty string in the .csv .

Example:
UserName,Password,Claims
name1,Password1,http://wso2.org/claims/emailaddress=name1@gmail.com,http://wso2.org/claims/country=France
name2,Password2,http://wso2.org/claims/emailaddress=name2@gmail.com,http://wso2.org/claims/country=France
name3,,http://wso2.org/claims/emailaddress=name3@gmail.com,http://wso2.org/claims/country=France

However, this can only be achieved (tested using the default LDAP and a JDBC userstore) by passing a string in the password field and setting the askPassword claim as true.

Example:
UserName,Password,Claims
name1,Password1,http://wso2.org/claims/emailaddress=name1@gmail.com,http://wso2.org/claims/identity/askPassword=true

I can't say if it is a system bug or a documentation error.

**Comment by piraveena** [comment]
Hi @RenanMartorelli , Thanks for reporting this issue.

Yes. As you mentioned, Instead of setting an empty password, we need to add a new claim ('http://wso2.org/claims/identity/askPassword') to trigger an ask password flow. Refer to [1] for more information. 

Looks like this information is missing in the official documentation. We need to add these contents to the official documentation.


[1] https://medium.com/@isurakarunaratne/ask-password-feature-in-wso2-identity-server-16d1273ecdd8

**Comment by gomathyk** [comment]
Hi, 

This has been addressed in the official documents now. Thanks for reporting. 

https://docs.wso2.com/display/IS570/Configuring+Users
https://docs.wso2.com/display/IS580/Configuring+Users
