### ISSUE TITLE
WantAuthnRequestsSigned, NameIDFormat & more elements in IDPSSODescriptor is not configurable in resident IDP.

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#7323]
Therefore SAML2 medata is not properly generated.  However we do not want to configure all.  But mostly common values like WantAuthnRequestsSigned + NameIDFormat must be configurable

This is similar to https://github.com/wso2/product-is/issues/4616

**Comment by SiluniPathirana** [comment]
Implemented WantAuthnRequestsSigned element configurable in resident IDP

Configuring NameIDFormat and AttributeProfile in the resident IDP is yet to be addressed. 
Due to the complexities that came across when implementing those elements, It will be addressed in the future.
 Please track the progress from https://github.com/wso2/product-is/issues/7419
