### ISSUE TITLE
The USER_CODE in device flow has to be unique

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7348]
The USER_CODE in the device code has to be unique. Currently, the user_code has only 6 characters for usability. The queries in the code[1] need to be checked on whether the user_code is actually treated as a unique. Currently, the USER_CODE does not have a unique constraint in the DB.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/device/dao/SQLQueries.java

**Comment by ashendes** [comment]
A temporary unique constraint has been added to USER_CODE with this [PR](https://github.com/wso2/carbon-identity-framework/pull/2806).

**Comment by ChamathNS** [comment]
The 6-character USER_CODE can be made unique for a specific time interval. Say the validity period for the USER_CODE (T_val) is 10 minutes. Let's quantize time into intervals of length 2*t_val and call it T_q .

T_q = 2*T_val

To do this, define the quantized time intervals from the epoch time.
![09CBE8FD-EFAB-4B51-8215-14C58206CFD5_1_201_a](https://user-images.githubusercontent.com/25428696/75742569-057d4600-5d34-11ea-92ea-f8c3c6650a3b.jpeg)

take the current time based upon epoch time and find the quanta which it resides in. Then, generate a USER_CODE that is unique in that quanta. Thus, we can guarantee that the generated USER_CODE is unique during its validity period. (T_val)

In the DB table, a new field should be created to store the T_q which the issued USER_CODE belongs to. A celan-up task service should be run periodically (every 12 hours or so) to delete the expired entries.
In the clean up service, it should have a limit as to the number of entries it should delete in one session (eg: 1000 entries max) since the table would have to be locked during this task.

**Comment by janakamarasena** [comment]
As the device flow is already available in IS-5.10.0 we also need to look into handling any possible migration concerns that can come with the fix for this issue.

**Comment by janakamarasena** [comment]
Related PRs:
Fix: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1569
Schema change: https://github.com/wso2/carbon-identity-framework/pull/3461
Migration: https://github.com/wso2-extensions/identity-migration-resources/pull/196
