### ISSUE TITLE
Multiple missing configurations with the new config model

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#7386]
### The following configurations are reported missing from the new config model.

1. catalina-server.xml.j2
   1. Add/remove secure vault configuration
   2. Enable/disable SSLHostConfig
2. carbon.xml.j2
   1. Configurations to add additional parameters to the Tenant configurations.
   2. Add the user store password-encryption property.
   3. Enable/disable token store class name.
3. identity.xml.j2
   1. Ability to configure access token partitioning. This is set to false by default in the configs.
   2. Add additional properties to the SSO service configs.
   3. Add multiple cookie configurations and customize their parameters. Currently, this is not available.
4. output-event-adapters.xml.j2
   1. Add additional properties to the email adapter config

### Affected version: 5.9.0

**Comment by nilasini** [comment]
Hi @vihanga-liyanage 

1. identity.xml.j2
i. Ability to configure access token partitioning
This feature had been deprecated\[1] hence we don't need the configuration

ii. Add additional properties to the SSO service configs.
We do not recommend adding properties other than the templated values. 

iii. Add multiple cookie configurations and customize their parameters. Currently, this is not available.
Already fixed with \[2]

2. output-event-adapters.xml.j2
Add additional properties to the email adapter config
Already fixed with \[3]

3. catalina-server.xml.j2
i. Add/remove secure vault configuration
ii. Enable/disable SSLHostConfig
Please describe the reason of needing these properties? Seems it is not needed.

4. carbon.xml.j2
i. Configurations to add additional parameters to the Tenant configurations.
If any properties used by custom components, we do not recommend adding those to the carbon.xml.j2. We recommend to add the new configs to a separate file and use it during the migration process. 

ii. Add the user store password-encryption property.
Already done with \[4]

iii. Enable/disable token store class name.
Please describe the reason of needing these properties? Seems it is not needed.

\[1] https://is.docs.wso2.com/en/latest/get-started/about-this-release/#deprecated-features-and-functionalities
\[2] https://github.com/wso2/carbon-identity-framework/pull/2724
\[3] https://github.com/wso2/carbon-analytics-common/pull/735
\[4] https://github.com/wso2/carbon-kernel/pull/2538
