### ISSUE TITLE
Issue with displaying consents in user portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7405]
**Description**
When user create SP, via management console without description, then the SP name will take as the display name in the user portal (Manage consents section)

But, if put any description then that description will take as the display name in the user portal (Manage consents section)

please refer screenshots :
![image](https://user-images.githubusercontent.com/39120228/73262582-8b1d4b80-41f4-11ea-989b-a57f94c38ec5.png)

**Comment by thanujalk** [comment]
The description gets the priority when show the application information in the Manage Consents view. If the description is not there we will show the application name. This is implemented like this to improve the user experience, as sometimes the application name can be something like "app_dev_1221", which makes no sense to the end-user.  So this is the expected behavior.
