### ISSUE TITLE
Deleting a Internal Role created via UserAdmin Admin service fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7417]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to uniqueidjdbc userstore
[user_store]
type = "database_unique_id"
[user_store.properties]
SCIMEnabled= true

2. Add a user as kim2 for the primary user store created in step1

3. Add an Internal Role with addInternalRole Request as below.
Admin Service - https://localhost:9443/services/UserAdmin/

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addInternalRole>
         
         <xsd:roleName>Internal/test4</xsd:roleName>
         
         <xsd:userList>kim2</xsd:userList>
         
         <xsd:permissions>/permission/admin</xsd:permissions>
      </xsd:addInternalRole>
   </soapenv:Body>
</soapenv:Envelope>
5. Login to the management console. There will be a Internal role created with name Internal/test4 and kim user will be assigned to this role.
6. Try to Delete the Internal role from the management console

**Observation**
UI will show as the role got deleted successfully. But the Role is still available in the UI

![internal](https://user-images.githubusercontent.com/31848014/73354178-152fe780-42bb-11ea-9ecd-5f0d70aad154.png)

**Comment by IsuraD** [comment]
This is happening since you have used **Internal/test4** as the roleName in the request. The expected behavior of addInternalRole API is to add internal roles. Hence the domain is not expected. This issue is not happing if you use just **test4** as the roleName. 

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addInternalRole>
         
         <xsd:roleName>Internal/test4</xsd:roleName>
         
         <xsd:userList>kim2</xsd:userList>
         
         <xsd:permissions>/permission/admin</xsd:permissions>
      </xsd:addInternalRole>
   </soapenv:Body>
</soapenv:Envelope>`
