### ISSUE TITLE
Allowed grant types returned in Rest APIs are not consistent

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7451]
Currently, there are two issues in the rest APIs regarding allowed grant types in service provider(application) API. 

1. The values returned in meta endpoint `(*/t/carbon.super/api/server/v1/applications/meta/inbound-protocols/oidc)` and GET `(*t/carbon.super/api/server/v1/applications/{app-id}/inbound-protocols/oidc)` are different like "Code" is coming from meta and "authorization_code" coming from GET

2. Some of the default grant types are not human readable like: 
- `urn:ietf:params:oauth:grant-type:device_code`,
- ` urn:ietf:params:oauth:grant-type:uma-ticket`,
- ` urn:ietf:params:oauth:grant-type:jwt-bearer`,
- `account_switch` 
in both the endpoints

**Comment by Kanapriya** [comment]
@vihanga-liyanage : Any reason to remove the authorization_code grant type and replace it with Code in https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.application.management/org.wso2.carbon.identity.api.server.application.management.common/src/main/java/org/wso2/carbon/identity/api/server/application/management/common/ApplicationManagementConstants.java#L138

because of that in metadata endpoint (*/t/carbon.super/api/server/v1/applications/meta/inbound-protocols/oidc) return  Code and *t/carbon.super/api/server/v1/applications/{app-id}/inbound-protocols/oidc endpoint return authorizstion_code.

**Comment by Kanapriya** [comment]
This issue can be closed and the relevant improvement can be tracked with the following issue:

https://github.com/wso2/product-is/issues/8207
