### ISSUE TITLE
Backup codes support for Email OTP authenticator

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#7474]
Currently, the backup code support is only there for SMS OTP. 

SMS OTP backup codes are stored in the `http://wso2.org/claims/otpbackupcodes` claim. Ideally, it should be an identity claim as raised in the issue https://github.com/wso2/product-is/issues/6486.

So it's better if we can implement to use the same backup codes for both the Email OTP and SMS OTP as well. Once the user uses a backup code during any of the flow (SMS OTP/Email OTP) we should update the above claim value by removing the used OTP code.

**Comment by piraveena** [comment]
1. From the application-authentication.xml file, we can enable the backup codes using the  config <Parameter name="BackupCode">true</Parameter> for email-otp authenticator 
2. Use the existing "http://wso2.org/claims/otpbackupcodes" claim to store backup codes for email-otp-authenticator.
3. Since sms-otp-authenticator is not using an identity claim currently, we can consider it as a future improvement
4. With the next release, we can address this in sms-otp-authenticator and email-otp authenticator to use the identity claim (http://wso2.org/claims/identity/otpbackupcodes) to store backup codes in a backward compatible manner
5. So in future, both sms-otp and email-otp will use the same identity claim to store backup codes.

**Comment by piraveena** [comment]
- To support this backup codes for emailotp authenticator, add this `<Parameter name="BackupCode">true</Parameter> `config under EmailOTP authenticator config.

```
<AuthenticatorConfig name="EmailOTP" enabled="true">
      -
      -
      -
     <Parameter name="BackupCode">true</Parameter>
     -
</AuthenticatorConfig>


```

- Add "http://wso2.org/claims/otpbackupcodes" claim in management console to store backup codes for email-otp-authenticator

**Comment by bhagyasakalanka** [comment]
Fixed with backup code authenticator feature
