### ISSUE TITLE
SCIM2 PATCH/ Remove Group Member API response is invalid

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7475]
SCIM2 PATCH/ Remove Group Member API response suppose to give the latest status of the update group. But the response contained the removed group member details as well. 

Note: Verified with the product version 5.8.0. Issue is available in this version too. 

Request:

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"remove","path":"members[display eq kim,value eq 95f94686-a0dd-43ce-bf95-6c055425ab3e]"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/b9147263-7c2e-466c-b8fe-5f1fc63b9393
`
Response:

`{"displayName":"PRIMARY/manager","meta":{"created":"2020-02-05T08:06:56.970Z","location":"https://localhost:9443/scim2/Groups/b9147263-7c2e-466c-b8fe-5f1fc63b9393","lastModified":"2020-02-05T08:06:56.970Z"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:Group"],"members":[{"display":"kim","value":"95f94686-a0dd-43ce-bf95-6c055425ab3e","$ref":"https://localhost:9443/scim2/Users/95f94686-a0dd-43ce-bf95-6c055425ab3e"},{"display":"test","value":"c3cfe948-93bd-4ec3-af31-ad5e7e0873ac","$ref":"https://localhost:9443/scim2/Users/c3cfe948-93bd-4ec3-af31-ad5e7e0873ac"}],"id":"b9147263-7c2e-466c-b8fe-5f1fc63b9393`

**Comment by sachiniWettasinghe** [comment]
Similar issue: https://github.com/wso2/product-is/issues/7040

The curl command used here is not valid since currently, SCIM supports simple filtering.

Valid sample request for SCIM2 PATCH/ Remove Group Member operation:
`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"remove","path":"members[display eq kim"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/9da83265-a227-4bf9-938a-4efe92755feb | json_pp`
