### ISSUE TITLE
Import cert is fail in super tenant

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7572]
Can not import cert in super tenant. Even though it get success message for importing the certificate, it's not available in the keystore. This scenario was success for the tenant domains. 

Issue observed once try to import then travelocity certificate in to IS keystore.

**Comment by denuwanthi** [comment]
This is a known issue in the previous versions as well. Now it is visible because, we have more than 50 certificates in the super tenant keystore. The paginaiton logic only allows  up to 50 certs to be paginated.
Since this issue is not visible in tenants, and super tenant certs are temporary(until server restart) we can de-prioritize this. 
The 5.10.0 version provides a REST API for keystores. Therfore we can make the priority low as this is visible in admin service.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
