### ISSUE TITLE
Unable to provisoin user claims using SCIM 1.1 - Role base provisoning

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7691]
**Description:**
After provision the user to external SCIM 1.1 supporting external Identity provider, user provisioned successfully. But when I try to update user profile by providing valid email, this email claim is not updated in external server. No logs in external server . Following errors printed in internal IS.

```
[2020-02-18 17:30:05,511] [83ec53c3-f261-4be2-9aa5-4821b096d360]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - SCIM update user operation returned with response code: 400
[2020-02-18 17:30:05,514] [83ec53c3-f261-4be2-9aa5-4821b096d360] ERROR {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - An array of "attributes" needs to be present in "meta" of the SCIM request
```

**OS, DB, other environment details and versions:**    
OS : Ubuntu 18.04
Primary Data store : LDAP
Secondary Data store : LDAP
**Steps to reproduce:**
- Deploy external IS
- Deploy internal IS
- Configure external IS for role based SCIM outbound provisioning
- Create new user. User will be created in external IS also.
- Update user claims (eg: email) . claims not provisioned.

**Comment by hung1998pro** [comment]
This issue originates from updating with PATCH request, meanwhile the request body using the syntax of the PUT request e.g:
This is the request which WSO2 sent, but it was wrong because updating with PATCH requires array "attributes" inside of "meta", this request should work well with PUT method.
```
curl -v -k --user admin:admin -X PATCH -d '{"emails":["test2@gmail.com"],"profileUrl":"","addresses":[{"type":"country","value":""}],"meta":{"lastModified":"2020-07-26T06:05:44"},"schemas":["urn:scim:schemas:core:1.0"],"name":{"familyName":"test24","givenName":"TEST23"},"userName":"PRIMARY/test2","phoneNumbers":[{"type":"mobile","value":""}],"ims":[""]}' -H "Content-Type:application/json" https://localhost:9443/wso2/scim/Users/d55a2f62-3ee5-4e4c-aa6a-502509e8e6c6
```
I'm seeking the way to change the update method from PATCH to PUT or edit the request SCIM body request, but It seems very tricky. The quickest way to fix this is removing all the meta claims in `urn:scim:schemas:core:1.0`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
