### ISSUE TITLE
[RESTAPI][DevPortal] Rest endpoint to update the OIDC protocol is not updating encryption option.

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7694]
**Description:**

The endpoint `api/server/v1/applications/{app-id}/inbound-protocols/oidc` is used to update the OIDC configuration for application via a PUT request. However, the **enabled** option in the section idToken --> encryption is not getting updated as expected. 

![image](https://user-images.githubusercontent.com/17597685/74759570-fcee2f80-529e-11ea-9618-b41847c9417c.png)

Although the response for the PUT request showing as 200, the get request for the above config is showing as encryption is not updated and in the admin console also we get the same observation.

    
**Steps to reproduce:**
1. Send GET request to `api/server/v1/applications/{app-id}/inbound-protocols/oidc` with correct application id.
2. Copy the body and change the **enabled** value. Then send it as a PUT request to the same endpoint.
3. Now send another GET request to see the updated configuration.

**Comment by mefarazath** [comment]
Needs to be fixed in below segment to read the id_token encryption-related information from the API model object and set to the underlying domain model

https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.application.management/org.wso2.carbon.identity.api.server.application.management.v1/src/main/java/org/wso2/carbon/identity/api/server/application/management/v1/core/functions/application/inbound/oauth2/ApiModelToOAuthConsumerApp.java#L88-L97

**Comment by sahanruwanga** [comment]
I'm working on this.

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2/identity-api-server/pull/108
