### ISSUE TITLE
Username recovery and password recovery with  leading whitespaces will lead to error in recovery flows

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#7847]
This will give an error message "Unable to retrieve Username/Password with given details"

This was fixed in login flows https://wso2.org/jira/browse/IDENTITY-5874

**Comment by somindatommy** [comment]
## Steps to reproduce

**prerequisite**
- Change the DB to PostgreSQL.
- Trying with a fresh pack with default configurations will not reproduce the issue.

**Steps to reproduce**

1. Enable Username recovery.
2. Create a user with some claims (Given name, last name, email, dob etc.)
3. Navigate to the **Dashboard** and click on **Forgot Username.**
4. Provide the details for the claims. (**NOTE**: While doing so add some spaces in front of the text)
5. Click on **Submit** to get username recovery notification.

**NOTE:** 
You will not get any email but the UI will say that notification has been sent via an EMAIL.
This is expected behavior since `NotifyUserExistence` is not enabled.

**Comment by somindatommy** [comment]
**Fix:** Remove leading and trailing white spaces in the user claims.

There are two recovery endpoints in the current master.
- [New user recover endpoint](https://github.com/wso2/identity-api-user/blob/master/components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/RecoveryApiService.java)
- Legacy [username recovery endpoint](https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery.endpoint/src/main/java/org/wso2/carbon/identity/recovery/endpoint/impl/RecoverUsernameApiServiceImpl.java) and [password recovery endpoint](https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery.endpoint/src/main/java/org/wso2/carbon/identity/recovery/endpoint/impl/RecoverPasswordApiServiceImpl.java).
NOTE: The UI support is avaible with legacy recovery APIs.

**Possible approaches for the fix**
1. Fix in the related _jsp_ pages since the UI support is only available via the legacy recovery APIs.
2. Both recovery APIs use the same core to identify the user. Therefore fix the claim validation in that method[1].

[1] - https://github.com/wso2-extensions/identity-governance/blob/824fa6505eeabcf50de13bb2272e586f7e34ff25/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/internal/service/impl/UserAccountRecoveryManager.java#L160
