### ISSUE TITLE
Error when accessing the SAML metadata endpoint

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7917]
**Description:**
401 Error is produced when trying to access the SAML metadata endpoint ([]()https://localhost:9443/identity/metadata/saml2 )

**Note:**
In the AuthenticationValve, it returns securedResourceConfig as null [1].

[1] - https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/67f1ba9d0e6d1660d6a56dd5b0c0c8314425c8a9/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/AuthenticationManager.java#L71

I was able to bypass the 401 error, after adding a resource context and a servlet config for the metadata endpoint as follows in the identity.xml.j2,
```
<ResourceAccessControl ...
    ...
    <Resource context="(.*)/identity/metadata/(.*)" secured="false" http-method="all"/>
```
```
<TenantContextsToRewrite>
    ...
    <Servlet>
        ...
        <Context>(.*)/identity/metadata/saml2</Context>
    </Servlet>
```

**Comment by emswbandara** [comment]
With fix introduced with: wso2/carbon-identity-framework#229 done for the git issue: #5907, for any resource context not added under ResourceAccessControl will be shown 401. @ChamathNS will you be able to send the PR for this with the fix you did?

**Comment by ChamathNS** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2828

**Comment by piraveena** [comment]
This issue exists in 5.10.0 as well. In order to fix this issue,

If you are using deployment.toml, add the following to deployment.toml

```
[[resource.access_control]]
context = "(.*)identity/metadata/saml2(.*)"
secure = "false"
http_method = "GET"
```

If you are using XML based configs, add the following line inside the "<ResourceAccessControl" tag in repository/conf/identity/identity.xml.

`<Resource context="(.*)identity/metadata/saml2(.*)" secured="false" http-method="GET" />`
Then restart WSO2 IS.
