### ISSUE TITLE
[FEATURE] Implementation of DefaultSecretCallbackHandler which communicates with AWS Secret Manager

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#7974]
**Is your feature request related to a problem? Please describe.**
Currently, since we are relying on DefaultSecretCallbackHandler we had to maintain a separate component to handle the communication with AWS Secret Manager. But this can be added to the product as a feature. 

**Describe the solution you would prefer**
Currently, we have done an implementation but since the minimum dependency requirements of the AWS SDK cannot be satisfied by the identity server this is not yet working as expected[1]

[1].https://github.com/Buddhimah/-identity-cloud-secret-handler-

**Comment by ruwanta** [comment]
We can only add this as a connector, as it contains a third party dependency and license may not be apache2 friendly

**Comment by gabrielandr** [comment]
Buddhimah, did you manage to make it work?
I'm trying to do the same thing but WSO2 IS won't let me use a 3rd party service inside the CustomSecretCallbackHandler

**Comment by Buddhimah** [comment]
> Buddhimah, did you manage to make it work?
> I'm trying to do the same thing but WSO2 IS won't let me use a 3rd party service inside the CustomSecretCallbackHandler

No im still getting that dependency issue

**Comment by gabrielandr** [comment]
Alright.. thanks for the answer! If I figure something out , i'll let you know!

**Comment by Lakshan-Banneheke** [comment]
An extension is being developed for the Carbon SecureVault in the WSO2 IS to facilitate the integration of AWS Secrets Manager for the retrieval of secrets in order to resolve #9150. 
As part of this extension, a custom secret callback handler has been implemented for retrieval of the root password. This extension has embedded the AWS SDK and uses it to communicate with the Secrets Manager in order to perform the secret retrieval.

By installing the extension into the IS and specifying the `AWSSecretCallbackHandler` to be used instead of the `DefaultSecretCallbackHandler` in the `secret-conf.properties` file, the IS can be configured to communicate with AWS Secrets Manager for retrieval of the root passwords.

**Comment by Lakshan-Banneheke** [comment]
This has been completed and the extension with the AWSSecretCallbackHandler is now available at https://github.com/wso2-extensions/carbon-securevault-aws

AWSSecretCallbackHandler: https://github.com/wso2-extensions/carbon-securevault-aws/blob/main/src/main/java/org/wso2/carbon/securevault/aws/secret/handler/AWSSecretCallbackHandler.java

**Comment by ayeshajay** [comment]
Closing based on the above comment.
