### ISSUE TITLE
When refreshing the token taken for OAuth2 public client it is required to send the client_id

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#8195]
**Describe the issue:**
When refreshing the token taken for OAuth2 public client it is required to send the client_id.

**How to reproduce:**
1. Create an OAuth2 public client from the admin-console
2. Generate access token & refresh pair
3. Try to refresh the token

It is required to send the client_id in the request.

**Expected behavior:**
IdP should able to identify the client from the refresh token.

**Comment by emswbandara** [comment]
@Yasasr1 will look into this

**Comment by mefarazath** [comment]
This could be the expected behaviour. Isn't it the same in the authorization code token request as well?

For the public client, when we sent the authorization code flow token request, we have to send the client_id as a body param since we are not indicating the client_id as part of the basic auth header.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
