### ISSUE TITLE
Validate whether 'Discoverable Application' can be used for Windows Desktop applications

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8290]
**Problem description**

Need to validate whether 'Discoverable Application' can be used for Windows Desktop applications. If it's not possible, have to update app template to remove that.

**Comment by darshanasbg** [comment]
Related to: https://github.com/wso2/product-is/issues/8103

**Comment by ayshsandu** [comment]
Making the `Windows desktop applications discoverable` is not meaningful, as providing a browser-based URL is not feasible in the current `.NET` Desktop sample application.

Since we don't maintain an application template for Windows desktop applications, the concern of making Windows desktop applications discoverable` is longer valid.
