### ISSUE TITLE
Cannot remove permissions from a created role when parent permissions are selected

### ISSUE THREAD

**Issue by yuniet87** [wso2/product-is#8517]
**Describe the issue:**
When the parent permissions of other permissions are selected, I cannot remove child permissions that are unnecessary. Example: I need a role that only creates users and manages them, for this there are many permissions that are unnecessary, but if I do not select the option "Manage" the section "Ask password from user" when I am creating the user does not appear and when I select this "Manage" option all permissions within it are enabled and cannot be disabled because their father is enabled. So what is needed is to be able to uncheck lower permissions without the higher ones being unchecked.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - Database: PostgreSQL 12.2

**Comment by ruwanta** [comment]
The permissions re implemented in father child inheritance by design and has been the model for long time in carbon 4 platform. 
The negative check would be good improvement, however there is always it works by only selecting the necessary permissions from the leaf of the permission tree for a particular role.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
