### ISSUE TITLE
When user session is terminated from the API, user-portal browser session is still active

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8700]
Steps to reproduce.
1. Log in to the user portal as a tenant user.
2. List all the available sessions of the user from the rest API : 
```curl -X GET "https://localhost:9443/t/wso2.com/api/users/v1/me/sessions" -H "accept: application/json" -H "authorization: Basic YXlzaEB3c28yLmNvbTpheXNoMTIz"```
3. Delete the session from REST API corresponding to wso2/identity-apps#1 session.
```curl -X DELETE "https://localhost:9443/t/carbon.super/api/users/v1/me/sessions/47979fea7f99f8f7a5bc49081bf6a60e3defb525ddccea2b9c335e67e88fefb7" -H "accept: application/json" -H "authorization: Basic YXlzaEB3c28yLmNvbTpheXNoMTIz"```
4. GO back to the browser in wso2/identity-apps#1 and try navigations. The browser session is still active.

**Comment by ayshsandu** [comment]
This is fixed in latest myaccount app.

**Comment by brionmario** [comment]
We are using the RP iframe to poll for the session state and when the User Portal session is terminated through the API, the session state appears unchanged for some reason[1]. Any idea why @pamodaaw?

[1] 
<img width="1904" alt="Screen Shot 2020-10-02 at 12 43 44 PM" src="https://user-images.githubusercontent.com/25959096/94898180-befcef00-04ae-11eb-9bc8-350fa96b6d29.png">

**Comment by LahiruLS** [comment]
Hi Team,
 I have created this https://github.com/wso2/product-is/issues/10419 for the same. Did some analysis and updated the findings.

**Comment by janakamarasena** [comment]
Related issues 
https://github.com/wso2/product-is/issues/10409
https://github.com/wso2/product-is/issues/10481

**Comment by piraveena** [comment]
We have done an improvement with this PR https://github.com/wso2-support/identity-inbound-auth-oauth/pull/774. In SSOSessionBasedTokenBinder, we check for the validity of commonauthId cookie. If the session is terminated by session management rest api, commonauthId cookie will be invalidated. 

From the valve level, when an accesstoken is used for authentication and if sso-session based binding is used, we check fro the validity of the https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/master/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/handler/impl/OAuth2AccessTokenHandler.java#L234. if the tokenbinding is not valid, we return 404 error from the valve. 

console app and myaccount are using sso-session based binding. once the session is terminated by the rest api, commonauth cookie will be invalidated. so valve will return 404 when a user tries to access a service (rest api) via the console/myaccount app , since we check the validity of commonauthId cookie in SSOSessionBasedTokenBinder and the session is invalidated. So console/my account will be automatically logged out.

**Comment by piraveena** [comment]
Eventhough the above issue is fixed, we still have the below issues when we terminate the session using session management rest api:

1. access tokens will not be revoked even if console app and myaccount app logout since the binding validation fails.
2. if cookie based binding is used in an oauth application, then even if the session is terminated via the api, the application will be active (because we don't do the binding validation for cookie-based binding and we don't revoke the tokens as mentioned in 1 )

**Comment by piraveena** [comment]
This improvement https://github.com/wso2/product-is/issues/10481 will resolve this issue as well irrespective of binding for any SPA. Token will be revoked upon session termination event after this issue is fixed https://github.com/wso2/product-is/issues/10481. Hence closing this issue
