### ISSUE TITLE
Rename unable to delete message

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8729]
**Describe the Issue:**
When deleting a local attribute which is also having associations, it will throw and error. The phrases should be updated to `attributes` rather than `claims`.

<img width="205" alt="Screenshot 2020-04-30 at 19 13 36" src="https://user-images.githubusercontent.com/11191791/80717896-13bec700-8b17-11ea-88cc-8d3271aed939.png">

**How To Reproduce:**
- Navigate to local attributes listing.
- Delete an attribute which has associations.

**Comment by dewniMW** [comment]
The aforementioned error message is defined at [1]. However, in the backend, as we are still using the term `claim` is it correct to rename `claim` as `attribute` in the REST API level? If we are to rename it as `attributes`, it is required to consider the other error responses mentioned in [2] as well. Otherwise, we may need to consider this as a UI improvement to maintain a mapping for the correct responses to be shown at the UI level. 

@IsuraD @emswbandara WDYT?

[1] https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.claim.management/org.wso2.carbon.identity.api.server.claim.management.common/src/main/java/org/wso2/carbon/identity/api/server/claim/management/common/Constant.java#L133-L134
[2] https://is.docs.wso2.com/en/latest/references/error-catalog/#claim-management-errors

**Comment by dewniMW** [comment]
As per the discussion with @IsuraD it was agreed that it is not scalable to change the error responses returned from the REST API. Therefore this needs to be addressed in the front-end implementation by having a way to display the proper error response based on the error code.
