### ISSUE TITLE
Analyze the impact of FIDO registration and verification domain for FIDO trusted domain configuration

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9005]
Need to analyze how the FIDO device registration domain (the end user portal) and the FIDO device verification domain (the login portal) is subjected to be changed with portal externalization and branding use cases.
Based on that decide how the server trusted origins should be configured

**Comment by ayshsandu** [comment]
Following is the output of the anaysis and the test setup.

- FIDO authentication should start at the [same domain or subdomain](https://html.spec.whatwg.org/multipage/origin.html#is-a-registrable-domain-suffix-of-or-is-equal-to) as that of the FIDO device registration.
- The origin of the registration/authentication is validated against the list of trusted origins at each scenario. 
- The origin (appId) in the registration ceremony is sent from the browser to the start-registration endpoint while the origin (appId) in the authentication ceremony is extracted from the request servlet. 

Based on these you need to consider following when doing a product deployment.

The hosted domain of the WSO2IS is referred as the **server-domain**.

In WSO2IS, FIDO2 device registration happens from the **myaccount** application. We will refer the **myaccount** hosted domain as the **registration-domain** as device registration capability comes under this portal.

In WSO2IS, Authentication with a FIDO2 device is serviced via **authenticationendpoint** application. We will refer the **authenticationendpoint** hosted domain as the **authentication-domain**.

If someone is building their own portals using WSO2 APIs instead of above mentioned portals, domain names can be referered accordingly. 

#### 1.  All in one WSO2IS instance

- **server-domain**, **registration-domain** and **authentication-domain** are same.
- FIDO2 registration and authentication will be successful as there are no domain changes.

#### 2.  [Externalize](https://is.docs.wso2.com/en/latest/develop/hosting-authentication-endpoint-on-a-different-server/) **authenticationendpoint**

- **server-domain** and **registration-domain** will be same
- It id mandatory that the **authentication-domain**  need to be configured as a subdomain of the **server-domain**
- For example: 
   - **server-domain** = _somedomain.com_
   - **registration-domain** (will be default to)= _somedomain.com_
   - **authentication-domain** = _suffix.somedomain.com_

#### 3.  Externalize **myaccount**
- **server-domain** and **registration-domain** can be different
- It id mandatory that the **authentication-domain**  need to be configured as same as **registration-domain** or a subdomain of the **registration-domain**
- As a result, whenever the **myaccount** is hosted externally, **authenticationendpoint**  also need to be externalized.
- For example: 
   - **server-domain** = _somedomain.com_
   - **registration-domain** = _someotherdomain.com_
   - **authentication-domain** = _someotherdomain.com_ or _suffix.someotherdomain.com_

#### 4.  Proxy domains for tenants
- each tenant in the deployment can be presented as a proxy domain 
- For example: 
   - **abc.com** tenant = `https://<some-host>:9443/myaccount`
   - **wso2.com** tenant = `https://<some-other-host>:9443/myaccount`
- each proxy domain must be a subdomain of the supertenant domain.
- each tenants **authenticationendpoint**  also need to be proxied under same domain as tenant domain or subdomain of the tenants registration domain.
- For example: 
   - **server-domain** = _somedomain.com_
   - **abc.com** tenant's **registration-domain** = _abc.somedomain.com_
   -  **abc.com** tenant's **authentication-domain** = _abc.somedomain.com_ or _suffix.abc.somedomain.com_

In Each case, all the domain origins need to be configured as FIDO2 trusted domains in `deployment.toml` file in the `<IS_HOME>/repository/conf` directory.

```
[fido.trusted]
origins=["server-domain", registration-domain", "authentication-domain"]
```

- For example
```
[fido.trusted]
origins=["https://server-domain:443", "https://registration-domain:443", "https://authentication-domain:443"]
```

**Comment by malithie** [comment]
Based on the analysis following is being derived to be fixed
https://github.com/wso2/product-is/issues/9948

**Comment by darshanasbg** [comment]
@ashensw Is this fixed now?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
