### ISSUE TITLE
Implement an application authethentication mechanism for REST APIs

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9019]
**Problem Description.** 
- Need a way of supporting application-level authentication mechanism to Identity Server. 
- Ex. The recovery portal needs to consume rest APIs in the Identity Server to support recovery functionalities. In order to call the APIs in Identity Server, the application should be authenticated and authorized. 
- Currently using the client authentication handler for this purpose. 
- Need to discuss how to authorization handles in such cases since there is no user involves. 

Effort BE::20

**Comment by jvitor83** [comment]
> Need to discuss how to authorization handles in such cases since there is no user involves.

I don't know if it helps, but that is the case to Client Credentials flow in OAuth2. If is the API who will need to get the access_token, then it should use the OAuth2 client credentials flow. _(maybe you guys already know, but just trying to help)_

**Comment by geve82** [comment]
My point of view about the actual system:

Currently, when using client credentials it inherits the permissions of its owner/creator. It's a mess because :
- you can know/manage who is the owner only by calling the legacy soap service or directly in the database. 
- the link between the application and the user is based on username and so if you delete the owner the application loses the permissions and if you create a new one with the same username it takes the ownership of the application...
- you need to set up a system account to create an application that needs access to IS APIs, when it is done take away its admin permissions to restrict access to APIs. If not, like everyone is doing currently, you have a security breach...

Ther is also more in-depth authorization issues like how to limit access on APIs based on business cases.  For example, I give an application the right to manage only users with a certain role/user store. Currently, only custom developments can address those uses cases and it's not an easy task.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
