### ISSUE TITLE
Core support for external Vault Support for Carbon Configurations

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#9149]
WSO2 IS can not integrate with cloud secure vault services with the default secure vault implementation. Therefore WSO2 IS needs support for prominent cloud vendor’s secure vault support built in to improve the deployment security.

Current approach is to store sensitive configurations encrypted using internal keys. We should be able to retrieve these sensitive information from external vaults by proving the server as a legitimate entity to consume that sensitive information. 

In order to plug external vaults we need to support core changes. This issue is to track the core changes that we need to do in order to address this issue.

**Comment by sanduniNagahage** [comment]
### Suggested Approach

A special secret annotation will be used to define the provider type as well as repository type along with the alias of the secret.

     $secret { alias }  : $secret { provider: repository: alias }
     
The SecretManager and the SecretManagerSecretCallbackHandler of the Carbon Securevault will get modified to build the required core support.

**SecretManager**

- Keep all the Secret Repositories initialized in order to access to retrieve the values for the aliases provided. This can accommodate filebaseSecretRepository and any other secret repository provided. 

**SecretManagerSecretCallbackHandler**

- To decouple the provider type and the repository type from the secret annotation.

**Comment by sanduniNagahage** [comment]
### Connecting the SecretRepositories

To connect the SecretRepository Implementation to the server, the following approaches has been suggested,

1. Using OSGi

2. Using java SPI 

3. Loading Classes via secret configurations file

proceed with the option [3]

Refer the email thread related to this for further information. [[IAM] External Vault Support for Carbon Configurations - Issue related to class loading using Java SPI
](https://mail.google.com/mail/u/0/#search/rfc822msgid%3ACAOUoev2vjAp7KRQxNyOYmauCXxZK%2BV7etuWfLBtSjdZWTbyXrw%40mail.gmail.com)

**Comment by sanduniNagahage** [comment]
### Configuration Model
No changes will be done to the existing configurations. The properties introduced are,
- **secretProviders** : List of Secret Provider types
- **secretProviders.<provider_type>.provider** : Fully Qualified class name of the Secret Provider
- **secretProviders.<provider_type>.repositories** : List of Secret Repositories belongs to a particular Secret Provider
- **secretProviders.<provider_type>.repositories.<repository_type>** : Fully Qualified class name of the Secret Repository
- **secretProviders.<provider_type>.repositories.<repository_type>.properties.<property_name>** : Properties pertaining to a particular repository can be defined

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
