### ISSUE TITLE
AWS KMS Support for Carbon Configurations

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#9150]
AWS vault support for Carbon configurations. This has to be done once the improvement https://github.com/wso2/product-is/issues/9149 is completed.

Effort BE::20

**Comment by Lakshan-Banneheke** [comment]
The WSO2 Identity server currently supports a file-based secure vault by default and the Carbon Secure Vault component has the functionality to utilize extensions that support external vaults such as Hashicorp Vault. An extension is being developed to support the AWS Secrets Manager as an external vault. Through this extension, it is now possible to store secrets in AWS Secrets Manager and retrieve them for use within the WSO2 Identity Server.

Note: The extension only supports WSO2 IS 5.12.0 onwards.

**Comment by Lakshan-Banneheke** [comment]
### Features of the extension

- Retrieval of secrets from AWS Secrets Manager.

- Facilitates retrieval and use of plain-text secrets as well as secrets encrypted using the internal keystore of the IS, from AWS Secrets Manager.
The user has the ability to define whether encryption is needed or not. When encryption is enabled, the extension will decrypt the secrets retrieved from AWS Secrets Manager using the internal keystore of the IS. 
Note: Encryption is only facilitated when secret repositories are defined in the legacy method due to limitations in the Carbon Secure Vault implementation.

- Facilitates secret versioning - The user can retrieve specific versions of secrets from AWS Secrets Manager. The version should be specified in the secret alias using "#" as the delimiter as shown below.
``` 
$secret{<alias>#<versionID>} 
```

- Allows a user-defined custom authentication chain for authenticating into AWS - The extension allows the user to define which authentication mechanism should be used for authenticating into AWS. The user can select one or multiple authentication providers from the below list.
	- Environment variables.
	- Amazon EC2 metadata service.
	- ECS metadata service.
	- AWS CLI.
	- Kubernetes Service Account/Pod identity.
	- Default authentication chain.

- Facilitates retrieval of root password from AWS Secrets Manager using a custom secret callback handler. This resolves #7974.

**Comment by Lakshan-Banneheke** [comment]
This has been completed and the extension is now available at https://github.com/wso2-extensions/carbon-securevault-aws

**Comment by ayeshajay** [comment]
Closing based on above comment
