### ISSUE TITLE
[Console] Create remote configurations fail

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9228]
**Describe the issue:**

Error while submitting the configuration detail and fail the submit

```
blob:https://localhost:9443/96af06c8-2c41-406e-8459-2d6e86e35bca:54 Uncaught TypeError: Cannot read property 'startsWith' of undefined
    at _.forEach.i (blob:https://localhost:9443/96af06c8-2c41-406e-8459-2d6e86e35bca:54)
    at Array.forEach (<anonymous>)
    at Object.ft [as httpRequest] (blob:https://localhost:9443/96af06c8-2c41-406e-8459-2d6e86e35bca:54)
    at self.onmessage (blob:https://localhost:9443/96af06c8-2c41-406e-8459-2d6e86e35bca:54)
```

**How to reproduce:**
1. Log in to console
2. Navigate to the developer portal and the Remote repo config
3. Click to add new remote repository config button
4. Add configuration details and click "Create configurations' button

**Expected behavior:**
Configuration should be submit.

**Environment information**
 - Product Version: [e.g., IS 5.11.0-M31]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
This feature was temporarily hidden[1] due to ongoing backend improvements.

[1] https://github.com/wso2/identity-apps/pull/1190

**Comment by thanujalk** [comment]
This feature is enabled again.

If you select the webhook option, it fails with the error,

`{"code":"UE-10000","message":"Invalid Request.","description":"Provided request body content is not in the expected format.","traceId":"a58b1809-2143-4a97-8210-0f4bcad81ea3"}`

Failed request body: webhook
```
{
  "actionListener": {
    "attributes": {
      "frequency": null
    },
    "type": "WEBHOOK"
  },
  "configurationDeployer": {
    "attributes": {},
    "type": "SP"
  },
  "isEnabled": true,
  "remoteFetchName": "ApplicationConfigurationRepository",
  "repositoryManager": {
    "attributes": {
      "branch": "master",
      "directory": "test",
      "uri": "https://github.com/wso2/identity-apps"
    },
    "type": "GIT"
  }
}
```

Success request body: polling,

```
{
  "actionListener": {
    "attributes": {
      "frequency": 60
    },
    "type": "POLLING"
  },
  "configurationDeployer": {
    "attributes": {},
    "type": "SP"
  },
  "isEnabled": true,
  "remoteFetchName": "ApplicationConfigurationRepository",
  "repositoryManager": {
    "attributes": {
      "accessToken": "dasdaasdad",
      "branch": "master",
      "directory": "test",
      "uri": "https://github.com/wso2/identity-apps",
      "username": "wso2carbon"
    },
    "type": "GIT"
  }
}
```

So the issue can be due to accessToken and username attributes missing in the request.

**Comment by Thumimku** [comment]
```
{
  "actionListener": {
    "attributes": {
      "frequency": null
    },
    "type": "WEB_HOOK"
  },
  "configurationDeployer": {
    "attributes": {},
    "type": "SP"
  },
  "isEnabled": true,
  "remoteFetchName": "ApplicationConfigurationRepository",
  "repositoryManager": {
    "attributes": {
      "branch": "master",
      "directory": "test",
      "uri": "https://github.com/wso2/identity-apps"
    },
    "type": "GIT"
  }
}
```
This will work. The issue is WEB_HOOK, not WEBHOOK. You can find the constant here.

https://github.com/wso2-extensions/identity-fetch-remote/blob/179437a3aaabacfac44f3ee0491fc25d0b35c89b/components/org.wso2.carbon.identity.remotefetch.common/src/main/java/org/wso2/carbon/identity/remotefetch/common/RemoteFetchConstants.java#L44
