### ISSUE TITLE
SCIM2 role API parameter values are case sensitive

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9285]
**Describe the issue:**
SCIM2 role API parameter values are case sensitive.
Ex: Can create two different roles from displayName, test and "test". 

**How to reproduce:**
1. Create roles from scim with displayName  "testRole" and "testrole"
2. Filter or search roles with  displayName  "testRole" and "testrole"

**Expected behavior:**
When second role creation response should be 409 and second atempt role creation should be fail

**Environment information** 
 - Product Version: [e.g., IS 5.11.0-m32]

**Comment by ashensw** [comment]
This requirement is not valid for roles. New roles implementation is using the hybrid roles and hybrid roles have been case sensitive from the beginning. You can try the same from the IS management console by creating an internal role with both cases and it allows to be created. So closing this issue as this is the expected behavior.

**Comment by ashensw** [comment]
This requirement is not valid. Our current behavior for Groups also depends on the case sensitivity of the user store. The default pack gives 409 for Groups as the embedded LDAP is case insensitive. But if you try it with a MySQL JDBC user store it will allow creating groups in both cases. So it depends on the underlying userstore or database. The same will apply for roles as well. Hence closing this issue.
