### ISSUE TITLE
Tenant qualified URL support for basic request path authentication

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#9527]
When using basic request path authentication with tenant qualified urls, users in the tenant domain specified in the url context should not be needed to append tenant domain in the login identifier. This is valid for both SaaS and non SaaS apps

Effort BE::15

**Comment by ImalshaG** [comment]
Tested the basic auth request path authentication flow. 

For both SaaS and non-SaaS apps, using tenant qualified URLs, users can login with both usernames with/without tenant appended.
Ex request:
```
https://localhost:9443/t/foo.com/oauth2/authorize?sectoken=cGV0ZXIxMjM0QGZvby5jb206YWRtaW4=&response_type=code&client_id=tX569N5nzlG1Wfl27kfi8QiTMg4a&redirect_uri=https://oidcdebugger.com/debug&scope=openid
```
where sec token is base64 encoded username:password of a user in foo.com tenant. Using the username without appending the tenant domain succeeded. 

Therefore this issue is fixed now.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
