### ISSUE TITLE
Duplicate attributes for the same attribute name in SCIM2 Extensions 

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9548]
In the latest scim2-schema-extension.config, there are 2 attributes defined for the same attribute name 'value'

urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:pendingEmails.value
urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.value

As a result, manager.value gets overridden by the other attribute.
We need to fix this in charon level or define a different attribute name for pendingEmails.value.

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config#L169

**Comment by janakamarasena** [comment]
I think we will need to fix this in charon as these are two sub-attributes I think it is okay to have the same attribute name.

**Comment by emswbandara** [comment]
could be reproduced in RC1 pack

**Request**

curl -v -k -u admin:admin  --data '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"Sachini","password":"vindula","emails":[{"primary":true,"value":"vindula_home.com","type":"home"},{"value":"vindula_work.com","type":"work"}],"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"employeeNumber":"123A","manager":{"value":"Johann"}}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

**Response**

{"emails":[{"type":"work","value":"vindula_work.com"},{"type":"home","value":"vindula_home.com"}],"meta":{"created":"2020-11-16T13:44:58.693Z","location":"https://localhost:9443/scim2/Users/65865279-5283-4b22-8bb5-3efab07b32a8","lastModified":"2020-11-16T13:44:58.693Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"},{"display":"everyone"}],"name":{"givenName":"vindula","familyName":"jayawardana"},"id":"65865279-5283-4b22-8bb5-3efab07b32a8","userName":"Sachini","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"employeeNumber":"123A"}}

**Comment by rksk** [comment]
The same happens if we have a use case like below.
Assume a set of custom extended schema attributes are configured like below.
- vehicle
-- private
-- work
- wallet
-- private
-- work

`vehicle` and `wallet` are complex attributes and `work` and `private` are included as subattributes of each.

Now if we try to create a user by providing values like below, only two of the four values get persisted.
```
   "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{
      "vehicle":{
         "private":"abcd",
         "work":"pqrs"
      },
      "wallet":{
         "private":"mnop",
         "work":"xyz"
      }
   },
   ```

**Comment by piraveena** [comment]
this happens because we remove the read-only sub-attributes https://github.com/wso2/charon/blob/v3.4.23/modules/charon-core/src/main/java/org/wso2/charon3/core/schema/AbstractValidator.java#L383 based on the attribute name. `PendingEmails.value` and `manager.value` have the same attribute name. Due to this, when it loops through and checks for `PendingEmails.value` read_only attribute, it deletes the `manager. value`.
