### ISSUE TITLE
Secondary userstore users/roles are not listed for workflow approvals

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9580]
**Describe the issue:**
Secondary Userstore users/roles are not listed for workflow approvals

**How to reproduce:**
- Add a secondary userstore and add few users/roles
- Go to Add workflow definition and give a name
- Search for users/roles to add as workflow approval step
- Only the primary users/roles are listed

**Expected behavior:**
All primary and secondary users to be listed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0-Alpha2
 - OS:  Mac
 - Database: H2
 - Userstore: LDAP primary/ LDAP secondary

**Comment by DinikaSen** [comment]
In order to appear a user/role in the workflow approval step configuration, the user/role should have the '**Human Tasks > View Task List**' permission. However, after the introduction of group-role separation concept, the primary/secondary userstore roles do not appear in the workflow approval step configuration because now those roles are considered groups, and groups no longer have permissions attached to them. Therefore, only the **internal** roles with the '**Human Tasks > View Task List'** permission will be shown in the workflow approvals step config. The users (in both primary and secondary userstores) who have as internal role with sufficient permissions can perform the approval tasks as configured in the approval step.
