### ISSUE TITLE
Wrong OpenID Provider Issuer location when using tenant qualified endpoint

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9701]
**Describe the issue:**
In [1] **Obtaining the OpenID Provider Issuer location** request doesn't work with tenant qualified mode. 
[1] https://is.docs.wso2.com/en/latest/learn/openid-connect-discovery/

**How to reproduce:**
1. Send the following request
`curl -v -k  https://localhost:9443/.well-known/webfinger?resource='acct:admin%40wso2.com@localhost&rel=http://openid.net/specs/connect/1.0/issuer'`

response will be
`{"subject":"acct:admin@wso2.com@localhost","links":[{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"https://localhost:9443/oauth2/token"}]}` 

Here tenant qualified URL should be return

Following tenant qualified request is not working.
`curl -v -k  https://localhost:9443/t/wso2.com/.well-known/webfinger?resource='acct:admin%40wso2.com@localhost&rel=http://openid.net/specs/connect/1.0/issuer' `

Getting response as 401.

**Expected behavior:**
Tenant qualified url should be returned for the first request, request 2 should work without 401.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Linux]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

**Comment by janakamarasena** [comment]
By default the issuer mentioned in the resident idp of the tenant gets returned. By default this config is not tenanted and this can be changed from the resident IDP config of the tenant.

When tenanted url mode is enabled using the following config it will send the issuer based on the request url path. 
```
[tenant_context]
enable_tenant_qualified_urls = true
```
e.i 
When the tenant url mode is enabled since we are calling a tenant path if the url used is the super tenant url then the issuer of the super tenant is received. 


The following PR fixes the 401 response when calling tenant path.
https://github.com/wso2/carbon-identity-framework/pull/3161

**Comment by janakamarasena** [comment]
Due to this https://github.com/wso2/product-is/issues/8528 the webfinger is not expected to be called in a tenant-specific way.
