### ISSUE TITLE
UI support for Managing SMS templates 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9762]
# Description
With the latest introduction of features, Identity Server is capable of Sending SMS notifications for the completed scenarios in issue https://github.com/wso2/product-is/issues/9754.

Currently, these SMS templates are managed from the registry. This was reported and fixed with the following issues.
- https://github.com/wso2/product-is/issues/6669
- https://github.com/wso2/product-is/issues/7006

# Requirement
Since the templates are managed from the registry, it is difficult to add and maintain SMS templates. In the current product, there is a separate UI to manage EMAIL templates. Therefore, having a separate UI to manage SMS templates will increase the user experience.

**Comment by darshanasbg** [comment]
With this, we need to onboard following things as well,
* (Rest) API to manage notification templates.
* Consider deprecating Email Template API, since above API could provide same function more generalized manner.
* Consider deprecating [EmailTemplateManager](https://github.com/wso2-extensions/identity-event-handler-notification/blob/b6906853fde8685facd9e57b1fbc8447ad002b60/components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/EmailTemplateManager.java) interface by moving to [NotificationTemplateManager](https://github.com/wso2-extensions/identity-governance/blob/ba607bc590e9e10ed06d47a21910d96347715bb6/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/service/notification/NotificationTemplateManager.java).
* Consider moving out from [org.wso2.carbon.email.mgt](https://github.com/wso2-extensions/identity-event-handler-notification/tree/master/components/email-mgt/org.wso2.carbon.email.mgt) introducing a new component like notification-mgt.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
