### ISSUE TITLE
Change the dialect id when updating claim dialect using PUT request

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9846]
**Describe the issue:**

When the claim dialect is updated using PUT request https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/#/management/updateClaimDialect it changes the dialect id. 

**How to reproduce:**
1. Get all dialects `GET /claim-dialects`. Notice one id of a dialect
2. Retrieve the particular dialect by id and check the dialect uri.  `GET /claim-dialects/{dialect-id}`.
3. Update the dialect uri  https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/#/management/updateClaimDialect (PUT ​/claim-dialects​/{dialect-id})
4. Perform the step 2. The resources will not be found by the previous id.
5. List out all dialects and find the id for the the dialect with updated uri. It is different from the previous. 

**Expected behavior:**
ID of the claim dialect should not be updated by PUT request.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0- Beta
 - OS: Windows
 - Database: Postgres
 - Userstore: JDBC

**Comment by somindatommy** [comment]
This is the expected behavior in the current implementation. According to the current implementation, we don't have a resource identifier bound to the dialect and the current resource identifier is the base64 encoded dialect URI. Due to this reason the identifier is changed.

Ideally, we need to have a separate ID for each resource. Therefore, this is a limitation in the current product and a valid **improvement**.

**Comment by somindatommy** [comment]
In the API response, if the request is successful, the new resource is returned in the API response header.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
