### ISSUE TITLE
OpenID connect web application image does not loaded when its set via the application image url section

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#9968]
**Describe the issue:**
Application image does not get loaded when it is set via a link
**How to reproduce:**
1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Applications > New Application > Web Application  > OpenID Connect 
4. Register the SP
5. Will get direct to the edit view of the application
6. Input a URL for the application image (https://images.app.goo.gl/bzemfR1EdSVr17Qk7)

**Observation**
Image is not getting loaded as the application image although it says that the application updated successfully

**Expected behavior:**
The image should be loaded as the application image
**Environment information**

Mssql 2019
uniqueid jdbc
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
This is because `https://images.app.goo.gl/bzemfR1EdSVr17Qk7` is not a valid image URL. It points to a webpage that hosts the image. The valid image URL, in this case, is `https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg`.

And this works fine.
![image](https://user-images.githubusercontent.com/20745428/97550208-62321d00-19f7-11eb-8374-5d0d2cb8b328.png)
